/* Generated by Nim Compiler v1.7.1 */
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(x, y)
#define nimln_(x, y)
typedef struct tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ;
struct tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ {
NI Field0;
NI Field1;
};
static N_INLINE(void, stareq___pureZtimes_2508)(NI* x, NI y);
N_LIB_PRIVATE N_NIMCALL(NI, nextPowerOfTwo__pureZmath_171)(NI x) {
	NI result;
	result = (NI)0;
	result = (NI)(x - ((NI) 1));
	result = (NI)(result | (NI)((NI64)(result) >> (NU64)(((NI) 32))));
	result = (NI)(result | (NI)((NI64)(result) >> (NU64)(((NI) 16))));
	result = (NI)(result | (NI)((NI64)(result) >> (NU64)(((NI) 8))));
	result = (NI)(result | (NI)((NI64)(result) >> (NU64)(((NI) 4))));
	result = (NI)(result | (NI)((NI64)(result) >> (NU64)(((NI) 2))));
	result = (NI)(result | (NI)((NI64)(result) >> (NU64)(((NI) 1))));
	result += (NI)(((NI) 1) + (x <= ((NI) 0)));
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, floorMod__OOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZsdl50_732)(NI x, NI y) {
	NI result;
	result = (NI)0;
	result = (NI)(x % y);
	{
		NIM_BOOL T3_;
		NIM_BOOL T4_;
		NIM_BOOL T7_;
		T3_ = (NIM_BOOL)0;
		T4_ = (NIM_BOOL)0;
		T4_ = (((NI) 0) < result);
		if (!(T4_)) goto LA5_;
		T4_ = (y < ((NI) 0));
		LA5_: ;
		T3_ = T4_;
		if (T3_) goto LA6_;
		T7_ = (NIM_BOOL)0;
		T7_ = (result < ((NI) 0));
		if (!(T7_)) goto LA8_;
		T7_ = (((NI) 0) < y);
		LA8_: ;
		T3_ = T7_;
		LA6_: ;
		if (!T3_) goto LA9_;
		result += y;
	}
	LA9_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI64, floorDiv__pureZtimes_260)(NI64 x, NI64 y) {
	NI64 result;
	NI64 r;
	result = (NI64)0;
	result = (NI64)(x / y);
	r = (NI64)(x % y);
	{
		NIM_BOOL T3_;
		NIM_BOOL T4_;
		NIM_BOOL T7_;
		T3_ = (NIM_BOOL)0;
		T4_ = (NIM_BOOL)0;
		T4_ = (IL64(0) < r);
		if (!(T4_)) goto LA5_;
		T4_ = (y < IL64(0));
		LA5_: ;
		T3_ = T4_;
		if (T3_) goto LA6_;
		T7_ = (NIM_BOOL)0;
		T7_ = (r < IL64(0));
		if (!(T7_)) goto LA8_;
		T7_ = (IL64(0) < y);
		LA8_: ;
		T3_ = T7_;
		LA6_: ;
		if (!T3_) goto LA9_;
		result -= ((NI) 1);
	}
	LA9_: ;
	return result;
}
static N_INLINE(void, stareq___pureZtimes_2508)(NI* x, NI y) {
	(*x) = (NI)((*x) * y);
}
N_LIB_PRIVATE N_NIMCALL(NI, roof___pureZtimes_2501)(NI x, NI y) {
	NI result;
	result = (NI)0;
	switch (y) {
	case ((NI) 0):
	{
		result = ((NI) 1);
	}
	break;
	case ((NI) 1):
	{
		result = x;
	}
	break;
	case ((NI) 2):
	{
		result = (NI)(x * x);
	}
	break;
	case ((NI) 3):
	{
		result = (NI)((NI)(x * x) * x);
	}
	break;
	default:
	{
		tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ T6_;
		NI x_2;
		NI y_2;
		T6_.Field0 = x;
		T6_.Field1 = y;
		x_2 = T6_.Field0;
		y_2 = T6_.Field1;
		result = ((NI) 1);
		{
			while (1) {
				{
					if (!!(((NI)(((NI) (y_2)) & ((NI) 1)) == ((NI) 0)))) goto LA11_;
					stareq___pureZtimes_2508((&result), x_2);
				}
				LA11_: ;
				y_2 = ((NI) ((NI)((NI64)(((NI) (y_2))) >> (NU64)(((NI) 1)))));
				{
					if (!(((NI) (y_2)) == ((NI) 0))) goto LA15_;
					goto LA7;
				}
				LA15_: ;
				stareq___pureZtimes_2508((&x_2), x_2);
			}
		} LA7: ;
	}
	break;
	}
	return result;
}
