/* Generated by Nim Compiler v1.7.1 */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#include <sys/types.h>
                          #include <pthread.h>
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(x, y)
#define nimln_(x, y)
typedef struct tyObject_nzStreamcolonObjectType___uAEM0djdUGvrhRJcCteRig tyObject_nzStreamcolonObjectType___uAEM0djdUGvrhRJcCteRig;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_BitStream__1VvBM1ZRgURezk58VPkyyg tyObject_BitStream__1VvBM1ZRgURezk58VPkyyg;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack__7fytPA5bBsob6See21YMRA tyObject_GcStack__7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk__tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk__tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk__XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk__XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk__W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk__W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple__ujsjpB2O9cjj3uDHsXbnSzg tyTuple__ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg;
typedef struct tyObject_SharedList__JI9cx34TL8n3aOKF6tSMBUw tyObject_SharedList__JI9cx34TL8n3aOKF6tSMBUw;
typedef struct tyObject_SharedListNodecolonObjectType___KGw0YAw6W9aSz3Sr9aXGu7zg tyObject_SharedListNodecolonObjectType___KGw0YAw6W9aSz3Sr9aXGu7zg;
typedef struct tyObject_NZError__Ihv5tO001K9aPAxxhJbC4Cw tyObject_NZError__Ihv5tO001K9aPAxxhJbC4Cw;
typedef struct tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct tySequence__uB9b75OUPRENsBAu4AnoePA tySequence__uB9b75OUPRENsBAu4AnoePA;
typedef struct tyObject_HuffmanTree__jJCPIerUDiHKi9bQLvybbzA tyObject_HuffmanTree__jJCPIerUDiHKi9bQLvybbzA;
typedef struct tySequence__qwqHTkRvwhrRyENtudHQ7g tySequence__qwqHTkRvwhrRyENtudHQ7g;
typedef struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct tyObject_BitStream__1VvBM1ZRgURezk58VPkyyg {
NI bitpointer;
NimStringDesc* data;
NI databitlen;
};
typedef NU8 tyEnum_nzStreamMode__84qAxH4EmXmdSDCwYfjvFQ;
struct tyObject_nzStreamcolonObjectType___uAEM0djdUGvrhRJcCteRig {
NI btype;
NIM_BOOL use_lz77;
NI windowsize;
NI minmatch;
NI nicematch;
NIM_BOOL lazymatching;
tyObject_BitStream__1VvBM1ZRgURezk58VPkyyg bits;
NimStringDesc* data;
tyEnum_nzStreamMode__84qAxH4EmXmdSDCwYfjvFQ mode;
NIM_BOOL ignoreAdler32;
};
typedef NU8 tyEnum_TNimKind__jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag__v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc__ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
NI align;
tyEnum_TNimKind__jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag__v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc__ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind__unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind__unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack__7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk__tXn60W2f8h3jgAYdEmy5NQ* tyArray__SPr7N6UKfuF549bNPiUvSRw[256];
typedef NU32 tyArray__BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg* tyArray__N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray__N1u1nqOgmuJN9cSZrnMHgOQ tyArray__B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk__W0r8S0Y3UGke6T9bIUWnnuw* tyArray__lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA {
tyArray__lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* tyArray__0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw {
tyArray__0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple__ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple__ujsjpB2O9cjj3uDHsXbnSzg tyArray__LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray__LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray__SPr7N6UKfuF549bNPiUvSRw freeSmallChunks;
NU32 flBitmap;
tyArray__BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray__B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk__XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_SharedList__JI9cx34TL8n3aOKF6tSMBUw {
tyObject_SharedListNodecolonObjectType___KGw0YAw6W9aSz3Sr9aXGu7zg* head;
tyObject_SharedListNodecolonObjectType___KGw0YAw6W9aSz3Sr9aXGu7zg* tail;
pthread_mutex_t lock;
};
struct tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack__7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
NI zctThreshold;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w additionalRoots;
tyObject_SharedList__JI9cx34TL8n3aOKF6tSMBUw toDispose;
NI gcThreadId;
};
struct RootObj {
TNimType* m_type;
};
struct Exception {
  RootObj Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
tySequence__uB9b75OUPRENsBAu4AnoePA* trace;
Exception* up;
};
struct tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA {
  Exception Sup;
};
struct tyObject_NZError__Ihv5tO001K9aPAxxhJbC4Cw {
  tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA Sup;
};
struct tyObject_HuffmanTree__jJCPIerUDiHKi9bQLvybbzA {
tySequence__qwqHTkRvwhrRyENtudHQ7g* tree2d;
tySequence__qwqHTkRvwhrRyENtudHQ7g* tree1d;
tySequence__qwqHTkRvwhrRyENtudHQ7g* lengths;
NI maxbitlen;
NI numcodes;
};
typedef NI tyArray__OwOytieXUe4SPSxAsbsyEA[288];
typedef NI tyArray__OYqzMMAeF9bf1yDDPNUyDgg[32];
typedef NI tyArray__Ntm7bvhzwbE9b2CkMppjB8A[19];
typedef NI tyArray__s9azk0bXjkHhm7i19ceN41rg[29];
typedef NI tyArray__q0oNe3lONaLAJQxP9c7FTZA[30];
struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA {
NCSTRING procname;
NI line;
NCSTRING filename;
};
struct tySequence__qwqHTkRvwhrRyENtudHQ7g {
  TGenericSeq Sup;
  NI data[SEQ_DECL_SIZE];
};
struct tySequence__uB9b75OUPRENsBAu4AnoePA {
  TGenericSeq Sup;
  tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];
};
N_LIB_PRIVATE N_NIMCALL(tyObject_nzStreamcolonObjectType___uAEM0djdUGvrhRJcCteRig*, nzInit__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Znimz_1650)(void);
N_LIB_PRIVATE N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, Marker_tyRef__VNtHIlFk6DdHbJolR3Euzg)(void* p, NI op);
N_LIB_PRIVATE N_NOINLINE(void*, newObj)(TNimType* typ, NI size);
N_NIMCALL(NimStringDesc*, rawNewString)(NI cap);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incRef__system_5877)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(NI, pluspercent___system_696)(NI x, NI y);
static N_INLINE(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell__system_5839)(void* usr);
static N_INLINE(NI, minuspercent___system_716)(NI x, NI y);
static N_INLINE(void, decRef__system_5884)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(NIM_BOOL, ltpercent___system_1005)(NI x, NI y);
static N_INLINE(void, rtlAddZCT__system_5882)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT__system_5833)(tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_NIMCALL(void, Marker_tyRef__8EFTeb6IiMkqB59a5RstjVw)(void* p, NI op);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
N_LIB_PRIVATE N_NIMCALL(void, raiseExceptionEx)(Exception* e, NCSTRING ename, NCSTRING procname, NCSTRING filename, NI line);
N_LIB_PRIVATE N_NIMCALL(NI, readByte__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Znimz_721)(tyObject_BitStream__1VvBM1ZRgURezk58VPkyyg* s);
N_LIB_PRIVATE N_NIMCALL(NU32, readInt32__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Znimz_1775)(NimStringDesc* input);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, substr__system_8679)(NimStringDesc* s, NI first, NI last);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, setLengthStr)(NimStringDesc* s, NI newLen);
N_LIB_PRIVATE N_NIMCALL(void, nzInflate__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Znimz_940)(tyObject_nzStreamcolonObjectType___uAEM0djdUGvrhRJcCteRig* nz);
static N_INLINE(NI, readBitFromStream__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Znimz_99)(tyObject_BitStream__1VvBM1ZRgURezk58VPkyyg* s);
static N_INLINE(NI, readBit__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Znimz_85)(tyObject_BitStream__1VvBM1ZRgURezk58VPkyyg s);
N_LIB_PRIVATE N_NIMCALL(void, inflateNoCompression__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Znimz_737)(tyObject_nzStreamcolonObjectType___uAEM0djdUGvrhRJcCteRig* nz);
N_LIB_PRIVATE N_NIMCALL(NI, readInt16__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Znimz_699)(tyObject_BitStream__1VvBM1ZRgURezk58VPkyyg* s);
N_LIB_PRIVATE N_NIMCALL(NI, getBytePosition__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Znimz_718)(tyObject_BitStream__1VvBM1ZRgURezk58VPkyyg* s);
N_LIB_PRIVATE N_NIMCALL(void, inflateHuffmanBlock__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Znimz_893)(tyObject_nzStreamcolonObjectType___uAEM0djdUGvrhRJcCteRig* nz, NI blockType);
static N_INLINE(void, nimZeroMem)(void* p, NI size);
static N_INLINE(void, nimSetMem__systemZmemory_7)(void* a, int v, NI size);
N_LIB_PRIVATE N_NIMCALL(void, getTreeInflateFixed__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Znimz_759)(tyObject_HuffmanTree__jJCPIerUDiHKi9bQLvybbzA* tree_ll, tyObject_HuffmanTree__jJCPIerUDiHKi9bQLvybbzA* tree_d);
N_LIB_PRIVATE N_NIMCALL(void, generateFixedLitLenTree__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Znimz_633)(tyObject_HuffmanTree__jJCPIerUDiHKi9bQLvybbzA* tree);
N_LIB_PRIVATE N_NIMCALL(void, HuffmanTree_makeFromLengths__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Znimz_292)(tyObject_HuffmanTree__jJCPIerUDiHKi9bQLvybbzA* tree, NI* bitlen, NI bitlenLen_0, NI maxbitlen);
N_LIB_PRIVATE N_NIMCALL(tySequence__qwqHTkRvwhrRyENtudHQ7g*, at___OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Znimz_296)(NI* a, NI aLen_0);
N_LIB_PRIVATE N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_LIB_PRIVATE N_NIMCALL(void, HuffmanTree_makeFromLengths2__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Znimz_224)(tyObject_HuffmanTree__jJCPIerUDiHKi9bQLvybbzA* tree);
N_LIB_PRIVATE N_NIMCALL(tySequence__qwqHTkRvwhrRyENtudHQ7g*, newSeq__pureZosproc_150)(NI len);
N_LIB_PRIVATE N_NIMCALL(void, HuffmanTree_make2DTree__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Znimz_167)(tyObject_HuffmanTree__jJCPIerUDiHKi9bQLvybbzA* tree);
N_LIB_PRIVATE N_NIMCALL(void, generateFixedDistanceTree__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Znimz_674)(tyObject_HuffmanTree__jJCPIerUDiHKi9bQLvybbzA* tree);
N_LIB_PRIVATE N_NIMCALL(void, getTreeInflateDynamic__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Znimz_777)(tyObject_BitStream__1VvBM1ZRgURezk58VPkyyg* s, tyObject_HuffmanTree__jJCPIerUDiHKi9bQLvybbzA* tree_ll, tyObject_HuffmanTree__jJCPIerUDiHKi9bQLvybbzA* tree_d);
N_LIB_PRIVATE N_NIMCALL(NI, readBitsFromStream__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Znimz_106)(tyObject_BitStream__1VvBM1ZRgURezk58VPkyyg* s, NI nbits);
N_LIB_PRIVATE N_NIMCALL(NI, huffmanDecodeSymbol__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Znimz_762)(tyObject_BitStream__1VvBM1ZRgURezk58VPkyyg* s, tyObject_HuffmanTree__jJCPIerUDiHKi9bQLvybbzA* codetree, NI inbitlength);
N_LIB_PRIVATE N_NIMCALL(NI, readBitsSafe__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Znimz_127)(tyObject_BitStream__1VvBM1ZRgURezk58VPkyyg* s, NI nbits);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, addChar)(NimStringDesc* s, NIM_CHAR c);
N_LIB_PRIVATE N_NIMCALL(NU32, nzAdler32__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Znimz_1704)(NU32 adler, NimStringDesc* data);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, nzGetResult__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Znimz_1696)(tyObject_nzStreamcolonObjectType___uAEM0djdUGvrhRJcCteRig* nz);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_LIB_PRIVATE TNimType NTInzstream58objecttype__uAEM0djdUGvrhRJcCteRig_;
N_LIB_PRIVATE TNimType NTIint__6YIzl9b2Xq7fIc5qJO0fYVw_;
extern TNimType NTIbool__VaVACK0bpYmqIQ0mKcHfQQ_;
N_LIB_PRIVATE TNimType NTIint__iP0zKMh4CnuWmtNdPhn0xQ_;
N_LIB_PRIVATE TNimType NTIint__5It9aoOeJWaKNUT1V1S4z8Q_;
N_LIB_PRIVATE TNimType NTIint__qg9bcJHx5JH9akIu7ZK7cf4Q_;
N_LIB_PRIVATE TNimType NTIbitstream__1VvBM1ZRgURezk58VPkyyg_;
extern TNimType NTIint__rR5Bzr1D5krxoo1NcNyeMA_;
extern TNimType NTIstring__77mFvmsOLKik79ci2hXkHEg_;
N_LIB_PRIVATE TNimType NTInzstreammode__84qAxH4EmXmdSDCwYfjvFQ_;
N_LIB_PRIVATE TNimType NTInzstream__VNtHIlFk6DdHbJolR3Euzg_;
extern TNimType NTIcatchableerror__qrLSDoe2oBoAqNtJ9badtnA_;
N_LIB_PRIVATE TNimType NTInzerror__Ihv5tO001K9aPAxxhJbC4Cw_;
N_LIB_PRIVATE TNimType NTIrefnzerror__8EFTeb6IiMkqB59a5RstjVw_;
STRING_LITERAL(TM__n9cknNhkm8Fa9boCSB3rtZeA_7, "size of zlib data too small", 27);
STRING_LITERAL(TM__n9cknNhkm8Fa9boCSB3rtZeA_8, "bit pointer will jump past memory", 33);
STRING_LITERAL(TM__n9cknNhkm8Fa9boCSB3rtZeA_9, " zlib header must be a multiple of 31", 37);
STRING_LITERAL(TM__n9cknNhkm8Fa9boCSB3rtZeA_10, "invalid blockType", 17);
STRING_LITERAL(TM__n9cknNhkm8Fa9boCSB3rtZeA_11, "NLEN is not one\'s complement of LEN", 35);
STRING_LITERAL(TM__n9cknNhkm8Fa9boCSB3rtZeA_12, "reading outside of input buffer", 31);
STRING_LITERAL(TM__n9cknNhkm8Fa9boCSB3rtZeA_13, "oversubscribed", 14);
STRING_LITERAL(TM__n9cknNhkm8Fa9boCSB3rtZeA_14, "the bit pointer is or will go past the memory", 45);
N_LIB_PRIVATE NIM_CONST tyArray__Ntm7bvhzwbE9b2CkMppjB8A CLCL_ORDER__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Znimz_11 = {((NI) 16),
((NI) 17),
((NI) 18),
((NI) 0),
((NI) 8),
((NI) 7),
((NI) 9),
((NI) 6),
((NI) 10),
((NI) 5),
((NI) 11),
((NI) 4),
((NI) 12),
((NI) 3),
((NI) 13),
((NI) 2),
((NI) 14),
((NI) 1),
((NI) 15)}
;
STRING_LITERAL(TM__n9cknNhkm8Fa9boCSB3rtZeA_15, "can\'t repeat previous if i is 0", 31);
STRING_LITERAL(TM__n9cknNhkm8Fa9boCSB3rtZeA_16, "bit pointer jumps past memory", 29);
STRING_LITERAL(TM__n9cknNhkm8Fa9boCSB3rtZeA_17, "i is larger than the amount of codes", 36);
STRING_LITERAL(TM__n9cknNhkm8Fa9boCSB3rtZeA_18, "no endcode", 10);
STRING_LITERAL(TM__n9cknNhkm8Fa9boCSB3rtZeA_19, "wrong jump outside of tree", 26);
STRING_LITERAL(TM__n9cknNhkm8Fa9boCSB3rtZeA_20, "unexisting code, this can never happen", 38);
STRING_LITERAL(TM__n9cknNhkm8Fa9boCSB3rtZeA_21, "the length of the end code 256 must be larger than 0", 52);
N_LIB_PRIVATE NIM_CONST tyArray__s9azk0bXjkHhm7i19ceN41rg LENGTHBASE__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Znimz_7 = {((NI) 3),
((NI) 4),
((NI) 5),
((NI) 6),
((NI) 7),
((NI) 8),
((NI) 9),
((NI) 10),
((NI) 11),
((NI) 13),
((NI) 15),
((NI) 17),
((NI) 19),
((NI) 23),
((NI) 27),
((NI) 31),
((NI) 35),
((NI) 43),
((NI) 51),
((NI) 59),
((NI) 67),
((NI) 83),
((NI) 99),
((NI) 115),
((NI) 131),
((NI) 163),
((NI) 195),
((NI) 227),
((NI) 258)}
;
N_LIB_PRIVATE NIM_CONST tyArray__s9azk0bXjkHhm7i19ceN41rg LENGTHEXTRA__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Znimz_8 = {((NI) 0),
((NI) 0),
((NI) 0),
((NI) 0),
((NI) 0),
((NI) 0),
((NI) 0),
((NI) 0),
((NI) 1),
((NI) 1),
((NI) 1),
((NI) 1),
((NI) 2),
((NI) 2),
((NI) 2),
((NI) 2),
((NI) 3),
((NI) 3),
((NI) 3),
((NI) 3),
((NI) 4),
((NI) 4),
((NI) 4),
((NI) 4),
((NI) 5),
((NI) 5),
((NI) 5),
((NI) 5),
((NI) 0)}
;
STRING_LITERAL(TM__n9cknNhkm8Fa9boCSB3rtZeA_22, "invalid distance code (30-31 are never used)", 44);
N_LIB_PRIVATE NIM_CONST tyArray__q0oNe3lONaLAJQxP9c7FTZA DISTANCEBASE__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Znimz_9 = {((NI) 1),
((NI) 2),
((NI) 3),
((NI) 4),
((NI) 5),
((NI) 7),
((NI) 9),
((NI) 13),
((NI) 17),
((NI) 25),
((NI) 33),
((NI) 49),
((NI) 65),
((NI) 97),
((NI) 129),
((NI) 193),
((NI) 257),
((NI) 385),
((NI) 513),
((NI) 769),
((NI) 1025),
((NI) 1537),
((NI) 2049),
((NI) 3073),
((NI) 4097),
((NI) 6145),
((NI) 8193),
((NI) 12289),
((NI) 16385),
((NI) 24577)}
;
N_LIB_PRIVATE NIM_CONST tyArray__q0oNe3lONaLAJQxP9c7FTZA DISTANCEEXTRA__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Znimz_10 = {((NI) 0),
((NI) 0),
((NI) 0),
((NI) 0),
((NI) 1),
((NI) 1),
((NI) 2),
((NI) 2),
((NI) 3),
((NI) 3),
((NI) 4),
((NI) 4),
((NI) 5),
((NI) 5),
((NI) 6),
((NI) 6),
((NI) 7),
((NI) 7),
((NI) 8),
((NI) 8),
((NI) 9),
((NI) 9),
((NI) 10),
((NI) 10),
((NI) 11),
((NI) 11),
((NI) 12),
((NI) 12),
((NI) 13),
((NI) 13)}
;
STRING_LITERAL(TM__n9cknNhkm8Fa9boCSB3rtZeA_23, "too long backward distance", 26);
STRING_LITERAL(TM__n9cknNhkm8Fa9boCSB3rtZeA_24, "adler checksum not correct, data must be corrupted", 50);
extern NIM_THREADVAR tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ gch__system_5772;
static N_NIMCALL(void, Marker_tyRef__VNtHIlFk6DdHbJolR3Euzg)(void* p, NI op) {
	tyObject_nzStreamcolonObjectType___uAEM0djdUGvrhRJcCteRig* a;
	a = (tyObject_nzStreamcolonObjectType___uAEM0djdUGvrhRJcCteRig*)p;
	nimGCvisit((void*)(*a).bits.data, op);
	nimGCvisit((void*)(*a).data, op);
}
N_LIB_PRIVATE N_NIMCALL(tyObject_nzStreamcolonObjectType___uAEM0djdUGvrhRJcCteRig*, nzInit__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Znimz_1650)(void) {
	tyObject_nzStreamcolonObjectType___uAEM0djdUGvrhRJcCteRig* result;
	tyObject_nzStreamcolonObjectType___uAEM0djdUGvrhRJcCteRig* T1_;
	result = NIM_NIL;
	T1_ = NIM_NIL;
	T1_ = (tyObject_nzStreamcolonObjectType___uAEM0djdUGvrhRJcCteRig*) newObj((&NTInzstream__VNtHIlFk6DdHbJolR3Euzg_), sizeof(tyObject_nzStreamcolonObjectType___uAEM0djdUGvrhRJcCteRig));
	(*T1_).btype = ((NI) 2);
	(*T1_).use_lz77 = NIM_TRUE;
	(*T1_).windowsize = ((NI) 2048);
	(*T1_).minmatch = ((NI) 3);
	(*T1_).nicematch = ((NI) 128);
	(*T1_).lazymatching = NIM_TRUE;
	(*T1_).ignoreAdler32 = NIM_FALSE;
	result = T1_;
	return result;
}
static N_INLINE(NI, pluspercent___system_696)(NI x, NI y) {
	NI result;
	result = (NI)0;
	result = ((NI) ((NU)((NU64)(((NU) (x))) + (NU64)(((NU) (y))))));
	return result;
}
static N_INLINE(void, incRef__system_5877)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c) {
	(*c).refcount = pluspercent___system_696((*c).refcount, ((NI) 8));
}
static N_INLINE(NI, minuspercent___system_716)(NI x, NI y) {
	NI result;
	result = (NI)0;
	result = ((NI) ((NU)((NU64)(((NU) (x))) - (NU64)(((NU) (y))))));
	return result;
}
static N_INLINE(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell__system_5839)(void* usr) {
	tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* result;
	NI T1_;
	result = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;
	T1_ = (NI)0;
	T1_ = minuspercent___system_716(((NI) (ptrdiff_t) (usr)), ((NI) 16));
	result = ((tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*) (T1_));
	return result;
}
static N_INLINE(NIM_BOOL, ltpercent___system_1005)(NI x, NI y) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	result = ((NU64)(((NU) (x))) < (NU64)(((NU) (y))));
	return result;
}
static N_INLINE(void, rtlAddZCT__system_5882)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c) {
	addZCT__system_5833((&gch__system_5772.zct), c);
}
static N_INLINE(void, decRef__system_5884)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c) {
	(*c).refcount = minuspercent___system_716((*c).refcount, ((NI) 8));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = ltpercent___system_1005((*c).refcount, ((NI) 8));
		if (!T3_) goto LA4_;
		rtlAddZCT__system_5882(c);
	}
	LA4_: ;
}
static N_INLINE(void, asgnRef)(void** dest, void* src) {
	{
		tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* T5_;
		if (!!((src == NIM_NIL))) goto LA3_;
		T5_ = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T5_ = usrToCell__system_5839(src);
		incRef__system_5877(T5_);
	}
	LA3_: ;
	{
		tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* T10_;
		if (!!(((*dest) == NIM_NIL))) goto LA8_;
		T10_ = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T10_ = usrToCell__system_5839((*dest));
		decRef__system_5884(T10_);
	}
	LA8_: ;
	(*dest) = src;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_nzStreamcolonObjectType___uAEM0djdUGvrhRJcCteRig*, nzInflateInit__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Znimz_1690)(NimStringDesc* input) {
	tyObject_nzStreamcolonObjectType___uAEM0djdUGvrhRJcCteRig* result;
	tyObject_nzStreamcolonObjectType___uAEM0djdUGvrhRJcCteRig* nz;
	result = NIM_NIL;
	nz = nzInit__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Znimz_1650();
	asgnRef((void**) (&(*nz).data), rawNewString(((NI) 5242880)));
	asgnRef((void**) (&(*nz).bits.data), input);
	(*nz).bits.bitpointer = ((NI) 0);
	(*nz).bits.databitlen = (NI)((input ? input->Sup.len : 0) * ((NI) 8));
	(*nz).mode = ((tyEnum_nzStreamMode__84qAxH4EmXmdSDCwYfjvFQ) 1);
	result = nz;
	return result;
}
static N_NIMCALL(void, Marker_tyRef__8EFTeb6IiMkqB59a5RstjVw)(void* p, NI op) {
	tyObject_NZError__Ihv5tO001K9aPAxxhJbC4Cw* a;
	a = (tyObject_NZError__Ihv5tO001K9aPAxxhJbC4Cw*)p;
	nimGCvisit((void*)(*a).Sup.Sup.parent, op);
	nimGCvisit((void*)(*a).Sup.Sup.message, op);
	nimGCvisit((void*)(*a).Sup.Sup.trace, op);
	nimGCvisit((void*)(*a).Sup.Sup.up, op);
}
static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* T1_;
	T1_ = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;
	T1_ = usrToCell__system_5839(p);
	decRef__system_5884(T1_);
}
N_LIB_PRIVATE N_NIMCALL(NI, readByte__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Znimz_721)(tyObject_BitStream__1VvBM1ZRgURezk58VPkyyg* s) {
	NI result;
	NI p;
	result = (NI)0;
	{
		while (1) {
			if (!!(((NI)((*s).bitpointer & ((NI) 7)) == ((NI) 0)))) goto LA2;
			(*s).bitpointer += ((NI) 1);
		} LA2: ;
	}
	p = (NI)((*s).bitpointer / ((NI) 8));
	{
		tyObject_NZError__Ihv5tO001K9aPAxxhJbC4Cw* T7_;
		NimStringDesc* T8_;
		if (!(((*s).data ? (*s).data->Sup.len : 0) <= (NI)(p + ((NI) 1)))) goto LA5_;
		T7_ = NIM_NIL;
		T7_ = (tyObject_NZError__Ihv5tO001K9aPAxxhJbC4Cw*) newObj((&NTIrefnzerror__8EFTeb6IiMkqB59a5RstjVw_), sizeof(tyObject_NZError__Ihv5tO001K9aPAxxhJbC4Cw));
		(*T7_).Sup.Sup.Sup.m_type = (&NTInzerror__Ihv5tO001K9aPAxxhJbC4Cw_);
		(*T7_).Sup.Sup.name = "NZError";
		T8_ = NIM_NIL;
		T8_ = (*T7_).Sup.Sup.message; (*T7_).Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TM__n9cknNhkm8Fa9boCSB3rtZeA_8));
		if (T8_) nimGCunrefNoCycle(T8_);
		asgnRef((void**) (&(*T7_).Sup.Sup.parent), ((Exception*) NIM_NIL));
		raiseExceptionEx((Exception*)T7_, "NZError", "readByte", "nimz.nim", 422);
	}
	LA5_: ;
	result = ((NU8)((*s).data->data[p]));
	(*s).bitpointer += ((NI) 8);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NU32, readInt32__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Znimz_1775)(NimStringDesc* input) {
	NU32 result;
	result = (NU32)0;
	result = (NU32)((NU64)(((NU32) (((NU8)(input->data[((NI) 0)]))))) << (NU64)(((NI) 24)));
	result += (NU32)((NU64)(((NU32) (((NU8)(input->data[((NI) 1)]))))) << (NU64)(((NI) 16)));
	result += (NU32)((NU64)(((NU32) (((NU8)(input->data[((NI) 2)]))))) << (NU64)(((NI) 8)));
	result += ((NU32) (((NU8)(input->data[((NI) 3)]))));
	return result;
}
static N_INLINE(NI, readBit__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Znimz_85)(tyObject_BitStream__1VvBM1ZRgURezk58VPkyyg s) {
	NI result;
	result = (NI)0;
	result = (NI)((NI)((NI64)(((NU8)(s.data->data[(NI)((NI64)(s.bitpointer) >> (NU64)(((NI) 3)))]))) >> (NU64)((NI)(s.bitpointer & ((NI) 7)))) & ((NI) 1));
	return result;
}
static N_INLINE(NI, readBitFromStream__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Znimz_99)(tyObject_BitStream__1VvBM1ZRgURezk58VPkyyg* s) {
	NI result;
	result = (NI)0;
	result = readBit__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Znimz_85((*s));
	(*s).bitpointer += ((NI) 1);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, readInt16__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Znimz_699)(tyObject_BitStream__1VvBM1ZRgURezk58VPkyyg* s) {
	NI result;
	NI p;
	result = (NI)0;
	{
		while (1) {
			if (!!(((NI)((*s).bitpointer & ((NI) 7)) == ((NI) 0)))) goto LA2;
			(*s).bitpointer += ((NI) 1);
		} LA2: ;
	}
	p = (NI)((*s).bitpointer / ((NI) 8));
	{
		tyObject_NZError__Ihv5tO001K9aPAxxhJbC4Cw* T7_;
		NimStringDesc* T8_;
		if (!(((*s).data ? (*s).data->Sup.len : 0) < (NI)(p + ((NI) 2)))) goto LA5_;
		T7_ = NIM_NIL;
		T7_ = (tyObject_NZError__Ihv5tO001K9aPAxxhJbC4Cw*) newObj((&NTIrefnzerror__8EFTeb6IiMkqB59a5RstjVw_), sizeof(tyObject_NZError__Ihv5tO001K9aPAxxhJbC4Cw));
		(*T7_).Sup.Sup.Sup.m_type = (&NTInzerror__Ihv5tO001K9aPAxxhJbC4Cw_);
		(*T7_).Sup.Sup.name = "NZError";
		T8_ = NIM_NIL;
		T8_ = (*T7_).Sup.Sup.message; (*T7_).Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TM__n9cknNhkm8Fa9boCSB3rtZeA_8));
		if (T8_) nimGCunrefNoCycle(T8_);
		asgnRef((void**) (&(*T7_).Sup.Sup.parent), ((Exception*) NIM_NIL));
		raiseExceptionEx((Exception*)T7_, "NZError", "readInt16", "nimz.nim", 412);
	}
	LA5_: ;
	result = (NI)(((NU8)((*s).data->data[p])) + (NI)(((NI) 256) * ((NU8)((*s).data->data[(NI)(p + ((NI) 1))]))));
	(*s).bitpointer += ((NI) 16);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, getBytePosition__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Znimz_718)(tyObject_BitStream__1VvBM1ZRgURezk58VPkyyg* s) {
	NI result;
	result = (NI)0;
	result = (NI)((*s).bitpointer / ((NI) 8));
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, inflateNoCompression__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Znimz_737)(tyObject_nzStreamcolonObjectType___uAEM0djdUGvrhRJcCteRig* nz) {
	NI inlength;
	NI LEN;
	NI NLEN;
	NI p;
	NI pos;
	inlength = ((*nz).bits.data ? (*nz).bits.data->Sup.len : 0);
	LEN = readInt16__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Znimz_699((&(*nz).bits));
	NLEN = readInt16__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Znimz_699((&(*nz).bits));
	{
		tyObject_NZError__Ihv5tO001K9aPAxxhJbC4Cw* T5_;
		NimStringDesc* T6_;
		if (!!(((NI)(LEN + NLEN) == ((NI) 65535)))) goto LA3_;
		T5_ = NIM_NIL;
		T5_ = (tyObject_NZError__Ihv5tO001K9aPAxxhJbC4Cw*) newObj((&NTIrefnzerror__8EFTeb6IiMkqB59a5RstjVw_), sizeof(tyObject_NZError__Ihv5tO001K9aPAxxhJbC4Cw));
		(*T5_).Sup.Sup.Sup.m_type = (&NTInzerror__Ihv5tO001K9aPAxxhJbC4Cw_);
		(*T5_).Sup.Sup.name = "NZError";
		T6_ = NIM_NIL;
		T6_ = (*T5_).Sup.Sup.message; (*T5_).Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TM__n9cknNhkm8Fa9boCSB3rtZeA_11));
		if (T6_) nimGCunrefNoCycle(T6_);
		asgnRef((void**) (&(*T5_).Sup.Sup.parent), ((Exception*) NIM_NIL));
		raiseExceptionEx((Exception*)T5_, "NZError", "inflateNoCompression", "nimz.nim", 435);
	}
	LA3_: ;
	p = getBytePosition__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Znimz_718((&(*nz).bits));
	{
		tyObject_NZError__Ihv5tO001K9aPAxxhJbC4Cw* T11_;
		NimStringDesc* T12_;
		if (!(inlength < (NI)(p + LEN))) goto LA9_;
		T11_ = NIM_NIL;
		T11_ = (tyObject_NZError__Ihv5tO001K9aPAxxhJbC4Cw*) newObj((&NTIrefnzerror__8EFTeb6IiMkqB59a5RstjVw_), sizeof(tyObject_NZError__Ihv5tO001K9aPAxxhJbC4Cw));
		(*T11_).Sup.Sup.Sup.m_type = (&NTInzerror__Ihv5tO001K9aPAxxhJbC4Cw_);
		(*T11_).Sup.Sup.name = "NZError";
		T12_ = NIM_NIL;
		T12_ = (*T11_).Sup.Sup.message; (*T11_).Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TM__n9cknNhkm8Fa9boCSB3rtZeA_12));
		if (T12_) nimGCunrefNoCycle(T12_);
		asgnRef((void**) (&(*T11_).Sup.Sup.parent), ((Exception*) NIM_NIL));
		raiseExceptionEx((Exception*)T11_, "NZError", "inflateNoCompression", "nimz.nim", 440);
	}
	LA9_: ;
	pos = ((*nz).data ? (*nz).data->Sup.len : 0);
	asgnRef((void**) (&(*nz).data), setLengthStr((*nz).data, ((NI) ((NI)(pos + LEN)))));
	{
		NI i;
		NI colontmp_;
		NI res;
		i = (NI)0;
		colontmp_ = (NI)0;
		colontmp_ = (NI)(LEN - ((NI) 1));
		res = ((NI) 0);
		{
			while (1) {
				if (!(res <= colontmp_)) goto LA15;
				i = res;
				(*nz).data->data[pos] = (*nz).bits.data->data[p];
				pos += ((NI) 1);
				p += ((NI) 1);
				res += ((NI) 1);
			} LA15: ;
		}
	}
	(*nz).bits.bitpointer = (NI)(p * ((NI) 8));
}
static N_INLINE(void, nimSetMem__systemZmemory_7)(void* a, int v, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a, v, ((size_t) (size)));
}
static N_INLINE(void, nimZeroMem)(void* p, NI size) {
	nimSetMem__systemZmemory_7(p, ((int) 0), size);
}
N_LIB_PRIVATE N_NIMCALL(void, HuffmanTree_makeFromLengths2__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Znimz_224)(tyObject_HuffmanTree__jJCPIerUDiHKi9bQLvybbzA* tree) {
	tySequence__qwqHTkRvwhrRyENtudHQ7g* blcount;
	tySequence__qwqHTkRvwhrRyENtudHQ7g* nextcode;
	unsureAsgnRef((void**) (&(*tree).tree1d), newSeq__pureZosproc_150(((NI) ((*tree).numcodes))));
	blcount = newSeq__pureZosproc_150(((NI) ((NI)((*tree).maxbitlen + ((NI) 1)))));
	nextcode = newSeq__pureZosproc_150(((NI) ((NI)((*tree).maxbitlen + ((NI) 1)))));
	{
		NI* len;
		NI i;
		NI L;
		NI T2_;
		len = (NI*)0;
		i = ((NI) 0);
		T2_ = ((*tree).lengths ? (*tree).lengths->Sup.len : 0);
		L = T2_;
		{
			while (1) {
				if (!(i < L)) goto LA4;
				len = (&(*tree).lengths->data[i]);
				blcount->data[(*len)] += ((NI) 1);
				i += ((NI) 1);
			} LA4: ;
		}
	}
	{
		NI bits;
		NI res;
		bits = (NI)0;
		res = ((NI) 1);
		{
			while (1) {
				if (!(res <= (*tree).maxbitlen)) goto LA7;
				bits = res;
				nextcode->data[bits] = (NI)((NU64)((NI)(nextcode->data[(NI)(bits - ((NI) 1))] + blcount->data[(NI)(bits - ((NI) 1))])) << (NU64)(((NI) 1)));
				res += ((NI) 1);
			} LA7: ;
		}
	}
	{
		NI n;
		NI colontmp_;
		NI res_2;
		n = (NI)0;
		colontmp_ = (NI)0;
		colontmp_ = (NI)((*tree).numcodes - ((NI) 1));
		res_2 = ((NI) 0);
		{
			while (1) {
				NI len_2;
				if (!(res_2 <= colontmp_)) goto LA10;
				n = res_2;
				len_2 = (*tree).lengths->data[n];
				{
					if (!!((len_2 == ((NI) 0)))) goto LA13_;
					(*tree).tree1d->data[n] = nextcode->data[len_2];
					nextcode->data[len_2] += ((NI) 1);
				}
				LA13_: ;
				res_2 += ((NI) 1);
			} LA10: ;
		}
	}
}
N_LIB_PRIVATE N_NIMCALL(void, HuffmanTree_make2DTree__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Znimz_167)(tyObject_HuffmanTree__jJCPIerUDiHKi9bQLvybbzA* tree) {
	NI nodefilled;
	NI treepos;
	tySequence__qwqHTkRvwhrRyENtudHQ7g* resultX60gensym3_;
	nodefilled = ((NI) 0);
	treepos = ((NI) 0);
	resultX60gensym3_ = newSeq__pureZosproc_150(((NI) ((NI)((*tree).numcodes * ((NI) 2)))));
	{
		NI iX60gensym3_;
		NI colontmp_;
		NI i;
		iX60gensym3_ = (NI)0;
		colontmp_ = (NI)0;
		colontmp_ = (NI)((*tree).numcodes * ((NI) 2));
		i = ((NI) 0);
		{
			while (1) {
				if (!(i < colontmp_)) goto LA3;
				iX60gensym3_ = i;
				resultX60gensym3_->data[iX60gensym3_] = ((NI) 32767);
				i += ((NI) 1);
			} LA3: ;
		}
	}
	unsureAsgnRef((void**) (&(*tree).tree2d), resultX60gensym3_);
	resultX60gensym3_ = NIM_NIL;
	{
		NI n;
		NI colontmp__2;
		NI res;
		n = (NI)0;
		colontmp__2 = (NI)0;
		colontmp__2 = (NI)((*tree).numcodes - ((NI) 1));
		res = ((NI) 0);
		{
			while (1) {
				NI len;
				if (!(res <= colontmp__2)) goto LA6;
				n = res;
				len = (*tree).lengths->data[n];
				{
					NI i_2;
					NI colontmp__3;
					NI res_2;
					i_2 = (NI)0;
					colontmp__3 = (NI)0;
					colontmp__3 = (NI)(len - ((NI) 1));
					res_2 = ((NI) 0);
					{
						while (1) {
							if (!(res_2 <= colontmp__3)) goto LA9;
							i_2 = res_2;
							{
								NI bit;
								NI branch;
								bit = (NI)((NI)((NI64)((*tree).tree1d->data[n]) >> (NU64)((NI)((NI)(len - i_2) - ((NI) 1)))) & ((NI) 1));
								branch = (NI)((NI)(((NI) 2) * treepos) + bit);
								{
									NIM_BOOL T13_;
									tyObject_NZError__Ihv5tO001K9aPAxxhJbC4Cw* T17_;
									NimStringDesc* T18_;
									T13_ = (NIM_BOOL)0;
									T13_ = (((NI) 2147483647) < treepos);
									if (T13_) goto LA14_;
									T13_ = ((*tree).numcodes < (NI)(treepos + ((NI) 2)));
									LA14_: ;
									if (!T13_) goto LA15_;
									T17_ = NIM_NIL;
									T17_ = (tyObject_NZError__Ihv5tO001K9aPAxxhJbC4Cw*) newObj((&NTIrefnzerror__8EFTeb6IiMkqB59a5RstjVw_), sizeof(tyObject_NZError__Ihv5tO001K9aPAxxhJbC4Cw));
									(*T17_).Sup.Sup.Sup.m_type = (&NTInzerror__Ihv5tO001K9aPAxxhJbC4Cw_);
									(*T17_).Sup.Sup.name = "NZError";
									T18_ = NIM_NIL;
									T18_ = (*T17_).Sup.Sup.message; (*T17_).Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TM__n9cknNhkm8Fa9boCSB3rtZeA_13));
									if (T18_) nimGCunrefNoCycle(T18_);
									asgnRef((void**) (&(*T17_).Sup.Sup.parent), ((Exception*) NIM_NIL));
									raiseExceptionEx((Exception*)T17_, "NZError", "HuffmanTree_make2DTree", "nimz.nim", 183);
								}
								LA15_: ;
								{
									if (!!(((*tree).tree2d->data[branch] == ((NI) 32767)))) goto LA21_;
									treepos = (NI)((*tree).tree2d->data[branch] - (*tree).numcodes);
									goto LA10;
								}
								LA21_: ;
								{
									if (!((NI)(i_2 + ((NI) 1)) < len)) goto LA25_;
									nodefilled += ((NI) 1);
									(*tree).tree2d->data[branch] = (NI)(nodefilled + (*tree).numcodes);
									treepos = nodefilled;
									goto LA10;
								}
								LA25_: ;
								(*tree).tree2d->data[branch] = n;
								treepos = ((NI) 0);
							} LA10: ;
							res_2 += ((NI) 1);
						} LA9: ;
					}
				}
				res += ((NI) 1);
			} LA6: ;
		}
	}
	{
		NI iX60gensym9_;
		NI colontmp__4;
		NI T28_;
		NI res_3;
		iX60gensym9_ = (NI)0;
		colontmp__4 = (NI)0;
		T28_ = (((*tree).tree2d ? (*tree).tree2d->Sup.len : 0)-1);
		colontmp__4 = T28_;
		res_3 = ((NI) 0);
		{
			while (1) {
				NI it;
				if (!(res_3 <= colontmp__4)) goto LA30;
				iX60gensym9_ = res_3;
				it = (*tree).tree2d->data[iX60gensym9_];
				{
					if (!(it == ((NI) 32767))) goto LA33_;
					(*tree).tree2d->data[iX60gensym9_] = ((NI) 0);
				}
				goto LA31_;
				LA33_: ;
				{
					(*tree).tree2d->data[iX60gensym9_] = it;
				}
				LA31_: ;
				res_3 += ((NI) 1);
			} LA30: ;
		}
	}
}
N_LIB_PRIVATE N_NIMCALL(void, HuffmanTree_makeFromLengths__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Znimz_292)(tyObject_HuffmanTree__jJCPIerUDiHKi9bQLvybbzA* tree, NI* bitlen, NI bitlenLen_0, NI maxbitlen) {
	unsureAsgnRef((void**) (&(*tree).lengths), at___OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Znimz_296(bitlen, bitlenLen_0));
	(*tree).numcodes = bitlenLen_0;
	(*tree).maxbitlen = maxbitlen;
	HuffmanTree_makeFromLengths2__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Znimz_224(tree);
	HuffmanTree_make2DTree__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Znimz_167(tree);
}
N_LIB_PRIVATE N_NIMCALL(void, generateFixedLitLenTree__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Znimz_633)(tyObject_HuffmanTree__jJCPIerUDiHKi9bQLvybbzA* tree) {
	tyArray__OwOytieXUe4SPSxAsbsyEA bitlen;
	nimZeroMem((void*)bitlen, sizeof(tyArray__OwOytieXUe4SPSxAsbsyEA));
	{
		NI i;
		NI res;
		i = (NI)0;
		res = ((NI) 0);
		{
			while (1) {
				if (!(res <= ((NI) 143))) goto LA3;
				i = res;
				bitlen[(i)- 0] = ((NI) 8);
				res += ((NI) 1);
			} LA3: ;
		}
	}
	{
		NI i_2;
		NI res_2;
		i_2 = (NI)0;
		res_2 = ((NI) 144);
		{
			while (1) {
				if (!(res_2 <= ((NI) 255))) goto LA6;
				i_2 = res_2;
				bitlen[(i_2)- 0] = ((NI) 9);
				res_2 += ((NI) 1);
			} LA6: ;
		}
	}
	{
		NI i_3;
		NI res_3;
		i_3 = (NI)0;
		res_3 = ((NI) 256);
		{
			while (1) {
				if (!(res_3 <= ((NI) 279))) goto LA9;
				i_3 = res_3;
				bitlen[(i_3)- 0] = ((NI) 7);
				res_3 += ((NI) 1);
			} LA9: ;
		}
	}
	{
		NI i_4;
		NI res_4;
		i_4 = (NI)0;
		res_4 = ((NI) 280);
		{
			while (1) {
				if (!(res_4 <= ((NI) 287))) goto LA12;
				i_4 = res_4;
				bitlen[(i_4)- 0] = ((NI) 8);
				res_4 += ((NI) 1);
			} LA12: ;
		}
	}
	HuffmanTree_makeFromLengths__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Znimz_292(tree, bitlen, 288, ((NI) 15));
}
N_LIB_PRIVATE N_NIMCALL(void, generateFixedDistanceTree__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Znimz_674)(tyObject_HuffmanTree__jJCPIerUDiHKi9bQLvybbzA* tree) {
	tyArray__OYqzMMAeF9bf1yDDPNUyDgg bitlen;
	nimZeroMem((void*)bitlen, sizeof(tyArray__OYqzMMAeF9bf1yDDPNUyDgg));
	{
		NI i;
		NI res;
		i = (NI)0;
		res = ((NI) 0);
		{
			while (1) {
				if (!(res <= ((NI) 31))) goto LA3;
				i = res;
				bitlen[(i)- 0] = ((NI) 5);
				res += ((NI) 1);
			} LA3: ;
		}
	}
	HuffmanTree_makeFromLengths__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Znimz_292(tree, bitlen, 32, ((NI) 15));
}
N_LIB_PRIVATE N_NIMCALL(void, getTreeInflateFixed__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Znimz_759)(tyObject_HuffmanTree__jJCPIerUDiHKi9bQLvybbzA* tree_ll, tyObject_HuffmanTree__jJCPIerUDiHKi9bQLvybbzA* tree_d) {
	generateFixedLitLenTree__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Znimz_633(tree_ll);
	generateFixedDistanceTree__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Znimz_674(tree_d);
}
N_LIB_PRIVATE N_NIMCALL(NI, readBitsFromStream__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Znimz_106)(tyObject_BitStream__1VvBM1ZRgURezk58VPkyyg* s, NI nbits) {
	NI result;
	result = (NI)0;
	{
		NI i;
		NI colontmp_;
		NI res;
		i = (NI)0;
		colontmp_ = (NI)0;
		colontmp_ = (NI)(nbits - ((NI) 1));
		res = ((NI) 0);
		{
			while (1) {
				NI T4_;
				if (!(res <= colontmp_)) goto LA3;
				i = res;
				T4_ = (NI)0;
				T4_ = readBit__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Znimz_85((*s));
				result += (NI)((NU64)(T4_) << (NU64)(i));
				(*s).bitpointer += ((NI) 1);
				res += ((NI) 1);
			} LA3: ;
		}
	}
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, huffmanDecodeSymbol__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Znimz_762)(tyObject_BitStream__1VvBM1ZRgURezk58VPkyyg* s, tyObject_HuffmanTree__jJCPIerUDiHKi9bQLvybbzA* codetree, NI inbitlength) {
	NI result;
	NI treepos;
{	result = (NI)0;
	treepos = ((NI) 0);
	{
		while (1) {
			NI ct;
			NI T7_;
			{
				if (!(inbitlength <= (*s).bitpointer)) goto LA5_;
				result = ((NI) -1);
				goto BeforeRet_;
			}
			LA5_: ;
			T7_ = (NI)0;
			T7_ = readBit__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Znimz_85((*s));
			ct = (*codetree).tree2d->data[(NI)((NI)((NU64)(treepos) << (NU64)(((NI) 1))) + T7_)];
			(*s).bitpointer += ((NI) 1);
			{
				if (!(ct < (*codetree).numcodes)) goto LA10_;
				result = ct;
				goto BeforeRet_;
			}
			goto LA8_;
			LA10_: ;
			{
				treepos = (NI)(ct - (*codetree).numcodes);
			}
			LA8_: ;
			{
				if (!((*codetree).numcodes <= treepos)) goto LA15_;
				result = ((NI) -1);
				goto BeforeRet_;
			}
			LA15_: ;
		}
	}
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, readBitsSafe__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Znimz_127)(tyObject_BitStream__1VvBM1ZRgURezk58VPkyyg* s, NI nbits) {
	NI result;
	result = (NI)0;
	{
		tyObject_NZError__Ihv5tO001K9aPAxxhJbC4Cw* T5_;
		NimStringDesc* T6_;
		if (!((*s).databitlen < (NI)((*s).bitpointer + nbits))) goto LA3_;
		T5_ = NIM_NIL;
		T5_ = (tyObject_NZError__Ihv5tO001K9aPAxxhJbC4Cw*) newObj((&NTIrefnzerror__8EFTeb6IiMkqB59a5RstjVw_), sizeof(tyObject_NZError__Ihv5tO001K9aPAxxhJbC4Cw));
		(*T5_).Sup.Sup.Sup.m_type = (&NTInzerror__Ihv5tO001K9aPAxxhJbC4Cw_);
		(*T5_).Sup.Sup.name = "NZError";
		T6_ = NIM_NIL;
		T6_ = (*T5_).Sup.Sup.message; (*T5_).Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TM__n9cknNhkm8Fa9boCSB3rtZeA_16));
		if (T6_) nimGCunrefNoCycle(T6_);
		asgnRef((void**) (&(*T5_).Sup.Sup.parent), ((Exception*) NIM_NIL));
		raiseExceptionEx((Exception*)T5_, "NZError", "readBitsSafe", "nimz.nim", 153);
	}
	LA3_: ;
	{
		NI i;
		NI colontmp_;
		NI res;
		i = (NI)0;
		colontmp_ = (NI)0;
		colontmp_ = (NI)(nbits - ((NI) 1));
		res = ((NI) 0);
		{
			while (1) {
				NI T10_;
				if (!(res <= colontmp_)) goto LA9;
				i = res;
				T10_ = (NI)0;
				T10_ = readBit__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Znimz_85((*s));
				result += (NI)((NU64)(T10_) << (NU64)(i));
				(*s).bitpointer += ((NI) 1);
				res += ((NI) 1);
			} LA9: ;
		}
	}
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, getTreeInflateDynamic__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Znimz_777)(tyObject_BitStream__1VvBM1ZRgURezk58VPkyyg* s, tyObject_HuffmanTree__jJCPIerUDiHKi9bQLvybbzA* tree_ll, tyObject_HuffmanTree__jJCPIerUDiHKi9bQLvybbzA* tree_d) {
	NI inlength;
	NI inbitlength;
	tySequence__qwqHTkRvwhrRyENtudHQ7g* bitlen_ll;
	tySequence__qwqHTkRvwhrRyENtudHQ7g* bitlen_d;
	tySequence__qwqHTkRvwhrRyENtudHQ7g* bitlen_cl;
	tyObject_HuffmanTree__jJCPIerUDiHKi9bQLvybbzA tree_cl;
	NI HLIT;
	NI T7_;
	NI HDIST;
	NI T8_;
	NI HCLEN;
	NI T9_;
	NI i_2;
	inlength = ((*s).data ? (*s).data->Sup.len : 0);
	inbitlength = (NI)(inlength * ((NI) 8));
	bitlen_ll = newSeq__pureZosproc_150(((NI) 288));
	bitlen_d = newSeq__pureZosproc_150(((NI) 32));
	bitlen_cl = newSeq__pureZosproc_150(((NI) 19));
	nimZeroMem((void*)(&tree_cl), sizeof(tyObject_HuffmanTree__jJCPIerUDiHKi9bQLvybbzA));
	{
		tyObject_NZError__Ihv5tO001K9aPAxxhJbC4Cw* T5_;
		NimStringDesc* T6_;
		if (!(inbitlength < (NI)((*s).bitpointer + ((NI) 14)))) goto LA3_;
		T5_ = NIM_NIL;
		T5_ = (tyObject_NZError__Ihv5tO001K9aPAxxhJbC4Cw*) newObj((&NTIrefnzerror__8EFTeb6IiMkqB59a5RstjVw_), sizeof(tyObject_NZError__Ihv5tO001K9aPAxxhJbC4Cw));
		(*T5_).Sup.Sup.Sup.m_type = (&NTInzerror__Ihv5tO001K9aPAxxhJbC4Cw_);
		(*T5_).Sup.Sup.name = "NZError";
		T6_ = NIM_NIL;
		T6_ = (*T5_).Sup.Sup.message; (*T5_).Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TM__n9cknNhkm8Fa9boCSB3rtZeA_14));
		if (T6_) nimGCunrefNoCycle(T6_);
		asgnRef((void**) (&(*T5_).Sup.Sup.parent), ((Exception*) NIM_NIL));
		raiseExceptionEx((Exception*)T5_, "NZError", "getTreeInflateDynamic", "nimz.nim", 497);
	}
	LA3_: ;
	T7_ = (NI)0;
	T7_ = readBitsFromStream__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Znimz_106(s, ((NI) 5));
	HLIT = (NI)(T7_ + ((NI) 257));
	T8_ = (NI)0;
	T8_ = readBitsFromStream__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Znimz_106(s, ((NI) 5));
	HDIST = (NI)(T8_ + ((NI) 1));
	T9_ = (NI)0;
	T9_ = readBitsFromStream__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Znimz_106(s, ((NI) 4));
	HCLEN = (NI)(T9_ + ((NI) 4));
	{
		tyObject_NZError__Ihv5tO001K9aPAxxhJbC4Cw* T14_;
		NimStringDesc* T15_;
		if (!(inbitlength < (NI)((*s).bitpointer + (NI)(HCLEN * ((NI) 3))))) goto LA12_;
		T14_ = NIM_NIL;
		T14_ = (tyObject_NZError__Ihv5tO001K9aPAxxhJbC4Cw*) newObj((&NTIrefnzerror__8EFTeb6IiMkqB59a5RstjVw_), sizeof(tyObject_NZError__Ihv5tO001K9aPAxxhJbC4Cw));
		(*T14_).Sup.Sup.Sup.m_type = (&NTInzerror__Ihv5tO001K9aPAxxhJbC4Cw_);
		(*T14_).Sup.Sup.name = "NZError";
		T15_ = NIM_NIL;
		T15_ = (*T14_).Sup.Sup.message; (*T14_).Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TM__n9cknNhkm8Fa9boCSB3rtZeA_14));
		if (T15_) nimGCunrefNoCycle(T15_);
		asgnRef((void**) (&(*T14_).Sup.Sup.parent), ((Exception*) NIM_NIL));
		raiseExceptionEx((Exception*)T14_, "NZError", "getTreeInflateDynamic", "nimz.nim", 511);
	}
	LA12_: ;
	{
		NI i;
		NI res;
		i = (NI)0;
		res = ((NI) 0);
		{
			while (1) {
				if (!(res <= ((NI) 18))) goto LA18;
				i = res;
				{
					if (!(i < HCLEN)) goto LA21_;
					bitlen_cl->data[CLCL_ORDER__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Znimz_11[(i)- 0]] = readBitsFromStream__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Znimz_106(s, ((NI) 3));
				}
				goto LA19_;
				LA21_: ;
				{
					bitlen_cl->data[CLCL_ORDER__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Znimz_11[(i)- 0]] = ((NI) 0);
				}
				LA19_: ;
				res += ((NI) 1);
			} LA18: ;
		}
	}
	HuffmanTree_makeFromLengths__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Znimz_292((&tree_cl), bitlen_cl->data, (bitlen_cl ? bitlen_cl->Sup.len : 0), ((NI) 7));
	i_2 = ((NI) 0);
	{
		while (1) {
			NI code;
			if (!(i_2 < (NI)(HLIT + HDIST))) goto LA25;
			code = huffmanDecodeSymbol__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Znimz_762(s, (&tree_cl), inbitlength);
			{
				if (!(code <= ((NI) 15))) goto LA28_;
				{
					if (!(i_2 < HLIT)) goto LA32_;
					bitlen_ll->data[i_2] = code;
				}
				goto LA30_;
				LA32_: ;
				{
					bitlen_d->data[(NI)(i_2 - HLIT)] = code;
				}
				LA30_: ;
				i_2 += ((NI) 1);
			}
			goto LA26_;
			LA28_: ;
			{
				NI replength;
				NI value;
				NI T44_;
				if (!(code == ((NI) 16))) goto LA36_;
				replength = ((NI) 3);
				value = ((NI) 0);
				{
					tyObject_NZError__Ihv5tO001K9aPAxxhJbC4Cw* T42_;
					NimStringDesc* T43_;
					if (!(i_2 == ((NI) 0))) goto LA40_;
					T42_ = NIM_NIL;
					T42_ = (tyObject_NZError__Ihv5tO001K9aPAxxhJbC4Cw*) newObj((&NTIrefnzerror__8EFTeb6IiMkqB59a5RstjVw_), sizeof(tyObject_NZError__Ihv5tO001K9aPAxxhJbC4Cw));
					(*T42_).Sup.Sup.Sup.m_type = (&NTInzerror__Ihv5tO001K9aPAxxhJbC4Cw_);
					(*T42_).Sup.Sup.name = "NZError";
					T43_ = NIM_NIL;
					T43_ = (*T42_).Sup.Sup.message; (*T42_).Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TM__n9cknNhkm8Fa9boCSB3rtZeA_15));
					if (T43_) nimGCunrefNoCycle(T43_);
					asgnRef((void**) (&(*T42_).Sup.Sup.parent), ((Exception*) NIM_NIL));
					raiseExceptionEx((Exception*)T42_, "NZError", "getTreeInflateDynamic", "nimz.nim", 535);
				}
				LA40_: ;
				T44_ = (NI)0;
				T44_ = readBitsSafe__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Znimz_127(s, ((NI) 2));
				replength += T44_;
				{
					if (!(i_2 < (NI)(HLIT + ((NI) 1)))) goto LA47_;
					value = bitlen_ll->data[(NI)(i_2 - ((NI) 1))];
				}
				goto LA45_;
				LA47_: ;
				{
					value = bitlen_d->data[(NI)((NI)(i_2 - HLIT) - ((NI) 1))];
				}
				LA45_: ;
				{
					NI n;
					NI colontmp_;
					NI res_2;
					n = (NI)0;
					colontmp_ = (NI)0;
					colontmp_ = (NI)(replength - ((NI) 1));
					res_2 = ((NI) 0);
					{
						while (1) {
							if (!(res_2 <= colontmp_)) goto LA52;
							n = res_2;
							{
								tyObject_NZError__Ihv5tO001K9aPAxxhJbC4Cw* T57_;
								NimStringDesc* T58_;
								if (!((NI)(HLIT + HDIST) <= i_2)) goto LA55_;
								T57_ = NIM_NIL;
								T57_ = (tyObject_NZError__Ihv5tO001K9aPAxxhJbC4Cw*) newObj((&NTIrefnzerror__8EFTeb6IiMkqB59a5RstjVw_), sizeof(tyObject_NZError__Ihv5tO001K9aPAxxhJbC4Cw));
								(*T57_).Sup.Sup.Sup.m_type = (&NTInzerror__Ihv5tO001K9aPAxxhJbC4Cw_);
								(*T57_).Sup.Sup.name = "NZError";
								T58_ = NIM_NIL;
								T58_ = (*T57_).Sup.Sup.message; (*T57_).Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TM__n9cknNhkm8Fa9boCSB3rtZeA_17));
								if (T58_) nimGCunrefNoCycle(T58_);
								asgnRef((void**) (&(*T57_).Sup.Sup.parent), ((Exception*) NIM_NIL));
								raiseExceptionEx((Exception*)T57_, "NZError", "getTreeInflateDynamic", "nimz.nim", 543);
							}
							LA55_: ;
							{
								if (!(i_2 < HLIT)) goto LA61_;
								bitlen_ll->data[i_2] = value;
							}
							goto LA59_;
							LA61_: ;
							{
								bitlen_d->data[(NI)(i_2 - HLIT)] = value;
							}
							LA59_: ;
							i_2 += ((NI) 1);
							res_2 += ((NI) 1);
						} LA52: ;
					}
				}
			}
			goto LA26_;
			LA36_: ;
			{
				NI replength_2;
				NI T67_;
				if (!(code == ((NI) 17))) goto LA65_;
				replength_2 = ((NI) 3);
				T67_ = (NI)0;
				T67_ = readBitsSafe__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Znimz_127(s, ((NI) 3));
				replength_2 += T67_;
				{
					NI n_2;
					NI colontmp__2;
					NI res_3;
					n_2 = (NI)0;
					colontmp__2 = (NI)0;
					colontmp__2 = (NI)(replength_2 - ((NI) 1));
					res_3 = ((NI) 0);
					{
						while (1) {
							if (!(res_3 <= colontmp__2)) goto LA70;
							n_2 = res_3;
							{
								tyObject_NZError__Ihv5tO001K9aPAxxhJbC4Cw* T75_;
								NimStringDesc* T76_;
								if (!((NI)(HLIT + HDIST) <= i_2)) goto LA73_;
								T75_ = NIM_NIL;
								T75_ = (tyObject_NZError__Ihv5tO001K9aPAxxhJbC4Cw*) newObj((&NTIrefnzerror__8EFTeb6IiMkqB59a5RstjVw_), sizeof(tyObject_NZError__Ihv5tO001K9aPAxxhJbC4Cw));
								(*T75_).Sup.Sup.Sup.m_type = (&NTInzerror__Ihv5tO001K9aPAxxhJbC4Cw_);
								(*T75_).Sup.Sup.name = "NZError";
								T76_ = NIM_NIL;
								T76_ = (*T75_).Sup.Sup.message; (*T75_).Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TM__n9cknNhkm8Fa9boCSB3rtZeA_17));
								if (T76_) nimGCunrefNoCycle(T76_);
								asgnRef((void**) (&(*T75_).Sup.Sup.parent), ((Exception*) NIM_NIL));
								raiseExceptionEx((Exception*)T75_, "NZError", "getTreeInflateDynamic", "nimz.nim", 553);
							}
							LA73_: ;
							{
								if (!(i_2 < HLIT)) goto LA79_;
								bitlen_ll->data[i_2] = ((NI) 0);
							}
							goto LA77_;
							LA79_: ;
							{
								bitlen_d->data[(NI)(i_2 - HLIT)] = ((NI) 0);
							}
							LA77_: ;
							i_2 += ((NI) 1);
							res_3 += ((NI) 1);
						} LA70: ;
					}
				}
			}
			goto LA26_;
			LA65_: ;
			{
				NI replength_3;
				NI T85_;
				if (!(code == ((NI) 18))) goto LA83_;
				replength_3 = ((NI) 11);
				T85_ = (NI)0;
				T85_ = readBitsSafe__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Znimz_127(s, ((NI) 7));
				replength_3 += T85_;
				{
					NI n_3;
					NI colontmp__3;
					NI res_4;
					n_3 = (NI)0;
					colontmp__3 = (NI)0;
					colontmp__3 = (NI)(replength_3 - ((NI) 1));
					res_4 = ((NI) 0);
					{
						while (1) {
							if (!(res_4 <= colontmp__3)) goto LA88;
							n_3 = res_4;
							{
								tyObject_NZError__Ihv5tO001K9aPAxxhJbC4Cw* T93_;
								NimStringDesc* T94_;
								if (!((NI)(HLIT + HDIST) <= i_2)) goto LA91_;
								T93_ = NIM_NIL;
								T93_ = (tyObject_NZError__Ihv5tO001K9aPAxxhJbC4Cw*) newObj((&NTIrefnzerror__8EFTeb6IiMkqB59a5RstjVw_), sizeof(tyObject_NZError__Ihv5tO001K9aPAxxhJbC4Cw));
								(*T93_).Sup.Sup.Sup.m_type = (&NTInzerror__Ihv5tO001K9aPAxxhJbC4Cw_);
								(*T93_).Sup.Sup.name = "NZError";
								T94_ = NIM_NIL;
								T94_ = (*T93_).Sup.Sup.message; (*T93_).Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TM__n9cknNhkm8Fa9boCSB3rtZeA_17));
								if (T94_) nimGCunrefNoCycle(T94_);
								asgnRef((void**) (&(*T93_).Sup.Sup.parent), ((Exception*) NIM_NIL));
								raiseExceptionEx((Exception*)T93_, "NZError", "getTreeInflateDynamic", "nimz.nim", 563);
							}
							LA91_: ;
							{
								if (!(i_2 < HLIT)) goto LA97_;
								bitlen_ll->data[i_2] = ((NI) 0);
							}
							goto LA95_;
							LA97_: ;
							{
								bitlen_d->data[(NI)(i_2 - HLIT)] = ((NI) 0);
							}
							LA95_: ;
							i_2 += ((NI) 1);
							res_4 += ((NI) 1);
						} LA88: ;
					}
				}
			}
			goto LA26_;
			LA83_: ;
			{
				{
					if (!(code == ((NI) -1))) goto LA103_;
					{
						tyObject_NZError__Ihv5tO001K9aPAxxhJbC4Cw* T109_;
						NimStringDesc* T110_;
						if (!(inbitlength < (*s).bitpointer)) goto LA107_;
						T109_ = NIM_NIL;
						T109_ = (tyObject_NZError__Ihv5tO001K9aPAxxhJbC4Cw*) newObj((&NTIrefnzerror__8EFTeb6IiMkqB59a5RstjVw_), sizeof(tyObject_NZError__Ihv5tO001K9aPAxxhJbC4Cw));
						(*T109_).Sup.Sup.Sup.m_type = (&NTInzerror__Ihv5tO001K9aPAxxhJbC4Cw_);
						(*T109_).Sup.Sup.name = "NZError";
						T110_ = NIM_NIL;
						T110_ = (*T109_).Sup.Sup.message; (*T109_).Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TM__n9cknNhkm8Fa9boCSB3rtZeA_18));
						if (T110_) nimGCunrefNoCycle(T110_);
						asgnRef((void**) (&(*T109_).Sup.Sup.parent), ((Exception*) NIM_NIL));
						raiseExceptionEx((Exception*)T109_, "NZError", "getTreeInflateDynamic", "nimz.nim", 571);
					}
					goto LA105_;
					LA107_: ;
					{
						tyObject_NZError__Ihv5tO001K9aPAxxhJbC4Cw* T112_;
						NimStringDesc* T113_;
						T112_ = NIM_NIL;
						T112_ = (tyObject_NZError__Ihv5tO001K9aPAxxhJbC4Cw*) newObj((&NTIrefnzerror__8EFTeb6IiMkqB59a5RstjVw_), sizeof(tyObject_NZError__Ihv5tO001K9aPAxxhJbC4Cw));
						(*T112_).Sup.Sup.Sup.m_type = (&NTInzerror__Ihv5tO001K9aPAxxhJbC4Cw_);
						(*T112_).Sup.Sup.name = "NZError";
						T113_ = NIM_NIL;
						T113_ = (*T112_).Sup.Sup.message; (*T112_).Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TM__n9cknNhkm8Fa9boCSB3rtZeA_19));
						if (T113_) nimGCunrefNoCycle(T113_);
						asgnRef((void**) (&(*T112_).Sup.Sup.parent), ((Exception*) NIM_NIL));
						raiseExceptionEx((Exception*)T112_, "NZError", "getTreeInflateDynamic", "nimz.nim", 572);
					}
					LA105_: ;
				}
				goto LA101_;
				LA103_: ;
				{
					tyObject_NZError__Ihv5tO001K9aPAxxhJbC4Cw* T115_;
					NimStringDesc* T116_;
					T115_ = NIM_NIL;
					T115_ = (tyObject_NZError__Ihv5tO001K9aPAxxhJbC4Cw*) newObj((&NTIrefnzerror__8EFTeb6IiMkqB59a5RstjVw_), sizeof(tyObject_NZError__Ihv5tO001K9aPAxxhJbC4Cw));
					(*T115_).Sup.Sup.Sup.m_type = (&NTInzerror__Ihv5tO001K9aPAxxhJbC4Cw_);
					(*T115_).Sup.Sup.name = "NZError";
					T116_ = NIM_NIL;
					T116_ = (*T115_).Sup.Sup.message; (*T115_).Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TM__n9cknNhkm8Fa9boCSB3rtZeA_20));
					if (T116_) nimGCunrefNoCycle(T116_);
					asgnRef((void**) (&(*T115_).Sup.Sup.parent), ((Exception*) NIM_NIL));
					raiseExceptionEx((Exception*)T115_, "NZError", "getTreeInflateDynamic", "nimz.nim", 574);
				}
				LA101_: ;
				goto LA24;
			}
			LA26_: ;
		} LA25: ;
	} LA24: ;
	{
		tyObject_NZError__Ihv5tO001K9aPAxxhJbC4Cw* T121_;
		NimStringDesc* T122_;
		if (!(bitlen_ll->data[((NI) 256)] == ((NI) 0))) goto LA119_;
		T121_ = NIM_NIL;
		T121_ = (tyObject_NZError__Ihv5tO001K9aPAxxhJbC4Cw*) newObj((&NTIrefnzerror__8EFTeb6IiMkqB59a5RstjVw_), sizeof(tyObject_NZError__Ihv5tO001K9aPAxxhJbC4Cw));
		(*T121_).Sup.Sup.Sup.m_type = (&NTInzerror__Ihv5tO001K9aPAxxhJbC4Cw_);
		(*T121_).Sup.Sup.name = "NZError";
		T122_ = NIM_NIL;
		T122_ = (*T121_).Sup.Sup.message; (*T121_).Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TM__n9cknNhkm8Fa9boCSB3rtZeA_21));
		if (T122_) nimGCunrefNoCycle(T122_);
		asgnRef((void**) (&(*T121_).Sup.Sup.parent), ((Exception*) NIM_NIL));
		raiseExceptionEx((Exception*)T121_, "NZError", "getTreeInflateDynamic", "nimz.nim", 578);
	}
	LA119_: ;
	HuffmanTree_makeFromLengths__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Znimz_292(tree_ll, bitlen_ll->data, (bitlen_ll ? bitlen_ll->Sup.len : 0), ((NI) 15));
	HuffmanTree_makeFromLengths__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Znimz_292(tree_d, bitlen_d->data, (bitlen_d ? bitlen_d->Sup.len : 0), ((NI) 15));
}
N_LIB_PRIVATE N_NIMCALL(void, inflateHuffmanBlock__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Znimz_893)(tyObject_nzStreamcolonObjectType___uAEM0djdUGvrhRJcCteRig* nz, NI blockType) {
	tyObject_HuffmanTree__jJCPIerUDiHKi9bQLvybbzA tree_ll;
	tyObject_HuffmanTree__jJCPIerUDiHKi9bQLvybbzA tree_d;
	NI inlength;
	NI inbitlength;
	nimZeroMem((void*)(&tree_ll), sizeof(tyObject_HuffmanTree__jJCPIerUDiHKi9bQLvybbzA));
	nimZeroMem((void*)(&tree_d), sizeof(tyObject_HuffmanTree__jJCPIerUDiHKi9bQLvybbzA));
	inlength = ((*nz).bits.data ? (*nz).bits.data->Sup.len : 0);
	inbitlength = (NI)(inlength * ((NI) 8));
	{
		if (!(blockType == ((NI) 1))) goto LA3_;
		getTreeInflateFixed__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Znimz_759((&tree_ll), (&tree_d));
	}
	goto LA1_;
	LA3_: ;
	{
		if (!(blockType == ((NI) 2))) goto LA6_;
		getTreeInflateDynamic__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Znimz_777((&(*nz).bits), (&tree_ll), (&tree_d));
	}
	goto LA1_;
	LA6_: ;
	LA1_: ;
	{
		while (1) {
			NI code_ll;
			code_ll = huffmanDecodeSymbol__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Znimz_762((&(*nz).bits), (&tree_ll), inbitlength);
			{
				if (!(code_ll <= ((NI) 255))) goto LA12_;
				asgnRef((void**) (&(*nz).data), addChar((*nz).data, ((NIM_CHAR) (((NI) (code_ll))))));
			}
			goto LA10_;
			LA12_: ;
			{
				NIM_BOOL T15_;
				NI length;
				NI numextrabits_l;
				NI T19_;
				NI code_d;
				NI distance;
				NI numextrabits_d;
				NI T40_;
				NI start;
				NI backward;
				T15_ = (NIM_BOOL)0;
				T15_ = (((NI) 257) <= code_ll);
				if (!(T15_)) goto LA16_;
				T15_ = (code_ll <= ((NI) 285));
				LA16_: ;
				if (!T15_) goto LA17_;
				length = LENGTHBASE__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Znimz_7[((NI)(code_ll - ((NI) 257)))- 0];
				numextrabits_l = LENGTHEXTRA__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Znimz_8[((NI)(code_ll - ((NI) 257)))- 0];
				T19_ = (NI)0;
				T19_ = readBitsSafe__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Znimz_127((&(*nz).bits), numextrabits_l);
				length += T19_;
				code_d = huffmanDecodeSymbol__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Znimz_762((&(*nz).bits), (&tree_d), inbitlength);
				{
					if (!(((NI) 29) < code_d)) goto LA22_;
					{
						if (!(code_ll == ((NI) -1))) goto LA26_;
						{
							tyObject_NZError__Ihv5tO001K9aPAxxhJbC4Cw* T32_;
							NimStringDesc* T33_;
							if (!(inbitlength < (*nz).bits.bitpointer)) goto LA30_;
							T32_ = NIM_NIL;
							T32_ = (tyObject_NZError__Ihv5tO001K9aPAxxhJbC4Cw*) newObj((&NTIrefnzerror__8EFTeb6IiMkqB59a5RstjVw_), sizeof(tyObject_NZError__Ihv5tO001K9aPAxxhJbC4Cw));
							(*T32_).Sup.Sup.Sup.m_type = (&NTInzerror__Ihv5tO001K9aPAxxhJbC4Cw_);
							(*T32_).Sup.Sup.name = "NZError";
							T33_ = NIM_NIL;
							T33_ = (*T32_).Sup.Sup.message; (*T32_).Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TM__n9cknNhkm8Fa9boCSB3rtZeA_18));
							if (T33_) nimGCunrefNoCycle(T33_);
							asgnRef((void**) (&(*T32_).Sup.Sup.parent), ((Exception*) NIM_NIL));
							raiseExceptionEx((Exception*)T32_, "NZError", "inflateHuffmanBlock", "nimz.nim", 615);
						}
						goto LA28_;
						LA30_: ;
						{
							tyObject_NZError__Ihv5tO001K9aPAxxhJbC4Cw* T35_;
							NimStringDesc* T36_;
							T35_ = NIM_NIL;
							T35_ = (tyObject_NZError__Ihv5tO001K9aPAxxhJbC4Cw*) newObj((&NTIrefnzerror__8EFTeb6IiMkqB59a5RstjVw_), sizeof(tyObject_NZError__Ihv5tO001K9aPAxxhJbC4Cw));
							(*T35_).Sup.Sup.Sup.m_type = (&NTInzerror__Ihv5tO001K9aPAxxhJbC4Cw_);
							(*T35_).Sup.Sup.name = "NZError";
							T36_ = NIM_NIL;
							T36_ = (*T35_).Sup.Sup.message; (*T35_).Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TM__n9cknNhkm8Fa9boCSB3rtZeA_19));
							if (T36_) nimGCunrefNoCycle(T36_);
							asgnRef((void**) (&(*T35_).Sup.Sup.parent), ((Exception*) NIM_NIL));
							raiseExceptionEx((Exception*)T35_, "NZError", "inflateHuffmanBlock", "nimz.nim", 616);
						}
						LA28_: ;
					}
					goto LA24_;
					LA26_: ;
					{
						tyObject_NZError__Ihv5tO001K9aPAxxhJbC4Cw* T38_;
						NimStringDesc* T39_;
						T38_ = NIM_NIL;
						T38_ = (tyObject_NZError__Ihv5tO001K9aPAxxhJbC4Cw*) newObj((&NTIrefnzerror__8EFTeb6IiMkqB59a5RstjVw_), sizeof(tyObject_NZError__Ihv5tO001K9aPAxxhJbC4Cw));
						(*T38_).Sup.Sup.Sup.m_type = (&NTInzerror__Ihv5tO001K9aPAxxhJbC4Cw_);
						(*T38_).Sup.Sup.name = "NZError";
						T39_ = NIM_NIL;
						T39_ = (*T38_).Sup.Sup.message; (*T38_).Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TM__n9cknNhkm8Fa9boCSB3rtZeA_22));
						if (T39_) nimGCunrefNoCycle(T39_);
						asgnRef((void**) (&(*T38_).Sup.Sup.parent), ((Exception*) NIM_NIL));
						raiseExceptionEx((Exception*)T38_, "NZError", "inflateHuffmanBlock", "nimz.nim", 618);
					}
					LA24_: ;
					goto LA8;
				}
				LA22_: ;
				distance = DISTANCEBASE__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Znimz_9[(code_d)- 0];
				numextrabits_d = DISTANCEEXTRA__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Znimz_10[(code_d)- 0];
				T40_ = (NI)0;
				T40_ = readBitsSafe__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Znimz_127((&(*nz).bits), numextrabits_d);
				distance += T40_;
				start = ((*nz).data ? (*nz).data->Sup.len : 0);
				{
					tyObject_NZError__Ihv5tO001K9aPAxxhJbC4Cw* T45_;
					NimStringDesc* T46_;
					if (!(start < distance)) goto LA43_;
					T45_ = NIM_NIL;
					T45_ = (tyObject_NZError__Ihv5tO001K9aPAxxhJbC4Cw*) newObj((&NTIrefnzerror__8EFTeb6IiMkqB59a5RstjVw_), sizeof(tyObject_NZError__Ihv5tO001K9aPAxxhJbC4Cw));
					(*T45_).Sup.Sup.Sup.m_type = (&NTInzerror__Ihv5tO001K9aPAxxhJbC4Cw_);
					(*T45_).Sup.Sup.name = "NZError";
					T46_ = NIM_NIL;
					T46_ = (*T45_).Sup.Sup.message; (*T45_).Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TM__n9cknNhkm8Fa9boCSB3rtZeA_23));
					if (T46_) nimGCunrefNoCycle(T46_);
					asgnRef((void**) (&(*T45_).Sup.Sup.parent), ((Exception*) NIM_NIL));
					raiseExceptionEx((Exception*)T45_, "NZError", "inflateHuffmanBlock", "nimz.nim", 629);
				}
				LA43_: ;
				backward = (NI)(start - distance);
				asgnRef((void**) (&(*nz).data), setLengthStr((*nz).data, ((NI) ((NI)(start + length)))));
				{
					NI pos;
					NI colontmp_;
					NI res;
					pos = (NI)0;
					colontmp_ = (NI)0;
					colontmp_ = (NI)(length - ((NI) 1));
					res = ((NI) 0);
					{
						while (1) {
							if (!(res <= colontmp_)) goto LA49;
							pos = res;
							(*nz).data->data[(NI)(pos + start)] = (*nz).data->data[backward];
							backward += ((NI) 1);
							{
								if (!(start <= backward)) goto LA52_;
								backward = (NI)(start - distance);
							}
							LA52_: ;
							res += ((NI) 1);
						} LA49: ;
					}
				}
			}
			goto LA10_;
			LA17_: ;
			{
				if (!(code_ll == ((NI) 256))) goto LA55_;
				goto LA8;
			}
			goto LA10_;
			LA55_: ;
			{
				{
					tyObject_NZError__Ihv5tO001K9aPAxxhJbC4Cw* T62_;
					NimStringDesc* T63_;
					if (!(inbitlength < (*nz).bits.bitpointer)) goto LA60_;
					T62_ = NIM_NIL;
					T62_ = (tyObject_NZError__Ihv5tO001K9aPAxxhJbC4Cw*) newObj((&NTIrefnzerror__8EFTeb6IiMkqB59a5RstjVw_), sizeof(tyObject_NZError__Ihv5tO001K9aPAxxhJbC4Cw));
					(*T62_).Sup.Sup.Sup.m_type = (&NTInzerror__Ihv5tO001K9aPAxxhJbC4Cw_);
					(*T62_).Sup.Sup.name = "NZError";
					T63_ = NIM_NIL;
					T63_ = (*T62_).Sup.Sup.message; (*T62_).Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TM__n9cknNhkm8Fa9boCSB3rtZeA_18));
					if (T63_) nimGCunrefNoCycle(T63_);
					asgnRef((void**) (&(*T62_).Sup.Sup.parent), ((Exception*) NIM_NIL));
					raiseExceptionEx((Exception*)T62_, "NZError", "inflateHuffmanBlock", "nimz.nim", 642);
				}
				goto LA58_;
				LA60_: ;
				{
					tyObject_NZError__Ihv5tO001K9aPAxxhJbC4Cw* T65_;
					NimStringDesc* T66_;
					T65_ = NIM_NIL;
					T65_ = (tyObject_NZError__Ihv5tO001K9aPAxxhJbC4Cw*) newObj((&NTIrefnzerror__8EFTeb6IiMkqB59a5RstjVw_), sizeof(tyObject_NZError__Ihv5tO001K9aPAxxhJbC4Cw));
					(*T65_).Sup.Sup.Sup.m_type = (&NTInzerror__Ihv5tO001K9aPAxxhJbC4Cw_);
					(*T65_).Sup.Sup.name = "NZError";
					T66_ = NIM_NIL;
					T66_ = (*T65_).Sup.Sup.message; (*T65_).Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TM__n9cknNhkm8Fa9boCSB3rtZeA_19));
					if (T66_) nimGCunrefNoCycle(T66_);
					asgnRef((void**) (&(*T65_).Sup.Sup.parent), ((Exception*) NIM_NIL));
					raiseExceptionEx((Exception*)T65_, "NZError", "inflateHuffmanBlock", "nimz.nim", 643);
				}
				LA58_: ;
				goto LA8;
			}
			LA10_: ;
		}
	} LA8: ;
}
N_LIB_PRIVATE N_NIMCALL(void, nzInflate__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Znimz_940)(tyObject_nzStreamcolonObjectType___uAEM0djdUGvrhRJcCteRig* nz) {
	NIM_BOOL finalBlock;
	NI streamLen;
	finalBlock = NIM_FALSE;
	streamLen = (*nz).bits.databitlen;
	{
		while (1) {
			NI T7_;
			NI blockType;
			NI T8_;
			NI T9_;
			if (!!(finalBlock)) goto LA2;
			{
				if (!(streamLen <= (NI)((*nz).bits.bitpointer + ((NI) 2)))) goto LA5_;
				goto LA1;
			}
			LA5_: ;
			T7_ = (NI)0;
			T7_ = readBitFromStream__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Znimz_99((&(*nz).bits));
			finalBlock = !((T7_ == ((NI) 0)));
			T8_ = (NI)0;
			T8_ = readBitFromStream__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Znimz_99((&(*nz).bits));
			T9_ = (NI)0;
			T9_ = readBitFromStream__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Znimz_99((&(*nz).bits));
			blockType = (NI)(T8_ + (NI)(((NI) 2) * T9_));
			{
				tyObject_NZError__Ihv5tO001K9aPAxxhJbC4Cw* T14_;
				NimStringDesc* T15_;
				if (!(blockType == ((NI) 3))) goto LA12_;
				T14_ = NIM_NIL;
				T14_ = (tyObject_NZError__Ihv5tO001K9aPAxxhJbC4Cw*) newObj((&NTIrefnzerror__8EFTeb6IiMkqB59a5RstjVw_), sizeof(tyObject_NZError__Ihv5tO001K9aPAxxhJbC4Cw));
				(*T14_).Sup.Sup.Sup.m_type = (&NTInzerror__Ihv5tO001K9aPAxxhJbC4Cw_);
				(*T14_).Sup.Sup.name = "NZError";
				T15_ = NIM_NIL;
				T15_ = (*T14_).Sup.Sup.message; (*T14_).Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TM__n9cknNhkm8Fa9boCSB3rtZeA_10));
				if (T15_) nimGCunrefNoCycle(T15_);
				asgnRef((void**) (&(*T14_).Sup.Sup.parent), ((Exception*) NIM_NIL));
				raiseExceptionEx((Exception*)T14_, "NZError", "nzInflate", "nimz.nim", 657);
			}
			goto LA10_;
			LA12_: ;
			{
				if (!(blockType == ((NI) 0))) goto LA17_;
				inflateNoCompression__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Znimz_737(nz);
			}
			goto LA10_;
			LA17_: ;
			{
				inflateHuffmanBlock__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Znimz_893(nz, blockType);
			}
			LA10_: ;
		} LA2: ;
	} LA1: ;
}
N_LIB_PRIVATE N_NIMCALL(NU32, nzAdler32__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Znimz_1704)(NU32 adler, NimStringDesc* data) {
	NU32 result;
	NU32 s1;
	NU32 s2;
	NI len;
	NI i;
	result = (NU32)0;
	s1 = (NU32)(adler & ((NU32) 65535));
	s2 = (NU32)((NU32)((NU32)(adler) >> (NU64)(((NI) 16))) & ((NU32) 65535));
	len = (data ? data->Sup.len : 0);
	i = ((NI) 0);
	{
		while (1) {
			NI amount;
			if (!(((NI) 0) < len)) goto LA2;
			amount = ((len <= ((NI) 5550)) ? len : ((NI) 5550));
			len -= amount;
			{
				while (1) {
					if (!(((NI) 0) < amount)) goto LA4;
					s1 += ((NU32) ((NI)(((NU8)(data->data[i])) | ((NI) 0))));
					s2 += s1;
					amount -= ((NI) 1);
					i += ((NI) 1);
				} LA4: ;
			}
			s1 = (NU32)((NU32)(s1) % (NU32)(((NU32) 65521)));
			s2 = (NU32)((NU32)(s2) % (NU32)(((NU32) 65521)));
		} LA2: ;
	}
	result = (NU32)((NU32)((NU32)(s2) << (NU32)(((NU32) 16))) | s1);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, nzGetResult__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Znimz_1696)(tyObject_nzStreamcolonObjectType___uAEM0djdUGvrhRJcCteRig* nz) {
	NimStringDesc* result;
{	result = NIM_NIL;
	{
		if (!((*nz).mode == ((tyEnum_nzStreamMode__84qAxH4EmXmdSDCwYfjvFQ) 1))) goto LA3_;
		result = copyString((*nz).data);
		goto BeforeRet_;
	}
	LA3_: ;
	result = copyString((*nz).bits.data);
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, zlib_decompress__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Znimz_1817)(tyObject_nzStreamcolonObjectType___uAEM0djdUGvrhRJcCteRig* nz) {
	NimStringDesc* result;
	NI insize;
	NI CMF;
	NI FLG;
	NU32 checksum;
	NimStringDesc* T13_;
	result = NIM_NIL;
	insize = ((*nz).bits.data ? (*nz).bits.data->Sup.len : 0);
	{
		tyObject_NZError__Ihv5tO001K9aPAxxhJbC4Cw* T5_;
		NimStringDesc* T6_;
		if (!(insize < ((NI) 2))) goto LA3_;
		T5_ = NIM_NIL;
		T5_ = (tyObject_NZError__Ihv5tO001K9aPAxxhJbC4Cw*) newObj((&NTIrefnzerror__8EFTeb6IiMkqB59a5RstjVw_), sizeof(tyObject_NZError__Ihv5tO001K9aPAxxhJbC4Cw));
		(*T5_).Sup.Sup.Sup.m_type = (&NTInzerror__Ihv5tO001K9aPAxxhJbC4Cw_);
		(*T5_).Sup.Sup.name = "NZError";
		T6_ = NIM_NIL;
		T6_ = (*T5_).Sup.Sup.message; (*T5_).Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TM__n9cknNhkm8Fa9boCSB3rtZeA_7));
		if (T6_) nimGCunrefNoCycle(T6_);
		asgnRef((void**) (&(*T5_).Sup.Sup.parent), ((Exception*) NIM_NIL));
		raiseExceptionEx((Exception*)T5_, "NZError", "zlib_decompress", "nimz.nim", 1310);
	}
	LA3_: ;
	CMF = readByte__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Znimz_721((&(*nz).bits));
	FLG = readByte__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Znimz_721((&(*nz).bits));
	{
		tyObject_NZError__Ihv5tO001K9aPAxxhJbC4Cw* T11_;
		NimStringDesc* T12_;
		if (!!(((NI)((NI)((NI)(CMF * ((NI) 256)) + FLG) % ((NI) 31)) == ((NI) 0)))) goto LA9_;
		T11_ = NIM_NIL;
		T11_ = (tyObject_NZError__Ihv5tO001K9aPAxxhJbC4Cw*) newObj((&NTIrefnzerror__8EFTeb6IiMkqB59a5RstjVw_), sizeof(tyObject_NZError__Ihv5tO001K9aPAxxhJbC4Cw));
		(*T11_).Sup.Sup.Sup.m_type = (&NTInzerror__Ihv5tO001K9aPAxxhJbC4Cw_);
		(*T11_).Sup.Sup.name = "NZError";
		T12_ = NIM_NIL;
		T12_ = (*T11_).Sup.Sup.message; (*T11_).Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TM__n9cknNhkm8Fa9boCSB3rtZeA_9));
		if (T12_) nimGCunrefNoCycle(T12_);
		asgnRef((void**) (&(*T11_).Sup.Sup.parent), ((Exception*) NIM_NIL));
		raiseExceptionEx((Exception*)T11_, "NZError", "zlib_decompress", "nimz.nim", 1317);
	}
	LA9_: ;
	T13_ = NIM_NIL;
	T13_ = substr__system_8679((*nz).bits.data, (NI)(insize - ((NI) 4)), (NI)(insize - ((NI) 1)));
	checksum = readInt32__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Znimz_1775(T13_);
	asgnRef((void**) (&(*nz).bits.data), setLengthStr((*nz).bits.data, ((NI) ((NI)(insize - ((NI) 4))))));
	(*nz).bits.databitlen = (NI)((NI)(insize - ((NI) 4)) * ((NI) 8));
	nzInflate__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Znimz_940(nz);
	{
		NU32 adler32;
		if (!!((*nz).ignoreAdler32)) goto LA16_;
		adler32 = nzAdler32__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Znimz_1704(((NU32) 1), (*nz).data);
		{
			tyObject_NZError__Ihv5tO001K9aPAxxhJbC4Cw* T22_;
			NimStringDesc* T23_;
			if (!!((checksum == adler32))) goto LA20_;
			T22_ = NIM_NIL;
			T22_ = (tyObject_NZError__Ihv5tO001K9aPAxxhJbC4Cw*) newObj((&NTIrefnzerror__8EFTeb6IiMkqB59a5RstjVw_), sizeof(tyObject_NZError__Ihv5tO001K9aPAxxhJbC4Cw));
			(*T22_).Sup.Sup.Sup.m_type = (&NTInzerror__Ihv5tO001K9aPAxxhJbC4Cw_);
			(*T22_).Sup.Sup.name = "NZError";
			T23_ = NIM_NIL;
			T23_ = (*T22_).Sup.Sup.message; (*T22_).Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TM__n9cknNhkm8Fa9boCSB3rtZeA_24));
			if (T23_) nimGCunrefNoCycle(T23_);
			asgnRef((void**) (&(*T22_).Sup.Sup.parent), ((Exception*) NIM_NIL));
			raiseExceptionEx((Exception*)T22_, "NZError", "zlib_decompress", "nimz.nim", 1343);
		}
		LA20_: ;
	}
	LA16_: ;
	result = nzGetResult__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Znimz_1696(nz);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatsdotnimbleatspkgsatsnimPNGminus0dot3dot1atsnimPNGatsnimzdotnim_DatInit000)(void) {
static TNimNode* TM__n9cknNhkm8Fa9boCSB3rtZeA_2_10[10];
static TNimNode* TM__n9cknNhkm8Fa9boCSB3rtZeA_3_3[3];
static TNimNode* TM__n9cknNhkm8Fa9boCSB3rtZeA_4_2[2];
NI TM__n9cknNhkm8Fa9boCSB3rtZeA_6;
static char* NIM_CONST TM__n9cknNhkm8Fa9boCSB3rtZeA_5[2] = {
"nzsDeflate", 
"nzsInflate"};
static TNimNode TM__n9cknNhkm8Fa9boCSB3rtZeA_0[19];
NTInzstream58objecttype__uAEM0djdUGvrhRJcCteRig_.size = sizeof(tyObject_nzStreamcolonObjectType___uAEM0djdUGvrhRJcCteRig);
NTInzstream58objecttype__uAEM0djdUGvrhRJcCteRig_.align = NIM_ALIGNOF(tyObject_nzStreamcolonObjectType___uAEM0djdUGvrhRJcCteRig);
NTInzstream58objecttype__uAEM0djdUGvrhRJcCteRig_.kind = 18;
NTInzstream58objecttype__uAEM0djdUGvrhRJcCteRig_.base = 0;
TM__n9cknNhkm8Fa9boCSB3rtZeA_2_10[0] = &TM__n9cknNhkm8Fa9boCSB3rtZeA_0[1];
NTIint__6YIzl9b2Xq7fIc5qJO0fYVw_.size = sizeof(NI);
NTIint__6YIzl9b2Xq7fIc5qJO0fYVw_.align = NIM_ALIGNOF(NI);
NTIint__6YIzl9b2Xq7fIc5qJO0fYVw_.kind = 31;
NTIint__6YIzl9b2Xq7fIc5qJO0fYVw_.base = 0;
NTIint__6YIzl9b2Xq7fIc5qJO0fYVw_.flags = 3;
TM__n9cknNhkm8Fa9boCSB3rtZeA_0[1].kind = 1;
TM__n9cknNhkm8Fa9boCSB3rtZeA_0[1].offset = offsetof(tyObject_nzStreamcolonObjectType___uAEM0djdUGvrhRJcCteRig, btype);
TM__n9cknNhkm8Fa9boCSB3rtZeA_0[1].typ = (&NTIint__6YIzl9b2Xq7fIc5qJO0fYVw_);
TM__n9cknNhkm8Fa9boCSB3rtZeA_0[1].name = "btype";
TM__n9cknNhkm8Fa9boCSB3rtZeA_2_10[1] = &TM__n9cknNhkm8Fa9boCSB3rtZeA_0[2];
TM__n9cknNhkm8Fa9boCSB3rtZeA_0[2].kind = 1;
TM__n9cknNhkm8Fa9boCSB3rtZeA_0[2].offset = offsetof(tyObject_nzStreamcolonObjectType___uAEM0djdUGvrhRJcCteRig, use_lz77);
TM__n9cknNhkm8Fa9boCSB3rtZeA_0[2].typ = (&NTIbool__VaVACK0bpYmqIQ0mKcHfQQ_);
TM__n9cknNhkm8Fa9boCSB3rtZeA_0[2].name = "use_lz77";
TM__n9cknNhkm8Fa9boCSB3rtZeA_2_10[2] = &TM__n9cknNhkm8Fa9boCSB3rtZeA_0[3];
NTIint__iP0zKMh4CnuWmtNdPhn0xQ_.size = sizeof(NI);
NTIint__iP0zKMh4CnuWmtNdPhn0xQ_.align = NIM_ALIGNOF(NI);
NTIint__iP0zKMh4CnuWmtNdPhn0xQ_.kind = 31;
NTIint__iP0zKMh4CnuWmtNdPhn0xQ_.base = 0;
NTIint__iP0zKMh4CnuWmtNdPhn0xQ_.flags = 3;
TM__n9cknNhkm8Fa9boCSB3rtZeA_0[3].kind = 1;
TM__n9cknNhkm8Fa9boCSB3rtZeA_0[3].offset = offsetof(tyObject_nzStreamcolonObjectType___uAEM0djdUGvrhRJcCteRig, windowsize);
TM__n9cknNhkm8Fa9boCSB3rtZeA_0[3].typ = (&NTIint__iP0zKMh4CnuWmtNdPhn0xQ_);
TM__n9cknNhkm8Fa9boCSB3rtZeA_0[3].name = "windowsize";
TM__n9cknNhkm8Fa9boCSB3rtZeA_2_10[3] = &TM__n9cknNhkm8Fa9boCSB3rtZeA_0[4];
NTIint__5It9aoOeJWaKNUT1V1S4z8Q_.size = sizeof(NI);
NTIint__5It9aoOeJWaKNUT1V1S4z8Q_.align = NIM_ALIGNOF(NI);
NTIint__5It9aoOeJWaKNUT1V1S4z8Q_.kind = 31;
NTIint__5It9aoOeJWaKNUT1V1S4z8Q_.base = 0;
NTIint__5It9aoOeJWaKNUT1V1S4z8Q_.flags = 3;
TM__n9cknNhkm8Fa9boCSB3rtZeA_0[4].kind = 1;
TM__n9cknNhkm8Fa9boCSB3rtZeA_0[4].offset = offsetof(tyObject_nzStreamcolonObjectType___uAEM0djdUGvrhRJcCteRig, minmatch);
TM__n9cknNhkm8Fa9boCSB3rtZeA_0[4].typ = (&NTIint__5It9aoOeJWaKNUT1V1S4z8Q_);
TM__n9cknNhkm8Fa9boCSB3rtZeA_0[4].name = "minmatch";
TM__n9cknNhkm8Fa9boCSB3rtZeA_2_10[4] = &TM__n9cknNhkm8Fa9boCSB3rtZeA_0[5];
NTIint__qg9bcJHx5JH9akIu7ZK7cf4Q_.size = sizeof(NI);
NTIint__qg9bcJHx5JH9akIu7ZK7cf4Q_.align = NIM_ALIGNOF(NI);
NTIint__qg9bcJHx5JH9akIu7ZK7cf4Q_.kind = 31;
NTIint__qg9bcJHx5JH9akIu7ZK7cf4Q_.base = 0;
NTIint__qg9bcJHx5JH9akIu7ZK7cf4Q_.flags = 3;
TM__n9cknNhkm8Fa9boCSB3rtZeA_0[5].kind = 1;
TM__n9cknNhkm8Fa9boCSB3rtZeA_0[5].offset = offsetof(tyObject_nzStreamcolonObjectType___uAEM0djdUGvrhRJcCteRig, nicematch);
TM__n9cknNhkm8Fa9boCSB3rtZeA_0[5].typ = (&NTIint__qg9bcJHx5JH9akIu7ZK7cf4Q_);
TM__n9cknNhkm8Fa9boCSB3rtZeA_0[5].name = "nicematch";
TM__n9cknNhkm8Fa9boCSB3rtZeA_2_10[5] = &TM__n9cknNhkm8Fa9boCSB3rtZeA_0[6];
TM__n9cknNhkm8Fa9boCSB3rtZeA_0[6].kind = 1;
TM__n9cknNhkm8Fa9boCSB3rtZeA_0[6].offset = offsetof(tyObject_nzStreamcolonObjectType___uAEM0djdUGvrhRJcCteRig, lazymatching);
TM__n9cknNhkm8Fa9boCSB3rtZeA_0[6].typ = (&NTIbool__VaVACK0bpYmqIQ0mKcHfQQ_);
TM__n9cknNhkm8Fa9boCSB3rtZeA_0[6].name = "lazymatching";
TM__n9cknNhkm8Fa9boCSB3rtZeA_2_10[6] = &TM__n9cknNhkm8Fa9boCSB3rtZeA_0[7];
NTIbitstream__1VvBM1ZRgURezk58VPkyyg_.size = sizeof(tyObject_BitStream__1VvBM1ZRgURezk58VPkyyg);
NTIbitstream__1VvBM1ZRgURezk58VPkyyg_.align = NIM_ALIGNOF(tyObject_BitStream__1VvBM1ZRgURezk58VPkyyg);
NTIbitstream__1VvBM1ZRgURezk58VPkyyg_.kind = 18;
NTIbitstream__1VvBM1ZRgURezk58VPkyyg_.base = 0;
TM__n9cknNhkm8Fa9boCSB3rtZeA_3_3[0] = &TM__n9cknNhkm8Fa9boCSB3rtZeA_0[9];
TM__n9cknNhkm8Fa9boCSB3rtZeA_0[9].kind = 1;
TM__n9cknNhkm8Fa9boCSB3rtZeA_0[9].offset = offsetof(tyObject_BitStream__1VvBM1ZRgURezk58VPkyyg, bitpointer);
TM__n9cknNhkm8Fa9boCSB3rtZeA_0[9].typ = (&NTIint__rR5Bzr1D5krxoo1NcNyeMA_);
TM__n9cknNhkm8Fa9boCSB3rtZeA_0[9].name = "bitpointer";
TM__n9cknNhkm8Fa9boCSB3rtZeA_3_3[1] = &TM__n9cknNhkm8Fa9boCSB3rtZeA_0[10];
TM__n9cknNhkm8Fa9boCSB3rtZeA_0[10].kind = 1;
TM__n9cknNhkm8Fa9boCSB3rtZeA_0[10].offset = offsetof(tyObject_BitStream__1VvBM1ZRgURezk58VPkyyg, data);
TM__n9cknNhkm8Fa9boCSB3rtZeA_0[10].typ = (&NTIstring__77mFvmsOLKik79ci2hXkHEg_);
TM__n9cknNhkm8Fa9boCSB3rtZeA_0[10].name = "data";
TM__n9cknNhkm8Fa9boCSB3rtZeA_3_3[2] = &TM__n9cknNhkm8Fa9boCSB3rtZeA_0[11];
TM__n9cknNhkm8Fa9boCSB3rtZeA_0[11].kind = 1;
TM__n9cknNhkm8Fa9boCSB3rtZeA_0[11].offset = offsetof(tyObject_BitStream__1VvBM1ZRgURezk58VPkyyg, databitlen);
TM__n9cknNhkm8Fa9boCSB3rtZeA_0[11].typ = (&NTIint__rR5Bzr1D5krxoo1NcNyeMA_);
TM__n9cknNhkm8Fa9boCSB3rtZeA_0[11].name = "databitlen";
TM__n9cknNhkm8Fa9boCSB3rtZeA_0[8].len = 3; TM__n9cknNhkm8Fa9boCSB3rtZeA_0[8].kind = 2; TM__n9cknNhkm8Fa9boCSB3rtZeA_0[8].sons = &TM__n9cknNhkm8Fa9boCSB3rtZeA_3_3[0];
NTIbitstream__1VvBM1ZRgURezk58VPkyyg_.node = &TM__n9cknNhkm8Fa9boCSB3rtZeA_0[8];
TM__n9cknNhkm8Fa9boCSB3rtZeA_0[7].kind = 1;
TM__n9cknNhkm8Fa9boCSB3rtZeA_0[7].offset = offsetof(tyObject_nzStreamcolonObjectType___uAEM0djdUGvrhRJcCteRig, bits);
TM__n9cknNhkm8Fa9boCSB3rtZeA_0[7].typ = (&NTIbitstream__1VvBM1ZRgURezk58VPkyyg_);
TM__n9cknNhkm8Fa9boCSB3rtZeA_0[7].name = "bits";
TM__n9cknNhkm8Fa9boCSB3rtZeA_2_10[7] = &TM__n9cknNhkm8Fa9boCSB3rtZeA_0[12];
TM__n9cknNhkm8Fa9boCSB3rtZeA_0[12].kind = 1;
TM__n9cknNhkm8Fa9boCSB3rtZeA_0[12].offset = offsetof(tyObject_nzStreamcolonObjectType___uAEM0djdUGvrhRJcCteRig, data);
TM__n9cknNhkm8Fa9boCSB3rtZeA_0[12].typ = (&NTIstring__77mFvmsOLKik79ci2hXkHEg_);
TM__n9cknNhkm8Fa9boCSB3rtZeA_0[12].name = "data";
TM__n9cknNhkm8Fa9boCSB3rtZeA_2_10[8] = &TM__n9cknNhkm8Fa9boCSB3rtZeA_0[13];
NTInzstreammode__84qAxH4EmXmdSDCwYfjvFQ_.size = sizeof(tyEnum_nzStreamMode__84qAxH4EmXmdSDCwYfjvFQ);
NTInzstreammode__84qAxH4EmXmdSDCwYfjvFQ_.align = NIM_ALIGNOF(tyEnum_nzStreamMode__84qAxH4EmXmdSDCwYfjvFQ);
NTInzstreammode__84qAxH4EmXmdSDCwYfjvFQ_.kind = 14;
NTInzstreammode__84qAxH4EmXmdSDCwYfjvFQ_.base = 0;
NTInzstreammode__84qAxH4EmXmdSDCwYfjvFQ_.flags = 3;
for (TM__n9cknNhkm8Fa9boCSB3rtZeA_6 = 0; TM__n9cknNhkm8Fa9boCSB3rtZeA_6 < 2; TM__n9cknNhkm8Fa9boCSB3rtZeA_6++) {
TM__n9cknNhkm8Fa9boCSB3rtZeA_0[TM__n9cknNhkm8Fa9boCSB3rtZeA_6+14].kind = 1;
TM__n9cknNhkm8Fa9boCSB3rtZeA_0[TM__n9cknNhkm8Fa9boCSB3rtZeA_6+14].offset = TM__n9cknNhkm8Fa9boCSB3rtZeA_6;
TM__n9cknNhkm8Fa9boCSB3rtZeA_0[TM__n9cknNhkm8Fa9boCSB3rtZeA_6+14].name = TM__n9cknNhkm8Fa9boCSB3rtZeA_5[TM__n9cknNhkm8Fa9boCSB3rtZeA_6];
TM__n9cknNhkm8Fa9boCSB3rtZeA_4_2[TM__n9cknNhkm8Fa9boCSB3rtZeA_6] = &TM__n9cknNhkm8Fa9boCSB3rtZeA_0[TM__n9cknNhkm8Fa9boCSB3rtZeA_6+14];
}
TM__n9cknNhkm8Fa9boCSB3rtZeA_0[16].len = 2; TM__n9cknNhkm8Fa9boCSB3rtZeA_0[16].kind = 2; TM__n9cknNhkm8Fa9boCSB3rtZeA_0[16].sons = &TM__n9cknNhkm8Fa9boCSB3rtZeA_4_2[0];
NTInzstreammode__84qAxH4EmXmdSDCwYfjvFQ_.node = &TM__n9cknNhkm8Fa9boCSB3rtZeA_0[16];
TM__n9cknNhkm8Fa9boCSB3rtZeA_0[13].kind = 1;
TM__n9cknNhkm8Fa9boCSB3rtZeA_0[13].offset = offsetof(tyObject_nzStreamcolonObjectType___uAEM0djdUGvrhRJcCteRig, mode);
TM__n9cknNhkm8Fa9boCSB3rtZeA_0[13].typ = (&NTInzstreammode__84qAxH4EmXmdSDCwYfjvFQ_);
TM__n9cknNhkm8Fa9boCSB3rtZeA_0[13].name = "mode";
TM__n9cknNhkm8Fa9boCSB3rtZeA_2_10[9] = &TM__n9cknNhkm8Fa9boCSB3rtZeA_0[17];
TM__n9cknNhkm8Fa9boCSB3rtZeA_0[17].kind = 1;
TM__n9cknNhkm8Fa9boCSB3rtZeA_0[17].offset = offsetof(tyObject_nzStreamcolonObjectType___uAEM0djdUGvrhRJcCteRig, ignoreAdler32);
TM__n9cknNhkm8Fa9boCSB3rtZeA_0[17].typ = (&NTIbool__VaVACK0bpYmqIQ0mKcHfQQ_);
TM__n9cknNhkm8Fa9boCSB3rtZeA_0[17].name = "ignoreAdler32";
TM__n9cknNhkm8Fa9boCSB3rtZeA_0[0].len = 10; TM__n9cknNhkm8Fa9boCSB3rtZeA_0[0].kind = 2; TM__n9cknNhkm8Fa9boCSB3rtZeA_0[0].sons = &TM__n9cknNhkm8Fa9boCSB3rtZeA_2_10[0];
NTInzstream58objecttype__uAEM0djdUGvrhRJcCteRig_.node = &TM__n9cknNhkm8Fa9boCSB3rtZeA_0[0];
NTInzstream__VNtHIlFk6DdHbJolR3Euzg_.size = sizeof(tyObject_nzStreamcolonObjectType___uAEM0djdUGvrhRJcCteRig*);
NTInzstream__VNtHIlFk6DdHbJolR3Euzg_.align = NIM_ALIGNOF(tyObject_nzStreamcolonObjectType___uAEM0djdUGvrhRJcCteRig*);
NTInzstream__VNtHIlFk6DdHbJolR3Euzg_.kind = 22;
NTInzstream__VNtHIlFk6DdHbJolR3Euzg_.base = (&NTInzstream58objecttype__uAEM0djdUGvrhRJcCteRig_);
NTInzstream__VNtHIlFk6DdHbJolR3Euzg_.marker = Marker_tyRef__VNtHIlFk6DdHbJolR3Euzg;
NTInzerror__Ihv5tO001K9aPAxxhJbC4Cw_.size = sizeof(tyObject_NZError__Ihv5tO001K9aPAxxhJbC4Cw);
NTInzerror__Ihv5tO001K9aPAxxhJbC4Cw_.align = NIM_ALIGNOF(tyObject_NZError__Ihv5tO001K9aPAxxhJbC4Cw);
NTInzerror__Ihv5tO001K9aPAxxhJbC4Cw_.kind = 17;
NTInzerror__Ihv5tO001K9aPAxxhJbC4Cw_.base = (&NTIcatchableerror__qrLSDoe2oBoAqNtJ9badtnA_);
TM__n9cknNhkm8Fa9boCSB3rtZeA_0[18].len = 0; TM__n9cknNhkm8Fa9boCSB3rtZeA_0[18].kind = 2;
NTInzerror__Ihv5tO001K9aPAxxhJbC4Cw_.node = &TM__n9cknNhkm8Fa9boCSB3rtZeA_0[18];
NTIrefnzerror__8EFTeb6IiMkqB59a5RstjVw_.size = sizeof(tyObject_NZError__Ihv5tO001K9aPAxxhJbC4Cw*);
NTIrefnzerror__8EFTeb6IiMkqB59a5RstjVw_.align = NIM_ALIGNOF(tyObject_NZError__Ihv5tO001K9aPAxxhJbC4Cw*);
NTIrefnzerror__8EFTeb6IiMkqB59a5RstjVw_.kind = 22;
NTIrefnzerror__8EFTeb6IiMkqB59a5RstjVw_.base = (&NTInzerror__Ihv5tO001K9aPAxxhJbC4Cw_);
NTIrefnzerror__8EFTeb6IiMkqB59a5RstjVw_.marker = Marker_tyRef__8EFTeb6IiMkqB59a5RstjVw;
}

