/* Generated by Nim Compiler v1.7.1 */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(x, y)
#define nimln_(x, y)
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef NU8 tyEnum_TNimKind__jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag__v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc__ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
NI align;
tyEnum_TNimKind__jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag__v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc__ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind__unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind__unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef NI tyArray__HU7qaqKu9czJLT84iCBJnsA[2];
static N_INLINE(void, nimZeroMem)(void* p, NI size);
static N_INLINE(void, nimSetMem__systemZmemory_7)(void* a, int v, NI size);
extern TNimType NTIint__rR5Bzr1D5krxoo1NcNyeMA_;
N_LIB_PRIVATE TNimType NTIvec__HU7qaqKu9czJLT84iCBJnsA_;
static N_INLINE(void, nimSetMem__systemZmemory_7)(void* a, int v, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a, v, ((size_t) (size)));
}
static N_INLINE(void, nimZeroMem)(void* p, NI size) {
	nimSetMem__systemZmemory_7(p, ((int) 0), size);
}
N_LIB_PRIVATE N_NIMCALL(void, vec2i__OOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZvec_121)(NI x, NI y, tyArray__HU7qaqKu9czJLT84iCBJnsA Result) {
	nimZeroMem((void*)Result, sizeof(tyArray__HU7qaqKu9czJLT84iCBJnsA));
	Result[(((NI) 0))- 0] = x;
	Result[(((NI) 1))- 0] = y;
}
N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatsdotnimbleatspkgsatsnicominus0dot4dot9atsnicoatsvecdotnim_DatInit000)(void) {
NTIvec__HU7qaqKu9czJLT84iCBJnsA_.size = sizeof(tyArray__HU7qaqKu9czJLT84iCBJnsA);
NTIvec__HU7qaqKu9czJLT84iCBJnsA_.align = NIM_ALIGNOF(tyArray__HU7qaqKu9czJLT84iCBJnsA);
NTIvec__HU7qaqKu9czJLT84iCBJnsA_.kind = 16;
NTIvec__HU7qaqKu9czJLT84iCBJnsA_.base = (&NTIint__rR5Bzr1D5krxoo1NcNyeMA_);
NTIvec__HU7qaqKu9czJLT84iCBJnsA_.flags = 1;
}

