/* Generated by Nim Compiler v1.7.1 */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#include <sys/types.h>
                          #include <pthread.h>
#include <string.h>
#include <math.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(x, y)
#define nimln_(x, y)
typedef struct tyObject_ObjcolonObjectType___Lrhq8PAaFQuOMGFep4lPIw tyObject_ObjcolonObjectType___Lrhq8PAaFQuOMGFep4lPIw;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack__7fytPA5bBsob6See21YMRA tyObject_GcStack__7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk__tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk__tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk__XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk__XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk__W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk__W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple__ujsjpB2O9cjj3uDHsXbnSzg tyTuple__ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg;
typedef struct tyObject_SharedList__JI9cx34TL8n3aOKF6tSMBUw tyObject_SharedList__JI9cx34TL8n3aOKF6tSMBUw;
typedef struct tyObject_SharedListNodecolonObjectType___KGw0YAw6W9aSz3Sr9aXGu7zg tyObject_SharedListNodecolonObjectType___KGw0YAw6W9aSz3Sr9aXGu7zg;
typedef struct tySequence__qwqHTkRvwhrRyENtudHQ7g tySequence__qwqHTkRvwhrRyENtudHQ7g;
typedef struct tyObject_Table__Jqg9bbNxGV6Sf9cnDeeNaaIg tyObject_Table__Jqg9bbNxGV6Sf9cnDeeNaaIg;
typedef struct tySequence__yzpjn9bWJt3ZvUgZyAolosA tySequence__yzpjn9bWJt3ZvUgZyAolosA;
typedef struct tyTuple__nuNGPJxv0UxszHtmd9czUsA tyTuple__nuNGPJxv0UxszHtmd9czUsA;
typedef NI tyArray__HU7qaqKu9czJLT84iCBJnsA[2];
struct tyObject_ObjcolonObjectType___Lrhq8PAaFQuOMGFep4lPIw {
tyArray__HU7qaqKu9czJLT84iCBJnsA pos;
};
typedef NU8 tyEnum_TNimKind__jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag__v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc__ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
NI align;
tyEnum_TNimKind__jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag__v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc__ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind__unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind__unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef N_NIMCALL_PTR(void, tyProc__T4eqaYlFJYZUv9aG9b1TV0bQ) (void);
struct tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ {
NI Field0;
NI Field1;
};
typedef NU8 tyEnum_Direction__xXRgXwCzgGRAl4Ebc25nyw;
typedef NI tyArray__L3PSb4W2On0GIfHMtJOWYQ[11];
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (void* ClE_0);
void* ClE_0;
} tyProc__HzVCwACFYM9cx9aV62PdjtuA;
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (NF32 dt, void* ClE_0);
void* ClE_0;
} tyProc__y9aUXu4JGz72YDIZVWUrK5w;
struct tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack__7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk__tXn60W2f8h3jgAYdEmy5NQ* tyArray__SPr7N6UKfuF549bNPiUvSRw[256];
typedef NU32 tyArray__BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg* tyArray__N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray__N1u1nqOgmuJN9cSZrnMHgOQ tyArray__B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk__W0r8S0Y3UGke6T9bIUWnnuw* tyArray__lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA {
tyArray__lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* tyArray__0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw {
tyArray__0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple__ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple__ujsjpB2O9cjj3uDHsXbnSzg tyArray__LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray__LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray__SPr7N6UKfuF549bNPiUvSRw freeSmallChunks;
NU32 flBitmap;
tyArray__BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray__B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk__XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_SharedList__JI9cx34TL8n3aOKF6tSMBUw {
tyObject_SharedListNodecolonObjectType___KGw0YAw6W9aSz3Sr9aXGu7zg* head;
tyObject_SharedListNodecolonObjectType___KGw0YAw6W9aSz3Sr9aXGu7zg* tail;
pthread_mutex_t lock;
};
struct tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack__7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
NI zctThreshold;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w additionalRoots;
tyObject_SharedList__JI9cx34TL8n3aOKF6tSMBUw toDispose;
NI gcThreadId;
};
typedef N_CLOSURE_PTR(void, TM__16AxP8K8JV58vb0pPrOrmA_9) (void* ClE_0);
typedef NU8 tyEnum_NicoButton__uhwLFGrWiWLeGBuK2zmKfg;
typedef NI32 tyEnum_Keycode__4FafBrLvG2wfvPTkNrrFRQ;
struct tyObject_Table__Jqg9bbNxGV6Sf9cnDeeNaaIg {
tySequence__yzpjn9bWJt3ZvUgZyAolosA* data;
NI counter;
};
struct tyTuple__nuNGPJxv0UxszHtmd9czUsA {
NI Field0;
NimStringDesc* Field1;
tySequence__qwqHTkRvwhrRyENtudHQ7g* Field2;
};
typedef N_CLOSURE_PTR(void, TM__16AxP8K8JV58vb0pPrOrmA_34) (NF32 dt, void* ClE_0);
typedef N_CLOSURE_PTR(void, TM__16AxP8K8JV58vb0pPrOrmA_35) (void* ClE_0);
struct tySequence__qwqHTkRvwhrRyENtudHQ7g {
  TGenericSeq Sup;
  NI data[SEQ_DECL_SIZE];
};
struct tySequence__yzpjn9bWJt3ZvUgZyAolosA {
  TGenericSeq Sup;
  tyTuple__nuNGPJxv0UxszHtmd9czUsA data[SEQ_DECL_SIZE];
};
static N_NIMCALL(void, Marker_tyRef__I6RJaoLSAS8qrdAw1TPCYw)(void* p, NI op);
N_LIB_PRIVATE N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, TM__16AxP8K8JV58vb0pPrOrmA_2)(void);
N_LIB_PRIVATE N_NIMCALL(void, nimRegisterGlobalMarker)(tyProc__T4eqaYlFJYZUv9aG9b1TV0bQ markerProc);
static N_NIMCALL(void, TM__16AxP8K8JV58vb0pPrOrmA_3)(void);
N_LIB_PRIVATE N_NIMCALL(void, init__OOZOOZOnimbleZpkgsZnico4548O52O57Znico_444)(NimStringDesc* org, NimStringDesc* app);
N_LIB_PRIVATE N_NIMCALL(void, createWindow__OOZOOZOnimbleZpkgsZnico4548O52O57Znico_6570)(NimStringDesc* title, NI w, NI h, NI scale, NIM_BOOL fullscreen);
N_LIB_PRIVATE N_NIMCALL(void, run__OOZOOZOnimbleZpkgsZnico4548O52O57Znico_6652)(tyProc__HzVCwACFYM9cx9aV62PdjtuA init, tyProc__y9aUXu4JGz72YDIZVWUrK5w update, tyProc__HzVCwACFYM9cx9aV62PdjtuA draw);
N_LIB_PRIVATE N_NIMCALL(void, gameInit__main_2340)(void);
N_LIB_PRIVATE N_NIMCALL(void, loadSpriteSheet__OOZOOZOnimbleZpkgsZnico4548O52O57Znico_5845)(NI index, NimStringDesc* filename, NI32 tileWidth, NI32 tileHeight);
N_LIB_PRIVATE N_NIMCALL(void, loadMap__OOZOOZOnimbleZpkgsZnico4548O52O57Znico_468)(NI index, NimStringDesc* filename, NI layer);
N_LIB_PRIVATE N_NIMCALL(void, loadFont__OOZOOZOnimbleZpkgsZnico4548O52O57Znico_4935)(NI index, NimStringDesc* filename);
N_LIB_PRIVATE N_NIMCALL(void, setMap__OOZOOZOnimbleZpkgsZnico4548O52O57Znico_466)(NI index);
N_LIB_PRIVATE N_NOINLINE(void*, newObj)(TNimType* typ, NI size);
N_LIB_PRIVATE N_NIMCALL(void, vec2i__OOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZvec_121)(NI x, NI y, tyArray__HU7qaqKu9czJLT84iCBJnsA Result);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incRef__system_5877)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(NI, pluspercent___system_696)(NI x, NI y);
static N_INLINE(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell__system_5839)(void* usr);
static N_INLINE(NI, minuspercent___system_716)(NI x, NI y);
static N_INLINE(void, decRef__system_5884)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(NIM_BOOL, ltpercent___system_1005)(NI x, NI y);
static N_INLINE(void, rtlAddZCT__system_5882)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT__system_5833)(tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NIMCALL(void, randomize__pureZrandom_289)(void);
N_LIB_PRIVATE N_NIMCALL(NI*, sample__main_1568)(NI* a, NI aLen_0);
static N_INLINE(void, nimZeroMem)(void* p, NI size);
static N_INLINE(void, nimSetMem__systemZmemory_7)(void* a, int v, NI size);
N_LIB_PRIVATE N_NIMCALL(void, gameUpdate__main_2358)(NF32 dt);
N_LIB_PRIVATE N_NIMCALL(void, checkKeys__main_1715)(tyEnum_Direction__xXRgXwCzgGRAl4Ebc25nyw* direction);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, btn__OOZOOZOnimbleZpkgsZnico4548O52O57Znico_190)(tyEnum_NicoButton__uhwLFGrWiWLeGBuK2zmKfg b);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, keyp__OOZOOZOnimbleZpkgsZnico4548O52O57Znico_1120)(tyEnum_Keycode__4FafBrLvG2wfvPTkNrrFRQ k);
N_LIB_PRIVATE N_NIMCALL(void, shutdown__OOZOOZOnimbleZpkgsZnico4548O52O57Znico_443)(void);
N_LIB_PRIVATE N_NIMCALL(void, move__main_1734)(tyObject_ObjcolonObjectType___Lrhq8PAaFQuOMGFep4lPIw* self, tyEnum_Direction__xXRgXwCzgGRAl4Ebc25nyw direction);
N_LIB_PRIVATE N_NIMCALL(tySequence__qwqHTkRvwhrRyENtudHQ7g*, X5BX5D___main_1793)(tyObject_Table__Jqg9bbNxGV6Sf9cnDeeNaaIg t, NimStringDesc* key);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, reprEnum)(NI e, TNimType* typ);
N_LIB_PRIVATE N_NIMCALL(void, checkOut__main_1983)(tyObject_ObjcolonObjectType___Lrhq8PAaFQuOMGFep4lPIw* self);
N_LIB_PRIVATE N_NIMCALL(NI, mget__OOZOOZOnimbleZpkgsZnico4548O52O57Znico_451)(NI32 tx, NI32 ty);
N_LIB_PRIVATE N_NIMCALL(int, toCint__OOZOOZOnimbleZpkgsZsdl5095nim4550O48O4952O51Zsdl5095nimZsdl_578)(NI x);
N_LIB_PRIVATE N_NIMCALL(void, gameOver__main_1982)(void);
N_LIB_PRIVATE N_NIMCALL(void, draw__main_1451)(tyObject_ObjcolonObjectType___Lrhq8PAaFQuOMGFep4lPIw* self, NI idx);
N_LIB_PRIVATE N_NIMCALL(void, spr__OOZOOZOnimbleZpkgsZnico4548O52O57Znico_354)(NI32 spr, NI32 x, NI32 y, NI32 w, NI32 h, NIM_BOOL hflip, NIM_BOOL vflip);
N_LIB_PRIVATE N_NIMCALL(void, checkOverlap__main_2096)(tyObject_ObjcolonObjectType___Lrhq8PAaFQuOMGFep4lPIw* snake, tyObject_ObjcolonObjectType___Lrhq8PAaFQuOMGFep4lPIw* fruit);
N_LIB_PRIVATE N_NIMCALL(NF, getDistance__main_1698)(tySequence__qwqHTkRvwhrRyENtudHQ7g* pos1, tySequence__qwqHTkRvwhrRyENtudHQ7g* pos2);
static N_INLINE(NF32, toPfloat__OOZOOZOnimbleZpkgsZnico4548O52O57Znico_6869)(NI x);
N_LIB_PRIVATE N_NIMCALL(NI, roof___pureZtimes_2501)(NI x, NI y);
N_LIB_PRIVATE N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
N_LIB_PRIVATE N_NIMCALL(void, drawFruit__main_1564)(tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ* loc);
N_LIB_PRIVATE N_NIMCALL(void, gameDraw__main_2360)(void);
N_LIB_PRIVATE N_NIMCALL(void, cls__OOZOOZOnimbleZpkgsZnico4548O52O57Znico_1485)(NI c);
N_LIB_PRIVATE N_NIMCALL(void, mapDraw__OOZOOZOnimbleZpkgsZnico4548O52O57Znico_454)(NI32 startTX, NI32 startTY, NI32 tw, NI32 th, NI32 dx, NI32 dy, NI32 dw, NI32 dh, NIM_BOOL loop, NI32 ox, NI32 oy);
N_LIB_PRIVATE N_NIMCALL(void, setColor__OOZOOZOnimbleZpkgsZnico4548O52O57Znico_59)(NI colId);
N_LIB_PRIVATE N_NIMCALL(void, printc__OOZOOZOnimbleZpkgsZnico4548O52O57Znico_40)(NimStringDesc* text, NI32 x, NI32 y, NI32 scale);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar___systemZdollars_8)(NI x);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_LIB_PRIVATE N_NOINLINE(void, nimGC_setStackBottom)(void* theStackBottom);
N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatsdotchoosenimatstoolchainsatsnimminusathheadatslibatsstdatssynciodotnim_DatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatsdotchoosenimatstoolchainsatsnimminusathheadatslibatssystemdotnim_DatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatsdotchoosenimatstoolchainsatsnimminusathheadatslibatssystemdotnim_Init000)(void);
N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatsdotchoosenimatstoolchainsatsnimminusathheadatslibatspureatsunicodedotnim_DatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatsdotchoosenimatstoolchainsatsnimminusathheadatslibatspureatstimesdotnim_DatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatsdotchoosenimatstoolchainsatsnimminusathheadatslibatspureatstimesdotnim_Init000)(void);
N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatsdotnimbleatspkgsatsnicominus0dot4dot9atsnicoatskeycodesdotnim_DatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatsdotnimbleatspkgsatssdl2_nimminus2dot0dot14dot3atssdl2_nimatssdldotnim_DatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatsdotnimbleatspkgsatsnicominus0dot4dot9atsnicoatscontrollerdotnim_DatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatsdotnimbleatspkgsatsnicominus0dot4dot9atsnicoatsbackendsatscommondotnim_DatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatsdotnimbleatspkgsatsnicominus0dot4dot9atsnicoatsbackendsatscommondotnim_Init000)(void);
N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatsdotchoosenimatstoolchainsatsnimminusathheadatslibatspureatsstreamsdotnim_DatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatsdotchoosenimatstoolchainsatsnimminusathheadatslibatspureatslexbasedotnim_DatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatsdotchoosenimatstoolchainsatsnimminusathheadatslibatspureatsparsejsondotnim_DatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatsdotchoosenimatstoolchainsatsnimminusathheadatslibatspureatsjsondotnim_DatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatsdotchoosenimatstoolchainsatsnimminusathheadatslibatspureatsrandomdotnim_Init000)(void);
N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatsdotchoosenimatstoolchainsatsnimminusathheadatslibatspureatsparsecfgdotnim_DatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatsdotnimbleatspkgsatsnimPNGminus0dot3dot1atsnimPNGatsnimzdotnim_DatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatsdotnimbleatspkgsatsnimPNGminus0dot3dot1atsnimPNGdotnim_DatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatsdotnimbleatspkgsatsnicominus0dot4dot9atsnicoatsstb_vorbisdotnim_DatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatsdotnimbleatspkgsatsnicominus0dot4dot9atsnicoatsbackendsatssdl2dotnim_DatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatsdotnimbleatspkgsatsnicominus0dot4dot9atsnicoatsbackendsatssdl2dotnim_Init000)(void);
N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatsdotnimbleatspkgsatsnicominus0dot4dot9atsnicoatsfontdatadotnim_Init000)(void);
N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatsdotnimbleatspkgsatsnicominus0dot4dot9atsnicodotnim_DatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatsdotnimbleatspkgsatsnicominus0dot4dot9atsnicodotnim_Init000)(void);
N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatsdotnimbleatspkgsatsnicominus0dot4dot9atsnicoatsvecdotnim_DatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, atmmaindotnim_DatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, NimMainModule)(void);
N_LIB_PRIVATE TNimType NTIobj58objecttype__Lrhq8PAaFQuOMGFep4lPIw_;
extern TNimType NTIvec__HU7qaqKu9czJLT84iCBJnsA_;
N_LIB_PRIVATE TNimType NTIobj__I6RJaoLSAS8qrdAw1TPCYw_;
STRING_LITERAL(TM__16AxP8K8JV58vb0pPrOrmA_4, "Infinitybeond1", 14);
STRING_LITERAL(TM__16AxP8K8JV58vb0pPrOrmA_5, "testgame", 8);
STRING_LITERAL(TM__16AxP8K8JV58vb0pPrOrmA_6, "sprites.png", 11);
STRING_LITERAL(TM__16AxP8K8JV58vb0pPrOrmA_7, "map.json", 8);
STRING_LITERAL(TM__16AxP8K8JV58vb0pPrOrmA_8, "font.png", 8);
static NIM_CONST struct {
  TGenericSeq Sup;
  NI data[0];
} TM__16AxP8K8JV58vb0pPrOrmA_10 = {{0, 0 | NIM_STRLIT_FLAG}};
static NIM_CONST struct {
  TGenericSeq Sup;
  NI data[0];
} TM__16AxP8K8JV58vb0pPrOrmA_11 = {{0, 0 | NIM_STRLIT_FLAG}};
static NIM_CONST struct {
  TGenericSeq Sup;
  NI data[0];
} TM__16AxP8K8JV58vb0pPrOrmA_12 = {{0, 0 | NIM_STRLIT_FLAG}};
static NIM_CONST struct {
  TGenericSeq Sup;
  NI data[0];
} TM__16AxP8K8JV58vb0pPrOrmA_13 = {{0, 0 | NIM_STRLIT_FLAG}};
static NIM_CONST struct {
  TGenericSeq Sup;
  NI data[0];
} TM__16AxP8K8JV58vb0pPrOrmA_14 = {{0, 0 | NIM_STRLIT_FLAG}};
static NIM_CONST struct {
  TGenericSeq Sup;
  NI data[0];
} TM__16AxP8K8JV58vb0pPrOrmA_15 = {{0, 0 | NIM_STRLIT_FLAG}};
static NIM_CONST struct {
  TGenericSeq Sup;
  NI data[0];
} TM__16AxP8K8JV58vb0pPrOrmA_16 = {{0, 0 | NIM_STRLIT_FLAG}};
static NIM_CONST struct {
  TGenericSeq Sup;
  NI data[0];
} TM__16AxP8K8JV58vb0pPrOrmA_17 = {{0, 0 | NIM_STRLIT_FLAG}};
STRING_LITERAL(TM__16AxP8K8JV58vb0pPrOrmA_18, "left", 4);
static NIM_CONST struct {
  TGenericSeq Sup;
  NI data[2];
} TM__16AxP8K8JV58vb0pPrOrmA_19 = {{2, 2 | NIM_STRLIT_FLAG}, {((NI) -1),
((NI) 0)}};
STRING_LITERAL(TM__16AxP8K8JV58vb0pPrOrmA_20, "down", 4);
static NIM_CONST struct {
  TGenericSeq Sup;
  NI data[2];
} TM__16AxP8K8JV58vb0pPrOrmA_21 = {{2, 2 | NIM_STRLIT_FLAG}, {((NI) 0),
((NI) 1)}};
static NIM_CONST struct {
  TGenericSeq Sup;
  NI data[0];
} TM__16AxP8K8JV58vb0pPrOrmA_22 = {{0, 0 | NIM_STRLIT_FLAG}};
static NIM_CONST struct {
  TGenericSeq Sup;
  NI data[0];
} TM__16AxP8K8JV58vb0pPrOrmA_23 = {{0, 0 | NIM_STRLIT_FLAG}};
static NIM_CONST struct {
  TGenericSeq Sup;
  NI data[0];
} TM__16AxP8K8JV58vb0pPrOrmA_24 = {{0, 0 | NIM_STRLIT_FLAG}};
STRING_LITERAL(TM__16AxP8K8JV58vb0pPrOrmA_25, "up", 2);
static NIM_CONST struct {
  TGenericSeq Sup;
  NI data[2];
} TM__16AxP8K8JV58vb0pPrOrmA_26 = {{2, 2 | NIM_STRLIT_FLAG}, {((NI) 0),
((NI) -1)}};
static NIM_CONST struct {
  TGenericSeq Sup;
  NI data[0];
} TM__16AxP8K8JV58vb0pPrOrmA_27 = {{0, 0 | NIM_STRLIT_FLAG}};
STRING_LITERAL(TM__16AxP8K8JV58vb0pPrOrmA_28, "right", 5);
static NIM_CONST struct {
  TGenericSeq Sup;
  NI data[2];
} TM__16AxP8K8JV58vb0pPrOrmA_29 = {{2, 2 | NIM_STRLIT_FLAG}, {((NI) 1),
((NI) 0)}};
static NIM_CONST struct {
  TGenericSeq Sup;
  tyTuple__nuNGPJxv0UxszHtmd9czUsA data[16];
} TM__16AxP8K8JV58vb0pPrOrmA_30 = {{16, 16 | NIM_STRLIT_FLAG}, {{((NI) 0),
((NimStringDesc*) NIM_NIL),
((tySequence__qwqHTkRvwhrRyENtudHQ7g*)&TM__16AxP8K8JV58vb0pPrOrmA_10)}
,
{((NI) 0),
((NimStringDesc*) NIM_NIL),
((tySequence__qwqHTkRvwhrRyENtudHQ7g*)&TM__16AxP8K8JV58vb0pPrOrmA_11)}
,
{((NI) 0),
((NimStringDesc*) NIM_NIL),
((tySequence__qwqHTkRvwhrRyENtudHQ7g*)&TM__16AxP8K8JV58vb0pPrOrmA_12)}
,
{((NI) 0),
((NimStringDesc*) NIM_NIL),
((tySequence__qwqHTkRvwhrRyENtudHQ7g*)&TM__16AxP8K8JV58vb0pPrOrmA_13)}
,
{((NI) 0),
((NimStringDesc*) NIM_NIL),
((tySequence__qwqHTkRvwhrRyENtudHQ7g*)&TM__16AxP8K8JV58vb0pPrOrmA_14)}
,
{((NI) 0),
((NimStringDesc*) NIM_NIL),
((tySequence__qwqHTkRvwhrRyENtudHQ7g*)&TM__16AxP8K8JV58vb0pPrOrmA_15)}
,
{((NI) 0),
((NimStringDesc*) NIM_NIL),
((tySequence__qwqHTkRvwhrRyENtudHQ7g*)&TM__16AxP8K8JV58vb0pPrOrmA_16)}
,
{((NI) 0),
((NimStringDesc*) NIM_NIL),
((tySequence__qwqHTkRvwhrRyENtudHQ7g*)&TM__16AxP8K8JV58vb0pPrOrmA_17)}
,
{((NI) IL64(2840212248)),
((NimStringDesc*) &TM__16AxP8K8JV58vb0pPrOrmA_18),
((tySequence__qwqHTkRvwhrRyENtudHQ7g*)&TM__16AxP8K8JV58vb0pPrOrmA_19)}
,
{((NI) 1672064345),
((NimStringDesc*) &TM__16AxP8K8JV58vb0pPrOrmA_20),
((tySequence__qwqHTkRvwhrRyENtudHQ7g*)&TM__16AxP8K8JV58vb0pPrOrmA_21)}
,
{((NI) 0),
((NimStringDesc*) NIM_NIL),
((tySequence__qwqHTkRvwhrRyENtudHQ7g*)&TM__16AxP8K8JV58vb0pPrOrmA_22)}
,
{((NI) 0),
((NimStringDesc*) NIM_NIL),
((tySequence__qwqHTkRvwhrRyENtudHQ7g*)&TM__16AxP8K8JV58vb0pPrOrmA_23)}
,
{((NI) 0),
((NimStringDesc*) NIM_NIL),
((tySequence__qwqHTkRvwhrRyENtudHQ7g*)&TM__16AxP8K8JV58vb0pPrOrmA_24)}
,
{((NI) 1720810685),
((NimStringDesc*) &TM__16AxP8K8JV58vb0pPrOrmA_25),
((tySequence__qwqHTkRvwhrRyENtudHQ7g*)&TM__16AxP8K8JV58vb0pPrOrmA_26)}
,
{((NI) 0),
((NimStringDesc*) NIM_NIL),
((tySequence__qwqHTkRvwhrRyENtudHQ7g*)&TM__16AxP8K8JV58vb0pPrOrmA_27)}
,
{((NI) 1786548735),
((NimStringDesc*) &TM__16AxP8K8JV58vb0pPrOrmA_28),
((tySequence__qwqHTkRvwhrRyENtudHQ7g*)&TM__16AxP8K8JV58vb0pPrOrmA_29)}
}};
N_LIB_PRIVATE NIM_CONST tyObject_Table__Jqg9bbNxGV6Sf9cnDeeNaaIg directions__main_1404 = {((tySequence__yzpjn9bWJt3ZvUgZyAolosA*)&TM__16AxP8K8JV58vb0pPrOrmA_30), ((NI) 4)}
;
N_LIB_PRIVATE TNimType NTIdirection__xXRgXwCzgGRAl4Ebc25nyw_;
extern TNimType NTIseqLintT__qwqHTkRvwhrRyENtudHQ7g_;
N_LIB_PRIVATE tyObject_ObjcolonObjectType___Lrhq8PAaFQuOMGFep4lPIw* head__main_1416;
N_LIB_PRIVATE tyObject_ObjcolonObjectType___Lrhq8PAaFQuOMGFep4lPIw* fruit__main_1417;
N_LIB_PRIVATE tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ fruitLoc__main_1420;
N_LIB_PRIVATE tyEnum_Direction__xXRgXwCzgGRAl4Ebc25nyw direction__main_1421;
N_LIB_PRIVATE NI score__main_1422 = ((NI) 0);
N_LIB_PRIVATE NIM_CONST tyArray__L3PSb4W2On0GIfHMtJOWYQ multiples__main_1423 = {((NI) 24),
((NI) 32),
((NI) 40),
((NI) 48),
((NI) 56),
((NI) 64),
((NI) 72),
((NI) 80),
((NI) 88),
((NI) 96),
((NI) 104)}
;
extern NIM_THREADVAR tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ gch__system_5772;
static N_NIMCALL(void, Marker_tyRef__I6RJaoLSAS8qrdAw1TPCYw)(void* p, NI op) {
	tyObject_ObjcolonObjectType___Lrhq8PAaFQuOMGFep4lPIw* a;
	NI T1_;
	a = (tyObject_ObjcolonObjectType___Lrhq8PAaFQuOMGFep4lPIw*)p;
	T1_ = (NI)0;
}
static N_NIMCALL(void, TM__16AxP8K8JV58vb0pPrOrmA_2)(void) {
	nimGCvisit((void*)head__main_1416, 0);
}
static N_NIMCALL(void, TM__16AxP8K8JV58vb0pPrOrmA_3)(void) {
	nimGCvisit((void*)fruit__main_1417, 0);
}
static N_INLINE(NI, pluspercent___system_696)(NI x, NI y) {
	NI result;
	result = (NI)0;
	result = ((NI) ((NU)((NU64)(((NU) (x))) + (NU64)(((NU) (y))))));
	return result;
}
static N_INLINE(void, incRef__system_5877)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c) {
	(*c).refcount = pluspercent___system_696((*c).refcount, ((NI) 8));
}
static N_INLINE(NI, minuspercent___system_716)(NI x, NI y) {
	NI result;
	result = (NI)0;
	result = ((NI) ((NU)((NU64)(((NU) (x))) - (NU64)(((NU) (y))))));
	return result;
}
static N_INLINE(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell__system_5839)(void* usr) {
	tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* result;
	NI T1_;
	result = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;
	T1_ = (NI)0;
	T1_ = minuspercent___system_716(((NI) (ptrdiff_t) (usr)), ((NI) 16));
	result = ((tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*) (T1_));
	return result;
}
static N_INLINE(NIM_BOOL, ltpercent___system_1005)(NI x, NI y) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	result = ((NU64)(((NU) (x))) < (NU64)(((NU) (y))));
	return result;
}
static N_INLINE(void, rtlAddZCT__system_5882)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c) {
	addZCT__system_5833((&gch__system_5772.zct), c);
}
static N_INLINE(void, decRef__system_5884)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c) {
	(*c).refcount = minuspercent___system_716((*c).refcount, ((NI) 8));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = ltpercent___system_1005((*c).refcount, ((NI) 8));
		if (!T3_) goto LA4_;
		rtlAddZCT__system_5882(c);
	}
	LA4_: ;
}
static N_INLINE(void, asgnRef)(void** dest, void* src) {
	{
		tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* T5_;
		if (!!((src == NIM_NIL))) goto LA3_;
		T5_ = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T5_ = usrToCell__system_5839(src);
		incRef__system_5877(T5_);
	}
	LA3_: ;
	{
		tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* T10_;
		if (!!(((*dest) == NIM_NIL))) goto LA8_;
		T10_ = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T10_ = usrToCell__system_5839((*dest));
		decRef__system_5884(T10_);
	}
	LA8_: ;
	(*dest) = src;
}
N_LIB_PRIVATE N_NIMCALL(void, gameInit__main_2340)(void) {
	tyObject_ObjcolonObjectType___Lrhq8PAaFQuOMGFep4lPIw* T1_;
	NI colontmp_;
	NI* T2_;
	NI colontmp__2;
	NI* T3_;
	tyObject_ObjcolonObjectType___Lrhq8PAaFQuOMGFep4lPIw* T4_;
	loadSpriteSheet__OOZOOZOnimbleZpkgsZnico4548O52O57Znico_5845(((NI) 0), ((NimStringDesc*) &TM__16AxP8K8JV58vb0pPrOrmA_6), ((NI32) 8), ((NI32) 8));
	loadMap__OOZOOZOnimbleZpkgsZnico4548O52O57Znico_468(((NI) 0), ((NimStringDesc*) &TM__16AxP8K8JV58vb0pPrOrmA_7), ((NI) 0));
	loadFont__OOZOOZOnimbleZpkgsZnico4548O52O57Znico_4935(((NI) 0), ((NimStringDesc*) &TM__16AxP8K8JV58vb0pPrOrmA_8));
	setMap__OOZOOZOnimbleZpkgsZnico4548O52O57Znico_466(((NI) 0));
	T1_ = NIM_NIL;
	T1_ = (tyObject_ObjcolonObjectType___Lrhq8PAaFQuOMGFep4lPIw*) newObj((&NTIobj__I6RJaoLSAS8qrdAw1TPCYw_), sizeof(tyObject_ObjcolonObjectType___Lrhq8PAaFQuOMGFep4lPIw));
	vec2i__OOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZvec_121(((NI) 64), ((NI) 64), (*T1_).pos);
	asgnRef((void**) (&head__main_1416), T1_);
	direction__main_1421 = ((tyEnum_Direction__xXRgXwCzgGRAl4Ebc25nyw) 0);
	randomize__pureZrandom_289();
	T2_ = (NI*)0;
	T2_ = sample__main_1568(multiples__main_1423, 11);
	colontmp_ = (*T2_);
	T3_ = (NI*)0;
	T3_ = sample__main_1568(multiples__main_1423, 11);
	colontmp__2 = (*T3_);
	fruitLoc__main_1420.Field0 = colontmp_;
	fruitLoc__main_1420.Field1 = colontmp__2;
	T4_ = NIM_NIL;
	T4_ = (tyObject_ObjcolonObjectType___Lrhq8PAaFQuOMGFep4lPIw*) newObj((&NTIobj__I6RJaoLSAS8qrdAw1TPCYw_), sizeof(tyObject_ObjcolonObjectType___Lrhq8PAaFQuOMGFep4lPIw));
	vec2i__OOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZvec_121(fruitLoc__main_1420.Field0, fruitLoc__main_1420.Field1, (*T4_).pos);
	asgnRef((void**) (&fruit__main_1417), T4_);
}
static N_INLINE(void, nimSetMem__systemZmemory_7)(void* a, int v, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a, v, ((size_t) (size)));
}
static N_INLINE(void, nimZeroMem)(void* p, NI size) {
	nimSetMem__systemZmemory_7(p, ((int) 0), size);
}
N_LIB_PRIVATE N_NIMCALL(void, checkKeys__main_1715)(tyEnum_Direction__xXRgXwCzgGRAl4Ebc25nyw* direction) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = btn__OOZOOZOnimbleZpkgsZnico4548O52O57Znico_190(((tyEnum_NicoButton__uhwLFGrWiWLeGBuK2zmKfg) 2));
		if (T3_) goto LA4_;
		T3_ = keyp__OOZOOZOnimbleZpkgsZnico4548O52O57Znico_1120(((tyEnum_Keycode__4FafBrLvG2wfvPTkNrrFRQ) 119));
		LA4_: ;
		if (!T3_) goto LA5_;
		{
			if (!!(((*direction) == ((tyEnum_Direction__xXRgXwCzgGRAl4Ebc25nyw) 1)))) goto LA9_;
			(*direction) = ((tyEnum_Direction__xXRgXwCzgGRAl4Ebc25nyw) 0);
		}
		LA9_: ;
	}
	goto LA1_;
	LA5_: ;
	{
		NIM_BOOL T12_;
		T12_ = (NIM_BOOL)0;
		T12_ = btn__OOZOOZOnimbleZpkgsZnico4548O52O57Znico_190(((tyEnum_NicoButton__uhwLFGrWiWLeGBuK2zmKfg) 3));
		if (T12_) goto LA13_;
		T12_ = keyp__OOZOOZOnimbleZpkgsZnico4548O52O57Znico_1120(((tyEnum_Keycode__4FafBrLvG2wfvPTkNrrFRQ) 115));
		LA13_: ;
		if (!T12_) goto LA14_;
		{
			if (!!(((*direction) == ((tyEnum_Direction__xXRgXwCzgGRAl4Ebc25nyw) 0)))) goto LA18_;
			(*direction) = ((tyEnum_Direction__xXRgXwCzgGRAl4Ebc25nyw) 1);
		}
		LA18_: ;
	}
	goto LA1_;
	LA14_: ;
	{
		NIM_BOOL T21_;
		T21_ = (NIM_BOOL)0;
		T21_ = btn__OOZOOZOnimbleZpkgsZnico4548O52O57Znico_190(((tyEnum_NicoButton__uhwLFGrWiWLeGBuK2zmKfg) 0));
		if (T21_) goto LA22_;
		T21_ = keyp__OOZOOZOnimbleZpkgsZnico4548O52O57Znico_1120(((tyEnum_Keycode__4FafBrLvG2wfvPTkNrrFRQ) 97));
		LA22_: ;
		if (!T21_) goto LA23_;
		{
			if (!!(((*direction) == ((tyEnum_Direction__xXRgXwCzgGRAl4Ebc25nyw) 3)))) goto LA27_;
			(*direction) = ((tyEnum_Direction__xXRgXwCzgGRAl4Ebc25nyw) 2);
		}
		LA27_: ;
	}
	goto LA1_;
	LA23_: ;
	{
		NIM_BOOL T30_;
		T30_ = (NIM_BOOL)0;
		T30_ = btn__OOZOOZOnimbleZpkgsZnico4548O52O57Znico_190(((tyEnum_NicoButton__uhwLFGrWiWLeGBuK2zmKfg) 1));
		if (T30_) goto LA31_;
		T30_ = keyp__OOZOOZOnimbleZpkgsZnico4548O52O57Znico_1120(((tyEnum_Keycode__4FafBrLvG2wfvPTkNrrFRQ) 100));
		LA31_: ;
		if (!T30_) goto LA32_;
		{
			if (!!(((*direction) == ((tyEnum_Direction__xXRgXwCzgGRAl4Ebc25nyw) 2)))) goto LA36_;
			(*direction) = ((tyEnum_Direction__xXRgXwCzgGRAl4Ebc25nyw) 3);
		}
		LA36_: ;
	}
	goto LA1_;
	LA32_: ;
	{
		NIM_BOOL T39_;
		T39_ = (NIM_BOOL)0;
		T39_ = keyp__OOZOOZOnimbleZpkgsZnico4548O52O57Znico_1120(((tyEnum_Keycode__4FafBrLvG2wfvPTkNrrFRQ) 113));
		if (!T39_) goto LA40_;
		shutdown__OOZOOZOnimbleZpkgsZnico4548O52O57Znico_443();
	}
	goto LA1_;
	LA40_: ;
	LA1_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, move__main_1734)(tyObject_ObjcolonObjectType___Lrhq8PAaFQuOMGFep4lPIw* self, tyEnum_Direction__xXRgXwCzgGRAl4Ebc25nyw direction) {
	tySequence__qwqHTkRvwhrRyENtudHQ7g* coord;
	coord = X5BX5D___main_1793(directions__main_1404, reprEnum((NI)direction, (&NTIdirection__xXRgXwCzgGRAl4Ebc25nyw_)));
	(*self).pos[(((NI) 0))- 0] += coord->data[((NI) 0)];
	(*self).pos[(((NI) 1))- 0] += coord->data[((NI) 1)];
}
N_LIB_PRIVATE N_NIMCALL(void, gameOver__main_1982)(void) {
	shutdown__OOZOOZOnimbleZpkgsZnico4548O52O57Znico_443();
}
N_LIB_PRIVATE N_NIMCALL(void, checkOut__main_1983)(tyObject_ObjcolonObjectType___Lrhq8PAaFQuOMGFep4lPIw* self) {
	NI m;
	int T1_;
	int T2_;
	T1_ = (int)0;
	T1_ = toCint__OOZOOZOnimbleZpkgsZsdl5095nim4550O48O4952O51Zsdl5095nimZsdl_578((NI)((*self).pos[(((NI) 0))- 0] / ((NI) 8)));
	T2_ = (int)0;
	T2_ = toCint__OOZOOZOnimbleZpkgsZsdl5095nim4550O48O4952O51Zsdl5095nimZsdl_578((NI)((*self).pos[(((NI) 1))- 0] / ((NI) 8)));
	m = mget__OOZOOZOnimbleZpkgsZnico4548O52O57Znico_451(T1_, T2_);
	{
		if (!(m == ((NI) 1))) goto LA5_;
		gameOver__main_1982();
	}
	LA5_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, draw__main_1451)(tyObject_ObjcolonObjectType___Lrhq8PAaFQuOMGFep4lPIw* self, NI idx) {
	int T1_;
	int T2_;
	int T3_;
	T1_ = (int)0;
	T1_ = toCint__OOZOOZOnimbleZpkgsZsdl5095nim4550O48O4952O51Zsdl5095nimZsdl_578(idx);
	T2_ = (int)0;
	T2_ = toCint__OOZOOZOnimbleZpkgsZsdl5095nim4550O48O4952O51Zsdl5095nimZsdl_578((*self).pos[(((NI) 0))- 0]);
	T3_ = (int)0;
	T3_ = toCint__OOZOOZOnimbleZpkgsZsdl5095nim4550O48O4952O51Zsdl5095nimZsdl_578((*self).pos[(((NI) 1))- 0]);
	spr__OOZOOZOnimbleZpkgsZnico4548O52O57Znico_354(T1_, T2_, T3_, ((NI32) 1), ((NI32) 1), NIM_FALSE, NIM_FALSE);
}
static N_INLINE(NF32, toPfloat__OOZOOZOnimbleZpkgsZnico4548O52O57Znico_6869)(NI x) {
	NF32 result;
{	result = (NF32)0;
	result = ((NF32) (x));
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NF, getDistance__main_1698)(tySequence__qwqHTkRvwhrRyENtudHQ7g* pos1, tySequence__qwqHTkRvwhrRyENtudHQ7g* pos2) {
	NF result;
	NI x1;
	NI y1;
	NI x2;
	NI y2;
	NF32 distance;
	NI T1_;
	NI T2_;
	NF32 T3_;
{	result = (NF)0;
	x1 = pos1->data[((NI) 0)];
	y1 = pos1->data[((NI) 1)];
	x2 = pos2->data[((NI) 0)];
	y2 = pos2->data[((NI) 1)];
	T1_ = (NI)0;
	T1_ = roof___pureZtimes_2501((NI)(y2 - y1), ((NI) 2));
	T2_ = (NI)0;
	T2_ = roof___pureZtimes_2501((NI)(x2 - x1), ((NI) 2));
	T3_ = (NF32)0;
	T3_ = toPfloat__OOZOOZOnimbleZpkgsZnico4548O52O57Znico_6869((NI)(T1_ + T2_));
	distance = sqrtf(T3_);
	result = ((NF) (distance));
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, drawFruit__main_1564)(tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ* loc) {
	tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ c;
	NI* T1_;
	NI* T2_;
	T1_ = (NI*)0;
	T1_ = sample__main_1568(multiples__main_1423, 11);
	c.Field0 = (*T1_);
	T2_ = (NI*)0;
	T2_ = sample__main_1568(multiples__main_1423, 11);
	c.Field1 = (*T2_);
	(*fruit__main_1417).pos[(((NI) 0))- 0] = (NI)(c.Field0 + ((NI) 8));
	(*fruit__main_1417).pos[(((NI) 1))- 0] = (NI)(c.Field1 + ((NI) 8));
	(*loc) = c;
}
N_LIB_PRIVATE N_NIMCALL(void, checkOverlap__main_2096)(tyObject_ObjcolonObjectType___Lrhq8PAaFQuOMGFep4lPIw* snake, tyObject_ObjcolonObjectType___Lrhq8PAaFQuOMGFep4lPIw* fruit) {
	{
		tySequence__qwqHTkRvwhrRyENtudHQ7g* T3_;
		tySequence__qwqHTkRvwhrRyENtudHQ7g* T4_;
		NF T5_;
		T3_ = NIM_NIL;
		T3_ = (tySequence__qwqHTkRvwhrRyENtudHQ7g*) newSeq((&NTIseqLintT__qwqHTkRvwhrRyENtudHQ7g_), 2);
		T3_->data[0] = (*snake).pos[(((NI) 0))- 0];
		T3_->data[1] = (*snake).pos[(((NI) 1))- 0];
		T4_ = NIM_NIL;
		T4_ = (tySequence__qwqHTkRvwhrRyENtudHQ7g*) newSeq((&NTIseqLintT__qwqHTkRvwhrRyENtudHQ7g_), 2);
		T4_->data[0] = (*fruit).pos[(((NI) 0))- 0];
		T4_->data[1] = (*fruit).pos[(((NI) 1))- 0];
		T5_ = (NF)0;
		T5_ = getDistance__main_1698(T3_, T4_);
		if (!(T5_ <= 8.0)) goto LA6_;
		score__main_1422 += ((NI) 1);
		drawFruit__main_1564((&fruitLoc__main_1420));
	}
	LA6_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, gameUpdate__main_2358)(NF32 dt) {
	checkKeys__main_1715((&direction__main_1421));
	move__main_1734(head__main_1416, direction__main_1421);
	checkOut__main_1983(head__main_1416);
	draw__main_1451(head__main_1416, ((NI) 16));
	checkOverlap__main_2096(head__main_1416, fruit__main_1417);
}
N_LIB_PRIVATE N_NIMCALL(void, gameDraw__main_2360)(void) {
	NimStringDesc* T1_;
	cls__OOZOOZOnimbleZpkgsZnico4548O52O57Znico_1485(((NI) 0));
	mapDraw__OOZOOZOnimbleZpkgsZnico4548O52O57Znico_454(((NI32) 0), ((NI32) 0), ((NI32) 16), ((NI32) 16), ((NI32) 0), ((NI32) 0), ((NI32) -1), ((NI32) -1), NIM_FALSE, ((NI32) 0), ((NI32) 0));
	draw__main_1451(head__main_1416, ((NI) 16));
	draw__main_1451(fruit__main_1417, ((NI) 18));
	setColor__OOZOOZOnimbleZpkgsZnico4548O52O57Znico_59(((NI) 3));
	T1_ = NIM_NIL;
	T1_ = dollar___systemZdollars_8(score__main_1422);
	printc__OOZOOZOnimbleZpkgsZnico4548O52O57Znico_40(T1_, ((NI32) 64), ((NI32) 16), ((NI32) 1));
}
static N_INLINE(void, initStackBottomWith)(void* locals) {
	nimGC_setStackBottom(locals);
}

N_LIB_PRIVATE void PreMainInner(void) {
	atmdotdotatsdotdotatsdotchoosenimatstoolchainsatsnimminusathheadatslibatspureatstimesdotnim_Init000();
	atmdotdotatsdotdotatsdotnimbleatspkgsatsnicominus0dot4dot9atsnicoatsbackendsatscommondotnim_Init000();
	atmdotdotatsdotdotatsdotchoosenimatstoolchainsatsnimminusathheadatslibatspureatsrandomdotnim_Init000();
	atmdotdotatsdotdotatsdotnimbleatspkgsatsnicominus0dot4dot9atsnicoatsbackendsatssdl2dotnim_Init000();
	atmdotdotatsdotdotatsdotnimbleatspkgsatsnicominus0dot4dot9atsnicoatsfontdatadotnim_Init000();
	atmdotdotatsdotdotatsdotnimbleatspkgsatsnicominus0dot4dot9atsnicodotnim_Init000();
}

N_LIB_PRIVATE void PreMain(void) {
	void (*volatile inner)(void);
	inner = PreMainInner;
	atmdotdotatsdotdotatsdotchoosenimatstoolchainsatsnimminusathheadatslibatsstdatssynciodotnim_DatInit000();
	atmdotdotatsdotdotatsdotchoosenimatstoolchainsatsnimminusathheadatslibatssystemdotnim_DatInit000();
	initStackBottomWith((void *)&inner);
	atmdotdotatsdotdotatsdotchoosenimatstoolchainsatsnimminusathheadatslibatssystemdotnim_Init000();
	atmdotdotatsdotdotatsdotchoosenimatstoolchainsatsnimminusathheadatslibatspureatsunicodedotnim_DatInit000();
	atmdotdotatsdotdotatsdotchoosenimatstoolchainsatsnimminusathheadatslibatspureatstimesdotnim_DatInit000();
	atmdotdotatsdotdotatsdotnimbleatspkgsatsnicominus0dot4dot9atsnicoatskeycodesdotnim_DatInit000();
	atmdotdotatsdotdotatsdotnimbleatspkgsatssdl2_nimminus2dot0dot14dot3atssdl2_nimatssdldotnim_DatInit000();
	atmdotdotatsdotdotatsdotnimbleatspkgsatsnicominus0dot4dot9atsnicoatscontrollerdotnim_DatInit000();
	atmdotdotatsdotdotatsdotnimbleatspkgsatsnicominus0dot4dot9atsnicoatsbackendsatscommondotnim_DatInit000();
	atmdotdotatsdotdotatsdotchoosenimatstoolchainsatsnimminusathheadatslibatspureatsstreamsdotnim_DatInit000();
	atmdotdotatsdotdotatsdotchoosenimatstoolchainsatsnimminusathheadatslibatspureatslexbasedotnim_DatInit000();
	atmdotdotatsdotdotatsdotchoosenimatstoolchainsatsnimminusathheadatslibatspureatsparsejsondotnim_DatInit000();
	atmdotdotatsdotdotatsdotchoosenimatstoolchainsatsnimminusathheadatslibatspureatsjsondotnim_DatInit000();
	atmdotdotatsdotdotatsdotchoosenimatstoolchainsatsnimminusathheadatslibatspureatsparsecfgdotnim_DatInit000();
	atmdotdotatsdotdotatsdotnimbleatspkgsatsnimPNGminus0dot3dot1atsnimPNGatsnimzdotnim_DatInit000();
	atmdotdotatsdotdotatsdotnimbleatspkgsatsnimPNGminus0dot3dot1atsnimPNGdotnim_DatInit000();
	atmdotdotatsdotdotatsdotnimbleatspkgsatsnicominus0dot4dot9atsnicoatsstb_vorbisdotnim_DatInit000();
	atmdotdotatsdotdotatsdotnimbleatspkgsatsnicominus0dot4dot9atsnicoatsbackendsatssdl2dotnim_DatInit000();
	atmdotdotatsdotdotatsdotnimbleatspkgsatsnicominus0dot4dot9atsnicodotnim_DatInit000();
	atmdotdotatsdotdotatsdotnimbleatspkgsatsnicominus0dot4dot9atsnicoatsvecdotnim_DatInit000();
	atmmaindotnim_DatInit000();
	(*inner)();
}

N_LIB_PRIVATE N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

N_LIB_PRIVATE N_NIMCALL(void, NimMainModule)(void) {
{
	TFrame FR_; FR_.len = 0;

	nimRegisterGlobalMarker(TM__16AxP8K8JV58vb0pPrOrmA_2);


	nimRegisterGlobalMarker(TM__16AxP8K8JV58vb0pPrOrmA_3);

}/* preInitProc end */
{
	tyProc__HzVCwACFYM9cx9aV62PdjtuA T1_;
	tyProc__y9aUXu4JGz72YDIZVWUrK5w T2_;
	tyProc__HzVCwACFYM9cx9aV62PdjtuA T3_;
	init__OOZOOZOnimbleZpkgsZnico4548O52O57Znico_444(((NimStringDesc*) &TM__16AxP8K8JV58vb0pPrOrmA_4), ((NimStringDesc*) &TM__16AxP8K8JV58vb0pPrOrmA_5));
	createWindow__OOZOOZOnimbleZpkgsZnico4548O52O57Znico_6570(((NimStringDesc*) &TM__16AxP8K8JV58vb0pPrOrmA_5), ((NI) 128), ((NI) 128), ((NI) 4), NIM_FALSE);
	nimZeroMem((void*)(&T1_), sizeof(tyProc__HzVCwACFYM9cx9aV62PdjtuA));
	T1_.ClP_0 = ((TM__16AxP8K8JV58vb0pPrOrmA_9) (gameInit__main_2340)); T1_.ClE_0 = NIM_NIL;
	nimZeroMem((void*)(&T2_), sizeof(tyProc__y9aUXu4JGz72YDIZVWUrK5w));
	T2_.ClP_0 = ((TM__16AxP8K8JV58vb0pPrOrmA_34) (gameUpdate__main_2358)); T2_.ClE_0 = NIM_NIL;
	nimZeroMem((void*)(&T3_), sizeof(tyProc__HzVCwACFYM9cx9aV62PdjtuA));
	T3_.ClP_0 = ((TM__16AxP8K8JV58vb0pPrOrmA_35) (gameDraw__main_2360)); T3_.ClE_0 = NIM_NIL;
	run__OOZOOZOnimbleZpkgsZnico4548O52O57Znico_6652(T1_, T2_, T3_);
}
}

N_LIB_PRIVATE N_NIMCALL(void, atmmaindotnim_DatInit000)(void) {
static TNimNode* TM__16AxP8K8JV58vb0pPrOrmA_31_4[4];
NI TM__16AxP8K8JV58vb0pPrOrmA_33;
static char* NIM_CONST TM__16AxP8K8JV58vb0pPrOrmA_32[4] = {
"up", 
"down", 
"left", 
"right"};
static TNimNode TM__16AxP8K8JV58vb0pPrOrmA_0[6];
NTIobj58objecttype__Lrhq8PAaFQuOMGFep4lPIw_.size = sizeof(tyObject_ObjcolonObjectType___Lrhq8PAaFQuOMGFep4lPIw);
NTIobj58objecttype__Lrhq8PAaFQuOMGFep4lPIw_.align = NIM_ALIGNOF(tyObject_ObjcolonObjectType___Lrhq8PAaFQuOMGFep4lPIw);
NTIobj58objecttype__Lrhq8PAaFQuOMGFep4lPIw_.kind = 18;
NTIobj58objecttype__Lrhq8PAaFQuOMGFep4lPIw_.base = 0;
NTIobj58objecttype__Lrhq8PAaFQuOMGFep4lPIw_.flags = 1;
TM__16AxP8K8JV58vb0pPrOrmA_0[0].kind = 1;
TM__16AxP8K8JV58vb0pPrOrmA_0[0].offset = offsetof(tyObject_ObjcolonObjectType___Lrhq8PAaFQuOMGFep4lPIw, pos);
TM__16AxP8K8JV58vb0pPrOrmA_0[0].typ = (&NTIvec__HU7qaqKu9czJLT84iCBJnsA_);
TM__16AxP8K8JV58vb0pPrOrmA_0[0].name = "pos";
NTIobj58objecttype__Lrhq8PAaFQuOMGFep4lPIw_.node = &TM__16AxP8K8JV58vb0pPrOrmA_0[0];
NTIobj__I6RJaoLSAS8qrdAw1TPCYw_.size = sizeof(tyObject_ObjcolonObjectType___Lrhq8PAaFQuOMGFep4lPIw*);
NTIobj__I6RJaoLSAS8qrdAw1TPCYw_.align = NIM_ALIGNOF(tyObject_ObjcolonObjectType___Lrhq8PAaFQuOMGFep4lPIw*);
NTIobj__I6RJaoLSAS8qrdAw1TPCYw_.kind = 22;
NTIobj__I6RJaoLSAS8qrdAw1TPCYw_.base = (&NTIobj58objecttype__Lrhq8PAaFQuOMGFep4lPIw_);
NTIobj__I6RJaoLSAS8qrdAw1TPCYw_.marker = Marker_tyRef__I6RJaoLSAS8qrdAw1TPCYw;
NTIdirection__xXRgXwCzgGRAl4Ebc25nyw_.size = sizeof(tyEnum_Direction__xXRgXwCzgGRAl4Ebc25nyw);
NTIdirection__xXRgXwCzgGRAl4Ebc25nyw_.align = NIM_ALIGNOF(tyEnum_Direction__xXRgXwCzgGRAl4Ebc25nyw);
NTIdirection__xXRgXwCzgGRAl4Ebc25nyw_.kind = 14;
NTIdirection__xXRgXwCzgGRAl4Ebc25nyw_.base = 0;
NTIdirection__xXRgXwCzgGRAl4Ebc25nyw_.flags = 3;
for (TM__16AxP8K8JV58vb0pPrOrmA_33 = 0; TM__16AxP8K8JV58vb0pPrOrmA_33 < 4; TM__16AxP8K8JV58vb0pPrOrmA_33++) {
TM__16AxP8K8JV58vb0pPrOrmA_0[TM__16AxP8K8JV58vb0pPrOrmA_33+1].kind = 1;
TM__16AxP8K8JV58vb0pPrOrmA_0[TM__16AxP8K8JV58vb0pPrOrmA_33+1].offset = TM__16AxP8K8JV58vb0pPrOrmA_33;
TM__16AxP8K8JV58vb0pPrOrmA_0[TM__16AxP8K8JV58vb0pPrOrmA_33+1].name = TM__16AxP8K8JV58vb0pPrOrmA_32[TM__16AxP8K8JV58vb0pPrOrmA_33];
TM__16AxP8K8JV58vb0pPrOrmA_31_4[TM__16AxP8K8JV58vb0pPrOrmA_33] = &TM__16AxP8K8JV58vb0pPrOrmA_0[TM__16AxP8K8JV58vb0pPrOrmA_33+1];
}
TM__16AxP8K8JV58vb0pPrOrmA_0[5].len = 4; TM__16AxP8K8JV58vb0pPrOrmA_0[5].kind = 2; TM__16AxP8K8JV58vb0pPrOrmA_0[5].sons = &TM__16AxP8K8JV58vb0pPrOrmA_31_4[0];
NTIdirection__xXRgXwCzgGRAl4Ebc25nyw_.node = &TM__16AxP8K8JV58vb0pPrOrmA_0[5];
}

