/* Generated by Nim Compiler v1.7.1 */
#define NIM_INTBITS 32
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(x, y)
#define nimln_(x, y)
typedef struct tyObject_RingBuffer__ar8gPNEddpLhY9aLusEPT9aw tyObject_RingBuffer__ar8gPNEddpLhY9aLusEPT9aw;
typedef struct tySequence__JVUCJoIAFxiGphM572dT1g tySequence__JVUCJoIAFxiGphM572dT1g;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_ProfilerNode__E5E7TqSVxrgG73gWhKEuAw tyObject_ProfilerNode__E5E7TqSVxrgG73gWhKEuAw;
typedef struct NimStringDesc NimStringDesc;
typedef struct tyObject_Time__3y2ZpqsTJLqdZvpC9a0rU2Q tyObject_Time__3y2ZpqsTJLqdZvpC9a0rU2Q;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyObject_RingBuffer__pisyLaDNau6Opdq0jCP9bCA tyObject_RingBuffer__pisyLaDNau6Opdq0jCP9bCA;
typedef struct tySequence__4Xyxy0Om14N6K1l5e9bUPSQ tySequence__4Xyxy0Om14N6K1l5e9bUPSQ;
typedef struct tyObject_SurfacecolonObjectType___s5bbV5gDnl2gfvzhWCmDXQ tyObject_SurfacecolonObjectType___s5bbV5gDnl2gfvzhWCmDXQ;
typedef struct tyObject_RingBuffer__NuIhs9cwSwZ5os3vyq9b7Ekg tyObject_RingBuffer__NuIhs9cwSwZ5os3vyq9b7Ekg;
typedef struct tySequence__BPX0nQ9a18neVv9cyL9bIVAbg tySequence__BPX0nQ9a18neVv9cyL9bIVAbg;
typedef struct tySequence__wgMvnlQViw7eTDXNUYd1uQ tySequence__wgMvnlQViw7eTDXNUYd1uQ;
typedef struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ tySequence__6H5Oh5UUvVCLiakt9aTwtUQ;
typedef struct tyTuple__hSHiEU6uEtL7soi1F4tKCg tyTuple__hSHiEU6uEtL7soi1F4tKCg;
struct tyObject_RingBuffer__ar8gPNEddpLhY9aLusEPT9aw {
tySequence__JVUCJoIAFxiGphM572dT1g* data;
NI head;
NI tail;
NI size;
NI length;
};
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct tyObject_Time__3y2ZpqsTJLqdZvpC9a0rU2Q {
NI64 seconds;
NI nanosecond;
};
struct tyObject_ProfilerNode__E5E7TqSVxrgG73gWhKEuAw {
NimStringDesc* name;
tyObject_Time__3y2ZpqsTJLqdZvpC9a0rU2Q start;
NI64 time;
NI count;
tyObject_ProfilerNode__E5E7TqSVxrgG73gWhKEuAw* parent;
tySequence__JVUCJoIAFxiGphM572dT1g* children;
};
typedef NU8 tyEnum_TNimKind__jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag__v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc__ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
NI align;
tyEnum_TNimKind__jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag__v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc__ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind__unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind__unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct tyObject_RingBuffer__pisyLaDNau6Opdq0jCP9bCA {
tySequence__4Xyxy0Om14N6K1l5e9bUPSQ* data;
NI head;
NI tail;
NI size;
NI length;
};
struct tyObject_RingBuffer__NuIhs9cwSwZ5os3vyq9b7Ekg {
tySequence__BPX0nQ9a18neVv9cyL9bIVAbg* data;
NI head;
NI tail;
NI size;
NI length;
};
struct tyObject_SurfacecolonObjectType___s5bbV5gDnl2gfvzhWCmDXQ {
tySequence__wgMvnlQViw7eTDXNUYd1uQ* palette;
tySequence__6H5Oh5UUvVCLiakt9aTwtUQ* data;
NI channels;
NI w;
NI h;
NI tw;
NI th;
NimStringDesc* filename;
tySequence__6H5Oh5UUvVCLiakt9aTwtUQ* spriteFlags;
};
struct tyTuple__hSHiEU6uEtL7soi1F4tKCg {
NU8 Field0;
NU8 Field1;
NU8 Field2;
};
struct tySequence__JVUCJoIAFxiGphM572dT1g {
  TGenericSeq Sup;
  tyObject_ProfilerNode__E5E7TqSVxrgG73gWhKEuAw data[SEQ_DECL_SIZE];
};
struct tySequence__4Xyxy0Om14N6K1l5e9bUPSQ {
  TGenericSeq Sup;
  NF32 data[SEQ_DECL_SIZE];
};
struct tySequence__BPX0nQ9a18neVv9cyL9bIVAbg {
  TGenericSeq Sup;
  tyObject_SurfacecolonObjectType___s5bbV5gDnl2gfvzhWCmDXQ* data[SEQ_DECL_SIZE];
};
struct tySequence__wgMvnlQViw7eTDXNUYd1uQ {
  TGenericSeq Sup;
  tyTuple__hSHiEU6uEtL7soi1F4tKCg data[SEQ_DECL_SIZE];
};
struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ {
  TGenericSeq Sup;
  NU8 data[SEQ_DECL_SIZE];
};
N_LIB_PRIVATE N_NIMCALL(tySequence__JVUCJoIAFxiGphM572dT1g*, newSeq__OOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZcommon_1525)(NI len);
N_LIB_PRIVATE N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_LIB_PRIVATE N_NIMCALL(void, genericSeqAssign)(void* dest, void* src, TNimType* mt);
N_LIB_PRIVATE N_NIMCALL(tySequence__4Xyxy0Om14N6K1l5e9bUPSQ*, newSeq__OOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZsdl50_5784)(NI len);
N_LIB_PRIVATE N_NIMCALL(NI, idx__OOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZsdl50_727)(tyObject_RingBuffer__NuIhs9cwSwZ5os3vyq9b7Ekg b, NI i);
N_LIB_PRIVATE N_NIMCALL(NI, floorMod__OOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZsdl50_732)(NI x, NI y);
extern TNimType NTIseqLprofilernodeT__JVUCJoIAFxiGphM572dT1g_;
extern TNimType NTIseqLfloat5150T__4Xyxy0Om14N6K1l5e9bUPSQ_;
N_LIB_PRIVATE N_NIMCALL(void, initRingBuffer__OOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZcommon_1516)(NI length, tyObject_RingBuffer__ar8gPNEddpLhY9aLusEPT9aw* Result) {
	tySequence__JVUCJoIAFxiGphM572dT1g* s;
	s = newSeq__OOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZcommon_1525(((NI) (length)));
	unsureAsgnRef((void**)&(*Result).data, NIM_NIL);
	(*Result).head = 0;
	(*Result).tail = 0;
	(*Result).size = 0;
	(*Result).length = 0;
	genericSeqAssign((&(*Result).data), s, (&NTIseqLprofilernodeT__JVUCJoIAFxiGphM572dT1g_));
	(*Result).head = ((NI) 0);
	(*Result).tail = ((NI) -1);
	(*Result).size = ((NI) 0);
	(*Result).length = length;
}
N_LIB_PRIVATE N_NIMCALL(void, initRingBuffer__OOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZsdl50_5862)(NI length, tyObject_RingBuffer__pisyLaDNau6Opdq0jCP9bCA* Result) {
	tySequence__4Xyxy0Om14N6K1l5e9bUPSQ* s;
	s = newSeq__OOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZsdl50_5784(((NI) (length)));
	unsureAsgnRef((void**)&(*Result).data, NIM_NIL);
	(*Result).head = 0;
	(*Result).tail = 0;
	(*Result).size = 0;
	(*Result).length = 0;
	genericSeqAssign((&(*Result).data), s, (&NTIseqLfloat5150T__4Xyxy0Om14N6K1l5e9bUPSQ_));
	(*Result).head = ((NI) 0);
	(*Result).tail = ((NI) -1);
	(*Result).size = ((NI) 0);
	(*Result).length = length;
}
N_LIB_PRIVATE N_NIMCALL(void, add__OOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZsdl50_5749)(tyObject_RingBuffer__pisyLaDNau6Opdq0jCP9bCA* b, NF32 data) {
	(*b).tail = (NI)((NI)((*b).tail + ((NI) 1)) % (*b).length);
	(*b).data->data[(*b).tail] = data;
	(*b).size = (((NI)((*b).size + ((NI) 1)) <= (*b).length) ? (NI)((*b).size + ((NI) 1)) : (*b).length);
	(*b).head = (NI)((NI)((NI)((NI)((*b).length + (*b).tail) - (*b).size) + ((NI) 1)) % (*b).length);
}
N_LIB_PRIVATE N_NIMCALL(NI, idx__OOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZsdl50_727)(tyObject_RingBuffer__NuIhs9cwSwZ5os3vyq9b7Ekg b, NI i) {
	NI result;
	result = (NI)0;
	{
		if (!(i < ((NI) 0))) goto LA3_;
		result = floorMod__OOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZsdl50_732((NI)(b.tail + (NI)(i + ((NI) 1))), b.length);
	}
	goto LA1_;
	LA3_: ;
	{
		result = floorMod__OOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZsdl50_732((NI)(i + b.head), b.length);
	}
	LA1_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SurfacecolonObjectType___s5bbV5gDnl2gfvzhWCmDXQ*, X5BX5D___OOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZsdl50_717)(tyObject_RingBuffer__NuIhs9cwSwZ5os3vyq9b7Ekg b, NI i) {
	tyObject_SurfacecolonObjectType___s5bbV5gDnl2gfvzhWCmDXQ* result;
	NI T1_;
	result = NIM_NIL;
	T1_ = (NI)0;
	T1_ = idx__OOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZsdl50_727(b, i);
	result = b.data->data[T1_];
	return result;
}
