/* Generated by Nim Compiler v1.7.1 */
#define NIM_INTBITS 32

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(x, y)
#define nimln_(x, y)
typedef struct tyObject_PNGPass__UIEYiTVMzvtEHEJp8vwRCg tyObject_PNGPass__UIEYiTVMzvtEHEJp8vwRCg;
typedef NU8 tyEnum_PNGFilter__CLz8Dj9bk9aunLUEoDHYLQNg;
typedef NI tyArray__7faYhUidbIkFZQJndG6Ggw[7];
typedef NI tyArray__9a8QARi5WsUggNU9bom7kzTQ[8];
struct tyObject_PNGPass__UIEYiTVMzvtEHEJp8vwRCg {
tyArray__7faYhUidbIkFZQJndG6Ggw w;
tyArray__7faYhUidbIkFZQJndG6Ggw h;
tyArray__9a8QARi5WsUggNU9bom7kzTQ filterStart;
tyArray__9a8QARi5WsUggNU9bom7kzTQ paddedStart;
tyArray__9a8QARi5WsUggNU9bom7kzTQ start;
};
N_LIB_PRIVATE N_NIMCALL(void, unfilterScanline__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871_3499)(NIM_CHAR* output, NI outputLen_0, NIM_CHAR* input, NI inputLen_0, NI byteWidth, NI len, tyEnum_PNGFilter__CLz8Dj9bk9aunLUEoDHYLQNg filterType);
N_LIB_PRIVATE N_NIMCALL(void, unfilterScanline__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871_3584)(NIM_CHAR* output, NI outputLen_0, NIM_CHAR* input, NI inputLen_0, NIM_CHAR* prevLine, NI prevLineLen_0, NI byteWidth, NI len, tyEnum_PNGFilter__CLz8Dj9bk9aunLUEoDHYLQNg filterType);
N_LIB_PRIVATE N_NIMCALL(NU, paethPredictor__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Zfilters_31)(NI a, NI b, NI c);
N_LIB_PRIVATE N_NIMCALL(NI, readBitFromReversedStream__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871_3675)(NI* bitptr, NIM_CHAR* bitstream, NI bitstreamLen_0);
N_LIB_PRIVATE N_NIMCALL(void, setBitOfReversedStream__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871_3693)(NI* bitptr, NIM_CHAR* bitstream, NI bitstreamLen_0, NI bit);
N_LIB_PRIVATE N_NIMCALL(void, ampeq___OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871_3706)(NIM_CHAR* a, NIM_CHAR b);
N_LIB_PRIVATE N_NIMCALL(void, bareq___OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871_3718)(NIM_CHAR* a, NIM_CHAR b);
static N_INLINE(void, nimZeroMem)(void* p, NI size);
static N_INLINE(void, nimSetMem__systemZmemory_7)(void* a, int v, NI size);
N_LIB_PRIVATE N_NIMCALL(void, adam7PassValues__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Zfilters_305)(tyObject_PNGPass__UIEYiTVMzvtEHEJp8vwRCg* pass, NI w, NI h, NI bpp);
N_LIB_PRIVATE N_NIMCALL(void, setBitOfReversedStream0__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871_5178)(NI* bitptr, NIM_CHAR* bitstream, NI bitstreamLen_0, NI bit);
N_LIB_PRIVATE NIM_CONST tyArray__7faYhUidbIkFZQJndG6Ggw ADAM7_DX__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Zfilters_20 = {((NI) 8),
((NI) 8),
((NI) 4),
((NI) 4),
((NI) 2),
((NI) 2),
((NI) 1)}
;
N_LIB_PRIVATE NIM_CONST tyArray__7faYhUidbIkFZQJndG6Ggw ADAM7_IX__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Zfilters_18 = {((NI) 0),
((NI) 4),
((NI) 0),
((NI) 2),
((NI) 0),
((NI) 1),
((NI) 0)}
;
N_LIB_PRIVATE NIM_CONST tyArray__7faYhUidbIkFZQJndG6Ggw ADAM7_DY__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Zfilters_21 = {((NI) 8),
((NI) 8),
((NI) 8),
((NI) 4),
((NI) 4),
((NI) 2),
((NI) 2)}
;
N_LIB_PRIVATE NIM_CONST tyArray__7faYhUidbIkFZQJndG6Ggw ADAM7_IY__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Zfilters_19 = {((NI) 0),
((NI) 0),
((NI) 4),
((NI) 0),
((NI) 2),
((NI) 0),
((NI) 1)}
;
N_LIB_PRIVATE N_NIMCALL(void, unfilterScanline__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871_3499)(NIM_CHAR* output, NI outputLen_0, NIM_CHAR* input, NI inputLen_0, NI byteWidth, NI len, tyEnum_PNGFilter__CLz8Dj9bk9aunLUEoDHYLQNg filterType) {
	switch (filterType) {
	case ((tyEnum_PNGFilter__CLz8Dj9bk9aunLUEoDHYLQNg) 0):
	{
		{
			NI i;
			NI i_2;
			i = (NI)0;
			i_2 = ((NI) 0);
			{
				while (1) {
					if (!(i_2 < len)) goto LA4;
					i = i_2;
					output[i] = input[i];
					i_2 += ((NI) 1);
				} LA4: ;
			}
		}
	}
	break;
	case ((tyEnum_PNGFilter__CLz8Dj9bk9aunLUEoDHYLQNg) 1):
	{
		{
			NI i_3;
			NI i_4;
			i_3 = (NI)0;
			i_4 = ((NI) 0);
			{
				while (1) {
					if (!(i_4 < byteWidth)) goto LA8;
					i_3 = i_4;
					output[i_3] = input[i_3];
					i_4 += ((NI) 1);
				} LA8: ;
			}
		}
		{
			NI i_5;
			NI i_6;
			i_5 = (NI)0;
			i_6 = byteWidth;
			{
				while (1) {
					if (!(i_6 < len)) goto LA11;
					i_5 = i_6;
					output[i_5] = ((NIM_CHAR) ((NU)((NU)((NU32)(((NU) (((NU8)(input[i_5]))))) + (NU32)(((NU) (((NU8)(output[(NI)(i_5 - byteWidth)])))))) & ((NU) 255))));
					i_6 += ((NI) 1);
				} LA11: ;
			}
		}
	}
	break;
	case ((tyEnum_PNGFilter__CLz8Dj9bk9aunLUEoDHYLQNg) 2):
	{
		{
			NI i_7;
			NI i_8;
			i_7 = (NI)0;
			i_8 = ((NI) 0);
			{
				while (1) {
					if (!(i_8 < len)) goto LA15;
					i_7 = i_8;
					output[i_7] = input[i_7];
					i_8 += ((NI) 1);
				} LA15: ;
			}
		}
	}
	break;
	case ((tyEnum_PNGFilter__CLz8Dj9bk9aunLUEoDHYLQNg) 3):
	{
		{
			NI i_9;
			NI i_10;
			i_9 = (NI)0;
			i_10 = ((NI) 0);
			{
				while (1) {
					if (!(i_10 < byteWidth)) goto LA19;
					i_9 = i_10;
					output[i_9] = input[i_9];
					i_10 += ((NI) 1);
				} LA19: ;
			}
		}
		{
			NI i_11;
			NI i_12;
			i_11 = (NI)0;
			i_12 = byteWidth;
			{
				while (1) {
					if (!(i_12 < len)) goto LA22;
					i_11 = i_12;
					output[i_11] = ((NIM_CHAR) ((NU)((NU)((NU32)(((NU) (((NU8)(input[i_11]))))) + (NU32)((NU)((NU32)(((NU) (((NU8)(output[(NI)(i_11 - byteWidth)]))))) / (NU32)(((NU) 2))))) & ((NU) 255))));
					i_12 += ((NI) 1);
				} LA22: ;
			}
		}
	}
	break;
	case ((tyEnum_PNGFilter__CLz8Dj9bk9aunLUEoDHYLQNg) 4):
	{
		{
			NI i_13;
			NI i_14;
			i_13 = (NI)0;
			i_14 = ((NI) 0);
			{
				while (1) {
					if (!(i_14 < byteWidth)) goto LA26;
					i_13 = i_14;
					output[i_13] = input[i_13];
					i_14 += ((NI) 1);
				} LA26: ;
			}
		}
		{
			NI i_15;
			NI i_16;
			i_15 = (NI)0;
			i_16 = byteWidth;
			{
				while (1) {
					if (!(i_16 < len)) goto LA29;
					i_15 = i_16;
					output[i_15] = ((NIM_CHAR) ((NU)((NU)((NU32)(((NU) (((NU8)(input[i_15]))))) + (NU32)(((NU) (((NU8)(output[(NI)(i_15 - byteWidth)])))))) & ((NU) 255))));
					i_16 += ((NI) 1);
				} LA29: ;
			}
		}
	}
	break;
	}
}
N_LIB_PRIVATE N_NIMCALL(NU, paethPredictor__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Zfilters_31)(NI a, NI b, NI c) {
	NU result;
	NI pa;
	NI pb;
	NI pc;
{	result = (NU)0;
	pa = ((NI)(b - c) > 0? ((NI)(b - c)) : -((NI)(b - c)));
	pb = ((NI)(a - c) > 0? ((NI)(a - c)) : -((NI)(a - c)));
	pc = ((NI)((NI)((NI)(a + b) - c) - c) > 0? ((NI)((NI)((NI)(a + b) - c) - c)) : -((NI)((NI)((NI)(a + b) - c) - c)));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (pc < pa);
		if (!(T3_)) goto LA4_;
		T3_ = (pc < pb);
		LA4_: ;
		if (!T3_) goto LA5_;
		result = ((NU) (c));
		goto BeforeRet_;
	}
	goto LA1_;
	LA5_: ;
	{
		if (!(pb < pa)) goto LA8_;
		result = ((NU) (b));
		goto BeforeRet_;
	}
	goto LA1_;
	LA8_: ;
	LA1_: ;
	result = ((NU) (a));
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, unfilterScanline__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871_3584)(NIM_CHAR* output, NI outputLen_0, NIM_CHAR* input, NI inputLen_0, NIM_CHAR* prevLine, NI prevLineLen_0, NI byteWidth, NI len, tyEnum_PNGFilter__CLz8Dj9bk9aunLUEoDHYLQNg filterType) {
	switch (filterType) {
	case ((tyEnum_PNGFilter__CLz8Dj9bk9aunLUEoDHYLQNg) 0):
	{
		{
			NI i;
			NI i_2;
			i = (NI)0;
			i_2 = ((NI) 0);
			{
				while (1) {
					if (!(i_2 < len)) goto LA4;
					i = i_2;
					output[i] = input[i];
					i_2 += ((NI) 1);
				} LA4: ;
			}
		}
	}
	break;
	case ((tyEnum_PNGFilter__CLz8Dj9bk9aunLUEoDHYLQNg) 1):
	{
		{
			NI i_3;
			NI i_4;
			i_3 = (NI)0;
			i_4 = ((NI) 0);
			{
				while (1) {
					if (!(i_4 < byteWidth)) goto LA8;
					i_3 = i_4;
					output[i_3] = input[i_3];
					i_4 += ((NI) 1);
				} LA8: ;
			}
		}
		{
			NI i_5;
			NI i_6;
			i_5 = (NI)0;
			i_6 = byteWidth;
			{
				while (1) {
					if (!(i_6 < len)) goto LA11;
					i_5 = i_6;
					output[i_5] = ((NIM_CHAR) ((NU)((NU)((NU32)(((NU) (((NU8)(input[i_5]))))) + (NU32)(((NU) (((NU8)(output[(NI)(i_5 - byteWidth)])))))) & ((NU) 255))));
					i_6 += ((NI) 1);
				} LA11: ;
			}
		}
	}
	break;
	case ((tyEnum_PNGFilter__CLz8Dj9bk9aunLUEoDHYLQNg) 2):
	{
		{
			NI i_7;
			NI i_8;
			i_7 = (NI)0;
			i_8 = ((NI) 0);
			{
				while (1) {
					if (!(i_8 < len)) goto LA15;
					i_7 = i_8;
					output[i_7] = ((NIM_CHAR) ((NU)((NU)((NU32)(((NU) (((NU8)(input[i_7]))))) + (NU32)(((NU) (((NU8)(prevLine[i_7])))))) & ((NU) 255))));
					i_8 += ((NI) 1);
				} LA15: ;
			}
		}
	}
	break;
	case ((tyEnum_PNGFilter__CLz8Dj9bk9aunLUEoDHYLQNg) 3):
	{
		{
			NI i_9;
			NI i_10;
			i_9 = (NI)0;
			i_10 = ((NI) 0);
			{
				while (1) {
					if (!(i_10 < byteWidth)) goto LA19;
					i_9 = i_10;
					output[i_9] = ((NIM_CHAR) ((NU)((NU)((NU32)(((NU) (((NU8)(input[i_9]))))) + (NU32)((NU)((NU32)(((NU) (((NU8)(prevLine[i_9]))))) / (NU32)(((NU) 2))))) & ((NU) 255))));
					i_10 += ((NI) 1);
				} LA19: ;
			}
		}
		{
			NI i_11;
			NI i_12;
			i_11 = (NI)0;
			i_12 = byteWidth;
			{
				while (1) {
					if (!(i_12 < len)) goto LA22;
					i_11 = i_12;
					output[i_11] = ((NIM_CHAR) ((NU)((NU)((NU32)(((NU) (((NU8)(input[i_11]))))) + (NU32)((NU)((NU32)((NU)((NU32)(((NU) (((NU8)(output[(NI)(i_11 - byteWidth)]))))) + (NU32)(((NU) (((NU8)(prevLine[i_11]))))))) / (NU32)(((NU) 2))))) & ((NU) 255))));
					i_12 += ((NI) 1);
				} LA22: ;
			}
		}
	}
	break;
	case ((tyEnum_PNGFilter__CLz8Dj9bk9aunLUEoDHYLQNg) 4):
	{
		{
			NI i_13;
			NI i_14;
			i_13 = (NI)0;
			i_14 = ((NI) 0);
			{
				while (1) {
					if (!(i_14 < byteWidth)) goto LA26;
					i_13 = i_14;
					output[i_13] = ((NIM_CHAR) ((NU)((NU)((NU32)(((NU) (((NU8)(input[i_13]))))) + (NU32)(((NU) (((NU8)(prevLine[i_13])))))) & ((NU) 255))));
					i_14 += ((NI) 1);
				} LA26: ;
			}
		}
		{
			NI i_15;
			NI i_16;
			i_15 = (NI)0;
			i_16 = byteWidth;
			{
				while (1) {
					NU T30_;
					if (!(i_16 < len)) goto LA29;
					i_15 = i_16;
					T30_ = (NU)0;
					T30_ = paethPredictor__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Zfilters_31(((NI) (((NU8)(output[(NI)(i_15 - byteWidth)])))), ((NI) (((NU8)(prevLine[i_15])))), ((NI) (((NU8)(prevLine[(NI)(i_15 - byteWidth)])))));
					output[i_15] = ((NIM_CHAR) ((NU)((NU)((NU32)(((NU) (((NU8)(input[i_15]))))) + (NU32)(T30_)) & ((NU) 255))));
					i_16 += ((NI) 1);
				} LA29: ;
			}
		}
	}
	break;
	}
}
N_LIB_PRIVATE N_NIMCALL(void, unfilter__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871_3481)(NIM_CHAR* output, NI outputLen_0, NIM_CHAR* input, NI inputLen_0, NI w, NI h, NI bpp) {
	NI byteWidth;
	NI lineTs;
	NI prevIndex;
	byteWidth = (NI)((NI)(bpp + ((NI) 7)) / ((NI) 8));
	lineTs = (NI)((NI)((NI)(w * bpp) + ((NI) 7)) / ((NI) 8));
	{
		if (!(((NI) 0) < h)) goto LA3_;
		unfilterScanline__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871_3499(output, outputLen_0, (NIM_CHAR*)(input)+(((NI) 1)), ((NI)(inputLen_0 - ((NI) 1)))-(((NI) 1))+1, byteWidth, lineTs, ((tyEnum_PNGFilter__CLz8Dj9bk9aunLUEoDHYLQNg) (((NU8)(input[((NI) 0)])))));
	}
	LA3_: ;
	prevIndex = ((NI) 0);
	{
		NI y;
		NI i;
		y = (NI)0;
		i = ((NI) 1);
		{
			while (1) {
				NI outIndex;
				NI inIndex;
				tyEnum_PNGFilter__CLz8Dj9bk9aunLUEoDHYLQNg filterType;
				if (!(i < h)) goto LA7;
				y = i;
				outIndex = (NI)(lineTs * y);
				inIndex = (NI)((NI)(((NI) 1) + lineTs) * y);
				filterType = ((tyEnum_PNGFilter__CLz8Dj9bk9aunLUEoDHYLQNg) (((NU8)(input[inIndex]))));
				unfilterScanline__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871_3584((NIM_CHAR*)(output)+(outIndex), ((NI)(outputLen_0 - ((NI) 1)))-(outIndex)+1, (NIM_CHAR*)(input)+((NI)(inIndex + ((NI) 1))), ((NI)(inputLen_0 - ((NI) 1)))-((NI)(inIndex + ((NI) 1)))+1, (NIM_CHAR*)(output)+(prevIndex), ((NI)(outputLen_0 - ((NI) 1)))-(prevIndex)+1, byteWidth, lineTs, filterType);
				prevIndex = outIndex;
				i += ((NI) 1);
			} LA7: ;
		}
	}
}
N_LIB_PRIVATE N_NIMCALL(NI, readBitFromReversedStream__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871_3675)(NI* bitptr, NIM_CHAR* bitstream, NI bitstreamLen_0) {
	NI result;
	result = (NI)0;
	result = (NI)((NI)((NI32)(((NI) (((NU8)(bitstream[(NI)((NI32)((*bitptr)) >> (NU32)(((NI) 3)))]))))) >> (NU32)((NI)(((NI) 7) - (NI)((*bitptr) & ((NI) 7))))) & ((NI) 1));
	(*bitptr) += ((NI) 1);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, ampeq___OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871_3706)(NIM_CHAR* a, NIM_CHAR b) {
	(*a) = ((NIM_CHAR) ((NI)(((NI) (((NU8)((*a))))) & ((NI) (((NU8)(b)))))));
}
N_LIB_PRIVATE N_NIMCALL(void, bareq___OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871_3718)(NIM_CHAR* a, NIM_CHAR b) {
	(*a) = ((NIM_CHAR) ((NI)(((NI) (((NU8)((*a))))) | ((NI) (((NU8)(b)))))));
}
N_LIB_PRIVATE N_NIMCALL(void, setBitOfReversedStream__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871_3693)(NI* bitptr, NIM_CHAR* bitstream, NI bitstreamLen_0, NI bit) {
	{
		if (!(bit == ((NI) 0))) goto LA3_;
		ampeq___OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871_3706((&bitstream[(NI)((NI32)((*bitptr)) >> (NU32)(((NI) 3)))]), ((NIM_CHAR) ((NI)((NU32) ~((NI)((NU32)(((NI) 1)) << (NU32)((NI)(((NI) 7) - (NI)((*bitptr) & ((NI) 7))))))))));
	}
	goto LA1_;
	LA3_: ;
	{
		bareq___OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871_3718((&bitstream[(NI)((NI32)((*bitptr)) >> (NU32)(((NI) 3)))]), ((NIM_CHAR) ((NI)((NU32)(((NI) 1)) << (NU32)((NI)(((NI) 7) - (NI)((*bitptr) & ((NI) 7))))))));
	}
	LA1_: ;
	(*bitptr) += ((NI) 1);
}
N_LIB_PRIVATE N_NIMCALL(void, removePaddingBits__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871_3654)(NIM_CHAR* output, NI outputLen_0, NIM_CHAR* input, NI inputLen_0, NI olinebits, NI ilinebits, NI h) {
	NI diff;
	NI ibp;
	NI obp;
	diff = (NI)(ilinebits - olinebits);
	ibp = ((NI) 0);
	obp = ((NI) 0);
	{
		NI y;
		NI colontmp_;
		NI res;
		y = (NI)0;
		colontmp_ = (NI)0;
		colontmp_ = (NI)(h - ((NI) 1));
		res = ((NI) 0);
		{
			while (1) {
				if (!(res <= colontmp_)) goto LA3;
				y = res;
				{
					NI x;
					NI colontmp__2;
					NI res_2;
					x = (NI)0;
					colontmp__2 = (NI)0;
					colontmp__2 = (NI)(olinebits - ((NI) 1));
					res_2 = ((NI) 0);
					{
						while (1) {
							NI bit;
							if (!(res_2 <= colontmp__2)) goto LA6;
							x = res_2;
							bit = readBitFromReversedStream__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871_3675((&ibp), input, inputLen_0);
							setBitOfReversedStream__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871_3693((&obp), output, outputLen_0, bit);
							res_2 += ((NI) 1);
						} LA6: ;
					}
				}
				ibp += diff;
				res += ((NI) 1);
			} LA3: ;
		}
	}
}
N_LIB_PRIVATE N_NIMCALL(void, adam7PassValues__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Zfilters_305)(tyObject_PNGPass__UIEYiTVMzvtEHEJp8vwRCg* pass, NI w, NI h, NI bpp) {
	{
		NI i;
		NI res;
		i = (NI)0;
		res = ((NI) 0);
		{
			while (1) {
				if (!(res <= ((NI) 6))) goto LA3;
				i = res;
				(*pass).w[(i)- 0] = (NI)((NI)((NI)((NI)(w + ADAM7_DX__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Zfilters_20[(i)- 0]) - ADAM7_IX__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Zfilters_18[(i)- 0]) - ((NI) 1)) / ADAM7_DX__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Zfilters_20[(i)- 0]);
				(*pass).h[(i)- 0] = (NI)((NI)((NI)((NI)(h + ADAM7_DY__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Zfilters_21[(i)- 0]) - ADAM7_IY__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Zfilters_19[(i)- 0]) - ((NI) 1)) / ADAM7_DY__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Zfilters_21[(i)- 0]);
				{
					if (!((*pass).w[(i)- 0] == ((NI) 0))) goto LA6_;
					(*pass).h[(i)- 0] = ((NI) 0);
				}
				LA6_: ;
				{
					if (!((*pass).h[(i)- 0] == ((NI) 0))) goto LA10_;
					(*pass).w[(i)- 0] = ((NI) 0);
				}
				LA10_: ;
				res += ((NI) 1);
			} LA3: ;
		}
	}
	(*pass).filterStart[(((NI) 0))- 0] = ((NI) 0);
	(*pass).paddedStart[(((NI) 0))- 0] = ((NI) 0);
	(*pass).start[(((NI) 0))- 0] = ((NI) 0);
	{
		NI i_2;
		NI res_2;
		i_2 = (NI)0;
		res_2 = ((NI) 0);
		{
			while (1) {
				if (!(res_2 <= ((NI) 6))) goto LA14;
				i_2 = res_2;
				(*pass).filterStart[((NI)(i_2 + ((NI) 1)))- 0] = (*pass).filterStart[(i_2)- 0];
				{
					NIM_BOOL T17_;
					T17_ = (NIM_BOOL)0;
					T17_ = !(((*pass).w[(i_2)- 0] == ((NI) 0)));
					if (!(T17_)) goto LA18_;
					T17_ = !(((*pass).h[(i_2)- 0] == ((NI) 0)));
					LA18_: ;
					if (!T17_) goto LA19_;
					(*pass).filterStart[((NI)(i_2 + ((NI) 1)))- 0] += (NI)((*pass).h[(i_2)- 0] * (NI)(((NI) 1) + (NI)((NI)((NI)((*pass).w[(i_2)- 0] * bpp) + ((NI) 7)) / ((NI) 8))));
				}
				LA19_: ;
				(*pass).paddedStart[((NI)(i_2 + ((NI) 1)))- 0] = (NI)((*pass).paddedStart[(i_2)- 0] + (NI)((*pass).h[(i_2)- 0] * (NI)((NI)((NI)((*pass).w[(i_2)- 0] * bpp) + ((NI) 7)) / ((NI) 8))));
				(*pass).start[((NI)(i_2 + ((NI) 1)))- 0] = (NI)((*pass).start[(i_2)- 0] + (NI)((NI)((NI)((NI)((*pass).h[(i_2)- 0] * (*pass).w[(i_2)- 0]) * bpp) + ((NI) 7)) / ((NI) 8)));
				res_2 += ((NI) 1);
			} LA14: ;
		}
	}
}
static N_INLINE(void, nimSetMem__systemZmemory_7)(void* a, int v, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a, v, ((size_t) (size)));
}
static N_INLINE(void, nimZeroMem)(void* p, NI size) {
	nimSetMem__systemZmemory_7(p, ((int) 0), size);
}
N_LIB_PRIVATE N_NIMCALL(void, setBitOfReversedStream0__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871_5178)(NI* bitptr, NIM_CHAR* bitstream, NI bitstreamLen_0, NI bit) {
	{
		if (!!((bit == ((NI) 0)))) goto LA3_;
		bareq___OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871_3718((&bitstream[(NI)((NI32)((*bitptr)) >> (NU32)(((NI) 3)))]), ((NIM_CHAR) ((NI)((NU32)(bit) << (NU32)((NI)(((NI) 7) - (NI)((*bitptr) & ((NI) 7))))))));
	}
	LA3_: ;
	(*bitptr) += ((NI) 1);
}
N_LIB_PRIVATE N_NIMCALL(void, adam7Deinterlace__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871_4269)(NIM_CHAR* output, NI outputLen_0, NIM_CHAR* input, NI inputLen_0, NI w, NI h, NI bpp) {
	tyObject_PNGPass__UIEYiTVMzvtEHEJp8vwRCg pass;
	nimZeroMem((void*)(&pass), sizeof(tyObject_PNGPass__UIEYiTVMzvtEHEJp8vwRCg));
	adam7PassValues__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Zfilters_305((&pass), w, h, bpp);
	{
		if (!(((NI) 8) <= bpp)) goto LA3_;
		{
			NI i;
			NI res;
			i = (NI)0;
			res = ((NI) 0);
			{
				while (1) {
					NI byteWidth;
					if (!(res <= ((NI) 6))) goto LA7;
					i = res;
					byteWidth = (NI)(bpp / ((NI) 8));
					{
						NI y;
						NI colontmp_;
						NI i_2;
						y = (NI)0;
						colontmp_ = (NI)0;
						colontmp_ = pass.h[(i)- 0];
						i_2 = ((NI) 0);
						{
							while (1) {
								if (!(i_2 < colontmp_)) goto LA10;
								y = i_2;
								{
									NI x;
									NI colontmp__2;
									NI i_3;
									x = (NI)0;
									colontmp__2 = (NI)0;
									colontmp__2 = pass.w[(i)- 0];
									i_3 = ((NI) 0);
									{
										while (1) {
											NI inStart;
											NI outStart;
											if (!(i_3 < colontmp__2)) goto LA13;
											x = i_3;
											inStart = (NI)(pass.start[(i)- 0] + (NI)((NI)((NI)(y * pass.w[(i)- 0]) + x) * byteWidth));
											outStart = (NI)((NI)((NI)((NI)((NI)(ADAM7_IY__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Zfilters_19[(i)- 0] + (NI)(y * ADAM7_DY__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Zfilters_21[(i)- 0])) * w) + ADAM7_IX__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Zfilters_18[(i)- 0]) + (NI)(x * ADAM7_DX__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Zfilters_20[(i)- 0])) * byteWidth);
											{
												NI b;
												NI i_4;
												b = (NI)0;
												i_4 = ((NI) 0);
												{
													while (1) {
														if (!(i_4 < byteWidth)) goto LA16;
														b = i_4;
														output[(NI)(outStart + b)] = input[(NI)(inStart + b)];
														i_4 += ((NI) 1);
													} LA16: ;
												}
											}
											i_3 += ((NI) 1);
										} LA13: ;
									}
								}
								i_2 += ((NI) 1);
							} LA10: ;
						}
					}
					res += ((NI) 1);
				} LA7: ;
			}
		}
	}
	goto LA1_;
	LA3_: ;
	{
		{
			NI i_5;
			NI res_2;
			i_5 = (NI)0;
			res_2 = ((NI) 0);
			{
				while (1) {
					NI ilinebits;
					NI olinebits;
					if (!(res_2 <= ((NI) 6))) goto LA20;
					i_5 = res_2;
					ilinebits = (NI)(bpp * pass.w[(i_5)- 0]);
					olinebits = (NI)(bpp * w);
					{
						NI y_2;
						NI colontmp__3;
						NI i_6;
						y_2 = (NI)0;
						colontmp__3 = (NI)0;
						colontmp__3 = pass.h[(i_5)- 0];
						i_6 = ((NI) 0);
						{
							while (1) {
								if (!(i_6 < colontmp__3)) goto LA23;
								y_2 = i_6;
								{
									NI x_2;
									NI colontmp__4;
									NI i_7;
									x_2 = (NI)0;
									colontmp__4 = (NI)0;
									colontmp__4 = pass.w[(i_5)- 0];
									i_7 = ((NI) 0);
									{
										while (1) {
											NI ibp;
											NI obp;
											if (!(i_7 < colontmp__4)) goto LA26;
											x_2 = i_7;
											ibp = (NI)((NI)(((NI) 8) * pass.start[(i_5)- 0]) + (NI)((NI)(y_2 * ilinebits) + (NI)(x_2 * bpp)));
											obp = (NI)((NI)((NI)(ADAM7_IY__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Zfilters_19[(i_5)- 0] + (NI)(y_2 * ADAM7_DY__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Zfilters_21[(i_5)- 0])) * olinebits) + (NI)((NI)(ADAM7_IX__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Zfilters_18[(i_5)- 0] + (NI)(x_2 * ADAM7_DX__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871Zfilters_20[(i_5)- 0])) * bpp));
											{
												NI b_2;
												NI i_8;
												b_2 = (NI)0;
												i_8 = ((NI) 0);
												{
													while (1) {
														NI bit;
														if (!(i_8 < bpp)) goto LA29;
														b_2 = i_8;
														bit = readBitFromReversedStream__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871_3675((&ibp), input, inputLen_0);
														setBitOfReversedStream0__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871_5178((&obp), output, outputLen_0, bit);
														i_8 += ((NI) 1);
													} LA29: ;
												}
											}
											i_7 += ((NI) 1);
										} LA26: ;
									}
								}
								i_6 += ((NI) 1);
							} LA23: ;
						}
					}
					res_2 += ((NI) 1);
				} LA20: ;
			}
		}
	}
	LA1_: ;
}
N_LIB_PRIVATE N_NIMCALL(NI, readBitsFromReversedStream__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871_6887)(NI* bitptr, NIM_CHAR* bitstream, NI bitstreamLen_0, NI nbits) {
	NI result;
	NI i;
	result = (NI)0;
	result = ((NI) 0);
	i = (NI)(nbits - ((NI) 1));
	{
		while (1) {
			NI T3_;
			if (!(((NI) -1) < i)) goto LA2;
			T3_ = (NI)0;
			T3_ = readBitFromReversedStream__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871_3675(bitptr, bitstream, bitstreamLen_0);
			result += (NI)((NU32)(T3_) << (NU32)(i));
			i -= ((NI) 1);
		} LA2: ;
	}
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, addColorBits__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871_7520)(NIM_CHAR* output, NI outputLen_0, NI index, NI bits, NI input) {
	NI m;
	NI p;
	NI val;
	NI idx;
	m = ((NI) 1);
	{
		if (!(bits == ((NI) 1))) goto LA3_;
		m = ((NI) 7);
	}
	goto LA1_;
	LA3_: ;
	{
		if (!(bits == ((NI) 2))) goto LA6_;
		m = ((NI) 3);
	}
	goto LA1_;
	LA6_: ;
	LA1_: ;
	p = (NI)(index & m);
	val = (NI)(input & (NI)((NI)((NU32)(((NI) 1)) << (NU32)(bits)) - ((NI) 1)));
	val = (NI)((NU32)(val) << (NU32)((NI)(bits * (NI)(m - p))));
	idx = (NI)((NI)(index * bits) / ((NI) 8));
	{
		if (!(p == ((NI) 0))) goto LA10_;
		output[idx] = ((NIM_CHAR) (val));
	}
	goto LA8_;
	LA10_: ;
	{
		output[idx] = ((NIM_CHAR) ((NI)(((NI) (((NU8)(output[idx])))) | val)));
	}
	LA8_: ;
}
