/* Generated by Nim Compiler v1.7.1 */
#define NIM_INTBITS 32

#include "nimbase.h"
#include <setjmp.h>
#include <string.h>
#include <stdio.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(x, y)
#define nimln_(x, y)
typedef struct tyObject_OrderedTable__UVxsO8EtsgVrmdBJlfhbxA tyObject_OrderedTable__UVxsO8EtsgVrmdBJlfhbxA;
typedef struct tySequence__9b9bQp3iQ3wUkkIUUJdnRM5Q tySequence__9b9bQp3iQ3wUkkIUUJdnRM5Q;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyTuple__FVrpX6NSm2kCOe3mqHLSLQ tyTuple__FVrpX6NSm2kCOe3mqHLSLQ;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_OrderedTable__aBRulY0v9b6F4b7NLhEoU1Q tyObject_OrderedTable__aBRulY0v9b6F4b7NLhEoU1Q;
typedef struct tySequence__dl1tcid0VwP1mpWNDzitYw tySequence__dl1tcid0VwP1mpWNDzitYw;
typedef struct tyTuple__pmSRO1HvsVFWcLoeG9bs4Yg tyTuple__pmSRO1HvsVFWcLoeG9bs4Yg;
typedef struct tyObject_FileStreamObj__9bEVSsOIpkY9cf5lCtaS39bPQ tyObject_FileStreamObj__9bEVSsOIpkY9cf5lCtaS39bPQ;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct tySequence__uB9b75OUPRENsBAu4AnoePA tySequence__uB9b75OUPRENsBAu4AnoePA;
typedef struct TSafePoint TSafePoint;
typedef struct tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ;
typedef struct tyObject_CfgParser__r3Jw8HBNj9b667nxe8vVd9bw tyObject_CfgParser__r3Jw8HBNj9b667nxe8vVd9bw;
typedef struct tyObject_BaseLexer__MAw8rJZtJ279bVV3TWMtXSg tyObject_BaseLexer__MAw8rJZtJ279bVV3TWMtXSg;
typedef struct tyObject_Token__yWkcM1ijvGYnxTAxtl3FPw tyObject_Token__yWkcM1ijvGYnxTAxtl3FPw;
typedef struct tyObject_CfgEvent__9blb2N9brhIlBVapT72kwOHg tyObject_CfgEvent__9blb2N9brhIlBVapT72kwOHg;
typedef struct tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA;
typedef struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA;
struct tyObject_OrderedTable__UVxsO8EtsgVrmdBJlfhbxA {
tySequence__9b9bQp3iQ3wUkkIUUJdnRM5Q* data;
NI counter;
NI first;
NI last;
};
typedef NU8 tyEnum_TNimKind__jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag__v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc__ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
NI align;
tyEnum_TNimKind__jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag__v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc__ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct tyTuple__FVrpX6NSm2kCOe3mqHLSLQ {
NI Field0;
NI Field1;
NimStringDesc* Field2;
tyObject_OrderedTable__aBRulY0v9b6F4b7NLhEoU1Q* Field3;
};
typedef NU8 tyEnum_TNimNodeKind__unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind__unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct tyObject_OrderedTable__aBRulY0v9b6F4b7NLhEoU1Q {
tySequence__dl1tcid0VwP1mpWNDzitYw* data;
NI counter;
NI first;
NI last;
};
struct tyTuple__pmSRO1HvsVFWcLoeG9bs4Yg {
NI Field0;
NI Field1;
NimStringDesc* Field2;
NimStringDesc* Field3;
};
typedef NU8 tyEnum_FileMode__4sJyy9aOSN8X63XdWXl5iDg;
struct RootObj {
TNimType* m_type;
};
struct Exception {
  RootObj Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
tySequence__uB9b75OUPRENsBAu4AnoePA* trace;
Exception* up;
};
struct TSafePoint {
TSafePoint* prev;
NI status;
jmp_buf context;
};
typedef NU8 tySet_tyChar__nmiMWKVIe46vacnhAFrQvw[32];
struct tyObject_BaseLexer__MAw8rJZtJ279bVV3TWMtXSg {
  RootObj Sup;
NI bufpos;
NimStringDesc* buf;
tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ* input;
NI lineNumber;
NI sentinel;
NI lineStart;
NI offsetBase;
tySet_tyChar__nmiMWKVIe46vacnhAFrQvw refillChars;
};
typedef NU8 tyEnum_TokKind__PvpTf9b5cBhdKx1DK5Ed3dg;
struct tyObject_Token__yWkcM1ijvGYnxTAxtl3FPw {
tyEnum_TokKind__PvpTf9b5cBhdKx1DK5Ed3dg kind;
NimStringDesc* literal;
};
struct tyObject_CfgParser__r3Jw8HBNj9b667nxe8vVd9bw {
  tyObject_BaseLexer__MAw8rJZtJ279bVV3TWMtXSg Sup;
tyObject_Token__yWkcM1ijvGYnxTAxtl3FPw tok;
NimStringDesc* filename;
};
typedef NU8 tyEnum_CfgEventKind__f0xwqI11H3rviaTXvjDJug;
struct tyObject_CfgEvent__9blb2N9brhIlBVapT72kwOHg {
  RootObj Sup;
tyEnum_CfgEventKind__f0xwqI11H3rviaTXvjDJug kind;
union{
struct {NimStringDesc* section;
} _kind_2;
struct {NimStringDesc* key;
NimStringDesc* value;
} _kind_3;
struct {NimStringDesc* msg;
} _kind_4;
};
};
typedef NimStringDesc* tyArray__sMpvt1sOxOJ3LFGulnbeMQ[4];
typedef N_NIMCALL_PTR(void, tyProc__JQrsH08b4uPTH9cyFPlVOZg) (tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ* s);
typedef N_NIMCALL_PTR(NIM_BOOL, tyProc__9bmhFrLahRsL2hltfRDVtlQ) (tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ* s);
typedef N_NIMCALL_PTR(void, tyProc__3svSoGIUJIsHkaBL7q4DAQ) (tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ* s, NI pos);
typedef N_NIMCALL_PTR(NI, tyProc__xflqkf2D1uVClg70czEDHA) (tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ* s);
typedef N_NIMCALL_PTR(NI, tyProc__c9c0f59ak4YGQ6neEym8LPKw) (tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ* s, NimStringDesc** buffer, tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA slice);
typedef N_NIMCALL_PTR(NIM_BOOL, tyProc__7jFfqMk9ajToCz6Hv9atCA4A) (tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ* s, NimStringDesc** line);
typedef N_NIMCALL_PTR(NI, tyProc__2VVzVL9bOnKhj1eZKkf9cEuA) (tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ* s, void* buffer, NI bufLen);
typedef N_NIMCALL_PTR(void, tyProc__ki6p1QyfOkJLQJ9aw5NI0AQ) (tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ* s, void* buffer, NI bufLen);
struct tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ {
  RootObj Sup;
tyProc__JQrsH08b4uPTH9cyFPlVOZg closeImpl;
tyProc__9bmhFrLahRsL2hltfRDVtlQ atEndImpl;
tyProc__3svSoGIUJIsHkaBL7q4DAQ setPositionImpl;
tyProc__xflqkf2D1uVClg70czEDHA getPositionImpl;
tyProc__c9c0f59ak4YGQ6neEym8LPKw readDataStrImpl;
tyProc__7jFfqMk9ajToCz6Hv9atCA4A readLineImpl;
tyProc__2VVzVL9bOnKhj1eZKkf9cEuA readDataImpl;
tyProc__2VVzVL9bOnKhj1eZKkf9cEuA peekDataImpl;
tyProc__ki6p1QyfOkJLQJ9aw5NI0AQ writeDataImpl;
tyProc__JQrsH08b4uPTH9cyFPlVOZg flushImpl;
};
struct tyObject_FileStreamObj__9bEVSsOIpkY9cf5lCtaS39bPQ {
  tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ Sup;
FILE* f;
};
struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA {
NCSTRING procname;
NI line;
NCSTRING filename;
};
struct tyObject_HSlice__EE5dzjqoOrHT6HJhIPXAvA {
NI a;
NI b;
};
struct tySequence__dl1tcid0VwP1mpWNDzitYw {
  TGenericSeq Sup;
  tyTuple__pmSRO1HvsVFWcLoeG9bs4Yg data[SEQ_DECL_SIZE];
};
struct tySequence__9b9bQp3iQ3wUkkIUUJdnRM5Q {
  TGenericSeq Sup;
  tyTuple__FVrpX6NSm2kCOe3mqHLSLQ data[SEQ_DECL_SIZE];
};
struct tySequence__uB9b75OUPRENsBAu4AnoePA {
  TGenericSeq Sup;
  tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];
};
N_LIB_PRIVATE N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, Marker_tySequence__dl1tcid0VwP1mpWNDzitYw)(void* p, NI op);
static N_NIMCALL(void, Marker_tyRef__8kFhhKJlXkGtMIodYIt4Sg)(void* p, NI op);
static N_NIMCALL(void, Marker_tySequence__9b9bQp3iQ3wUkkIUUJdnRM5Q)(void* p, NI op);
static N_NIMCALL(void, Marker_tyRef__r9abUm9c3sgFCZhdO4Iaq3NA)(void* p, NI op);
N_LIB_PRIVATE N_NIMCALL(FILE*, open__stdZsyncio_436)(NimStringDesc* filename, tyEnum_FileMode__4sJyy9aOSN8X63XdWXl5iDg mode, NI bufSize);
N_LIB_PRIVATE N_NIMCALL(tyObject_FileStreamObj__9bEVSsOIpkY9cf5lCtaS39bPQ*, newFileStream__pureZstreams_842)(FILE* f);
static N_INLINE(void, pushSafePoint)(TSafePoint* s);
N_LIB_PRIVATE N_NIMCALL(tyObject_OrderedTable__UVxsO8EtsgVrmdBJlfhbxA*, loadConfig__pureZparsecfg_2132)(tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ* stream, NimStringDesc* filename);
N_LIB_PRIVATE N_NIMCALL(tyObject_OrderedTable__UVxsO8EtsgVrmdBJlfhbxA*, newOrderedTable__pureZparsecfg_351)(NI initialSize);
static N_INLINE(void, nimZeroMem)(void* p, NI size);
static N_INLINE(void, nimSetMem__systemZmemory_7)(void* a, int v, NI size);
N_LIB_PRIVATE N_NIMCALL(void, npcopen)(tyObject_CfgParser__r3Jw8HBNj9b667nxe8vVd9bw* c, tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ* input, NimStringDesc* filename, NI lineOffset);
N_LIB_PRIVATE N_NIMCALL(void, open__pureZlexbase_122)(tyObject_BaseLexer__MAw8rJZtJ279bVV3TWMtXSg* L, tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ* input, NI bufLen, tySet_tyChar__nmiMWKVIe46vacnhAFrQvw refillChars);
N_LIB_PRIVATE N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_LIB_PRIVATE N_NIMCALL(void, rawGetTok__pureZparsecfg_45)(tyObject_CfgParser__r3Jw8HBNj9b667nxe8vVd9bw* c, tyObject_Token__yWkcM1ijvGYnxTAxtl3FPw* tok);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, setLengthStr)(NimStringDesc* s, NI newLen);
N_LIB_PRIVATE N_NIMCALL(void, skip__pureZparsecfg_214)(tyObject_CfgParser__r3Jw8HBNj9b667nxe8vVd9bw* c);
N_LIB_PRIVATE N_NIMCALL(NI, handleCRLF__pureZparsecfg_168)(tyObject_CfgParser__r3Jw8HBNj9b667nxe8vVd9bw* c, NI pos);
N_LIB_PRIVATE N_NIMCALL(NI, handleCR__pureZlexbase_79)(tyObject_BaseLexer__MAw8rJZtJ279bVV3TWMtXSg* L, NI pos);
N_LIB_PRIVATE N_NIMCALL(NI, handleLF__pureZlexbase_90)(tyObject_BaseLexer__MAw8rJZtJ279bVV3TWMtXSg* L, NI pos);
N_LIB_PRIVATE N_NIMCALL(void, getSymbol__pureZparsecfg_202)(tyObject_CfgParser__r3Jw8HBNj9b667nxe8vVd9bw* c, tyObject_Token__yWkcM1ijvGYnxTAxtl3FPw* tok);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, addChar)(NimStringDesc* s, NIM_CHAR c);
static N_INLINE(NIM_CHAR*, X5BX5D___system_8275)(NimStringDesc** s, NI i);
N_LIB_PRIVATE N_NIMCALL(void, getString__pureZparsecfg_172)(tyObject_CfgParser__r3Jw8HBNj9b667nxe8vVd9bw* c, tyObject_Token__yWkcM1ijvGYnxTAxtl3FPw* tok, NIM_BOOL rawMode);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem__system_1727)(void* dest, void* source, NI size);
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
N_LIB_PRIVATE N_NIMCALL(void, getEscapedChar__pureZparsecfg_103)(tyObject_CfgParser__r3Jw8HBNj9b667nxe8vVd9bw* c, tyObject_Token__yWkcM1ijvGYnxTAxtl3FPw* tok);
static N_INLINE(NIM_BOOL, handleHexChar__stdZprivateZdecode95helpers_1)(NIM_CHAR c, NI* x);
N_LIB_PRIVATE N_NIMCALL(void, handleDecChars__pureZparsecfg_86)(tyObject_CfgParser__r3Jw8HBNj9b667nxe8vVd9bw* c, NI* xi);
N_LIB_PRIVATE N_NIMCALL(void, npcnext)(tyObject_CfgParser__r3Jw8HBNj9b667nxe8vVd9bw* c, tyObject_CfgEvent__9blb2N9brhIlBVapT72kwOHg* Result);
N_LIB_PRIVATE N_NIMCALL(void, getKeyValPair__pureZparsecfg_276)(tyObject_CfgParser__r3Jw8HBNj9b667nxe8vVd9bw* c, tyEnum_CfgEventKind__f0xwqI11H3rviaTXvjDJug kind, tyObject_CfgEvent__9blb2N9brhIlBVapT72kwOHg* Result);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, npcerrorStr)(tyObject_CfgParser__r3Jw8HBNj9b667nxe8vVd9bw* c, NimStringDesc* msg);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, nsuFormatOpenArray)(NimStringDesc* formatstr, NimStringDesc** a, NI aLen_0);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar___systemZdollars_8)(NI x);
N_LIB_PRIVATE N_NIMCALL(NI, npcgetLine)(tyObject_CfgParser__r3Jw8HBNj9b667nxe8vVd9bw* c);
N_LIB_PRIVATE N_NIMCALL(NI, npcgetColumn)(tyObject_CfgParser__r3Jw8HBNj9b667nxe8vVd9bw* c);
N_LIB_PRIVATE N_NIMCALL(NI, getColNumber__pureZlexbase_137)(tyObject_BaseLexer__MAw8rJZtJ279bVV3TWMtXSg* L, NI pos);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
N_LIB_PRIVATE N_NIMCALL(tyObject_OrderedTable__aBRulY0v9b6F4b7NLhEoU1Q*, newOrderedTable__pureZparsecfg_2150)(NI initialSize);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, hasKey__pureZparsecfg_3923)(tyObject_OrderedTable__UVxsO8EtsgVrmdBJlfhbxA* t, NimStringDesc* key);
N_LIB_PRIVATE N_NIMCALL(tyObject_OrderedTable__aBRulY0v9b6F4b7NLhEoU1Q**, X5BX5D___pureZparsecfg_4096)(tyObject_OrderedTable__UVxsO8EtsgVrmdBJlfhbxA* t, NimStringDesc* key);
N_LIB_PRIVATE N_NIMCALL(void, X5BX5Deq___pureZparsecfg_2284)(tyObject_OrderedTable__aBRulY0v9b6F4b7NLhEoU1Q* t, NimStringDesc* key, NimStringDesc* val);
N_LIB_PRIVATE N_NIMCALL(void, X5BX5Deq___pureZparsecfg_503)(tyObject_OrderedTable__UVxsO8EtsgVrmdBJlfhbxA* t, NimStringDesc* key, tyObject_OrderedTable__aBRulY0v9b6F4b7NLhEoU1Q* val);
N_LIB_PRIVATE N_NIMCALL(void, npcclose)(tyObject_CfgParser__r3Jw8HBNj9b667nxe8vVd9bw* c);
N_LIB_PRIVATE N_NIMCALL(void, close__pureZlexbase_14)(tyObject_BaseLexer__MAw8rJZtJ279bVV3TWMtXSg* L);
static N_INLINE(void, popSafePoint)(void);
N_LIB_PRIVATE N_NIMCALL(void, close__pureZstreams_57)(tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ* s);
N_LIB_PRIVATE N_NIMCALL(void, nimLeaveFinally)(void);
N_LIB_PRIVATE N_NIMCALL(void, reraiseException)(void);
N_LIB_PRIVATE TNimType NTIorderedtable__UVxsO8EtsgVrmdBJlfhbxA_;
N_LIB_PRIVATE TNimType NTIorderedkeyvaluepair__FVrpX6NSm2kCOe3mqHLSLQ_;
extern TNimType NTIint__rR5Bzr1D5krxoo1NcNyeMA_;
extern TNimType NTIstring__77mFvmsOLKik79ci2hXkHEg_;
N_LIB_PRIVATE TNimType NTIorderedtable__aBRulY0v9b6F4b7NLhEoU1Q_;
N_LIB_PRIVATE TNimType NTIorderedkeyvaluepair__pmSRO1HvsVFWcLoeG9bs4Yg_;
N_LIB_PRIVATE TNimType NTIorderedkeyvaluepairseq__dl1tcid0VwP1mpWNDzitYw_;
N_LIB_PRIVATE TNimType NTIorderedtableref__8kFhhKJlXkGtMIodYIt4Sg_;
N_LIB_PRIVATE TNimType NTIorderedkeyvaluepairseq__9b9bQp3iQ3wUkkIUUJdnRM5Q_;
N_LIB_PRIVATE TNimType NTIorderedtableref__r9abUm9c3sgFCZhdO4Iaq3NA_;
extern TNimType NTIbaselexer__MAw8rJZtJ279bVV3TWMtXSg_;
N_LIB_PRIVATE TNimType NTIcfgparser__r3Jw8HBNj9b667nxe8vVd9bw_;
N_LIB_PRIVATE TNimType NTItoken__yWkcM1ijvGYnxTAxtl3FPw_;
N_LIB_PRIVATE TNimType NTItokkind__PvpTf9b5cBhdKx1DK5Ed3dg_;
static NIM_CONST tySet_tyChar__nmiMWKVIe46vacnhAFrQvw TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_12 = {
0x00, 0x24, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
;
STRING_LITERAL(TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_13, "=", 1);
STRING_LITERAL(TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_14, "--", 2);
static NIM_CONST tySet_tyChar__nmiMWKVIe46vacnhAFrQvw TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_15 = {
0x00, 0x00, 0x00, 0x00, 0x01, 0xe0, 0xff, 0x03,
0xfe, 0xff, 0xff, 0x97, 0xfe, 0xff, 0xff, 0x07,
0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff,
0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff}
;
STRING_LITERAL(TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_16, ":", 1);
STRING_LITERAL(TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_17, "\012", 1);
STRING_LITERAL(TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_18, "[", 1);
STRING_LITERAL(TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_19, "]", 1);
STRING_LITERAL(TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_20, "[EOF]", 5);
extern TNimType NTIrootobj__ytyiCJqK439aF9cIibuRVpAg_;
N_LIB_PRIVATE TNimType NTIcfgevent__9blb2N9brhIlBVapT72kwOHg_;
N_LIB_PRIVATE TNimType NTIcfgeventkind__f0xwqI11H3rviaTXvjDJug_;
TNimNode* NimDT___9blb2N9brhIlBVapT72kwOHg_kind[6];
STRING_LITERAL(TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_25, "$1($2, $3) Error: $4", 20);
STRING_LITERAL(TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_26, "symbol expected, but found: ", 28);
STRING_LITERAL(TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_27, "\']\' expected, but found: ", 25);
STRING_LITERAL(TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_28, "invalid token: ", 15);
extern NIM_THREADVAR TSafePoint* excHandler__system_3096;
extern NIM_THREADVAR TSafePoint* excHandler__system_3096;
extern NIM_THREADVAR TSafePoint* excHandler__system_3096;
extern NIM_THREADVAR TSafePoint* excHandler__system_3096;
static N_NIMCALL(void, Marker_tySequence__dl1tcid0VwP1mpWNDzitYw)(void* p, NI op) {
	tySequence__dl1tcid0VwP1mpWNDzitYw* a;
	NI T1_;
	a = (tySequence__dl1tcid0VwP1mpWNDzitYw*)p;
	T1_ = (NI)0;
	for (T1_ = 0; T1_ < (a ? a->Sup.len : 0); T1_++) {
	nimGCvisit((void*)a->data[T1_].Field2, op);
	nimGCvisit((void*)a->data[T1_].Field3, op);
	}
}
static N_NIMCALL(void, Marker_tyRef__8kFhhKJlXkGtMIodYIt4Sg)(void* p, NI op) {
	tyObject_OrderedTable__aBRulY0v9b6F4b7NLhEoU1Q* a;
	a = (tyObject_OrderedTable__aBRulY0v9b6F4b7NLhEoU1Q*)p;
	nimGCvisit((void*)(*a).data, op);
}
static N_NIMCALL(void, Marker_tySequence__9b9bQp3iQ3wUkkIUUJdnRM5Q)(void* p, NI op) {
	tySequence__9b9bQp3iQ3wUkkIUUJdnRM5Q* a;
	NI T1_;
	a = (tySequence__9b9bQp3iQ3wUkkIUUJdnRM5Q*)p;
	T1_ = (NI)0;
	for (T1_ = 0; T1_ < (a ? a->Sup.len : 0); T1_++) {
	nimGCvisit((void*)a->data[T1_].Field2, op);
	nimGCvisit((void*)a->data[T1_].Field3, op);
	}
}
static N_NIMCALL(void, Marker_tyRef__r9abUm9c3sgFCZhdO4Iaq3NA)(void* p, NI op) {
	tyObject_OrderedTable__UVxsO8EtsgVrmdBJlfhbxA* a;
	a = (tyObject_OrderedTable__UVxsO8EtsgVrmdBJlfhbxA*)p;
	nimGCvisit((void*)(*a).data, op);
}
static N_INLINE(void, pushSafePoint)(TSafePoint* s) {
	(*s).prev = excHandler__system_3096;
	excHandler__system_3096 = s;
}
static N_INLINE(void, nimSetMem__systemZmemory_7)(void* a, int v, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a, v, ((size_t) (size)));
}
static N_INLINE(void, nimZeroMem)(void* p, NI size) {
	nimSetMem__systemZmemory_7(p, ((int) 0), size);
}
N_LIB_PRIVATE N_NIMCALL(NI, handleCRLF__pureZparsecfg_168)(tyObject_CfgParser__r3Jw8HBNj9b667nxe8vVd9bw* c, NI pos) {
	NI result;
	result = (NI)0;
	switch (((NU8)((*c).Sup.buf->data[pos]))) {
	case 13:
	{
		result = handleCR__pureZlexbase_79(&c->Sup, pos);
	}
	break;
	case 10:
	{
		result = handleLF__pureZlexbase_90(&c->Sup, pos);
	}
	break;
	default:
	{
		result = pos;
	}
	break;
	}
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, skip__pureZparsecfg_214)(tyObject_CfgParser__r3Jw8HBNj9b667nxe8vVd9bw* c) {
	NI pos;
	pos = (*c).Sup.bufpos;
	{
		while (1) {
			switch (((NU8)((*c).Sup.buf->data[pos]))) {
			case 32:
			case 9:
			{
				pos += ((NI) 1);
			}
			break;
			case 35:
			case 59:
			{
				{
					while (1) {
						if (!!((((NU8)((*c).Sup.buf->data[pos])) == ((NU8)(13)) || ((NU8)((*c).Sup.buf->data[pos])) == ((NU8)(10)) || ((NU8)((*c).Sup.buf->data[pos])) == ((NU8)(0))))) goto LA6;
						pos += ((NI) 1);
					} LA6: ;
				}
			}
			break;
			case 13:
			case 10:
			{
				pos = handleCRLF__pureZparsecfg_168(c, pos);
			}
			break;
			default:
			{
				goto LA1;
			}
			break;
			}
		}
	} LA1: ;
	(*c).Sup.bufpos = pos;
}
static N_INLINE(NIM_CHAR*, X5BX5D___system_8275)(NimStringDesc** s, NI i) {
	NIM_CHAR* result;
	result = (NIM_CHAR*)0;
	result = (&(*s)->data[(NI)(((*s) ? (*s)->Sup.len : 0) - i)]);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, getSymbol__pureZparsecfg_202)(tyObject_CfgParser__r3Jw8HBNj9b667nxe8vVd9bw* c, tyObject_Token__yWkcM1ijvGYnxTAxtl3FPw* tok) {
	NI pos;
	pos = (*c).Sup.bufpos;
	{
		while (1) {
			unsureAsgnRef((void**) (&(*tok).literal), addChar((*tok).literal, (*c).Sup.buf->data[pos]));
			pos += ((NI) 1);
			{
				if (!!(((TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_15[(NU)(((NU8)((*c).Sup.buf->data[pos])))>>3] &(1U<<((NU)(((NU8)((*c).Sup.buf->data[pos])))&7U)))!=0))) goto LA5_;
				goto LA1;
			}
			LA5_: ;
		}
	} LA1: ;
	{
		while (1) {
			NIM_BOOL T9_;
			NIM_CHAR* T11_;
			T9_ = (NIM_BOOL)0;
			T9_ = (((NI) 0) < ((*tok).literal ? (*tok).literal->Sup.len : 0));
			if (!(T9_)) goto LA10_;
			T11_ = (NIM_CHAR*)0;
			T11_ = X5BX5D___system_8275((&(*tok).literal), ((NI) 1));
			T9_ = ((NU8)((*T11_)) == (NU8)(32));
			LA10_: ;
			if (!T9_) goto LA8;
			unsureAsgnRef((void**) (&(*tok).literal), setLengthStr((*tok).literal, ((NI) ((NI)(((*tok).literal ? (*tok).literal->Sup.len : 0) - ((NI) 1))))));
		} LA8: ;
	}
	(*c).Sup.bufpos = pos;
	(*tok).kind = ((tyEnum_TokKind__PvpTf9b5cBhdKx1DK5Ed3dg) 2);
}
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}
static N_INLINE(void, copyMem__system_1727)(void* dest, void* source, NI size) {
	nimCopyMem(dest, source, size);
}
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	{
		if (!!((src == ((NimStringDesc*) NIM_NIL)))) goto LA3_;
		copyMem__system_1727(((void*) ((&(*dest).data[(*dest).Sup.len]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
		(*dest).Sup.len += (*src).Sup.len;
	}
	LA3_: ;
}
static N_INLINE(NIM_BOOL, handleHexChar__stdZprivateZdecode95helpers_1)(NIM_CHAR c, NI* x) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	result = NIM_TRUE;
	switch (((NU8)(c))) {
	case 48 ... 57:
	{
		(*x) = (NI)((NI)((NU32)((*x)) << (NU32)(((NI) 4))) | (NI)(((NU8)(c)) - ((NI) 48)));
	}
	break;
	case 97 ... 102:
	{
		(*x) = (NI)((NI)((NU32)((*x)) << (NU32)(((NI) 4))) | (NI)((NI)(((NU8)(c)) - ((NI) 97)) + ((NI) 10)));
	}
	break;
	case 65 ... 70:
	{
		(*x) = (NI)((NI)((NU32)((*x)) << (NU32)(((NI) 4))) | (NI)((NI)(((NU8)(c)) - ((NI) 65)) + ((NI) 10)));
	}
	break;
	default:
	{
		result = NIM_FALSE;
	}
	break;
	}
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, handleDecChars__pureZparsecfg_86)(tyObject_CfgParser__r3Jw8HBNj9b667nxe8vVd9bw* c, NI* xi) {
	{
		while (1) {
			if (!(((NU8)((*c).Sup.buf->data[(*c).Sup.bufpos])) >= ((NU8)(48)) && ((NU8)((*c).Sup.buf->data[(*c).Sup.bufpos])) <= ((NU8)(57)))) goto LA2;
			(*xi) = (NI)((NI)((*xi) * ((NI) 10)) + (NI)(((NU8)((*c).Sup.buf->data[(*c).Sup.bufpos])) - ((NI) 48)));
			(*c).Sup.bufpos += ((NI) 1);
		} LA2: ;
	}
}
N_LIB_PRIVATE N_NIMCALL(void, getEscapedChar__pureZparsecfg_103)(tyObject_CfgParser__r3Jw8HBNj9b667nxe8vVd9bw* c, tyObject_Token__yWkcM1ijvGYnxTAxtl3FPw* tok) {
	(*c).Sup.bufpos += ((NI) 1);
	switch (((NU8)((*c).Sup.buf->data[(*c).Sup.bufpos]))) {
	case 110:
	case 78:
	{
		unsureAsgnRef((void**) (&(*tok).literal), resizeString((*tok).literal, 1));
appendString((*tok).literal, ((NimStringDesc*) &TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_17));
		(*c).Sup.bufpos += ((NI) 1);
	}
	break;
	case 114:
	case 82:
	case 99:
	case 67:
	{
		unsureAsgnRef((void**) (&(*tok).literal), addChar((*tok).literal, 13));
		(*c).Sup.bufpos += ((NI) 1);
	}
	break;
	case 108:
	case 76:
	{
		unsureAsgnRef((void**) (&(*tok).literal), addChar((*tok).literal, 10));
		(*c).Sup.bufpos += ((NI) 1);
	}
	break;
	case 102:
	case 70:
	{
		unsureAsgnRef((void**) (&(*tok).literal), addChar((*tok).literal, 12));
		(*c).Sup.bufpos += ((NI) 1);
	}
	break;
	case 101:
	case 69:
	{
		unsureAsgnRef((void**) (&(*tok).literal), addChar((*tok).literal, 27));
		(*c).Sup.bufpos += ((NI) 1);
	}
	break;
	case 97:
	case 65:
	{
		unsureAsgnRef((void**) (&(*tok).literal), addChar((*tok).literal, 7));
		(*c).Sup.bufpos += ((NI) 1);
	}
	break;
	case 98:
	case 66:
	{
		unsureAsgnRef((void**) (&(*tok).literal), addChar((*tok).literal, 8));
		(*c).Sup.bufpos += ((NI) 1);
	}
	break;
	case 118:
	case 86:
	{
		unsureAsgnRef((void**) (&(*tok).literal), addChar((*tok).literal, 11));
		(*c).Sup.bufpos += ((NI) 1);
	}
	break;
	case 116:
	case 84:
	{
		unsureAsgnRef((void**) (&(*tok).literal), addChar((*tok).literal, 9));
		(*c).Sup.bufpos += ((NI) 1);
	}
	break;
	case 39:
	case 34:
	{
		unsureAsgnRef((void**) (&(*tok).literal), addChar((*tok).literal, (*c).Sup.buf->data[(*c).Sup.bufpos]));
		(*c).Sup.bufpos += ((NI) 1);
	}
	break;
	case 92:
	{
		unsureAsgnRef((void**) (&(*tok).literal), addChar((*tok).literal, 92));
		(*c).Sup.bufpos += ((NI) 1);
	}
	break;
	case 120:
	case 88:
	{
		NI xi;
		(*c).Sup.bufpos += ((NI) 1);
		xi = ((NI) 0);
		{
			NIM_BOOL T15_;
			T15_ = (NIM_BOOL)0;
			T15_ = handleHexChar__stdZprivateZdecode95helpers_1((*c).Sup.buf->data[(*c).Sup.bufpos], (&xi));
			if (!T15_) goto LA16_;
			(*c).Sup.bufpos += ((NI) 1);
			{
				NIM_BOOL T20_;
				T20_ = (NIM_BOOL)0;
				T20_ = handleHexChar__stdZprivateZdecode95helpers_1((*c).Sup.buf->data[(*c).Sup.bufpos], (&xi));
				if (!T20_) goto LA21_;
				(*c).Sup.bufpos += ((NI) 1);
			}
			LA21_: ;
		}
		LA16_: ;
		unsureAsgnRef((void**) (&(*tok).literal), addChar((*tok).literal, ((NIM_CHAR) (((NI) (xi))))));
	}
	break;
	case 48 ... 57:
	{
		NI xi_2;
		xi_2 = ((NI) 0);
		handleDecChars__pureZparsecfg_86(c, (&xi_2));
		{
			if (!(xi_2 <= ((NI) 255))) goto LA26_;
			unsureAsgnRef((void**) (&(*tok).literal), addChar((*tok).literal, ((NIM_CHAR) (((NI) (xi_2))))));
		}
		goto LA24_;
		LA26_: ;
		{
			(*tok).kind = ((tyEnum_TokKind__PvpTf9b5cBhdKx1DK5Ed3dg) 0);
		}
		LA24_: ;
	}
	break;
	default:
	{
		(*tok).kind = ((tyEnum_TokKind__PvpTf9b5cBhdKx1DK5Ed3dg) 0);
	}
	break;
	}
}
N_LIB_PRIVATE N_NIMCALL(void, getString__pureZparsecfg_172)(tyObject_CfgParser__r3Jw8HBNj9b667nxe8vVd9bw* c, tyObject_Token__yWkcM1ijvGYnxTAxtl3FPw* tok, NIM_BOOL rawMode) {
	NI pos;
	pos = (NI)((*c).Sup.bufpos + ((NI) 1));
	(*tok).kind = ((tyEnum_TokKind__PvpTf9b5cBhdKx1DK5Ed3dg) 2);
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = ((NU8)((*c).Sup.buf->data[pos]) == (NU8)(34));
		if (!(T3_)) goto LA4_;
		T3_ = ((NU8)((*c).Sup.buf->data[(NI)(pos + ((NI) 1))]) == (NU8)(34));
		LA4_: ;
		if (!T3_) goto LA5_;
		pos += ((NI) 2);
		pos = handleCRLF__pureZparsecfg_168(c, pos);
		{
			while (1) {
				switch (((NU8)((*c).Sup.buf->data[pos]))) {
				case 34:
				{
					{
						NIM_BOOL T12_;
						T12_ = (NIM_BOOL)0;
						T12_ = ((NU8)((*c).Sup.buf->data[(NI)(pos + ((NI) 1))]) == (NU8)(34));
						if (!(T12_)) goto LA13_;
						T12_ = ((NU8)((*c).Sup.buf->data[(NI)(pos + ((NI) 2))]) == (NU8)(34));
						LA13_: ;
						if (!T12_) goto LA14_;
						goto LA7;
					}
					LA14_: ;
					unsureAsgnRef((void**) (&(*tok).literal), addChar((*tok).literal, 34));
					pos += ((NI) 1);
				}
				break;
				case 13:
				case 10:
				{
					pos = handleCRLF__pureZparsecfg_168(c, pos);
					unsureAsgnRef((void**) (&(*tok).literal), resizeString((*tok).literal, 1));
appendString((*tok).literal, ((NimStringDesc*) &TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_17));
				}
				break;
				case 0:
				{
					(*tok).kind = ((tyEnum_TokKind__PvpTf9b5cBhdKx1DK5Ed3dg) 0);
					goto LA7;
				}
				break;
				default:
				{
					unsureAsgnRef((void**) (&(*tok).literal), addChar((*tok).literal, (*c).Sup.buf->data[pos]));
					pos += ((NI) 1);
				}
				break;
				}
			}
		} LA7: ;
		(*c).Sup.bufpos = (NI)(pos + ((NI) 3));
	}
	goto LA1_;
	LA5_: ;
	{
		{
			while (1) {
				NIM_CHAR ch;
				ch = (*c).Sup.buf->data[pos];
				{
					if (!((NU8)(ch) == (NU8)(34))) goto LA24_;
					pos += ((NI) 1);
					goto LA20;
				}
				LA24_: ;
				{
					if (!(((NU8)(ch)) == ((NU8)(13)) || ((NU8)(ch)) == ((NU8)(10)) || ((NU8)(ch)) == ((NU8)(0)))) goto LA28_;
					(*tok).kind = ((tyEnum_TokKind__PvpTf9b5cBhdKx1DK5Ed3dg) 0);
					goto LA20;
				}
				LA28_: ;
				{
					NIM_BOOL T32_;
					T32_ = (NIM_BOOL)0;
					T32_ = ((NU8)(ch) == (NU8)(92));
					if (!(T32_)) goto LA33_;
					T32_ = !(rawMode);
					LA33_: ;
					if (!T32_) goto LA34_;
					(*c).Sup.bufpos = pos;
					getEscapedChar__pureZparsecfg_103(c, tok);
					pos = (*c).Sup.bufpos;
				}
				goto LA30_;
				LA34_: ;
				{
					unsureAsgnRef((void**) (&(*tok).literal), addChar((*tok).literal, ch));
					pos += ((NI) 1);
				}
				LA30_: ;
			}
		} LA20: ;
		(*c).Sup.bufpos = pos;
	}
	LA1_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, rawGetTok__pureZparsecfg_45)(tyObject_CfgParser__r3Jw8HBNj9b667nxe8vVd9bw* c, tyObject_Token__yWkcM1ijvGYnxTAxtl3FPw* tok) {
	(*tok).kind = ((tyEnum_TokKind__PvpTf9b5cBhdKx1DK5Ed3dg) 0);
	unsureAsgnRef((void**) (&(*tok).literal), setLengthStr((*tok).literal, ((NI) 0)));
	skip__pureZparsecfg_214(c);
	switch (((NU8)((*c).Sup.buf->data[(*c).Sup.bufpos]))) {
	case 61:
	{
		(*tok).kind = ((tyEnum_TokKind__PvpTf9b5cBhdKx1DK5Ed3dg) 3);
		(*c).Sup.bufpos += ((NI) 1);
		unsureAsgnRef((void**) (&(*tok).literal), copyString(((NimStringDesc*) &TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_13)));
	}
	break;
	case 45:
	{
		(*c).Sup.bufpos += ((NI) 1);
		{
			if (!((NU8)((*c).Sup.buf->data[(*c).Sup.bufpos]) == (NU8)(45))) goto LA5_;
			(*c).Sup.bufpos += ((NI) 1);
			(*tok).kind = ((tyEnum_TokKind__PvpTf9b5cBhdKx1DK5Ed3dg) 7);
			unsureAsgnRef((void**) (&(*tok).literal), copyString(((NimStringDesc*) &TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_14)));
		}
		goto LA3_;
		LA5_: ;
		{
			(*c).Sup.bufpos -= ((NI) 1);
			getSymbol__pureZparsecfg_202(c, tok);
		}
		LA3_: ;
	}
	break;
	case 58:
	{
		(*tok).kind = ((tyEnum_TokKind__PvpTf9b5cBhdKx1DK5Ed3dg) 4);
		(*c).Sup.bufpos += ((NI) 1);
		unsureAsgnRef((void**) (&(*tok).literal), copyString(((NimStringDesc*) &TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_16)));
	}
	break;
	case 114:
	case 82:
	{
		{
			if (!((NU8)((*c).Sup.buf->data[(NI)((*c).Sup.bufpos + ((NI) 1))]) == (NU8)(34))) goto LA12_;
			(*c).Sup.bufpos += ((NI) 1);
			getString__pureZparsecfg_172(c, tok, NIM_TRUE);
		}
		goto LA10_;
		LA12_: ;
		{
			getSymbol__pureZparsecfg_202(c, tok);
		}
		LA10_: ;
	}
	break;
	case 91:
	{
		(*tok).kind = ((tyEnum_TokKind__PvpTf9b5cBhdKx1DK5Ed3dg) 5);
		(*c).Sup.bufpos += ((NI) 1);
		unsureAsgnRef((void**) (&(*tok).literal), copyString(((NimStringDesc*) &TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_18)));
	}
	break;
	case 93:
	{
		(*tok).kind = ((tyEnum_TokKind__PvpTf9b5cBhdKx1DK5Ed3dg) 6);
		(*c).Sup.bufpos += ((NI) 1);
		unsureAsgnRef((void**) (&(*tok).literal), copyString(((NimStringDesc*) &TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_19)));
	}
	break;
	case 34:
	{
		getString__pureZparsecfg_172(c, tok, NIM_FALSE);
	}
	break;
	case 0:
	{
		(*tok).kind = ((tyEnum_TokKind__PvpTf9b5cBhdKx1DK5Ed3dg) 1);
		unsureAsgnRef((void**) (&(*tok).literal), copyString(((NimStringDesc*) &TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_20)));
	}
	break;
	default:
	{
		getSymbol__pureZparsecfg_202(c, tok);
	}
	break;
	}
}
N_LIB_PRIVATE N_NIMCALL(void, npcopen)(tyObject_CfgParser__r3Jw8HBNj9b667nxe8vVd9bw* c, tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ* input, NimStringDesc* filename, NI lineOffset) {
	open__pureZlexbase_122(&c->Sup, input, ((NI) 8192), TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_12);
	unsureAsgnRef((void**) (&(*c).filename), copyString(filename));
	(*c).tok.kind = ((tyEnum_TokKind__PvpTf9b5cBhdKx1DK5Ed3dg) 0);
	unsureAsgnRef((void**) (&(*c).tok.literal), ((NimStringDesc*) NIM_NIL));
	(*c).Sup.lineNumber += lineOffset;
	rawGetTok__pureZparsecfg_45(c, (&(*c).tok));
}
N_LIB_PRIVATE N_NIMCALL(NI, npcgetLine)(tyObject_CfgParser__r3Jw8HBNj9b667nxe8vVd9bw* c) {
	NI result;
	result = (NI)0;
	result = (*c).Sup.lineNumber;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, npcgetColumn)(tyObject_CfgParser__r3Jw8HBNj9b667nxe8vVd9bw* c) {
	NI result;
	result = (NI)0;
	result = getColNumber__pureZlexbase_137((&(*c).Sup), (*c).Sup.bufpos);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, npcerrorStr)(tyObject_CfgParser__r3Jw8HBNj9b667nxe8vVd9bw* c, NimStringDesc* msg) {
	NimStringDesc* result;
	tyArray__sMpvt1sOxOJ3LFGulnbeMQ T1_;
	NI T2_;
	NI T3_;
	result = NIM_NIL;
	nimZeroMem((void*)T1_, sizeof(tyArray__sMpvt1sOxOJ3LFGulnbeMQ));
	T1_[0] = copyString((*c).filename);
	T2_ = (NI)0;
	T2_ = npcgetLine(c);
	T1_[1] = dollar___systemZdollars_8(T2_);
	T3_ = (NI)0;
	T3_ = npcgetColumn(c);
	T1_[2] = dollar___systemZdollars_8(T3_);
	T1_[3] = copyString(msg);
	result = nsuFormatOpenArray(((NimStringDesc*) &TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_25), T1_, 4);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, getKeyValPair__pureZparsecfg_276)(tyObject_CfgParser__r3Jw8HBNj9b667nxe8vVd9bw* c, tyEnum_CfgEventKind__f0xwqI11H3rviaTXvjDJug kind, tyObject_CfgEvent__9blb2N9brhIlBVapT72kwOHg* Result) {
	switch ((*Result).kind) {
	case ((tyEnum_CfgEventKind__f0xwqI11H3rviaTXvjDJug) 0):
	break;
	case ((tyEnum_CfgEventKind__f0xwqI11H3rviaTXvjDJug) 1):
	unsureAsgnRef((void**)&(*Result)._kind_2.section, NIM_NIL);
	break;
	case ((tyEnum_CfgEventKind__f0xwqI11H3rviaTXvjDJug) 2):
	case ((tyEnum_CfgEventKind__f0xwqI11H3rviaTXvjDJug) 3):
	unsureAsgnRef((void**)&(*Result)._kind_3.key, NIM_NIL);
	unsureAsgnRef((void**)&(*Result)._kind_3.value, NIM_NIL);
	break;
	case ((tyEnum_CfgEventKind__f0xwqI11H3rviaTXvjDJug) 4):
	unsureAsgnRef((void**)&(*Result)._kind_4.msg, NIM_NIL);
	break;
	} 
	(*Result).kind = 0;
	(*Result).Sup.m_type = (&NTIcfgevent__9blb2N9brhIlBVapT72kwOHg_);
	{
		if (!((*c).tok.kind == ((tyEnum_TokKind__PvpTf9b5cBhdKx1DK5Ed3dg) 2))) goto LA3_;
		switch (kind) {
		case ((tyEnum_CfgEventKind__f0xwqI11H3rviaTXvjDJug) 3):
		case ((tyEnum_CfgEventKind__f0xwqI11H3rviaTXvjDJug) 2):
		{
			switch ((*Result).kind) {
			case ((tyEnum_CfgEventKind__f0xwqI11H3rviaTXvjDJug) 0):
			break;
			case ((tyEnum_CfgEventKind__f0xwqI11H3rviaTXvjDJug) 1):
			unsureAsgnRef((void**)&(*Result)._kind_2.section, NIM_NIL);
			break;
			case ((tyEnum_CfgEventKind__f0xwqI11H3rviaTXvjDJug) 2):
			case ((tyEnum_CfgEventKind__f0xwqI11H3rviaTXvjDJug) 3):
			unsureAsgnRef((void**)&(*Result)._kind_3.key, NIM_NIL);
			unsureAsgnRef((void**)&(*Result)._kind_3.value, NIM_NIL);
			break;
			case ((tyEnum_CfgEventKind__f0xwqI11H3rviaTXvjDJug) 4):
			unsureAsgnRef((void**)&(*Result)._kind_4.msg, NIM_NIL);
			break;
			} 
			(*Result).kind = 0;
			(*Result).Sup.m_type = (&NTIcfgevent__9blb2N9brhIlBVapT72kwOHg_);
			(*Result).kind = kind;
			unsureAsgnRef((void**) (&(*Result)._kind_3.key), copyString((*c).tok.literal));
			unsureAsgnRef((void**) (&(*Result)._kind_3.value), ((NimStringDesc*) NIM_NIL));
		}
		break;
		default:
		{
		}
		break;
		}
		rawGetTok__pureZparsecfg_45(c, (&(*c).tok));
		{
			if (!((24 &((NU8)1<<((NU)((*c).tok.kind)&7U)))!=0)) goto LA9_;
			rawGetTok__pureZparsecfg_45(c, (&(*c).tok));
			{
				if (!((*c).tok.kind == ((tyEnum_TokKind__PvpTf9b5cBhdKx1DK5Ed3dg) 2))) goto LA13_;
				unsureAsgnRef((void**) (&(*Result)._kind_3.value), copyString((*c).tok.literal));
			}
			goto LA11_;
			LA13_: ;
			{
				NimStringDesc* T16_;
				switch ((*Result).kind) {
				case ((tyEnum_CfgEventKind__f0xwqI11H3rviaTXvjDJug) 0):
				break;
				case ((tyEnum_CfgEventKind__f0xwqI11H3rviaTXvjDJug) 1):
				unsureAsgnRef((void**)&(*Result)._kind_2.section, NIM_NIL);
				break;
				case ((tyEnum_CfgEventKind__f0xwqI11H3rviaTXvjDJug) 2):
				case ((tyEnum_CfgEventKind__f0xwqI11H3rviaTXvjDJug) 3):
				unsureAsgnRef((void**)&(*Result)._kind_3.key, NIM_NIL);
				unsureAsgnRef((void**)&(*Result)._kind_3.value, NIM_NIL);
				break;
				case ((tyEnum_CfgEventKind__f0xwqI11H3rviaTXvjDJug) 4):
				unsureAsgnRef((void**)&(*Result)._kind_4.msg, NIM_NIL);
				break;
				} 
				(*Result).kind = 0;
				(*Result).Sup.m_type = (&NTIcfgevent__9blb2N9brhIlBVapT72kwOHg_);
				(*Result).kind = ((tyEnum_CfgEventKind__f0xwqI11H3rviaTXvjDJug) 4);
				T16_ = NIM_NIL;
				T16_ = rawNewString(((*c).tok.literal ? (*c).tok.literal->Sup.len : 0) + 28);
appendString(T16_, ((NimStringDesc*) &TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_26));
appendString(T16_, (*c).tok.literal);
				unsureAsgnRef((void**) (&(*Result)._kind_4.msg), npcerrorStr((&(*c)), T16_));
			}
			LA11_: ;
			rawGetTok__pureZparsecfg_45(c, (&(*c).tok));
		}
		LA9_: ;
	}
	goto LA1_;
	LA3_: ;
	{
		NimStringDesc* T18_;
		switch ((*Result).kind) {
		case ((tyEnum_CfgEventKind__f0xwqI11H3rviaTXvjDJug) 0):
		break;
		case ((tyEnum_CfgEventKind__f0xwqI11H3rviaTXvjDJug) 1):
		unsureAsgnRef((void**)&(*Result)._kind_2.section, NIM_NIL);
		break;
		case ((tyEnum_CfgEventKind__f0xwqI11H3rviaTXvjDJug) 2):
		case ((tyEnum_CfgEventKind__f0xwqI11H3rviaTXvjDJug) 3):
		unsureAsgnRef((void**)&(*Result)._kind_3.key, NIM_NIL);
		unsureAsgnRef((void**)&(*Result)._kind_3.value, NIM_NIL);
		break;
		case ((tyEnum_CfgEventKind__f0xwqI11H3rviaTXvjDJug) 4):
		unsureAsgnRef((void**)&(*Result)._kind_4.msg, NIM_NIL);
		break;
		} 
		(*Result).kind = 0;
		(*Result).Sup.m_type = (&NTIcfgevent__9blb2N9brhIlBVapT72kwOHg_);
		(*Result).kind = ((tyEnum_CfgEventKind__f0xwqI11H3rviaTXvjDJug) 4);
		T18_ = NIM_NIL;
		T18_ = rawNewString(((*c).tok.literal ? (*c).tok.literal->Sup.len : 0) + 28);
appendString(T18_, ((NimStringDesc*) &TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_26));
appendString(T18_, (*c).tok.literal);
		unsureAsgnRef((void**) (&(*Result)._kind_4.msg), npcerrorStr((&(*c)), T18_));
		rawGetTok__pureZparsecfg_45(c, (&(*c).tok));
	}
	LA1_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, npcnext)(tyObject_CfgParser__r3Jw8HBNj9b667nxe8vVd9bw* c, tyObject_CfgEvent__9blb2N9brhIlBVapT72kwOHg* Result) {
	switch ((*c).tok.kind) {
	case ((tyEnum_TokKind__PvpTf9b5cBhdKx1DK5Ed3dg) 1):
	{
		switch ((*Result).kind) {
		case ((tyEnum_CfgEventKind__f0xwqI11H3rviaTXvjDJug) 0):
		break;
		case ((tyEnum_CfgEventKind__f0xwqI11H3rviaTXvjDJug) 1):
		unsureAsgnRef((void**)&(*Result)._kind_2.section, NIM_NIL);
		break;
		case ((tyEnum_CfgEventKind__f0xwqI11H3rviaTXvjDJug) 2):
		case ((tyEnum_CfgEventKind__f0xwqI11H3rviaTXvjDJug) 3):
		unsureAsgnRef((void**)&(*Result)._kind_3.key, NIM_NIL);
		unsureAsgnRef((void**)&(*Result)._kind_3.value, NIM_NIL);
		break;
		case ((tyEnum_CfgEventKind__f0xwqI11H3rviaTXvjDJug) 4):
		unsureAsgnRef((void**)&(*Result)._kind_4.msg, NIM_NIL);
		break;
		} 
		(*Result).kind = 0;
		(*Result).Sup.m_type = (&NTIcfgevent__9blb2N9brhIlBVapT72kwOHg_);
		(*Result).kind = ((tyEnum_CfgEventKind__f0xwqI11H3rviaTXvjDJug) 0);
	}
	break;
	case ((tyEnum_TokKind__PvpTf9b5cBhdKx1DK5Ed3dg) 7):
	{
		rawGetTok__pureZparsecfg_45(c, (&(*c).tok));
		getKeyValPair__pureZparsecfg_276(c, ((tyEnum_CfgEventKind__f0xwqI11H3rviaTXvjDJug) 3), Result);
	}
	break;
	case ((tyEnum_TokKind__PvpTf9b5cBhdKx1DK5Ed3dg) 2):
	{
		getKeyValPair__pureZparsecfg_276(c, ((tyEnum_CfgEventKind__f0xwqI11H3rviaTXvjDJug) 2), Result);
	}
	break;
	case ((tyEnum_TokKind__PvpTf9b5cBhdKx1DK5Ed3dg) 5):
	{
		rawGetTok__pureZparsecfg_45(c, (&(*c).tok));
		{
			if (!((*c).tok.kind == ((tyEnum_TokKind__PvpTf9b5cBhdKx1DK5Ed3dg) 2))) goto LA7_;
			switch ((*Result).kind) {
			case ((tyEnum_CfgEventKind__f0xwqI11H3rviaTXvjDJug) 0):
			break;
			case ((tyEnum_CfgEventKind__f0xwqI11H3rviaTXvjDJug) 1):
			unsureAsgnRef((void**)&(*Result)._kind_2.section, NIM_NIL);
			break;
			case ((tyEnum_CfgEventKind__f0xwqI11H3rviaTXvjDJug) 2):
			case ((tyEnum_CfgEventKind__f0xwqI11H3rviaTXvjDJug) 3):
			unsureAsgnRef((void**)&(*Result)._kind_3.key, NIM_NIL);
			unsureAsgnRef((void**)&(*Result)._kind_3.value, NIM_NIL);
			break;
			case ((tyEnum_CfgEventKind__f0xwqI11H3rviaTXvjDJug) 4):
			unsureAsgnRef((void**)&(*Result)._kind_4.msg, NIM_NIL);
			break;
			} 
			(*Result).kind = 0;
			(*Result).Sup.m_type = (&NTIcfgevent__9blb2N9brhIlBVapT72kwOHg_);
			(*Result).kind = ((tyEnum_CfgEventKind__f0xwqI11H3rviaTXvjDJug) 1);
			unsureAsgnRef((void**) (&(*Result)._kind_2.section), copyString((*c).tok.literal));
		}
		goto LA5_;
		LA7_: ;
		{
			NimStringDesc* T10_;
			switch ((*Result).kind) {
			case ((tyEnum_CfgEventKind__f0xwqI11H3rviaTXvjDJug) 0):
			break;
			case ((tyEnum_CfgEventKind__f0xwqI11H3rviaTXvjDJug) 1):
			unsureAsgnRef((void**)&(*Result)._kind_2.section, NIM_NIL);
			break;
			case ((tyEnum_CfgEventKind__f0xwqI11H3rviaTXvjDJug) 2):
			case ((tyEnum_CfgEventKind__f0xwqI11H3rviaTXvjDJug) 3):
			unsureAsgnRef((void**)&(*Result)._kind_3.key, NIM_NIL);
			unsureAsgnRef((void**)&(*Result)._kind_3.value, NIM_NIL);
			break;
			case ((tyEnum_CfgEventKind__f0xwqI11H3rviaTXvjDJug) 4):
			unsureAsgnRef((void**)&(*Result)._kind_4.msg, NIM_NIL);
			break;
			} 
			(*Result).kind = 0;
			(*Result).Sup.m_type = (&NTIcfgevent__9blb2N9brhIlBVapT72kwOHg_);
			(*Result).kind = ((tyEnum_CfgEventKind__f0xwqI11H3rviaTXvjDJug) 4);
			T10_ = NIM_NIL;
			T10_ = rawNewString(((*c).tok.literal ? (*c).tok.literal->Sup.len : 0) + 28);
appendString(T10_, ((NimStringDesc*) &TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_26));
appendString(T10_, (*c).tok.literal);
			unsureAsgnRef((void**) (&(*Result)._kind_4.msg), npcerrorStr((&(*c)), T10_));
		}
		LA5_: ;
		rawGetTok__pureZparsecfg_45(c, (&(*c).tok));
		{
			if (!((*c).tok.kind == ((tyEnum_TokKind__PvpTf9b5cBhdKx1DK5Ed3dg) 6))) goto LA13_;
			rawGetTok__pureZparsecfg_45(c, (&(*c).tok));
		}
		goto LA11_;
		LA13_: ;
		{
			NimStringDesc* T16_;
			switch ((*Result).kind) {
			case ((tyEnum_CfgEventKind__f0xwqI11H3rviaTXvjDJug) 0):
			break;
			case ((tyEnum_CfgEventKind__f0xwqI11H3rviaTXvjDJug) 1):
			unsureAsgnRef((void**)&(*Result)._kind_2.section, NIM_NIL);
			break;
			case ((tyEnum_CfgEventKind__f0xwqI11H3rviaTXvjDJug) 2):
			case ((tyEnum_CfgEventKind__f0xwqI11H3rviaTXvjDJug) 3):
			unsureAsgnRef((void**)&(*Result)._kind_3.key, NIM_NIL);
			unsureAsgnRef((void**)&(*Result)._kind_3.value, NIM_NIL);
			break;
			case ((tyEnum_CfgEventKind__f0xwqI11H3rviaTXvjDJug) 4):
			unsureAsgnRef((void**)&(*Result)._kind_4.msg, NIM_NIL);
			break;
			} 
			(*Result).kind = 0;
			(*Result).Sup.m_type = (&NTIcfgevent__9blb2N9brhIlBVapT72kwOHg_);
			(*Result).kind = ((tyEnum_CfgEventKind__f0xwqI11H3rviaTXvjDJug) 4);
			T16_ = NIM_NIL;
			T16_ = rawNewString(((*c).tok.literal ? (*c).tok.literal->Sup.len : 0) + 25);
appendString(T16_, ((NimStringDesc*) &TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_27));
appendString(T16_, (*c).tok.literal);
			unsureAsgnRef((void**) (&(*Result)._kind_4.msg), npcerrorStr((&(*c)), T16_));
		}
		LA11_: ;
	}
	break;
	case ((tyEnum_TokKind__PvpTf9b5cBhdKx1DK5Ed3dg) 0):
	case ((tyEnum_TokKind__PvpTf9b5cBhdKx1DK5Ed3dg) 3):
	case ((tyEnum_TokKind__PvpTf9b5cBhdKx1DK5Ed3dg) 4):
	case ((tyEnum_TokKind__PvpTf9b5cBhdKx1DK5Ed3dg) 6):
	{
		NimStringDesc* T18_;
		switch ((*Result).kind) {
		case ((tyEnum_CfgEventKind__f0xwqI11H3rviaTXvjDJug) 0):
		break;
		case ((tyEnum_CfgEventKind__f0xwqI11H3rviaTXvjDJug) 1):
		unsureAsgnRef((void**)&(*Result)._kind_2.section, NIM_NIL);
		break;
		case ((tyEnum_CfgEventKind__f0xwqI11H3rviaTXvjDJug) 2):
		case ((tyEnum_CfgEventKind__f0xwqI11H3rviaTXvjDJug) 3):
		unsureAsgnRef((void**)&(*Result)._kind_3.key, NIM_NIL);
		unsureAsgnRef((void**)&(*Result)._kind_3.value, NIM_NIL);
		break;
		case ((tyEnum_CfgEventKind__f0xwqI11H3rviaTXvjDJug) 4):
		unsureAsgnRef((void**)&(*Result)._kind_4.msg, NIM_NIL);
		break;
		} 
		(*Result).kind = 0;
		(*Result).Sup.m_type = (&NTIcfgevent__9blb2N9brhIlBVapT72kwOHg_);
		(*Result).kind = ((tyEnum_CfgEventKind__f0xwqI11H3rviaTXvjDJug) 4);
		T18_ = NIM_NIL;
		T18_ = rawNewString(((*c).tok.literal ? (*c).tok.literal->Sup.len : 0) + 15);
appendString(T18_, ((NimStringDesc*) &TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_28));
appendString(T18_, (*c).tok.literal);
		unsureAsgnRef((void**) (&(*Result)._kind_4.msg), npcerrorStr((&(*c)), T18_));
		rawGetTok__pureZparsecfg_45(c, (&(*c).tok));
	}
	break;
	}
}
N_LIB_PRIVATE N_NIMCALL(void, npcclose)(tyObject_CfgParser__r3Jw8HBNj9b667nxe8vVd9bw* c) {
	close__pureZlexbase_14(&c->Sup);
}
N_LIB_PRIVATE N_NIMCALL(tyObject_OrderedTable__UVxsO8EtsgVrmdBJlfhbxA*, loadConfig__pureZparsecfg_2132)(tyObject_StreamObj__THYguAi9bSgidczZ3ywEIMQ* stream, NimStringDesc* filename) {
	tyObject_OrderedTable__UVxsO8EtsgVrmdBJlfhbxA* result;
	tyObject_OrderedTable__UVxsO8EtsgVrmdBJlfhbxA* dict;
	NimStringDesc* curSection;
	tyObject_CfgParser__r3Jw8HBNj9b667nxe8vVd9bw p;
	result = NIM_NIL;
	dict = newOrderedTable__pureZparsecfg_351(((NI) 32));
	curSection = ((NimStringDesc*) NIM_NIL);
	nimZeroMem((void*)(&p), sizeof(tyObject_CfgParser__r3Jw8HBNj9b667nxe8vVd9bw));
	p.Sup.Sup.m_type = (&NTIcfgparser__r3Jw8HBNj9b667nxe8vVd9bw_);
	npcopen((&p), stream, filename, ((NI) 0));
	{
		while (1) {
			tyObject_CfgEvent__9blb2N9brhIlBVapT72kwOHg e;
			nimZeroMem((void*)(&e), sizeof(tyObject_CfgEvent__9blb2N9brhIlBVapT72kwOHg));
			e.Sup.m_type = (&NTIcfgevent__9blb2N9brhIlBVapT72kwOHg_);
			npcnext((&p), (&e));
			switch (e.kind) {
			case ((tyEnum_CfgEventKind__f0xwqI11H3rviaTXvjDJug) 0):
			{
				goto LA1;
			}
			break;
			case ((tyEnum_CfgEventKind__f0xwqI11H3rviaTXvjDJug) 1):
			{
				curSection = copyString(e._kind_2.section);
			}
			break;
			case ((tyEnum_CfgEventKind__f0xwqI11H3rviaTXvjDJug) 2):
			{
				tyObject_OrderedTable__aBRulY0v9b6F4b7NLhEoU1Q* t;
				t = newOrderedTable__pureZparsecfg_2150(((NI) 32));
				{
					NIM_BOOL T8_;
					tyObject_OrderedTable__aBRulY0v9b6F4b7NLhEoU1Q** T11_;
					T8_ = (NIM_BOOL)0;
					T8_ = hasKey__pureZparsecfg_3923(dict, curSection);
					if (!T8_) goto LA9_;
					T11_ = (tyObject_OrderedTable__aBRulY0v9b6F4b7NLhEoU1Q**)0;
					T11_ = X5BX5D___pureZparsecfg_4096(dict, curSection);
					t = (*T11_);
				}
				LA9_: ;
				X5BX5Deq___pureZparsecfg_2284(t, e._kind_3.key, e._kind_3.value);
				X5BX5Deq___pureZparsecfg_503(dict, curSection, t);
			}
			break;
			case ((tyEnum_CfgEventKind__f0xwqI11H3rviaTXvjDJug) 3):
			{
				tyObject_OrderedTable__aBRulY0v9b6F4b7NLhEoU1Q* c;
				NimStringDesc* T19_;
				c = newOrderedTable__pureZparsecfg_2150(((NI) 32));
				{
					NIM_BOOL T15_;
					tyObject_OrderedTable__aBRulY0v9b6F4b7NLhEoU1Q** T18_;
					T15_ = (NIM_BOOL)0;
					T15_ = hasKey__pureZparsecfg_3923(dict, curSection);
					if (!T15_) goto LA16_;
					T18_ = (tyObject_OrderedTable__aBRulY0v9b6F4b7NLhEoU1Q**)0;
					T18_ = X5BX5D___pureZparsecfg_4096(dict, curSection);
					c = (*T18_);
				}
				LA16_: ;
				T19_ = NIM_NIL;
				T19_ = rawNewString((e._kind_3.key ? e._kind_3.key->Sup.len : 0) + 2);
appendString(T19_, ((NimStringDesc*) &TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_14));
appendString(T19_, e._kind_3.key);
				X5BX5Deq___pureZparsecfg_2284(c, T19_, e._kind_3.value);
				X5BX5Deq___pureZparsecfg_503(dict, curSection, c);
			}
			break;
			case ((tyEnum_CfgEventKind__f0xwqI11H3rviaTXvjDJug) 4):
			{
				goto LA1;
			}
			break;
			}
		}
	} LA1: ;
	npcclose((&p));
	result = dict;
	return result;
}
static N_INLINE(void, popSafePoint)(void) {
	excHandler__system_3096 = (*excHandler__system_3096).prev;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_OrderedTable__UVxsO8EtsgVrmdBJlfhbxA*, loadConfig__pureZparsecfg_4797)(NimStringDesc* filename) {
	tyObject_OrderedTable__UVxsO8EtsgVrmdBJlfhbxA* result;
	FILE* file;
	tyObject_FileStreamObj__9bEVSsOIpkY9cf5lCtaS39bPQ* fileStream;
	TSafePoint TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_6;
	result = NIM_NIL;
	file = open__stdZsyncio_436(filename, ((tyEnum_FileMode__4sJyy9aOSN8X63XdWXl5iDg) 0), ((NI) -1));
	fileStream = newFileStream__pureZstreams_842(file);
	pushSafePoint(&TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_6);
	TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_6.status = setjmp(TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_6.context);
	if (TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_6.status == 0) {
	result = loadConfig__pureZparsecfg_2132(&fileStream->Sup, filename);
	popSafePoint();
	}
	else {
		popSafePoint();
	}
	{
		close__pureZstreams_57(&fileStream->Sup);
		if (TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_6.status != 0) nimLeaveFinally();
	}
	if (TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_6.status != 0) reraiseException();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_OrderedTable__UVxsO8EtsgVrmdBJlfhbxA*, newConfig__pureZparsecfg_347)(void) {
	tyObject_OrderedTable__UVxsO8EtsgVrmdBJlfhbxA* result;
	result = NIM_NIL;
	result = newOrderedTable__pureZparsecfg_351(((NI) 32));
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatsdotchoosenimatstoolchainsatsnimminusathheadatslibatspureatsparsecfgdotnim_DatInit000)(void) {
static TNimNode* TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_2_4[4];
static TNimNode* TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_3_4[4];
static TNimNode* TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_4_4[4];
static TNimNode* TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_5_4[4];
static TNimNode* TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_7_2[2];
static TNimNode* TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_8_2[2];
static TNimNode* TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_9_8[8];
NI TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_11;
static char* NIM_CONST TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_10[8] = {
"tkInvalid", 
"tkEof", 
"tkSymbol", 
"tkEquals", 
"tkColon", 
"tkBracketLe", 
"tkBracketRi", 
"tkDashDash"};
static TNimNode* TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_21_5[5];
NI TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_23;
static char* NIM_CONST TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_22[5] = {
"cfgEof", 
"cfgSectionStart", 
"cfgKeyValuePair", 
"cfgOption", 
"cfgError"};
static TNimNode* TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_24_2[2];
static TNimNode TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[48];
NTIorderedtable__UVxsO8EtsgVrmdBJlfhbxA_.size = sizeof(tyObject_OrderedTable__UVxsO8EtsgVrmdBJlfhbxA);
NTIorderedtable__UVxsO8EtsgVrmdBJlfhbxA_.align = NIM_ALIGNOF(tyObject_OrderedTable__UVxsO8EtsgVrmdBJlfhbxA);
NTIorderedtable__UVxsO8EtsgVrmdBJlfhbxA_.kind = 18;
NTIorderedtable__UVxsO8EtsgVrmdBJlfhbxA_.base = 0;
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_2_4[0] = &TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[1];
NTIorderedkeyvaluepair__FVrpX6NSm2kCOe3mqHLSLQ_.size = sizeof(tyTuple__FVrpX6NSm2kCOe3mqHLSLQ);
NTIorderedkeyvaluepair__FVrpX6NSm2kCOe3mqHLSLQ_.align = NIM_ALIGNOF(tyTuple__FVrpX6NSm2kCOe3mqHLSLQ);
NTIorderedkeyvaluepair__FVrpX6NSm2kCOe3mqHLSLQ_.kind = 18;
NTIorderedkeyvaluepair__FVrpX6NSm2kCOe3mqHLSLQ_.base = 0;
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_3_4[0] = &TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[3];
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[3].kind = 1;
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[3].offset = offsetof(tyTuple__FVrpX6NSm2kCOe3mqHLSLQ, Field0);
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[3].typ = (&NTIint__rR5Bzr1D5krxoo1NcNyeMA_);
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[3].name = "Field0";
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_3_4[1] = &TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[4];
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[4].kind = 1;
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[4].offset = offsetof(tyTuple__FVrpX6NSm2kCOe3mqHLSLQ, Field1);
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[4].typ = (&NTIint__rR5Bzr1D5krxoo1NcNyeMA_);
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[4].name = "Field1";
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_3_4[2] = &TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[5];
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[5].kind = 1;
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[5].offset = offsetof(tyTuple__FVrpX6NSm2kCOe3mqHLSLQ, Field2);
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[5].typ = (&NTIstring__77mFvmsOLKik79ci2hXkHEg_);
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[5].name = "Field2";
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_3_4[3] = &TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[6];
NTIorderedtable__aBRulY0v9b6F4b7NLhEoU1Q_.size = sizeof(tyObject_OrderedTable__aBRulY0v9b6F4b7NLhEoU1Q);
NTIorderedtable__aBRulY0v9b6F4b7NLhEoU1Q_.align = NIM_ALIGNOF(tyObject_OrderedTable__aBRulY0v9b6F4b7NLhEoU1Q);
NTIorderedtable__aBRulY0v9b6F4b7NLhEoU1Q_.kind = 18;
NTIorderedtable__aBRulY0v9b6F4b7NLhEoU1Q_.base = 0;
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_4_4[0] = &TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[8];
NTIorderedkeyvaluepair__pmSRO1HvsVFWcLoeG9bs4Yg_.size = sizeof(tyTuple__pmSRO1HvsVFWcLoeG9bs4Yg);
NTIorderedkeyvaluepair__pmSRO1HvsVFWcLoeG9bs4Yg_.align = NIM_ALIGNOF(tyTuple__pmSRO1HvsVFWcLoeG9bs4Yg);
NTIorderedkeyvaluepair__pmSRO1HvsVFWcLoeG9bs4Yg_.kind = 18;
NTIorderedkeyvaluepair__pmSRO1HvsVFWcLoeG9bs4Yg_.base = 0;
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_5_4[0] = &TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[10];
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[10].kind = 1;
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[10].offset = offsetof(tyTuple__pmSRO1HvsVFWcLoeG9bs4Yg, Field0);
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[10].typ = (&NTIint__rR5Bzr1D5krxoo1NcNyeMA_);
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[10].name = "Field0";
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_5_4[1] = &TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[11];
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[11].kind = 1;
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[11].offset = offsetof(tyTuple__pmSRO1HvsVFWcLoeG9bs4Yg, Field1);
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[11].typ = (&NTIint__rR5Bzr1D5krxoo1NcNyeMA_);
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[11].name = "Field1";
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_5_4[2] = &TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[12];
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[12].kind = 1;
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[12].offset = offsetof(tyTuple__pmSRO1HvsVFWcLoeG9bs4Yg, Field2);
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[12].typ = (&NTIstring__77mFvmsOLKik79ci2hXkHEg_);
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[12].name = "Field2";
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_5_4[3] = &TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[13];
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[13].kind = 1;
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[13].offset = offsetof(tyTuple__pmSRO1HvsVFWcLoeG9bs4Yg, Field3);
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[13].typ = (&NTIstring__77mFvmsOLKik79ci2hXkHEg_);
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[13].name = "Field3";
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[9].len = 4; TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[9].kind = 2; TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[9].sons = &TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_5_4[0];
NTIorderedkeyvaluepair__pmSRO1HvsVFWcLoeG9bs4Yg_.node = &TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[9];
NTIorderedkeyvaluepairseq__dl1tcid0VwP1mpWNDzitYw_.size = sizeof(tySequence__dl1tcid0VwP1mpWNDzitYw*);
NTIorderedkeyvaluepairseq__dl1tcid0VwP1mpWNDzitYw_.align = NIM_ALIGNOF(tySequence__dl1tcid0VwP1mpWNDzitYw*);
NTIorderedkeyvaluepairseq__dl1tcid0VwP1mpWNDzitYw_.kind = 24;
NTIorderedkeyvaluepairseq__dl1tcid0VwP1mpWNDzitYw_.base = (&NTIorderedkeyvaluepair__pmSRO1HvsVFWcLoeG9bs4Yg_);
NTIorderedkeyvaluepairseq__dl1tcid0VwP1mpWNDzitYw_.marker = Marker_tySequence__dl1tcid0VwP1mpWNDzitYw;
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[8].kind = 1;
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[8].offset = offsetof(tyObject_OrderedTable__aBRulY0v9b6F4b7NLhEoU1Q, data);
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[8].typ = (&NTIorderedkeyvaluepairseq__dl1tcid0VwP1mpWNDzitYw_);
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[8].name = "data";
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_4_4[1] = &TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[14];
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[14].kind = 1;
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[14].offset = offsetof(tyObject_OrderedTable__aBRulY0v9b6F4b7NLhEoU1Q, counter);
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[14].typ = (&NTIint__rR5Bzr1D5krxoo1NcNyeMA_);
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[14].name = "counter";
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_4_4[2] = &TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[15];
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[15].kind = 1;
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[15].offset = offsetof(tyObject_OrderedTable__aBRulY0v9b6F4b7NLhEoU1Q, first);
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[15].typ = (&NTIint__rR5Bzr1D5krxoo1NcNyeMA_);
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[15].name = "first";
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_4_4[3] = &TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[16];
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[16].kind = 1;
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[16].offset = offsetof(tyObject_OrderedTable__aBRulY0v9b6F4b7NLhEoU1Q, last);
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[16].typ = (&NTIint__rR5Bzr1D5krxoo1NcNyeMA_);
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[16].name = "last";
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[7].len = 4; TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[7].kind = 2; TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[7].sons = &TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_4_4[0];
NTIorderedtable__aBRulY0v9b6F4b7NLhEoU1Q_.node = &TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[7];
NTIorderedtableref__8kFhhKJlXkGtMIodYIt4Sg_.size = sizeof(tyObject_OrderedTable__aBRulY0v9b6F4b7NLhEoU1Q*);
NTIorderedtableref__8kFhhKJlXkGtMIodYIt4Sg_.align = NIM_ALIGNOF(tyObject_OrderedTable__aBRulY0v9b6F4b7NLhEoU1Q*);
NTIorderedtableref__8kFhhKJlXkGtMIodYIt4Sg_.kind = 22;
NTIorderedtableref__8kFhhKJlXkGtMIodYIt4Sg_.base = (&NTIorderedtable__aBRulY0v9b6F4b7NLhEoU1Q_);
NTIorderedtableref__8kFhhKJlXkGtMIodYIt4Sg_.marker = Marker_tyRef__8kFhhKJlXkGtMIodYIt4Sg;
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[6].kind = 1;
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[6].offset = offsetof(tyTuple__FVrpX6NSm2kCOe3mqHLSLQ, Field3);
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[6].typ = (&NTIorderedtableref__8kFhhKJlXkGtMIodYIt4Sg_);
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[6].name = "Field3";
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[2].len = 4; TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[2].kind = 2; TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[2].sons = &TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_3_4[0];
NTIorderedkeyvaluepair__FVrpX6NSm2kCOe3mqHLSLQ_.node = &TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[2];
NTIorderedkeyvaluepairseq__9b9bQp3iQ3wUkkIUUJdnRM5Q_.size = sizeof(tySequence__9b9bQp3iQ3wUkkIUUJdnRM5Q*);
NTIorderedkeyvaluepairseq__9b9bQp3iQ3wUkkIUUJdnRM5Q_.align = NIM_ALIGNOF(tySequence__9b9bQp3iQ3wUkkIUUJdnRM5Q*);
NTIorderedkeyvaluepairseq__9b9bQp3iQ3wUkkIUUJdnRM5Q_.kind = 24;
NTIorderedkeyvaluepairseq__9b9bQp3iQ3wUkkIUUJdnRM5Q_.base = (&NTIorderedkeyvaluepair__FVrpX6NSm2kCOe3mqHLSLQ_);
NTIorderedkeyvaluepairseq__9b9bQp3iQ3wUkkIUUJdnRM5Q_.marker = Marker_tySequence__9b9bQp3iQ3wUkkIUUJdnRM5Q;
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[1].kind = 1;
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[1].offset = offsetof(tyObject_OrderedTable__UVxsO8EtsgVrmdBJlfhbxA, data);
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[1].typ = (&NTIorderedkeyvaluepairseq__9b9bQp3iQ3wUkkIUUJdnRM5Q_);
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[1].name = "data";
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_2_4[1] = &TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[17];
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[17].kind = 1;
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[17].offset = offsetof(tyObject_OrderedTable__UVxsO8EtsgVrmdBJlfhbxA, counter);
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[17].typ = (&NTIint__rR5Bzr1D5krxoo1NcNyeMA_);
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[17].name = "counter";
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_2_4[2] = &TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[18];
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[18].kind = 1;
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[18].offset = offsetof(tyObject_OrderedTable__UVxsO8EtsgVrmdBJlfhbxA, first);
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[18].typ = (&NTIint__rR5Bzr1D5krxoo1NcNyeMA_);
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[18].name = "first";
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_2_4[3] = &TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[19];
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[19].kind = 1;
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[19].offset = offsetof(tyObject_OrderedTable__UVxsO8EtsgVrmdBJlfhbxA, last);
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[19].typ = (&NTIint__rR5Bzr1D5krxoo1NcNyeMA_);
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[19].name = "last";
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[0].len = 4; TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[0].kind = 2; TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[0].sons = &TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_2_4[0];
NTIorderedtable__UVxsO8EtsgVrmdBJlfhbxA_.node = &TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[0];
NTIorderedtableref__r9abUm9c3sgFCZhdO4Iaq3NA_.size = sizeof(tyObject_OrderedTable__UVxsO8EtsgVrmdBJlfhbxA*);
NTIorderedtableref__r9abUm9c3sgFCZhdO4Iaq3NA_.align = NIM_ALIGNOF(tyObject_OrderedTable__UVxsO8EtsgVrmdBJlfhbxA*);
NTIorderedtableref__r9abUm9c3sgFCZhdO4Iaq3NA_.kind = 22;
NTIorderedtableref__r9abUm9c3sgFCZhdO4Iaq3NA_.base = (&NTIorderedtable__UVxsO8EtsgVrmdBJlfhbxA_);
NTIorderedtableref__r9abUm9c3sgFCZhdO4Iaq3NA_.marker = Marker_tyRef__r9abUm9c3sgFCZhdO4Iaq3NA;
NTIcfgparser__r3Jw8HBNj9b667nxe8vVd9bw_.size = sizeof(tyObject_CfgParser__r3Jw8HBNj9b667nxe8vVd9bw);
NTIcfgparser__r3Jw8HBNj9b667nxe8vVd9bw_.align = NIM_ALIGNOF(tyObject_CfgParser__r3Jw8HBNj9b667nxe8vVd9bw);
NTIcfgparser__r3Jw8HBNj9b667nxe8vVd9bw_.kind = 17;
NTIcfgparser__r3Jw8HBNj9b667nxe8vVd9bw_.base = (&NTIbaselexer__MAw8rJZtJ279bVV3TWMtXSg_);
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_7_2[0] = &TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[21];
NTItoken__yWkcM1ijvGYnxTAxtl3FPw_.size = sizeof(tyObject_Token__yWkcM1ijvGYnxTAxtl3FPw);
NTItoken__yWkcM1ijvGYnxTAxtl3FPw_.align = NIM_ALIGNOF(tyObject_Token__yWkcM1ijvGYnxTAxtl3FPw);
NTItoken__yWkcM1ijvGYnxTAxtl3FPw_.kind = 18;
NTItoken__yWkcM1ijvGYnxTAxtl3FPw_.base = 0;
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_8_2[0] = &TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[23];
NTItokkind__PvpTf9b5cBhdKx1DK5Ed3dg_.size = sizeof(tyEnum_TokKind__PvpTf9b5cBhdKx1DK5Ed3dg);
NTItokkind__PvpTf9b5cBhdKx1DK5Ed3dg_.align = NIM_ALIGNOF(tyEnum_TokKind__PvpTf9b5cBhdKx1DK5Ed3dg);
NTItokkind__PvpTf9b5cBhdKx1DK5Ed3dg_.kind = 14;
NTItokkind__PvpTf9b5cBhdKx1DK5Ed3dg_.base = 0;
NTItokkind__PvpTf9b5cBhdKx1DK5Ed3dg_.flags = 3;
for (TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_11 = 0; TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_11 < 8; TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_11++) {
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_11+24].kind = 1;
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_11+24].offset = TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_11;
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_11+24].name = TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_10[TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_11];
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_9_8[TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_11] = &TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_11+24];
}
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[32].len = 8; TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[32].kind = 2; TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[32].sons = &TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_9_8[0];
NTItokkind__PvpTf9b5cBhdKx1DK5Ed3dg_.node = &TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[32];
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[23].kind = 1;
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[23].offset = offsetof(tyObject_Token__yWkcM1ijvGYnxTAxtl3FPw, kind);
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[23].typ = (&NTItokkind__PvpTf9b5cBhdKx1DK5Ed3dg_);
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[23].name = "kind";
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_8_2[1] = &TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[33];
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[33].kind = 1;
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[33].offset = offsetof(tyObject_Token__yWkcM1ijvGYnxTAxtl3FPw, literal);
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[33].typ = (&NTIstring__77mFvmsOLKik79ci2hXkHEg_);
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[33].name = "literal";
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[22].len = 2; TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[22].kind = 2; TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[22].sons = &TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_8_2[0];
NTItoken__yWkcM1ijvGYnxTAxtl3FPw_.node = &TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[22];
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[21].kind = 1;
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[21].offset = offsetof(tyObject_CfgParser__r3Jw8HBNj9b667nxe8vVd9bw, tok);
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[21].typ = (&NTItoken__yWkcM1ijvGYnxTAxtl3FPw_);
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[21].name = "tok";
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_7_2[1] = &TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[34];
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[34].kind = 1;
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[34].offset = offsetof(tyObject_CfgParser__r3Jw8HBNj9b667nxe8vVd9bw, filename);
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[34].typ = (&NTIstring__77mFvmsOLKik79ci2hXkHEg_);
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[34].name = "filename";
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[20].len = 2; TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[20].kind = 2; TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[20].sons = &TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_7_2[0];
NTIcfgparser__r3Jw8HBNj9b667nxe8vVd9bw_.node = &TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[20];
NTIcfgevent__9blb2N9brhIlBVapT72kwOHg_.size = sizeof(tyObject_CfgEvent__9blb2N9brhIlBVapT72kwOHg);
NTIcfgevent__9blb2N9brhIlBVapT72kwOHg_.align = NIM_ALIGNOF(tyObject_CfgEvent__9blb2N9brhIlBVapT72kwOHg);
NTIcfgevent__9blb2N9brhIlBVapT72kwOHg_.kind = 17;
NTIcfgevent__9blb2N9brhIlBVapT72kwOHg_.base = (&NTIrootobj__ytyiCJqK439aF9cIibuRVpAg_);
NTIcfgeventkind__f0xwqI11H3rviaTXvjDJug_.size = sizeof(tyEnum_CfgEventKind__f0xwqI11H3rviaTXvjDJug);
NTIcfgeventkind__f0xwqI11H3rviaTXvjDJug_.align = NIM_ALIGNOF(tyEnum_CfgEventKind__f0xwqI11H3rviaTXvjDJug);
NTIcfgeventkind__f0xwqI11H3rviaTXvjDJug_.kind = 14;
NTIcfgeventkind__f0xwqI11H3rviaTXvjDJug_.base = 0;
NTIcfgeventkind__f0xwqI11H3rviaTXvjDJug_.flags = 3;
for (TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_23 = 0; TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_23 < 5; TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_23++) {
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_23+36].kind = 1;
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_23+36].offset = TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_23;
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_23+36].name = TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_22[TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_23];
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_21_5[TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_23] = &TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_23+36];
}
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[41].len = 5; TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[41].kind = 2; TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[41].sons = &TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_21_5[0];
NTIcfgeventkind__f0xwqI11H3rviaTXvjDJug_.node = &TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[41];
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[35].kind = 3;
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[35].offset = offsetof(tyObject_CfgEvent__9blb2N9brhIlBVapT72kwOHg, kind);
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[35].typ = (&NTIcfgeventkind__f0xwqI11H3rviaTXvjDJug_);
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[35].name = "kind";
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[35].sons = &NimDT___9blb2N9brhIlBVapT72kwOHg_kind[0];
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[35].len = 5;
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[42].len = 0; TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[42].kind = 2;
NimDT___9blb2N9brhIlBVapT72kwOHg_kind[0] = &TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[42];
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[43].kind = 1;
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[43].offset = offsetof(tyObject_CfgEvent__9blb2N9brhIlBVapT72kwOHg, _kind_2.section);
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[43].typ = (&NTIstring__77mFvmsOLKik79ci2hXkHEg_);
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[43].name = "section";
NimDT___9blb2N9brhIlBVapT72kwOHg_kind[1] = &TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[43];
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_24_2[0] = &TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[45];
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[45].kind = 1;
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[45].offset = offsetof(tyObject_CfgEvent__9blb2N9brhIlBVapT72kwOHg, _kind_3.key);
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[45].typ = (&NTIstring__77mFvmsOLKik79ci2hXkHEg_);
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[45].name = "key";
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_24_2[1] = &TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[46];
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[46].kind = 1;
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[46].offset = offsetof(tyObject_CfgEvent__9blb2N9brhIlBVapT72kwOHg, _kind_3.value);
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[46].typ = (&NTIstring__77mFvmsOLKik79ci2hXkHEg_);
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[46].name = "value";
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[44].len = 2; TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[44].kind = 2; TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[44].sons = &TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_24_2[0];
NimDT___9blb2N9brhIlBVapT72kwOHg_kind[2] = &TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[44];
NimDT___9blb2N9brhIlBVapT72kwOHg_kind[3] = &TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[44];
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[47].kind = 1;
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[47].offset = offsetof(tyObject_CfgEvent__9blb2N9brhIlBVapT72kwOHg, _kind_4.msg);
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[47].typ = (&NTIstring__77mFvmsOLKik79ci2hXkHEg_);
TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[47].name = "msg";
NimDT___9blb2N9brhIlBVapT72kwOHg_kind[4] = &TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[47];
NTIcfgevent__9blb2N9brhIlBVapT72kwOHg_.node = &TM__M7YvT9b1Jc1B2TU2FUEf9cHQ_0[35];
}

