/* Generated by Nim Compiler v1.7.1 */
#define NIM_INTBITS 32

#include "nimbase.h"
#include <string.h>
#include <sys/types.h>
                          #include <pthread.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(x, y)
#define nimln_(x, y)
typedef struct tyObject_Table__qyR3xLIFK9bnjRhAsVBPjVA tyObject_Table__qyR3xLIFK9bnjRhAsVBPjVA;
typedef struct tySequence__P9cgLJz9cK9czFckaAibTALJQ tySequence__P9cgLJz9cK9czFckaAibTALJQ;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyTuple__3gBPj2HWazk1I9akTDe3bAg tyTuple__3gBPj2HWazk1I9akTDe3bAg;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyObject_OrderedTable__UVxsO8EtsgVrmdBJlfhbxA tyObject_OrderedTable__UVxsO8EtsgVrmdBJlfhbxA;
typedef struct tySequence__9b9bQp3iQ3wUkkIUUJdnRM5Q tySequence__9b9bQp3iQ3wUkkIUUJdnRM5Q;
typedef struct tyTuple__FVrpX6NSm2kCOe3mqHLSLQ tyTuple__FVrpX6NSm2kCOe3mqHLSLQ;
typedef struct NimStringDesc NimStringDesc;
typedef struct tyObject_OrderedTable__aBRulY0v9b6F4b7NLhEoU1Q tyObject_OrderedTable__aBRulY0v9b6F4b7NLhEoU1Q;
typedef struct tySequence__dl1tcid0VwP1mpWNDzitYw tySequence__dl1tcid0VwP1mpWNDzitYw;
typedef struct tyTuple__pmSRO1HvsVFWcLoeG9bs4Yg tyTuple__pmSRO1HvsVFWcLoeG9bs4Yg;
typedef struct tyObject_KeyError__t7nhKLvXTQS9cS8ByJU9bIag tyObject_KeyError__t7nhKLvXTQS9cS8ByJU9bIag;
typedef struct tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw;
typedef struct tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct tySequence__uB9b75OUPRENsBAu4AnoePA tySequence__uB9b75OUPRENsBAu4AnoePA;
typedef struct tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack__7fytPA5bBsob6See21YMRA tyObject_GcStack__7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk__tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk__tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk__XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk__XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk__W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk__W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple__ujsjpB2O9cjj3uDHsXbnSzg tyTuple__ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg;
typedef struct tyObject_SharedList__JI9cx34TL8n3aOKF6tSMBUw tyObject_SharedList__JI9cx34TL8n3aOKF6tSMBUw;
typedef struct tyObject_SharedListNodecolonObjectType___KGw0YAw6W9aSz3Sr9aXGu7zg tyObject_SharedListNodecolonObjectType___KGw0YAw6W9aSz3Sr9aXGu7zg;
typedef struct tyObject_Table__pjVQUpmpjessb3kC1dSh5w tyObject_Table__pjVQUpmpjessb3kC1dSh5w;
typedef struct tySequence__Orgg2tA9c9cbNS8O19aPtx6fw tySequence__Orgg2tA9c9cbNS8O19aPtx6fw;
typedef struct tyTuple__X9cSs7W9bNQqctODYBYs00Dg tyTuple__X9cSs7W9bNQqctODYBYs00Dg;
typedef struct tyTuple__FtZxsWeKlOo83uVL9c4OOmg tyTuple__FtZxsWeKlOo83uVL9c4OOmg;
typedef struct tyObject_Table__HWSctC1WdhUfJtaLIvgFUw tyObject_Table__HWSctC1WdhUfJtaLIvgFUw;
typedef struct tySequence__fl4Fl0sjv6wLBM59aA9a59c9aw tySequence__fl4Fl0sjv6wLBM59aA9a59c9aw;
typedef struct tyTuple__w2pkV7dQ2qWCfR34rQj5Qw tyTuple__w2pkV7dQ2qWCfR34rQj5Qw;
typedef struct tyObject_RGBA8__P4w0wnmH7J1IGztO6QfG5A tyObject_RGBA8__P4w0wnmH7J1IGztO6QfG5A;
typedef struct tyObject_OrderedTable__ZZvSdVkA2s2sIyifu4cpkg tyObject_OrderedTable__ZZvSdVkA2s2sIyifu4cpkg;
typedef struct tySequence__MlAD6nAPq9bHKla9cWiIZP0g tySequence__MlAD6nAPq9bHKla9cWiIZP0g;
typedef struct tyTuple__awOivLjlO76sGdHY7nQUjQ tyTuple__awOivLjlO76sGdHY7nQUjQ;
typedef struct tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q;
typedef struct tySequence__oLpBKXzW3hF9aCVMo5EymfQ tySequence__oLpBKXzW3hF9aCVMo5EymfQ;
typedef struct tySequence__qwqHTkRvwhrRyENtudHQ7g tySequence__qwqHTkRvwhrRyENtudHQ7g;
typedef struct tyObject_Table__Jqg9bbNxGV6Sf9cnDeeNaaIg tyObject_Table__Jqg9bbNxGV6Sf9cnDeeNaaIg;
typedef struct tySequence__yzpjn9bWJt3ZvUgZyAolosA tySequence__yzpjn9bWJt3ZvUgZyAolosA;
typedef struct tyTuple__nuNGPJxv0UxszHtmd9czUsA tyTuple__nuNGPJxv0UxszHtmd9czUsA;
typedef struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA;
struct tyObject_Table__qyR3xLIFK9bnjRhAsVBPjVA {
tySequence__P9cgLJz9cK9czFckaAibTALJQ* data;
NI counter;
};
struct TGenericSeq {
NI len;
NI reserved;
};
typedef NI32 tyEnum_Keycode__4FafBrLvG2wfvPTkNrrFRQ;
struct tyTuple__3gBPj2HWazk1I9akTDe3bAg {
NI Field0;
tyEnum_Keycode__4FafBrLvG2wfvPTkNrrFRQ Field1;
NU32 Field2;
};
typedef NU8 tyEnum_TNimKind__jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag__v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc__ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
NI align;
tyEnum_TNimKind__jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag__v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc__ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc__WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind__unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind__unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct tyObject_OrderedTable__UVxsO8EtsgVrmdBJlfhbxA {
tySequence__9b9bQp3iQ3wUkkIUUJdnRM5Q* data;
NI counter;
NI first;
NI last;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct tyTuple__FVrpX6NSm2kCOe3mqHLSLQ {
NI Field0;
NI Field1;
NimStringDesc* Field2;
tyObject_OrderedTable__aBRulY0v9b6F4b7NLhEoU1Q* Field3;
};
struct tyObject_OrderedTable__aBRulY0v9b6F4b7NLhEoU1Q {
tySequence__dl1tcid0VwP1mpWNDzitYw* data;
NI counter;
NI first;
NI last;
};
struct tyTuple__pmSRO1HvsVFWcLoeG9bs4Yg {
NI Field0;
NI Field1;
NimStringDesc* Field2;
NimStringDesc* Field3;
};
struct RootObj {
TNimType* m_type;
};
struct Exception {
  RootObj Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
tySequence__uB9b75OUPRENsBAu4AnoePA* trace;
Exception* up;
};
struct tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA {
  Exception Sup;
};
struct tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw {
  tyObject_CatchableError__qrLSDoe2oBoAqNtJ9badtnA Sup;
};
struct tyObject_KeyError__t7nhKLvXTQS9cS8ByJU9bIag {
  tyObject_ValueError__yoNlBGx0D2tRizIdhQuENw Sup;
};
struct tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack__7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk__tXn60W2f8h3jgAYdEmy5NQ* tyArray__SPr7N6UKfuF549bNPiUvSRw[256];
typedef NU32 tyArray__BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg* tyArray__N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray__N1u1nqOgmuJN9cSZrnMHgOQ tyArray__B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk__W0r8S0Y3UGke6T9bIUWnnuw* tyArray__lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA {
tyArray__lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* tyArray__0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw {
tyArray__0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple__ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk__Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple__ujsjpB2O9cjj3uDHsXbnSzg tyArray__LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray__LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray__SPr7N6UKfuF549bNPiUvSRw freeSmallChunks;
NU32 flBitmap;
tyArray__BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray__B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk__XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet__EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode__IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks__PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc__fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_SharedList__JI9cx34TL8n3aOKF6tSMBUw {
tyObject_SharedListNodecolonObjectType___KGw0YAw6W9aSz3Sr9aXGu7zg* head;
tyObject_SharedListNodecolonObjectType___KGw0YAw6W9aSz3Sr9aXGu7zg* tail;
pthread_mutex_t lock;
};
struct tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack__7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
NI zctThreshold;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion__x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat__0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet__jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w additionalRoots;
tyObject_SharedList__JI9cx34TL8n3aOKF6tSMBUw toDispose;
NI gcThreadId;
};
struct tyObject_Table__pjVQUpmpjessb3kC1dSh5w {
tySequence__Orgg2tA9c9cbNS8O19aPtx6fw* data;
NI counter;
};
struct tyTuple__FtZxsWeKlOo83uVL9c4OOmg {
NI Field0;
NI Field1;
NI Field2;
NI Field3;
};
struct tyTuple__X9cSs7W9bNQqctODYBYs00Dg {
NI Field0;
NI32 Field1;
tyTuple__FtZxsWeKlOo83uVL9c4OOmg Field2;
};
struct tyObject_Table__HWSctC1WdhUfJtaLIvgFUw {
tySequence__fl4Fl0sjv6wLBM59aA9a59c9aw* data;
NI counter;
};
struct tyObject_RGBA8__P4w0wnmH7J1IGztO6QfG5A {
NIM_CHAR r;
NIM_CHAR g;
NIM_CHAR b;
NIM_CHAR a;
};
struct tyTuple__w2pkV7dQ2qWCfR34rQj5Qw {
NI Field0;
tyObject_RGBA8__P4w0wnmH7J1IGztO6QfG5A Field1;
NI Field2;
};
struct tyObject_OrderedTable__ZZvSdVkA2s2sIyifu4cpkg {
tySequence__MlAD6nAPq9bHKla9cWiIZP0g* data;
NI counter;
NI first;
NI last;
};
struct tyTuple__awOivLjlO76sGdHY7nQUjQ {
NI Field0;
NI Field1;
NimStringDesc* Field2;
tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* Field3;
};
typedef NU8 tyEnum_JsonNodeKind__RUngo7nCHe6O8aBGIcrhtg;
struct tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q {
NIM_BOOL isUnquoted;
tyEnum_JsonNodeKind__RUngo7nCHe6O8aBGIcrhtg kind;
union{
struct {NimStringDesc* str;
} _kind_1;
struct {NI64 num;
} _kind_2;
struct {NF fnum;
} _kind_3;
struct {NIM_BOOL bval;
} _kind_4;
struct {tyObject_OrderedTable__ZZvSdVkA2s2sIyifu4cpkg fields;
} _kind_6;
struct {tySequence__oLpBKXzW3hF9aCVMo5EymfQ* elems;
} _kind_7;
};
};
struct tyObject_Table__Jqg9bbNxGV6Sf9cnDeeNaaIg {
tySequence__yzpjn9bWJt3ZvUgZyAolosA* data;
NI counter;
};
struct tyTuple__nuNGPJxv0UxszHtmd9czUsA {
NI Field0;
NimStringDesc* Field1;
tySequence__qwqHTkRvwhrRyENtudHQ7g* Field2;
};
struct tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA {
NCSTRING procname;
NI line;
NCSTRING filename;
};
struct tySequence__P9cgLJz9cK9czFckaAibTALJQ {
  TGenericSeq Sup;
  tyTuple__3gBPj2HWazk1I9akTDe3bAg data[SEQ_DECL_SIZE];
};
struct tySequence__9b9bQp3iQ3wUkkIUUJdnRM5Q {
  TGenericSeq Sup;
  tyTuple__FVrpX6NSm2kCOe3mqHLSLQ data[SEQ_DECL_SIZE];
};
struct tySequence__dl1tcid0VwP1mpWNDzitYw {
  TGenericSeq Sup;
  tyTuple__pmSRO1HvsVFWcLoeG9bs4Yg data[SEQ_DECL_SIZE];
};
struct tySequence__Orgg2tA9c9cbNS8O19aPtx6fw {
  TGenericSeq Sup;
  tyTuple__X9cSs7W9bNQqctODYBYs00Dg data[SEQ_DECL_SIZE];
};
struct tySequence__fl4Fl0sjv6wLBM59aA9a59c9aw {
  TGenericSeq Sup;
  tyTuple__w2pkV7dQ2qWCfR34rQj5Qw data[SEQ_DECL_SIZE];
};
struct tySequence__MlAD6nAPq9bHKla9cWiIZP0g {
  TGenericSeq Sup;
  tyTuple__awOivLjlO76sGdHY7nQUjQ data[SEQ_DECL_SIZE];
};
struct tySequence__qwqHTkRvwhrRyENtudHQ7g {
  TGenericSeq Sup;
  NI data[SEQ_DECL_SIZE];
};
struct tySequence__uB9b75OUPRENsBAu4AnoePA {
  TGenericSeq Sup;
  tyObject_StackTraceEntry__oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];
};
struct tySequence__oLpBKXzW3hF9aCVMo5EymfQ {
  TGenericSeq Sup;
  tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* data[SEQ_DECL_SIZE];
};
struct tySequence__yzpjn9bWJt3ZvUgZyAolosA {
  TGenericSeq Sup;
  tyTuple__nuNGPJxv0UxszHtmd9czUsA data[SEQ_DECL_SIZE];
};
N_LIB_PRIVATE N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
static N_INLINE(NI, slotsNeeded__pureZcollectionsZtables_42)(NI count);
N_LIB_PRIVATE N_NIMCALL(NI, nextPowerOfTwo__pureZmath_171)(NI x);
N_LIB_PRIVATE N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
N_LIB_PRIVATE N_NOINLINE(void*, newObj)(TNimType* typ, NI size);
N_LIB_PRIVATE N_NIMCALL(void, initOrderedTable__pureZparsecfg_385)(NI initialSize, tyObject_OrderedTable__UVxsO8EtsgVrmdBJlfhbxA* Result);
N_LIB_PRIVATE N_NIMCALL(void, initOrderedTable__pureZparsecfg_2184)(NI initialSize, tyObject_OrderedTable__aBRulY0v9b6F4b7NLhEoU1Q* Result);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, hasKey__pureZparsecfg_4022)(tyObject_OrderedTable__UVxsO8EtsgVrmdBJlfhbxA t, NimStringDesc* key);
N_LIB_PRIVATE N_NIMCALL(NI, rawGet__pureZparsecfg_671)(tyObject_OrderedTable__UVxsO8EtsgVrmdBJlfhbxA t, NimStringDesc* key, NI* hc);
N_LIB_PRIVATE N_NIMCALL(NI, hash__pureZhashes_279)(NimStringDesc* x);
static N_INLINE(NIM_BOOL, isFilled__pureZcollectionsZtables_31)(NI hcode);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b);
static N_INLINE(NIM_BOOL, equalMem__system_1735)(void* a, void* b, NI size);
static N_INLINE(int, nimCmpMem)(void* a, void* b, NI size);
static N_INLINE(NI, nextTry__pureZcollectionsZtables_34)(NI h, NI maxHash);
N_LIB_PRIVATE N_NIMCALL(tyObject_OrderedTable__aBRulY0v9b6F4b7NLhEoU1Q**, X5BX5D___pureZparsecfg_4208)(tyObject_OrderedTable__UVxsO8EtsgVrmdBJlfhbxA* t, NimStringDesc* key);
static N_INLINE(NI, rawGet__pureZparsecfg_4215)(tyObject_OrderedTable__UVxsO8EtsgVrmdBJlfhbxA t, NimStringDesc* key, NI* hc);
N_LIB_PRIVATE N_NOINLINE(void, raiseKeyError__pureZjson_2938)(NimStringDesc* key) __attribute__((noreturn));
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem__system_1727)(void* dest, void* source, NI size);
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incRef__system_5847)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(NI, pluspercent___system_696)(NI x, NI y);
static N_INLINE(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell__system_5809)(void* usr);
static N_INLINE(NI, minuspercent___system_716)(NI x, NI y);
static N_INLINE(void, decRef__system_5854)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(NIM_BOOL, ltpercent___system_1005)(NI x, NI y);
static N_INLINE(void, rtlAddZCT__system_5852)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT__system_5803)(tyObject_CellSeq__Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NIMCALL(void, raiseExceptionEx)(Exception* e, NCSTRING ename, NCSTRING procname, NCSTRING filename, NI line);
N_LIB_PRIVATE N_NIMCALL(void, X5BX5Deq___pureZparsecfg_2383)(tyObject_OrderedTable__aBRulY0v9b6F4b7NLhEoU1Q* t, NimStringDesc* key, NimStringDesc* val);
N_LIB_PRIVATE N_NIMCALL(NI, rawGet__pureZparsecfg_2452)(tyObject_OrderedTable__aBRulY0v9b6F4b7NLhEoU1Q t, NimStringDesc* key, NI* hc);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(NIM_BOOL, mustRehash__pureZparsecfg_2788)(tyObject_OrderedTable__aBRulY0v9b6F4b7NLhEoU1Q t);
N_LIB_PRIVATE N_NIMCALL(void, enlarge__pureZparsecfg_2949)(tyObject_OrderedTable__aBRulY0v9b6F4b7NLhEoU1Q* t);
N_LIB_PRIVATE N_NIMCALL(void, rawInsert__pureZparsecfg_3356)(tyObject_OrderedTable__aBRulY0v9b6F4b7NLhEoU1Q* t, tySequence__dl1tcid0VwP1mpWNDzitYw** data, NimStringDesc* key, NimStringDesc* val, NI hc, NI h);
N_LIB_PRIVATE N_NIMCALL(NI, rawGetKnownHC__pureZparsecfg_3638)(tyObject_OrderedTable__aBRulY0v9b6F4b7NLhEoU1Q t, NimStringDesc* key, NI hc);
N_LIB_PRIVATE N_NIMCALL(void, X5BX5Deq___pureZparsecfg_602)(tyObject_OrderedTable__UVxsO8EtsgVrmdBJlfhbxA* t, NimStringDesc* key, tyObject_OrderedTable__aBRulY0v9b6F4b7NLhEoU1Q* val);
static N_INLINE(NIM_BOOL, mustRehash__pureZparsecfg_1007)(tyObject_OrderedTable__UVxsO8EtsgVrmdBJlfhbxA t);
N_LIB_PRIVATE N_NIMCALL(void, enlarge__pureZparsecfg_1168)(tyObject_OrderedTable__UVxsO8EtsgVrmdBJlfhbxA* t);
N_LIB_PRIVATE N_NIMCALL(void, rawInsert__pureZparsecfg_1588)(tyObject_OrderedTable__UVxsO8EtsgVrmdBJlfhbxA* t, tySequence__9b9bQp3iQ3wUkkIUUJdnRM5Q** data, NimStringDesc* key, tyObject_OrderedTable__aBRulY0v9b6F4b7NLhEoU1Q* val, NI hc, NI h);
N_LIB_PRIVATE N_NIMCALL(NI, rawGetKnownHC__pureZparsecfg_1870)(tyObject_OrderedTable__UVxsO8EtsgVrmdBJlfhbxA t, NimStringDesc* key, NI hc);
static N_INLINE(NI, rawGet__OOZOOZOnimbleZpkgsZnico4548O52O57Znico_3072)(tyObject_Table__pjVQUpmpjessb3kC1dSh5w t, NI32 key, NI* hc);
static N_INLINE(NI, hash__OOZOOZOnimbleZpkgsZnico4548O52O57Znico_3079)(NI32 x);
static N_INLINE(NI, hashWangYi1__pureZhashes_136)(NU64 x);
static N_INLINE(NU64, hiXorLo__pureZhashes_79)(NU64 a, NU64 b);
static N_INLINE(NU64, hiXorLoFallback64__pureZhashes_35)(NU64 a, NU64 b);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, eqeq___pureZunicode_908)(NI32 a, NI32 b);
static N_INLINE(NIM_BOOL, mustRehash__OOZOOZOnimbleZpkgsZnico4548O52O57Znico_3458)(tyObject_Table__pjVQUpmpjessb3kC1dSh5w t);
N_LIB_PRIVATE N_NIMCALL(void, enlarge__OOZOOZOnimbleZpkgsZnico4548O52O57Znico_3626)(tyObject_Table__pjVQUpmpjessb3kC1dSh5w* t);
N_LIB_PRIVATE N_NIMCALL(void, rawInsert__OOZOOZOnimbleZpkgsZnico4548O52O57Znico_3959)(tyObject_Table__pjVQUpmpjessb3kC1dSh5w* t, tySequence__Orgg2tA9c9cbNS8O19aPtx6fw** data, NI32 key, tyTuple__FtZxsWeKlOo83uVL9c4OOmg val, NI hc, NI h);
static N_INLINE(void, nimZeroMem)(void* p, NI size);
static N_INLINE(void, nimSetMem__systemZmemory_7)(void* a, int v, NI size);
static N_INLINE(NI, rawGetKnownHC__OOZOOZOnimbleZpkgsZnico4548O52O57Znico_4143)(tyObject_Table__pjVQUpmpjessb3kC1dSh5w t, NI32 key, NI hc);
static N_INLINE(NI, rawGet__OOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZsdl50_1668)(tyObject_Table__qyR3xLIFK9bnjRhAsVBPjVA t, tyEnum_Keycode__4FafBrLvG2wfvPTkNrrFRQ key, NI* hc);
N_LIB_PRIVATE N_NIMCALL(NI, hash__OOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZsdl50_35)(tyEnum_Keycode__4FafBrLvG2wfvPTkNrrFRQ x);
static N_INLINE(NIM_BOOL, mustRehash__OOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZsdl50_2039)(tyObject_Table__qyR3xLIFK9bnjRhAsVBPjVA t);
N_LIB_PRIVATE N_NIMCALL(void, enlarge__OOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZsdl50_2207)(tyObject_Table__qyR3xLIFK9bnjRhAsVBPjVA* t);
N_LIB_PRIVATE N_NIMCALL(void, rawInsert__OOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZsdl50_2540)(tyObject_Table__qyR3xLIFK9bnjRhAsVBPjVA* t, tySequence__P9cgLJz9cK9czFckaAibTALJQ** data, tyEnum_Keycode__4FafBrLvG2wfvPTkNrrFRQ key, NU32 val, NI hc, NI h);
static N_INLINE(NI, rawGetKnownHC__OOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZsdl50_2733)(tyObject_Table__qyR3xLIFK9bnjRhAsVBPjVA t, tyEnum_Keycode__4FafBrLvG2wfvPTkNrrFRQ key, NI hc);
static N_INLINE(NI, rawGet__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871_5416)(tyObject_Table__HWSctC1WdhUfJtaLIvgFUw t, tyObject_RGBA8__P4w0wnmH7J1IGztO6QfG5A key, NI* hc);
N_LIB_PRIVATE N_NIMCALL(NI, hash__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871_1636)(tyObject_RGBA8__P4w0wnmH7J1IGztO6QfG5A c);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, eqeq___OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871_547)(tyObject_RGBA8__P4w0wnmH7J1IGztO6QfG5A x, tyObject_RGBA8__P4w0wnmH7J1IGztO6QfG5A y);
static N_INLINE(NIM_BOOL, mustRehash__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871_5756)(tyObject_Table__HWSctC1WdhUfJtaLIvgFUw t);
N_LIB_PRIVATE N_NIMCALL(void, enlarge__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871_5909)(tyObject_Table__HWSctC1WdhUfJtaLIvgFUw* t);
N_LIB_PRIVATE N_NIMCALL(void, rawInsert__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871_6217)(tyObject_Table__HWSctC1WdhUfJtaLIvgFUw* t, tySequence__fl4Fl0sjv6wLBM59aA9a59c9aw** data, tyObject_RGBA8__P4w0wnmH7J1IGztO6QfG5A key, NI val, NI hc, NI h);
static N_INLINE(NI, rawGetKnownHC__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871_6386)(tyObject_Table__HWSctC1WdhUfJtaLIvgFUw t, tyObject_RGBA8__P4w0wnmH7J1IGztO6QfG5A key, NI hc);
N_LIB_PRIVATE N_NOINLINE(void, raiseKeyError__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871_7689)(tyObject_RGBA8__P4w0wnmH7J1IGztO6QfG5A key) __attribute__((noreturn));
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar___OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871_7754)(tyObject_RGBA8__P4w0wnmH7J1IGztO6QfG5A x);
N_LIB_PRIVATE N_NOINLINE(void, raiseKeyError__OOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZsdl50_3845)(tyEnum_Keycode__4FafBrLvG2wfvPTkNrrFRQ key) __attribute__((noreturn));
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, reprEnum)(NI e, TNimType* typ);
N_LIB_PRIVATE N_NIMCALL(NI, rawGet__pureZjson_362)(tyObject_OrderedTable__ZZvSdVkA2s2sIyifu4cpkg t, NimStringDesc* key, NI* hc);
static N_INLINE(NIM_BOOL, mustRehash__pureZjson_698)(tyObject_OrderedTable__ZZvSdVkA2s2sIyifu4cpkg t);
N_LIB_PRIVATE N_NIMCALL(void, enlarge__pureZjson_859)(tyObject_OrderedTable__ZZvSdVkA2s2sIyifu4cpkg* t);
N_LIB_PRIVATE N_NIMCALL(void, rawInsert__pureZjson_1274)(tyObject_OrderedTable__ZZvSdVkA2s2sIyifu4cpkg* t, tySequence__MlAD6nAPq9bHKla9cWiIZP0g** data, NimStringDesc* key, tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* val, NI hc, NI h);
N_LIB_PRIVATE N_NIMCALL(NI, rawGetKnownHC__pureZjson_1556)(tyObject_OrderedTable__ZZvSdVkA2s2sIyifu4cpkg t, NimStringDesc* key, NI hc);
static N_INLINE(NI, rawGet__pureZjson_2664)(tyObject_OrderedTable__ZZvSdVkA2s2sIyifu4cpkg t, NimStringDesc* key, NI* hc);
static N_INLINE(NI, rawGet__main_177)(tyObject_Table__Jqg9bbNxGV6Sf9cnDeeNaaIg t, NimStringDesc* key, NI* hc);
N_LIB_PRIVATE N_NIMCALL(void, genericSeqAssign)(void* dest, void* src, TNimType* mt);
N_LIB_PRIVATE N_NOINLINE(void, raiseKeyError__OOZOOZOnimbleZpkgsZnico4548O52O57Znico_5148)(NI32 key) __attribute__((noreturn));
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar___pureZunicode_591)(NI32 rune);
extern TNimType NTIkeyvaluepairseq__P9cgLJz9cK9czFckaAibTALJQ_;
extern TNimType NTIorderedtableref__r9abUm9c3sgFCZhdO4Iaq3NA_;
extern TNimType NTIorderedkeyvaluepairseq__9b9bQp3iQ3wUkkIUUJdnRM5Q_;
extern TNimType NTIorderedtableref__8kFhhKJlXkGtMIodYIt4Sg_;
extern TNimType NTIorderedkeyvaluepairseq__dl1tcid0VwP1mpWNDzitYw_;
extern TNimType NTIrefkeyerror__8SzoIAgLw9ci2v0yafHj9b6Q_;
extern TNimType NTIkeyerror__t7nhKLvXTQS9cS8ByJU9bIag_;
STRING_LITERAL(TM__4SoG2KRQy3oMm9aUzSLtGrA_2, "key not found: ", 15);
extern TNimType NTIkeyvaluepairseq__Orgg2tA9c9cbNS8O19aPtx6fw_;
extern TNimType NTIkeyvaluepairseq__fl4Fl0sjv6wLBM59aA9a59c9aw_;
extern TNimType NTIkeycode__4FafBrLvG2wfvPTkNrrFRQ_;
extern TNimType NTIorderedkeyvaluepairseq__MlAD6nAPq9bHKla9cWiIZP0g_;
extern TNimType NTIseqLintT__qwqHTkRvwhrRyENtudHQ7g_;
extern NIM_THREADVAR tyObject_GcHeap__1TRH1TZMaVZTnLNcIHuNFQ gch__system_5742;
static N_INLINE(NI, slotsNeeded__pureZcollectionsZtables_42)(NI count) {
	NI result;
	result = (NI)0;
	result = nextPowerOfTwo__pureZmath_171((NI)((NI)((NI)(((NI) (count)) * ((NI) 3)) / ((NI) 2)) + ((NI) 4)));
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, initTable__OOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZcommon_66)(NI initialSize, tyObject_Table__qyR3xLIFK9bnjRhAsVBPjVA* Result) {
	NI correctSizeX60gensym0_;
	unsureAsgnRef((void**)&(*Result).data, NIM_NIL);
	(*Result).counter = 0;
	correctSizeX60gensym0_ = slotsNeeded__pureZcollectionsZtables_42(((NI) (initialSize)));
	(*Result).counter = ((NI) 0);
	unsureAsgnRef((void**) (&(*Result).data), (tySequence__P9cgLJz9cK9czFckaAibTALJQ*) newSeq((&NTIkeyvaluepairseq__P9cgLJz9cK9czFckaAibTALJQ_), ((NI) (correctSizeX60gensym0_))));
}
N_LIB_PRIVATE N_NIMCALL(void, initOrderedTable__pureZparsecfg_385)(NI initialSize, tyObject_OrderedTable__UVxsO8EtsgVrmdBJlfhbxA* Result) {
	NI correctSizeX60gensym7_;
	unsureAsgnRef((void**)&(*Result).data, NIM_NIL);
	(*Result).counter = 0;
	(*Result).first = 0;
	(*Result).last = 0;
	correctSizeX60gensym7_ = slotsNeeded__pureZcollectionsZtables_42(((NI) (initialSize)));
	(*Result).counter = ((NI) 0);
	unsureAsgnRef((void**) (&(*Result).data), (tySequence__9b9bQp3iQ3wUkkIUUJdnRM5Q*) newSeq((&NTIorderedkeyvaluepairseq__9b9bQp3iQ3wUkkIUUJdnRM5Q_), ((NI) (correctSizeX60gensym7_))));
	(*Result).first = ((NI) -1);
	(*Result).last = ((NI) -1);
}
N_LIB_PRIVATE N_NIMCALL(tyObject_OrderedTable__UVxsO8EtsgVrmdBJlfhbxA*, newOrderedTable__pureZparsecfg_351)(NI initialSize) {
	tyObject_OrderedTable__UVxsO8EtsgVrmdBJlfhbxA* result;
	result = NIM_NIL;
	result = (tyObject_OrderedTable__UVxsO8EtsgVrmdBJlfhbxA*) newObj((&NTIorderedtableref__r9abUm9c3sgFCZhdO4Iaq3NA_), sizeof(tyObject_OrderedTable__UVxsO8EtsgVrmdBJlfhbxA));
	initOrderedTable__pureZparsecfg_385(initialSize, (&(*result)));
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, initOrderedTable__pureZparsecfg_2184)(NI initialSize, tyObject_OrderedTable__aBRulY0v9b6F4b7NLhEoU1Q* Result) {
	NI correctSizeX60gensym23_;
	unsureAsgnRef((void**)&(*Result).data, NIM_NIL);
	(*Result).counter = 0;
	(*Result).first = 0;
	(*Result).last = 0;
	correctSizeX60gensym23_ = slotsNeeded__pureZcollectionsZtables_42(((NI) (initialSize)));
	(*Result).counter = ((NI) 0);
	unsureAsgnRef((void**) (&(*Result).data), (tySequence__dl1tcid0VwP1mpWNDzitYw*) newSeq((&NTIorderedkeyvaluepairseq__dl1tcid0VwP1mpWNDzitYw_), ((NI) (correctSizeX60gensym23_))));
	(*Result).first = ((NI) -1);
	(*Result).last = ((NI) -1);
}
N_LIB_PRIVATE N_NIMCALL(tyObject_OrderedTable__aBRulY0v9b6F4b7NLhEoU1Q*, newOrderedTable__pureZparsecfg_2150)(NI initialSize) {
	tyObject_OrderedTable__aBRulY0v9b6F4b7NLhEoU1Q* result;
	result = NIM_NIL;
	result = (tyObject_OrderedTable__aBRulY0v9b6F4b7NLhEoU1Q*) newObj((&NTIorderedtableref__8kFhhKJlXkGtMIodYIt4Sg_), sizeof(tyObject_OrderedTable__aBRulY0v9b6F4b7NLhEoU1Q));
	initOrderedTable__pureZparsecfg_2184(initialSize, (&(*result)));
	return result;
}
static N_INLINE(NIM_BOOL, isFilled__pureZcollectionsZtables_31)(NI hcode) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	result = !((hcode == ((NI) 0)));
	return result;
}
static N_INLINE(int, nimCmpMem)(void* a, void* b, NI size) {
	int result;
	result = (int)0;
	result = memcmp(a, b, ((size_t) (size)));
	return result;
}
static N_INLINE(NIM_BOOL, equalMem__system_1735)(void* a, void* b, NI size) {
	NIM_BOOL result;
	int T1_;
	result = (NIM_BOOL)0;
	T1_ = (int)0;
	T1_ = nimCmpMem(a, b, size);
	result = (T1_ == ((NI32) 0));
	return result;
}
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	NI alen;
	NI blen;
{	result = (NIM_BOOL)0;
	alen = (a ? a->Sup.len : 0);
	blen = (b ? b->Sup.len : 0);
	{
		if (!(alen == blen)) goto LA3_;
		{
			if (!(alen == ((NI) 0))) goto LA7_;
			result = NIM_TRUE;
			goto BeforeRet_;
		}
		LA7_: ;
		result = equalMem__system_1735(((void*) ((&a->data[((NI) 0)]))), ((void*) ((&b->data[((NI) 0)]))), ((NI) (alen)));
		goto BeforeRet_;
	}
	LA3_: ;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NI, nextTry__pureZcollectionsZtables_34)(NI h, NI maxHash) {
	NI result;
	result = (NI)0;
	result = (NI)((NI)(h + ((NI) 1)) & maxHash);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, rawGet__pureZparsecfg_671)(tyObject_OrderedTable__UVxsO8EtsgVrmdBJlfhbxA t, NimStringDesc* key, NI* hc) {
	NI result;
	NI h;
	NI T10_;
{	result = (NI)0;
	(*hc) = hash__pureZhashes_279(key);
	{
		if (!((*hc) == ((NI) 0))) goto LA3_;
		(*hc) = ((NI) 314159265);
	}
	LA3_: ;
	{
		NI T7_;
		T7_ = (t.data ? t.data->Sup.len : 0);
		if (!(T7_ == ((NI) 0))) goto LA8_;
		result = ((NI) -1);
		goto BeforeRet_;
	}
	LA8_: ;
	T10_ = ((t.data ? t.data->Sup.len : 0)-1);
	h = (NI)((*hc) & T10_);
	{
		while (1) {
			NIM_BOOL T13_;
			NI T20_;
			T13_ = (NIM_BOOL)0;
			T13_ = isFilled__pureZcollectionsZtables_31(t.data->data[h].Field0);
			if (!T13_) goto LA12;
			{
				NIM_BOOL T16_;
				T16_ = (NIM_BOOL)0;
				T16_ = (t.data->data[h].Field0 == (*hc));
				if (!(T16_)) goto LA17_;
				T16_ = eqStrings(t.data->data[h].Field2, key);
				LA17_: ;
				if (!T16_) goto LA18_;
				result = h;
				goto BeforeRet_;
			}
			LA18_: ;
			T20_ = ((t.data ? t.data->Sup.len : 0)-1);
			h = nextTry__pureZcollectionsZtables_34(h, T20_);
		} LA12: ;
	}
	result = (NI)(((NI) -1) - h);
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, hasKey__pureZparsecfg_4022)(tyObject_OrderedTable__UVxsO8EtsgVrmdBJlfhbxA t, NimStringDesc* key) {
	NIM_BOOL result;
	NI hc;
	NI T1_;
	result = (NIM_BOOL)0;
	hc = (NI)0;
	T1_ = (NI)0;
	T1_ = rawGet__pureZparsecfg_671(t, key, (&hc));
	result = (((NI) 0) <= T1_);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, hasKey__pureZparsecfg_3923)(tyObject_OrderedTable__UVxsO8EtsgVrmdBJlfhbxA* t, NimStringDesc* key) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	result = hasKey__pureZparsecfg_4022((*t), key);
	return result;
}
static N_INLINE(NI, rawGet__pureZparsecfg_4215)(tyObject_OrderedTable__UVxsO8EtsgVrmdBJlfhbxA t, NimStringDesc* key, NI* hc) {
	NI result;
	NI h;
	NI T10_;
{	result = (NI)0;
	(*hc) = hash__pureZhashes_279(key);
	{
		if (!((*hc) == ((NI) 0))) goto LA3_;
		(*hc) = ((NI) 314159265);
	}
	LA3_: ;
	{
		NI T7_;
		T7_ = (t.data ? t.data->Sup.len : 0);
		if (!(T7_ == ((NI) 0))) goto LA8_;
		result = ((NI) -1);
		goto BeforeRet_;
	}
	LA8_: ;
	T10_ = ((t.data ? t.data->Sup.len : 0)-1);
	h = (NI)((*hc) & T10_);
	{
		while (1) {
			NIM_BOOL T13_;
			NI T20_;
			T13_ = (NIM_BOOL)0;
			T13_ = isFilled__pureZcollectionsZtables_31(t.data->data[h].Field0);
			if (!T13_) goto LA12;
			{
				NIM_BOOL T16_;
				T16_ = (NIM_BOOL)0;
				T16_ = (t.data->data[h].Field0 == (*hc));
				if (!(T16_)) goto LA17_;
				T16_ = eqStrings(t.data->data[h].Field2, key);
				LA17_: ;
				if (!T16_) goto LA18_;
				result = h;
				goto BeforeRet_;
			}
			LA18_: ;
			T20_ = ((t.data ? t.data->Sup.len : 0)-1);
			h = nextTry__pureZcollectionsZtables_34(h, T20_);
		} LA12: ;
	}
	result = (NI)(((NI) -1) - h);
	}BeforeRet_: ;
	return result;
}
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}
static N_INLINE(void, copyMem__system_1727)(void* dest, void* source, NI size) {
	nimCopyMem(dest, source, size);
}
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	{
		if (!!((src == ((NimStringDesc*) NIM_NIL)))) goto LA3_;
		copyMem__system_1727(((void*) ((&(*dest).data[(*dest).Sup.len]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
		(*dest).Sup.len += (*src).Sup.len;
	}
	LA3_: ;
}
static N_INLINE(NI, pluspercent___system_696)(NI x, NI y) {
	NI result;
	result = (NI)0;
	result = ((NI) ((NU)((NU32)(((NU) (x))) + (NU32)(((NU) (y))))));
	return result;
}
static N_INLINE(void, incRef__system_5847)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c) {
	(*c).refcount = pluspercent___system_696((*c).refcount, ((NI) 8));
}
static N_INLINE(NI, minuspercent___system_716)(NI x, NI y) {
	NI result;
	result = (NI)0;
	result = ((NI) ((NU)((NU32)(((NU) (x))) - (NU32)(((NU) (y))))));
	return result;
}
static N_INLINE(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell__system_5809)(void* usr) {
	tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* result;
	NI T1_;
	result = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;
	T1_ = (NI)0;
	T1_ = minuspercent___system_716(((NI) (ptrdiff_t) (usr)), ((NI) 8));
	result = ((tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*) (T1_));
	return result;
}
static N_INLINE(NIM_BOOL, ltpercent___system_1005)(NI x, NI y) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	result = ((NU32)(((NU) (x))) < (NU32)(((NU) (y))));
	return result;
}
static N_INLINE(void, rtlAddZCT__system_5852)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c) {
	addZCT__system_5803((&gch__system_5742.zct), c);
}
static N_INLINE(void, decRef__system_5854)(tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* c) {
	(*c).refcount = minuspercent___system_716((*c).refcount, ((NI) 8));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = ltpercent___system_1005((*c).refcount, ((NI) 8));
		if (!T3_) goto LA4_;
		rtlAddZCT__system_5852(c);
	}
	LA4_: ;
}
static N_INLINE(void, asgnRef)(void** dest, void* src) {
	{
		tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* T5_;
		if (!!((src == NIM_NIL))) goto LA3_;
		T5_ = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T5_ = usrToCell__system_5809(src);
		incRef__system_5847(T5_);
	}
	LA3_: ;
	{
		tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* T10_;
		if (!!(((*dest) == NIM_NIL))) goto LA8_;
		T10_ = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T10_ = usrToCell__system_5809((*dest));
		decRef__system_5854(T10_);
	}
	LA8_: ;
	(*dest) = src;
}
N_LIB_PRIVATE N_NOINLINE(void, raiseKeyError__pureZjson_2938)(NimStringDesc* key) {
	tyObject_KeyError__t7nhKLvXTQS9cS8ByJU9bIag* T1_;
	NimStringDesc* T2_;
	T1_ = NIM_NIL;
	T1_ = (tyObject_KeyError__t7nhKLvXTQS9cS8ByJU9bIag*) newObj((&NTIrefkeyerror__8SzoIAgLw9ci2v0yafHj9b6Q_), sizeof(tyObject_KeyError__t7nhKLvXTQS9cS8ByJU9bIag));
	(*T1_).Sup.Sup.Sup.Sup.m_type = (&NTIkeyerror__t7nhKLvXTQS9cS8ByJU9bIag_);
	(*T1_).Sup.Sup.Sup.name = "KeyError";
	T2_ = NIM_NIL;
	T2_ = rawNewString((key ? key->Sup.len : 0) + 15);
appendString(T2_, ((NimStringDesc*) &TM__4SoG2KRQy3oMm9aUzSLtGrA_2));
appendString(T2_, key);
	asgnRef((void**) (&(*T1_).Sup.Sup.Sup.message), T2_);
	asgnRef((void**) (&(*T1_).Sup.Sup.Sup.parent), ((Exception*) NIM_NIL));
	raiseExceptionEx((Exception*)T1_, "KeyError", "raiseKeyError", "tables.nim", 233);
}
N_LIB_PRIVATE N_NIMCALL(tyObject_OrderedTable__aBRulY0v9b6F4b7NLhEoU1Q**, X5BX5D___pureZparsecfg_4208)(tyObject_OrderedTable__UVxsO8EtsgVrmdBJlfhbxA* t, NimStringDesc* key) {
	tyObject_OrderedTable__aBRulY0v9b6F4b7NLhEoU1Q** result;
	NI hcX60gensym89_;
	NI indexX60gensym89_;
	result = (tyObject_OrderedTable__aBRulY0v9b6F4b7NLhEoU1Q**)0;
	hcX60gensym89_ = (NI)0;
	indexX60gensym89_ = rawGet__pureZparsecfg_4215((*t), key, (&hcX60gensym89_));
	{
		if (!(((NI) 0) <= indexX60gensym89_)) goto LA3_;
		result = &(*t).data->data[indexX60gensym89_].Field3;
	}
	goto LA1_;
	LA3_: ;
	{
		raiseKeyError__pureZjson_2938(key);
	}
	LA1_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_OrderedTable__aBRulY0v9b6F4b7NLhEoU1Q**, X5BX5D___pureZparsecfg_4096)(tyObject_OrderedTable__UVxsO8EtsgVrmdBJlfhbxA* t, NimStringDesc* key) {
	tyObject_OrderedTable__aBRulY0v9b6F4b7NLhEoU1Q** result;
	result = (tyObject_OrderedTable__aBRulY0v9b6F4b7NLhEoU1Q**)0;
	result = X5BX5D___pureZparsecfg_4208(t, key);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, rawGet__pureZparsecfg_2452)(tyObject_OrderedTable__aBRulY0v9b6F4b7NLhEoU1Q t, NimStringDesc* key, NI* hc) {
	NI result;
	NI h;
	NI T10_;
{	result = (NI)0;
	(*hc) = hash__pureZhashes_279(key);
	{
		if (!((*hc) == ((NI) 0))) goto LA3_;
		(*hc) = ((NI) 314159265);
	}
	LA3_: ;
	{
		NI T7_;
		T7_ = (t.data ? t.data->Sup.len : 0);
		if (!(T7_ == ((NI) 0))) goto LA8_;
		result = ((NI) -1);
		goto BeforeRet_;
	}
	LA8_: ;
	T10_ = ((t.data ? t.data->Sup.len : 0)-1);
	h = (NI)((*hc) & T10_);
	{
		while (1) {
			NIM_BOOL T13_;
			NI T20_;
			T13_ = (NIM_BOOL)0;
			T13_ = isFilled__pureZcollectionsZtables_31(t.data->data[h].Field0);
			if (!T13_) goto LA12;
			{
				NIM_BOOL T16_;
				T16_ = (NIM_BOOL)0;
				T16_ = (t.data->data[h].Field0 == (*hc));
				if (!(T16_)) goto LA17_;
				T16_ = eqStrings(t.data->data[h].Field2, key);
				LA17_: ;
				if (!T16_) goto LA18_;
				result = h;
				goto BeforeRet_;
			}
			LA18_: ;
			T20_ = ((t.data ? t.data->Sup.len : 0)-1);
			h = nextTry__pureZcollectionsZtables_34(h, T20_);
		} LA12: ;
	}
	result = (NI)(((NI) -1) - h);
	}BeforeRet_: ;
	return result;
}
static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g* T1_;
	T1_ = (tyObject_Cell__1zcF9cV8XIAtbN8h5HRUB8g*)0;
	T1_ = usrToCell__system_5809(p);
	decRef__system_5854(T1_);
}
static N_INLINE(NIM_BOOL, mustRehash__pureZparsecfg_2788)(tyObject_OrderedTable__aBRulY0v9b6F4b7NLhEoU1Q t) {
	NIM_BOOL result;
	NIM_BOOL T1_;
	NI T2_;
	NI T4_;
	result = (NIM_BOOL)0;
	T1_ = (NIM_BOOL)0;
	T2_ = (t.data ? t.data->Sup.len : 0);
	T1_ = ((NI)(T2_ * ((NI) 2)) < (NI)(t.counter * ((NI) 3)));
	if (T1_) goto LA3_;
	T4_ = (t.data ? t.data->Sup.len : 0);
	T1_ = ((NI)(T4_ - t.counter) < ((NI) 4));
	LA3_: ;
	result = T1_;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, rawInsert__pureZparsecfg_3356)(tyObject_OrderedTable__aBRulY0v9b6F4b7NLhEoU1Q* t, tySequence__dl1tcid0VwP1mpWNDzitYw** data, NimStringDesc* key, NimStringDesc* val, NI hc, NI h) {
	NimStringDesc* T1_;
	NimStringDesc* T2_;
	T1_ = NIM_NIL;
	T1_ = (*data)->data[h].Field2; (*data)->data[h].Field2 = copyStringRC1(key);
	if (T1_) nimGCunrefNoCycle(T1_);
	T2_ = NIM_NIL;
	T2_ = (*data)->data[h].Field3; (*data)->data[h].Field3 = copyStringRC1(val);
	if (T2_) nimGCunrefNoCycle(T2_);
	(*data)->data[h].Field0 = hc;
	(*data)->data[h].Field1 = ((NI) -1);
	{
		if (!((*t).first < ((NI) 0))) goto LA5_;
		(*t).first = h;
	}
	LA5_: ;
	{
		if (!(((NI) 0) <= (*t).last)) goto LA9_;
		(*data)->data[(*t).last].Field1 = h;
	}
	LA9_: ;
	(*t).last = h;
}
N_LIB_PRIVATE N_NIMCALL(void, enlarge__pureZparsecfg_2949)(tyObject_OrderedTable__aBRulY0v9b6F4b7NLhEoU1Q* t) {
	tySequence__dl1tcid0VwP1mpWNDzitYw* n;
	NI T1_;
	NI h;
	tySequence__dl1tcid0VwP1mpWNDzitYw* T2_;
	n = NIM_NIL;
	T1_ = ((*t).data ? (*t).data->Sup.len : 0);
	n = (tySequence__dl1tcid0VwP1mpWNDzitYw*) newSeq((&NTIorderedkeyvaluepairseq__dl1tcid0VwP1mpWNDzitYw_), ((NI) ((NI)(T1_ * ((NI) 2)))));
	h = (*t).first;
	(*t).first = ((NI) -1);
	(*t).last = ((NI) -1);
	T2_ = NIM_NIL;
	T2_ = (*t).data;
	unsureAsgnRef((void**) (&(*t).data), n);
	n = T2_;
	{
		while (1) {
			NI nxt;
			NI eh;
			if (!(((NI) 0) <= h)) goto LA4;
			nxt = n->data[h].Field1;
			eh = n->data[h].Field0;
			{
				NIM_BOOL T7_;
				NI j;
				NI T10_;
				NimStringDesc* T15_;
				NimStringDesc* T16_;
				T7_ = (NIM_BOOL)0;
				T7_ = isFilled__pureZcollectionsZtables_31(eh);
				if (!T7_) goto LA8_;
				T10_ = (((*t).data ? (*t).data->Sup.len : 0)-1);
				j = (NI)(eh & T10_);
				{
					while (1) {
						NIM_BOOL T13_;
						NI T14_;
						T13_ = (NIM_BOOL)0;
						T13_ = isFilled__pureZcollectionsZtables_31((*t).data->data[j].Field0);
						if (!T13_) goto LA12;
						T14_ = (((*t).data ? (*t).data->Sup.len : 0)-1);
						j = nextTry__pureZcollectionsZtables_34(j, T14_);
					} LA12: ;
				}
				T15_ = NIM_NIL;
				T15_ = n->data[h].Field2;
				asgnRef((void**) (&n->data[h].Field2), NIM_NIL);
				T16_ = NIM_NIL;
				T16_ = n->data[h].Field3;
				asgnRef((void**) (&n->data[h].Field3), NIM_NIL);
				rawInsert__pureZparsecfg_3356(t, (&(*t).data), T15_, T16_, n->data[h].Field0, j);
			}
			LA8_: ;
			h = nxt;
		} LA4: ;
	}
}
N_LIB_PRIVATE N_NIMCALL(NI, rawGetKnownHC__pureZparsecfg_3638)(tyObject_OrderedTable__aBRulY0v9b6F4b7NLhEoU1Q t, NimStringDesc* key, NI hc) {
	NI result;
	NI h;
	NI T6_;
{	result = (NI)0;
	{
		NI T3_;
		T3_ = (t.data ? t.data->Sup.len : 0);
		if (!(T3_ == ((NI) 0))) goto LA4_;
		result = ((NI) -1);
		goto BeforeRet_;
	}
	LA4_: ;
	T6_ = ((t.data ? t.data->Sup.len : 0)-1);
	h = (NI)(hc & T6_);
	{
		while (1) {
			NIM_BOOL T9_;
			NI T16_;
			T9_ = (NIM_BOOL)0;
			T9_ = isFilled__pureZcollectionsZtables_31(t.data->data[h].Field0);
			if (!T9_) goto LA8;
			{
				NIM_BOOL T12_;
				T12_ = (NIM_BOOL)0;
				T12_ = (t.data->data[h].Field0 == hc);
				if (!(T12_)) goto LA13_;
				T12_ = eqStrings(t.data->data[h].Field2, key);
				LA13_: ;
				if (!T12_) goto LA14_;
				result = h;
				goto BeforeRet_;
			}
			LA14_: ;
			T16_ = ((t.data ? t.data->Sup.len : 0)-1);
			h = nextTry__pureZcollectionsZtables_34(h, T16_);
		} LA8: ;
	}
	result = (NI)(((NI) -1) - h);
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, X5BX5Deq___pureZparsecfg_2383)(tyObject_OrderedTable__aBRulY0v9b6F4b7NLhEoU1Q* t, NimStringDesc* key, NimStringDesc* val) {
	NI hc;
	NI index;
	{
		NI T3_;
		NI correctSizeX60gensym26_;
		T3_ = ((*t).data ? (*t).data->Sup.len : 0);
		if (!(T3_ == ((NI) 0))) goto LA4_;
		correctSizeX60gensym26_ = slotsNeeded__pureZcollectionsZtables_42(((NI) 32));
		(*t).counter = ((NI) 0);
		unsureAsgnRef((void**) (&(*t).data), (tySequence__dl1tcid0VwP1mpWNDzitYw*) newSeq((&NTIorderedkeyvaluepairseq__dl1tcid0VwP1mpWNDzitYw_), ((NI) (correctSizeX60gensym26_))));
		(*t).first = ((NI) -1);
		(*t).last = ((NI) -1);
	}
	LA4_: ;
	hc = (NI)0;
	index = rawGet__pureZparsecfg_2452((*t), key, (&hc));
	{
		NimStringDesc* T10_;
		if (!(((NI) 0) <= index)) goto LA8_;
		T10_ = NIM_NIL;
		T10_ = (*t).data->data[index].Field3; (*t).data->data[index].Field3 = copyStringRC1(val);
		if (T10_) nimGCunrefNoCycle(T10_);
	}
	goto LA6_;
	LA8_: ;
	{
		{
			NI T14_;
			NI correctSizeX60gensym31_;
			T14_ = ((*t).data ? (*t).data->Sup.len : 0);
			if (!(T14_ == ((NI) 0))) goto LA15_;
			correctSizeX60gensym31_ = slotsNeeded__pureZcollectionsZtables_42(((NI) 32));
			(*t).counter = ((NI) 0);
			unsureAsgnRef((void**) (&(*t).data), (tySequence__dl1tcid0VwP1mpWNDzitYw*) newSeq((&NTIorderedkeyvaluepairseq__dl1tcid0VwP1mpWNDzitYw_), ((NI) (correctSizeX60gensym31_))));
			(*t).first = ((NI) -1);
			(*t).last = ((NI) -1);
		}
		LA15_: ;
		{
			NIM_BOOL T19_;
			T19_ = (NIM_BOOL)0;
			T19_ = mustRehash__pureZparsecfg_2788((*t));
			if (!T19_) goto LA20_;
			enlarge__pureZparsecfg_2949(t);
			index = rawGetKnownHC__pureZparsecfg_3638((*t), key, hc);
		}
		LA20_: ;
		index = (NI)(((NI) -1) - index);
		rawInsert__pureZparsecfg_3356(t, (&(*t).data), key, val, hc, index);
		(*t).counter += ((NI) 1);
	}
	LA6_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, X5BX5Deq___pureZparsecfg_2284)(tyObject_OrderedTable__aBRulY0v9b6F4b7NLhEoU1Q* t, NimStringDesc* key, NimStringDesc* val) {
	X5BX5Deq___pureZparsecfg_2383(t, key, val);
}
static N_INLINE(NIM_BOOL, mustRehash__pureZparsecfg_1007)(tyObject_OrderedTable__UVxsO8EtsgVrmdBJlfhbxA t) {
	NIM_BOOL result;
	NIM_BOOL T1_;
	NI T2_;
	NI T4_;
	result = (NIM_BOOL)0;
	T1_ = (NIM_BOOL)0;
	T2_ = (t.data ? t.data->Sup.len : 0);
	T1_ = ((NI)(T2_ * ((NI) 2)) < (NI)(t.counter * ((NI) 3)));
	if (T1_) goto LA3_;
	T4_ = (t.data ? t.data->Sup.len : 0);
	T1_ = ((NI)(T4_ - t.counter) < ((NI) 4));
	LA3_: ;
	result = T1_;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, rawInsert__pureZparsecfg_1588)(tyObject_OrderedTable__UVxsO8EtsgVrmdBJlfhbxA* t, tySequence__9b9bQp3iQ3wUkkIUUJdnRM5Q** data, NimStringDesc* key, tyObject_OrderedTable__aBRulY0v9b6F4b7NLhEoU1Q* val, NI hc, NI h) {
	NimStringDesc* T1_;
	T1_ = NIM_NIL;
	T1_ = (*data)->data[h].Field2; (*data)->data[h].Field2 = copyStringRC1(key);
	if (T1_) nimGCunrefNoCycle(T1_);
	asgnRef((void**) (&(*data)->data[h].Field3), val);
	(*data)->data[h].Field0 = hc;
	(*data)->data[h].Field1 = ((NI) -1);
	{
		if (!((*t).first < ((NI) 0))) goto LA4_;
		(*t).first = h;
	}
	LA4_: ;
	{
		if (!(((NI) 0) <= (*t).last)) goto LA8_;
		(*data)->data[(*t).last].Field1 = h;
	}
	LA8_: ;
	(*t).last = h;
}
N_LIB_PRIVATE N_NIMCALL(void, enlarge__pureZparsecfg_1168)(tyObject_OrderedTable__UVxsO8EtsgVrmdBJlfhbxA* t) {
	tySequence__9b9bQp3iQ3wUkkIUUJdnRM5Q* n;
	NI T1_;
	NI h;
	tySequence__9b9bQp3iQ3wUkkIUUJdnRM5Q* T2_;
	n = NIM_NIL;
	T1_ = ((*t).data ? (*t).data->Sup.len : 0);
	n = (tySequence__9b9bQp3iQ3wUkkIUUJdnRM5Q*) newSeq((&NTIorderedkeyvaluepairseq__9b9bQp3iQ3wUkkIUUJdnRM5Q_), ((NI) ((NI)(T1_ * ((NI) 2)))));
	h = (*t).first;
	(*t).first = ((NI) -1);
	(*t).last = ((NI) -1);
	T2_ = NIM_NIL;
	T2_ = (*t).data;
	unsureAsgnRef((void**) (&(*t).data), n);
	n = T2_;
	{
		while (1) {
			NI nxt;
			NI eh;
			if (!(((NI) 0) <= h)) goto LA4;
			nxt = n->data[h].Field1;
			eh = n->data[h].Field0;
			{
				NIM_BOOL T7_;
				NI j;
				NI T10_;
				NimStringDesc* T15_;
				tyObject_OrderedTable__aBRulY0v9b6F4b7NLhEoU1Q* T16_;
				T7_ = (NIM_BOOL)0;
				T7_ = isFilled__pureZcollectionsZtables_31(eh);
				if (!T7_) goto LA8_;
				T10_ = (((*t).data ? (*t).data->Sup.len : 0)-1);
				j = (NI)(eh & T10_);
				{
					while (1) {
						NIM_BOOL T13_;
						NI T14_;
						T13_ = (NIM_BOOL)0;
						T13_ = isFilled__pureZcollectionsZtables_31((*t).data->data[j].Field0);
						if (!T13_) goto LA12;
						T14_ = (((*t).data ? (*t).data->Sup.len : 0)-1);
						j = nextTry__pureZcollectionsZtables_34(j, T14_);
					} LA12: ;
				}
				T15_ = NIM_NIL;
				T15_ = n->data[h].Field2;
				asgnRef((void**) (&n->data[h].Field2), NIM_NIL);
				T16_ = NIM_NIL;
				T16_ = n->data[h].Field3;
				asgnRef((void**) (&n->data[h].Field3), NIM_NIL);
				rawInsert__pureZparsecfg_1588(t, (&(*t).data), T15_, T16_, n->data[h].Field0, j);
			}
			LA8_: ;
			h = nxt;
		} LA4: ;
	}
}
N_LIB_PRIVATE N_NIMCALL(NI, rawGetKnownHC__pureZparsecfg_1870)(tyObject_OrderedTable__UVxsO8EtsgVrmdBJlfhbxA t, NimStringDesc* key, NI hc) {
	NI result;
	NI h;
	NI T6_;
{	result = (NI)0;
	{
		NI T3_;
		T3_ = (t.data ? t.data->Sup.len : 0);
		if (!(T3_ == ((NI) 0))) goto LA4_;
		result = ((NI) -1);
		goto BeforeRet_;
	}
	LA4_: ;
	T6_ = ((t.data ? t.data->Sup.len : 0)-1);
	h = (NI)(hc & T6_);
	{
		while (1) {
			NIM_BOOL T9_;
			NI T16_;
			T9_ = (NIM_BOOL)0;
			T9_ = isFilled__pureZcollectionsZtables_31(t.data->data[h].Field0);
			if (!T9_) goto LA8;
			{
				NIM_BOOL T12_;
				T12_ = (NIM_BOOL)0;
				T12_ = (t.data->data[h].Field0 == hc);
				if (!(T12_)) goto LA13_;
				T12_ = eqStrings(t.data->data[h].Field2, key);
				LA13_: ;
				if (!T12_) goto LA14_;
				result = h;
				goto BeforeRet_;
			}
			LA14_: ;
			T16_ = ((t.data ? t.data->Sup.len : 0)-1);
			h = nextTry__pureZcollectionsZtables_34(h, T16_);
		} LA8: ;
	}
	result = (NI)(((NI) -1) - h);
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, X5BX5Deq___pureZparsecfg_602)(tyObject_OrderedTable__UVxsO8EtsgVrmdBJlfhbxA* t, NimStringDesc* key, tyObject_OrderedTable__aBRulY0v9b6F4b7NLhEoU1Q* val) {
	NI hc;
	NI index;
	{
		NI T3_;
		NI correctSizeX60gensym10_;
		T3_ = ((*t).data ? (*t).data->Sup.len : 0);
		if (!(T3_ == ((NI) 0))) goto LA4_;
		correctSizeX60gensym10_ = slotsNeeded__pureZcollectionsZtables_42(((NI) 32));
		(*t).counter = ((NI) 0);
		unsureAsgnRef((void**) (&(*t).data), (tySequence__9b9bQp3iQ3wUkkIUUJdnRM5Q*) newSeq((&NTIorderedkeyvaluepairseq__9b9bQp3iQ3wUkkIUUJdnRM5Q_), ((NI) (correctSizeX60gensym10_))));
		(*t).first = ((NI) -1);
		(*t).last = ((NI) -1);
	}
	LA4_: ;
	hc = (NI)0;
	index = rawGet__pureZparsecfg_671((*t), key, (&hc));
	{
		if (!(((NI) 0) <= index)) goto LA8_;
		asgnRef((void**) (&(*t).data->data[index].Field3), val);
	}
	goto LA6_;
	LA8_: ;
	{
		{
			NI T13_;
			NI correctSizeX60gensym15_;
			T13_ = ((*t).data ? (*t).data->Sup.len : 0);
			if (!(T13_ == ((NI) 0))) goto LA14_;
			correctSizeX60gensym15_ = slotsNeeded__pureZcollectionsZtables_42(((NI) 32));
			(*t).counter = ((NI) 0);
			unsureAsgnRef((void**) (&(*t).data), (tySequence__9b9bQp3iQ3wUkkIUUJdnRM5Q*) newSeq((&NTIorderedkeyvaluepairseq__9b9bQp3iQ3wUkkIUUJdnRM5Q_), ((NI) (correctSizeX60gensym15_))));
			(*t).first = ((NI) -1);
			(*t).last = ((NI) -1);
		}
		LA14_: ;
		{
			NIM_BOOL T18_;
			T18_ = (NIM_BOOL)0;
			T18_ = mustRehash__pureZparsecfg_1007((*t));
			if (!T18_) goto LA19_;
			enlarge__pureZparsecfg_1168(t);
			index = rawGetKnownHC__pureZparsecfg_1870((*t), key, hc);
		}
		LA19_: ;
		index = (NI)(((NI) -1) - index);
		rawInsert__pureZparsecfg_1588(t, (&(*t).data), key, val, hc, index);
		(*t).counter += ((NI) 1);
	}
	LA6_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, X5BX5Deq___pureZparsecfg_503)(tyObject_OrderedTable__UVxsO8EtsgVrmdBJlfhbxA* t, NimStringDesc* key, tyObject_OrderedTable__aBRulY0v9b6F4b7NLhEoU1Q* val) {
	X5BX5Deq___pureZparsecfg_602(t, key, val);
}
N_LIB_PRIVATE N_NIMCALL(void, initTable__OOZOOZOnimbleZpkgsZnico4548O52O57Znico_4455)(NI initialSize, tyObject_Table__pjVQUpmpjessb3kC1dSh5w* Result) {
	NI correctSizeX60gensym171_;
	unsureAsgnRef((void**)&(*Result).data, NIM_NIL);
	(*Result).counter = 0;
	correctSizeX60gensym171_ = slotsNeeded__pureZcollectionsZtables_42(((NI) (initialSize)));
	(*Result).counter = ((NI) 0);
	unsureAsgnRef((void**) (&(*Result).data), (tySequence__Orgg2tA9c9cbNS8O19aPtx6fw*) newSeq((&NTIkeyvaluepairseq__Orgg2tA9c9cbNS8O19aPtx6fw_), ((NI) (correctSizeX60gensym171_))));
}
static N_INLINE(NU64, hiXorLoFallback64__pureZhashes_35)(NU64 a, NU64 b) {
	NU64 result;
	NU64 aH;
	NU64 aL;
	NU64 bH;
	NU64 bL;
	NU64 rHH;
	NU64 rHL;
	NU64 rLH;
	NU64 rLL;
	NU64 t;
	NU64 c;
	NU64 lo;
	NU64 T6_;
	NU64 hi;
{	result = (NU64)0;
	aH = (NU64)((NU64)(a) >> (NU64)(((NI) 32)));
	aL = (NU64)(a & 4294967295ULL);
	bH = (NU64)((NU64)(b) >> (NU64)(((NI) 32)));
	bL = (NU64)(b & 4294967295ULL);
	rHH = (NU64)((NU64)(aH) * (NU64)(bH));
	rHL = (NU64)((NU64)(aH) * (NU64)(bL));
	rLH = (NU64)((NU64)(aL) * (NU64)(bH));
	rLL = (NU64)((NU64)(aL) * (NU64)(bL));
	t = (NU64)((NU64)(rLL) + (NU64)((NU64)((NU64)(rHL) << (NU64)(((NI) 32)))));
	{
		if (!((NU64)(t) < (NU64)(rLL))) goto LA3_;
		c = 1ULL;
	}
	goto LA1_;
	LA3_: ;
	{
		c = 0ULL;
	}
	LA1_: ;
	lo = (NU64)((NU64)(t) + (NU64)((NU64)((NU64)(rLH) << (NU64)(((NI) 32)))));
	T6_ = (NU64)0;
	{
		if (!((NU64)(lo) < (NU64)(t))) goto LA9_;
		T6_ = 1ULL;
	}
	goto LA7_;
	LA9_: ;
	{
		T6_ = 0ULL;
	}
	LA7_: ;
	c += T6_;
	hi = (NU64)((NU64)((NU64)((NU64)((NU64)((NU64)(rHH) + (NU64)((NU64)((NU64)(rHL) >> (NU64)(((NI) 32)))))) + (NU64)((NU64)((NU64)(rLH) >> (NU64)(((NI) 32)))))) + (NU64)(c));
	result = (NU64)(hi ^ lo);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NU64, hiXorLo__pureZhashes_79)(NU64 a, NU64 b) {
	NU64 result;
	result = (NU64)0;
	result = hiXorLoFallback64__pureZhashes_35(a, b);
	return result;
}
static N_INLINE(NI, hashWangYi1__pureZhashes_136)(NU64 x) {
	NI result;
	NU64 T1_;
	NU64 T2_;
	result = (NI)0;
	T1_ = (NU64)0;
	T1_ = hiXorLo__pureZhashes_79(11562461410679940143ULL, (NU64)(x ^ 16646288086500911323ULL));
	T2_ = (NU64)0;
	T2_ = hiXorLo__pureZhashes_79(T1_, 16952864883938283885ULL);
	result = ((NI) (T2_));
	return result;
}
static N_INLINE(NI, hash__OOZOOZOnimbleZpkgsZnico4548O52O57Znico_3079)(NI32 x) {
	NI result;
	result = (NI)0;
	result = hashWangYi1__pureZhashes_136(((NU64) (x)));
	return result;
}
static N_INLINE(NI, rawGet__OOZOOZOnimbleZpkgsZnico4548O52O57Znico_3072)(tyObject_Table__pjVQUpmpjessb3kC1dSh5w t, NI32 key, NI* hc) {
	NI result;
	NI h;
	NI T10_;
{	result = (NI)0;
	(*hc) = hash__OOZOOZOnimbleZpkgsZnico4548O52O57Znico_3079(key);
	{
		if (!((*hc) == ((NI) 0))) goto LA3_;
		(*hc) = ((NI) 314159265);
	}
	LA3_: ;
	{
		NI T7_;
		T7_ = (t.data ? t.data->Sup.len : 0);
		if (!(T7_ == ((NI) 0))) goto LA8_;
		result = ((NI) -1);
		goto BeforeRet_;
	}
	LA8_: ;
	T10_ = ((t.data ? t.data->Sup.len : 0)-1);
	h = (NI)((*hc) & T10_);
	{
		while (1) {
			NIM_BOOL T13_;
			NI T20_;
			T13_ = (NIM_BOOL)0;
			T13_ = isFilled__pureZcollectionsZtables_31(t.data->data[h].Field0);
			if (!T13_) goto LA12;
			{
				NIM_BOOL T16_;
				T16_ = (NIM_BOOL)0;
				T16_ = (t.data->data[h].Field0 == (*hc));
				if (!(T16_)) goto LA17_;
				T16_ = eqeq___pureZunicode_908(t.data->data[h].Field1, key);
				LA17_: ;
				if (!T16_) goto LA18_;
				result = h;
				goto BeforeRet_;
			}
			LA18_: ;
			T20_ = ((t.data ? t.data->Sup.len : 0)-1);
			h = nextTry__pureZcollectionsZtables_34(h, T20_);
		} LA12: ;
	}
	result = (NI)(((NI) -1) - h);
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, hasKey__OOZOOZOnimbleZpkgsZnico4548O52O57Znico_4721)(tyObject_Table__pjVQUpmpjessb3kC1dSh5w t, NI32 key) {
	NIM_BOOL result;
	NI hc;
	NI T1_;
	result = (NIM_BOOL)0;
	hc = (NI)0;
	T1_ = (NI)0;
	T1_ = rawGet__OOZOOZOnimbleZpkgsZnico4548O52O57Znico_3072(t, key, (&hc));
	result = (((NI) 0) <= T1_);
	return result;
}
static N_INLINE(NIM_BOOL, mustRehash__OOZOOZOnimbleZpkgsZnico4548O52O57Znico_3458)(tyObject_Table__pjVQUpmpjessb3kC1dSh5w t) {
	NIM_BOOL result;
	NIM_BOOL T1_;
	NI T2_;
	NI T4_;
	result = (NIM_BOOL)0;
	T1_ = (NIM_BOOL)0;
	T2_ = (t.data ? t.data->Sup.len : 0);
	T1_ = ((NI)(T2_ * ((NI) 2)) < (NI)(t.counter * ((NI) 3)));
	if (T1_) goto LA3_;
	T4_ = (t.data ? t.data->Sup.len : 0);
	T1_ = ((NI)(T4_ - t.counter) < ((NI) 4));
	LA3_: ;
	result = T1_;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, rawInsert__OOZOOZOnimbleZpkgsZnico4548O52O57Znico_3959)(tyObject_Table__pjVQUpmpjessb3kC1dSh5w* t, tySequence__Orgg2tA9c9cbNS8O19aPtx6fw** data, NI32 key, tyTuple__FtZxsWeKlOo83uVL9c4OOmg val, NI hc, NI h) {
	(*data)->data[h].Field1 = key;
	(*data)->data[h].Field2 = val;
	(*data)->data[h].Field0 = hc;
}
static N_INLINE(void, nimSetMem__systemZmemory_7)(void* a, int v, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a, v, ((size_t) (size)));
}
static N_INLINE(void, nimZeroMem)(void* p, NI size) {
	nimSetMem__systemZmemory_7(p, ((int) 0), size);
}
N_LIB_PRIVATE N_NIMCALL(void, enlarge__OOZOOZOnimbleZpkgsZnico4548O52O57Znico_3626)(tyObject_Table__pjVQUpmpjessb3kC1dSh5w* t) {
	tySequence__Orgg2tA9c9cbNS8O19aPtx6fw* n;
	NI T1_;
	tySequence__Orgg2tA9c9cbNS8O19aPtx6fw* T2_;
	n = NIM_NIL;
	T1_ = ((*t).data ? (*t).data->Sup.len : 0);
	n = (tySequence__Orgg2tA9c9cbNS8O19aPtx6fw*) newSeq((&NTIkeyvaluepairseq__Orgg2tA9c9cbNS8O19aPtx6fw_), ((NI) ((NI)(T1_ * ((NI) 2)))));
	T2_ = NIM_NIL;
	T2_ = (*t).data;
	unsureAsgnRef((void**) (&(*t).data), n);
	n = T2_;
	{
		NI i;
		NI colontmp_;
		NI T4_;
		NI res;
		i = (NI)0;
		colontmp_ = (NI)0;
		T4_ = ((n ? n->Sup.len : 0)-1);
		colontmp_ = T4_;
		res = ((NI) 0);
		{
			while (1) {
				NI eh;
				if (!(res <= colontmp_)) goto LA6;
				i = res;
				eh = n->data[i].Field0;
				{
					NIM_BOOL T9_;
					NI j;
					NI T12_;
					NI32 T17_;
					tyTuple__FtZxsWeKlOo83uVL9c4OOmg T18_;
					T9_ = (NIM_BOOL)0;
					T9_ = isFilled__pureZcollectionsZtables_31(eh);
					if (!T9_) goto LA10_;
					T12_ = (((*t).data ? (*t).data->Sup.len : 0)-1);
					j = (NI)(eh & T12_);
					{
						while (1) {
							NIM_BOOL T15_;
							NI T16_;
							T15_ = (NIM_BOOL)0;
							T15_ = isFilled__pureZcollectionsZtables_31((*t).data->data[j].Field0);
							if (!T15_) goto LA14;
							T16_ = (((*t).data ? (*t).data->Sup.len : 0)-1);
							j = nextTry__pureZcollectionsZtables_34(j, T16_);
						} LA14: ;
					}
					T17_ = (NI32)0;
					T17_ = n->data[i].Field1;
					n->data[i].Field1 = 0;
					T18_ = n->data[i].Field2;
					nimZeroMem((void*)(&n->data[i].Field2), sizeof(tyTuple__FtZxsWeKlOo83uVL9c4OOmg));
					rawInsert__OOZOOZOnimbleZpkgsZnico4548O52O57Znico_3959(t, (&(*t).data), T17_, T18_, eh, j);
				}
				LA10_: ;
				res += ((NI) 1);
			} LA6: ;
		}
	}
}
static N_INLINE(NI, rawGetKnownHC__OOZOOZOnimbleZpkgsZnico4548O52O57Znico_4143)(tyObject_Table__pjVQUpmpjessb3kC1dSh5w t, NI32 key, NI hc) {
	NI result;
	NI h;
	NI T6_;
{	result = (NI)0;
	{
		NI T3_;
		T3_ = (t.data ? t.data->Sup.len : 0);
		if (!(T3_ == ((NI) 0))) goto LA4_;
		result = ((NI) -1);
		goto BeforeRet_;
	}
	LA4_: ;
	T6_ = ((t.data ? t.data->Sup.len : 0)-1);
	h = (NI)(hc & T6_);
	{
		while (1) {
			NIM_BOOL T9_;
			NI T16_;
			T9_ = (NIM_BOOL)0;
			T9_ = isFilled__pureZcollectionsZtables_31(t.data->data[h].Field0);
			if (!T9_) goto LA8;
			{
				NIM_BOOL T12_;
				T12_ = (NIM_BOOL)0;
				T12_ = (t.data->data[h].Field0 == hc);
				if (!(T12_)) goto LA13_;
				T12_ = eqeq___pureZunicode_908(t.data->data[h].Field1, key);
				LA13_: ;
				if (!T12_) goto LA14_;
				result = h;
				goto BeforeRet_;
			}
			LA14_: ;
			T16_ = ((t.data ? t.data->Sup.len : 0)-1);
			h = nextTry__pureZcollectionsZtables_34(h, T16_);
		} LA8: ;
	}
	result = (NI)(((NI) -1) - h);
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, X5BX5Deq___OOZOOZOnimbleZpkgsZnico4548O52O57Znico_3006)(tyObject_Table__pjVQUpmpjessb3kC1dSh5w* t, NI32 key, tyTuple__FtZxsWeKlOo83uVL9c4OOmg val) {
	NI hc;
	NI index;
	{
		NI T3_;
		NI correctSizeX60gensym156_;
		T3_ = ((*t).data ? (*t).data->Sup.len : 0);
		if (!(T3_ == ((NI) 0))) goto LA4_;
		correctSizeX60gensym156_ = slotsNeeded__pureZcollectionsZtables_42(((NI) 32));
		(*t).counter = ((NI) 0);
		unsureAsgnRef((void**) (&(*t).data), (tySequence__Orgg2tA9c9cbNS8O19aPtx6fw*) newSeq((&NTIkeyvaluepairseq__Orgg2tA9c9cbNS8O19aPtx6fw_), ((NI) (correctSizeX60gensym156_))));
	}
	LA4_: ;
	hc = (NI)0;
	index = rawGet__OOZOOZOnimbleZpkgsZnico4548O52O57Znico_3072((*t), key, (&hc));
	{
		if (!(((NI) 0) <= index)) goto LA8_;
		(*t).data->data[index].Field2 = val;
	}
	goto LA6_;
	LA8_: ;
	{
		{
			NI T13_;
			NI correctSizeX60gensym161_;
			T13_ = ((*t).data ? (*t).data->Sup.len : 0);
			if (!(T13_ == ((NI) 0))) goto LA14_;
			correctSizeX60gensym161_ = slotsNeeded__pureZcollectionsZtables_42(((NI) 32));
			(*t).counter = ((NI) 0);
			unsureAsgnRef((void**) (&(*t).data), (tySequence__Orgg2tA9c9cbNS8O19aPtx6fw*) newSeq((&NTIkeyvaluepairseq__Orgg2tA9c9cbNS8O19aPtx6fw_), ((NI) (correctSizeX60gensym161_))));
		}
		LA14_: ;
		{
			NIM_BOOL T18_;
			T18_ = (NIM_BOOL)0;
			T18_ = mustRehash__OOZOOZOnimbleZpkgsZnico4548O52O57Znico_3458((*t));
			if (!T18_) goto LA19_;
			enlarge__OOZOOZOnimbleZpkgsZnico4548O52O57Znico_3626(t);
			index = rawGetKnownHC__OOZOOZOnimbleZpkgsZnico4548O52O57Znico_4143((*t), key, hc);
		}
		LA19_: ;
		index = (NI)(((NI) -1) - index);
		rawInsert__OOZOOZOnimbleZpkgsZnico4548O52O57Znico_3959(t, (&(*t).data), key, val, hc, index);
		(*t).counter += ((NI) 1);
	}
	LA6_: ;
}
N_LIB_PRIVATE N_NIMCALL(NI, len__OOZOOZOnimbleZpkgsZnico4548O52O57Znico_4788)(tyObject_Table__pjVQUpmpjessb3kC1dSh5w t) {
	NI result;
	result = (NI)0;
	result = t.counter;
	return result;
}
static N_INLINE(NI, rawGet__OOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZsdl50_1668)(tyObject_Table__qyR3xLIFK9bnjRhAsVBPjVA t, tyEnum_Keycode__4FafBrLvG2wfvPTkNrrFRQ key, NI* hc) {
	NI result;
	NI h;
	NI T10_;
{	result = (NI)0;
	(*hc) = hash__OOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZsdl50_35(key);
	{
		if (!((*hc) == ((NI) 0))) goto LA3_;
		(*hc) = ((NI) 314159265);
	}
	LA3_: ;
	{
		NI T7_;
		T7_ = (t.data ? t.data->Sup.len : 0);
		if (!(T7_ == ((NI) 0))) goto LA8_;
		result = ((NI) -1);
		goto BeforeRet_;
	}
	LA8_: ;
	T10_ = ((t.data ? t.data->Sup.len : 0)-1);
	h = (NI)((*hc) & T10_);
	{
		while (1) {
			NIM_BOOL T13_;
			NI T20_;
			T13_ = (NIM_BOOL)0;
			T13_ = isFilled__pureZcollectionsZtables_31(t.data->data[h].Field0);
			if (!T13_) goto LA12;
			{
				NIM_BOOL T16_;
				T16_ = (NIM_BOOL)0;
				T16_ = (t.data->data[h].Field0 == (*hc));
				if (!(T16_)) goto LA17_;
				T16_ = (t.data->data[h].Field1 == key);
				LA17_: ;
				if (!T16_) goto LA18_;
				result = h;
				goto BeforeRet_;
			}
			LA18_: ;
			T20_ = ((t.data ? t.data->Sup.len : 0)-1);
			h = nextTry__pureZcollectionsZtables_34(h, T20_);
		} LA12: ;
	}
	result = (NI)(((NI) -1) - h);
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NIM_BOOL, mustRehash__OOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZsdl50_2039)(tyObject_Table__qyR3xLIFK9bnjRhAsVBPjVA t) {
	NIM_BOOL result;
	NIM_BOOL T1_;
	NI T2_;
	NI T4_;
	result = (NIM_BOOL)0;
	T1_ = (NIM_BOOL)0;
	T2_ = (t.data ? t.data->Sup.len : 0);
	T1_ = ((NI)(T2_ * ((NI) 2)) < (NI)(t.counter * ((NI) 3)));
	if (T1_) goto LA3_;
	T4_ = (t.data ? t.data->Sup.len : 0);
	T1_ = ((NI)(T4_ - t.counter) < ((NI) 4));
	LA3_: ;
	result = T1_;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, rawInsert__OOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZsdl50_2540)(tyObject_Table__qyR3xLIFK9bnjRhAsVBPjVA* t, tySequence__P9cgLJz9cK9czFckaAibTALJQ** data, tyEnum_Keycode__4FafBrLvG2wfvPTkNrrFRQ key, NU32 val, NI hc, NI h) {
	(*data)->data[h].Field1 = key;
	(*data)->data[h].Field2 = val;
	(*data)->data[h].Field0 = hc;
}
N_LIB_PRIVATE N_NIMCALL(void, enlarge__OOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZsdl50_2207)(tyObject_Table__qyR3xLIFK9bnjRhAsVBPjVA* t) {
	tySequence__P9cgLJz9cK9czFckaAibTALJQ* n;
	NI T1_;
	tySequence__P9cgLJz9cK9czFckaAibTALJQ* T2_;
	n = NIM_NIL;
	T1_ = ((*t).data ? (*t).data->Sup.len : 0);
	n = (tySequence__P9cgLJz9cK9czFckaAibTALJQ*) newSeq((&NTIkeyvaluepairseq__P9cgLJz9cK9czFckaAibTALJQ_), ((NI) ((NI)(T1_ * ((NI) 2)))));
	T2_ = NIM_NIL;
	T2_ = (*t).data;
	unsureAsgnRef((void**) (&(*t).data), n);
	n = T2_;
	{
		NI i;
		NI colontmp_;
		NI T4_;
		NI res;
		i = (NI)0;
		colontmp_ = (NI)0;
		T4_ = ((n ? n->Sup.len : 0)-1);
		colontmp_ = T4_;
		res = ((NI) 0);
		{
			while (1) {
				NI eh;
				if (!(res <= colontmp_)) goto LA6;
				i = res;
				eh = n->data[i].Field0;
				{
					NIM_BOOL T9_;
					NI j;
					NI T12_;
					tyEnum_Keycode__4FafBrLvG2wfvPTkNrrFRQ T17_;
					NU32 T18_;
					T9_ = (NIM_BOOL)0;
					T9_ = isFilled__pureZcollectionsZtables_31(eh);
					if (!T9_) goto LA10_;
					T12_ = (((*t).data ? (*t).data->Sup.len : 0)-1);
					j = (NI)(eh & T12_);
					{
						while (1) {
							NIM_BOOL T15_;
							NI T16_;
							T15_ = (NIM_BOOL)0;
							T15_ = isFilled__pureZcollectionsZtables_31((*t).data->data[j].Field0);
							if (!T15_) goto LA14;
							T16_ = (((*t).data ? (*t).data->Sup.len : 0)-1);
							j = nextTry__pureZcollectionsZtables_34(j, T16_);
						} LA14: ;
					}
					T17_ = (tyEnum_Keycode__4FafBrLvG2wfvPTkNrrFRQ)0;
					T17_ = n->data[i].Field1;
					n->data[i].Field1 = 0;
					T18_ = (NU32)0;
					T18_ = n->data[i].Field2;
					n->data[i].Field2 = 0;
					rawInsert__OOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZsdl50_2540(t, (&(*t).data), T17_, T18_, eh, j);
				}
				LA10_: ;
				res += ((NI) 1);
			} LA6: ;
		}
	}
}
static N_INLINE(NI, rawGetKnownHC__OOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZsdl50_2733)(tyObject_Table__qyR3xLIFK9bnjRhAsVBPjVA t, tyEnum_Keycode__4FafBrLvG2wfvPTkNrrFRQ key, NI hc) {
	NI result;
	NI h;
	NI T6_;
{	result = (NI)0;
	{
		NI T3_;
		T3_ = (t.data ? t.data->Sup.len : 0);
		if (!(T3_ == ((NI) 0))) goto LA4_;
		result = ((NI) -1);
		goto BeforeRet_;
	}
	LA4_: ;
	T6_ = ((t.data ? t.data->Sup.len : 0)-1);
	h = (NI)(hc & T6_);
	{
		while (1) {
			NIM_BOOL T9_;
			NI T16_;
			T9_ = (NIM_BOOL)0;
			T9_ = isFilled__pureZcollectionsZtables_31(t.data->data[h].Field0);
			if (!T9_) goto LA8;
			{
				NIM_BOOL T12_;
				T12_ = (NIM_BOOL)0;
				T12_ = (t.data->data[h].Field0 == hc);
				if (!(T12_)) goto LA13_;
				T12_ = (t.data->data[h].Field1 == key);
				LA13_: ;
				if (!T12_) goto LA14_;
				result = h;
				goto BeforeRet_;
			}
			LA14_: ;
			T16_ = ((t.data ? t.data->Sup.len : 0)-1);
			h = nextTry__pureZcollectionsZtables_34(h, T16_);
		} LA8: ;
	}
	result = (NI)(((NI) -1) - h);
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, X5BX5Deq___OOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZsdl50_1602)(tyObject_Table__qyR3xLIFK9bnjRhAsVBPjVA* t, tyEnum_Keycode__4FafBrLvG2wfvPTkNrrFRQ key, NU32 val) {
	NI hc;
	NI index;
	{
		NI T3_;
		NI correctSizeX60gensym78_;
		T3_ = ((*t).data ? (*t).data->Sup.len : 0);
		if (!(T3_ == ((NI) 0))) goto LA4_;
		correctSizeX60gensym78_ = slotsNeeded__pureZcollectionsZtables_42(((NI) 32));
		(*t).counter = ((NI) 0);
		unsureAsgnRef((void**) (&(*t).data), (tySequence__P9cgLJz9cK9czFckaAibTALJQ*) newSeq((&NTIkeyvaluepairseq__P9cgLJz9cK9czFckaAibTALJQ_), ((NI) (correctSizeX60gensym78_))));
	}
	LA4_: ;
	hc = (NI)0;
	index = rawGet__OOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZsdl50_1668((*t), key, (&hc));
	{
		if (!(((NI) 0) <= index)) goto LA8_;
		(*t).data->data[index].Field2 = val;
	}
	goto LA6_;
	LA8_: ;
	{
		{
			NI T13_;
			NI correctSizeX60gensym83_;
			T13_ = ((*t).data ? (*t).data->Sup.len : 0);
			if (!(T13_ == ((NI) 0))) goto LA14_;
			correctSizeX60gensym83_ = slotsNeeded__pureZcollectionsZtables_42(((NI) 32));
			(*t).counter = ((NI) 0);
			unsureAsgnRef((void**) (&(*t).data), (tySequence__P9cgLJz9cK9czFckaAibTALJQ*) newSeq((&NTIkeyvaluepairseq__P9cgLJz9cK9czFckaAibTALJQ_), ((NI) (correctSizeX60gensym83_))));
		}
		LA14_: ;
		{
			NIM_BOOL T18_;
			T18_ = (NIM_BOOL)0;
			T18_ = mustRehash__OOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZsdl50_2039((*t));
			if (!T18_) goto LA19_;
			enlarge__OOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZsdl50_2207(t);
			index = rawGetKnownHC__OOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZsdl50_2733((*t), key, hc);
		}
		LA19_: ;
		index = (NI)(((NI) -1) - index);
		rawInsert__OOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZsdl50_2540(t, (&(*t).data), key, val, hc, index);
		(*t).counter += ((NI) 1);
	}
	LA6_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, initTable__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871_5290)(NI initialSize, tyObject_Table__HWSctC1WdhUfJtaLIvgFUw* Result) {
	NI correctSizeX60gensym265_;
	unsureAsgnRef((void**)&(*Result).data, NIM_NIL);
	(*Result).counter = 0;
	correctSizeX60gensym265_ = slotsNeeded__pureZcollectionsZtables_42(((NI) (initialSize)));
	(*Result).counter = ((NI) 0);
	unsureAsgnRef((void**) (&(*Result).data), (tySequence__fl4Fl0sjv6wLBM59aA9a59c9aw*) newSeq((&NTIkeyvaluepairseq__fl4Fl0sjv6wLBM59aA9a59c9aw_), ((NI) (correctSizeX60gensym265_))));
}
static N_INLINE(NI, rawGet__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871_5416)(tyObject_Table__HWSctC1WdhUfJtaLIvgFUw t, tyObject_RGBA8__P4w0wnmH7J1IGztO6QfG5A key, NI* hc) {
	NI result;
	NI h;
	NI T10_;
{	result = (NI)0;
	(*hc) = hash__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871_1636(key);
	{
		if (!((*hc) == ((NI) 0))) goto LA3_;
		(*hc) = ((NI) 314159265);
	}
	LA3_: ;
	{
		NI T7_;
		T7_ = (t.data ? t.data->Sup.len : 0);
		if (!(T7_ == ((NI) 0))) goto LA8_;
		result = ((NI) -1);
		goto BeforeRet_;
	}
	LA8_: ;
	T10_ = ((t.data ? t.data->Sup.len : 0)-1);
	h = (NI)((*hc) & T10_);
	{
		while (1) {
			NIM_BOOL T13_;
			NI T20_;
			T13_ = (NIM_BOOL)0;
			T13_ = isFilled__pureZcollectionsZtables_31(t.data->data[h].Field0);
			if (!T13_) goto LA12;
			{
				NIM_BOOL T16_;
				T16_ = (NIM_BOOL)0;
				T16_ = (t.data->data[h].Field0 == (*hc));
				if (!(T16_)) goto LA17_;
				T16_ = eqeq___OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871_547(t.data->data[h].Field1, key);
				LA17_: ;
				if (!T16_) goto LA18_;
				result = h;
				goto BeforeRet_;
			}
			LA18_: ;
			T20_ = ((t.data ? t.data->Sup.len : 0)-1);
			h = nextTry__pureZcollectionsZtables_34(h, T20_);
		} LA12: ;
	}
	result = (NI)(((NI) -1) - h);
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NIM_BOOL, mustRehash__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871_5756)(tyObject_Table__HWSctC1WdhUfJtaLIvgFUw t) {
	NIM_BOOL result;
	NIM_BOOL T1_;
	NI T2_;
	NI T4_;
	result = (NIM_BOOL)0;
	T1_ = (NIM_BOOL)0;
	T2_ = (t.data ? t.data->Sup.len : 0);
	T1_ = ((NI)(T2_ * ((NI) 2)) < (NI)(t.counter * ((NI) 3)));
	if (T1_) goto LA3_;
	T4_ = (t.data ? t.data->Sup.len : 0);
	T1_ = ((NI)(T4_ - t.counter) < ((NI) 4));
	LA3_: ;
	result = T1_;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, rawInsert__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871_6217)(tyObject_Table__HWSctC1WdhUfJtaLIvgFUw* t, tySequence__fl4Fl0sjv6wLBM59aA9a59c9aw** data, tyObject_RGBA8__P4w0wnmH7J1IGztO6QfG5A key, NI val, NI hc, NI h) {
	(*data)->data[h].Field1 = key;
	(*data)->data[h].Field2 = val;
	(*data)->data[h].Field0 = hc;
}
N_LIB_PRIVATE N_NIMCALL(void, enlarge__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871_5909)(tyObject_Table__HWSctC1WdhUfJtaLIvgFUw* t) {
	tySequence__fl4Fl0sjv6wLBM59aA9a59c9aw* n;
	NI T1_;
	tySequence__fl4Fl0sjv6wLBM59aA9a59c9aw* T2_;
	n = NIM_NIL;
	T1_ = ((*t).data ? (*t).data->Sup.len : 0);
	n = (tySequence__fl4Fl0sjv6wLBM59aA9a59c9aw*) newSeq((&NTIkeyvaluepairseq__fl4Fl0sjv6wLBM59aA9a59c9aw_), ((NI) ((NI)(T1_ * ((NI) 2)))));
	T2_ = NIM_NIL;
	T2_ = (*t).data;
	unsureAsgnRef((void**) (&(*t).data), n);
	n = T2_;
	{
		NI i;
		NI colontmp_;
		NI T4_;
		NI res;
		i = (NI)0;
		colontmp_ = (NI)0;
		T4_ = ((n ? n->Sup.len : 0)-1);
		colontmp_ = T4_;
		res = ((NI) 0);
		{
			while (1) {
				NI eh;
				if (!(res <= colontmp_)) goto LA6;
				i = res;
				eh = n->data[i].Field0;
				{
					NIM_BOOL T9_;
					NI j;
					NI T12_;
					tyObject_RGBA8__P4w0wnmH7J1IGztO6QfG5A T17_;
					NI T18_;
					T9_ = (NIM_BOOL)0;
					T9_ = isFilled__pureZcollectionsZtables_31(eh);
					if (!T9_) goto LA10_;
					T12_ = (((*t).data ? (*t).data->Sup.len : 0)-1);
					j = (NI)(eh & T12_);
					{
						while (1) {
							NIM_BOOL T15_;
							NI T16_;
							T15_ = (NIM_BOOL)0;
							T15_ = isFilled__pureZcollectionsZtables_31((*t).data->data[j].Field0);
							if (!T15_) goto LA14;
							T16_ = (((*t).data ? (*t).data->Sup.len : 0)-1);
							j = nextTry__pureZcollectionsZtables_34(j, T16_);
						} LA14: ;
					}
					T17_ = n->data[i].Field1;
					nimZeroMem((void*)(&n->data[i].Field1), sizeof(tyObject_RGBA8__P4w0wnmH7J1IGztO6QfG5A));
					T18_ = (NI)0;
					T18_ = n->data[i].Field2;
					n->data[i].Field2 = 0;
					rawInsert__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871_6217(t, (&(*t).data), T17_, T18_, eh, j);
				}
				LA10_: ;
				res += ((NI) 1);
			} LA6: ;
		}
	}
}
static N_INLINE(NI, rawGetKnownHC__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871_6386)(tyObject_Table__HWSctC1WdhUfJtaLIvgFUw t, tyObject_RGBA8__P4w0wnmH7J1IGztO6QfG5A key, NI hc) {
	NI result;
	NI h;
	NI T6_;
{	result = (NI)0;
	{
		NI T3_;
		T3_ = (t.data ? t.data->Sup.len : 0);
		if (!(T3_ == ((NI) 0))) goto LA4_;
		result = ((NI) -1);
		goto BeforeRet_;
	}
	LA4_: ;
	T6_ = ((t.data ? t.data->Sup.len : 0)-1);
	h = (NI)(hc & T6_);
	{
		while (1) {
			NIM_BOOL T9_;
			NI T16_;
			T9_ = (NIM_BOOL)0;
			T9_ = isFilled__pureZcollectionsZtables_31(t.data->data[h].Field0);
			if (!T9_) goto LA8;
			{
				NIM_BOOL T12_;
				T12_ = (NIM_BOOL)0;
				T12_ = (t.data->data[h].Field0 == hc);
				if (!(T12_)) goto LA13_;
				T12_ = eqeq___OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871_547(t.data->data[h].Field1, key);
				LA13_: ;
				if (!T12_) goto LA14_;
				result = h;
				goto BeforeRet_;
			}
			LA14_: ;
			T16_ = ((t.data ? t.data->Sup.len : 0)-1);
			h = nextTry__pureZcollectionsZtables_34(h, T16_);
		} LA8: ;
	}
	result = (NI)(((NI) -1) - h);
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, X5BX5Deq___OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871_5355)(tyObject_Table__HWSctC1WdhUfJtaLIvgFUw* t, tyObject_RGBA8__P4w0wnmH7J1IGztO6QfG5A key, NI val) {
	NI hc;
	NI index;
	{
		NI T3_;
		NI correctSizeX60gensym268_;
		T3_ = ((*t).data ? (*t).data->Sup.len : 0);
		if (!(T3_ == ((NI) 0))) goto LA4_;
		correctSizeX60gensym268_ = slotsNeeded__pureZcollectionsZtables_42(((NI) 32));
		(*t).counter = ((NI) 0);
		unsureAsgnRef((void**) (&(*t).data), (tySequence__fl4Fl0sjv6wLBM59aA9a59c9aw*) newSeq((&NTIkeyvaluepairseq__fl4Fl0sjv6wLBM59aA9a59c9aw_), ((NI) (correctSizeX60gensym268_))));
	}
	LA4_: ;
	hc = (NI)0;
	index = rawGet__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871_5416((*t), key, (&hc));
	{
		if (!(((NI) 0) <= index)) goto LA8_;
		(*t).data->data[index].Field2 = val;
	}
	goto LA6_;
	LA8_: ;
	{
		{
			NI T13_;
			NI correctSizeX60gensym273_;
			T13_ = ((*t).data ? (*t).data->Sup.len : 0);
			if (!(T13_ == ((NI) 0))) goto LA14_;
			correctSizeX60gensym273_ = slotsNeeded__pureZcollectionsZtables_42(((NI) 32));
			(*t).counter = ((NI) 0);
			unsureAsgnRef((void**) (&(*t).data), (tySequence__fl4Fl0sjv6wLBM59aA9a59c9aw*) newSeq((&NTIkeyvaluepairseq__fl4Fl0sjv6wLBM59aA9a59c9aw_), ((NI) (correctSizeX60gensym273_))));
		}
		LA14_: ;
		{
			NIM_BOOL T18_;
			T18_ = (NIM_BOOL)0;
			T18_ = mustRehash__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871_5756((*t));
			if (!T18_) goto LA19_;
			enlarge__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871_5909(t);
			index = rawGetKnownHC__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871_6386((*t), key, hc);
		}
		LA19_: ;
		index = (NI)(((NI) -1) - index);
		rawInsert__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871_6217(t, (&(*t).data), key, val, hc, index);
		(*t).counter += ((NI) 1);
	}
	LA6_: ;
}
N_LIB_PRIVATE N_NOINLINE(void, raiseKeyError__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871_7689)(tyObject_RGBA8__P4w0wnmH7J1IGztO6QfG5A key) {
	tyObject_KeyError__t7nhKLvXTQS9cS8ByJU9bIag* T1_;
	NimStringDesc* T2_;
	NimStringDesc* T3_;
	T1_ = NIM_NIL;
	T1_ = (tyObject_KeyError__t7nhKLvXTQS9cS8ByJU9bIag*) newObj((&NTIrefkeyerror__8SzoIAgLw9ci2v0yafHj9b6Q_), sizeof(tyObject_KeyError__t7nhKLvXTQS9cS8ByJU9bIag));
	(*T1_).Sup.Sup.Sup.Sup.m_type = (&NTIkeyerror__t7nhKLvXTQS9cS8ByJU9bIag_);
	(*T1_).Sup.Sup.Sup.name = "KeyError";
	T2_ = NIM_NIL;
	T3_ = NIM_NIL;
	T3_ = dollar___OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871_7754(key);
	T2_ = rawNewString((T3_ ? T3_->Sup.len : 0) + 15);
appendString(T2_, ((NimStringDesc*) &TM__4SoG2KRQy3oMm9aUzSLtGrA_2));
appendString(T2_, T3_);
	asgnRef((void**) (&(*T1_).Sup.Sup.Sup.message), T2_);
	asgnRef((void**) (&(*T1_).Sup.Sup.Sup.parent), ((Exception*) NIM_NIL));
	raiseExceptionEx((Exception*)T1_, "KeyError", "raiseKeyError", "tables.nim", 233);
}
N_LIB_PRIVATE N_NIMCALL(NI, X5BX5D___OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871_7622)(tyObject_Table__HWSctC1WdhUfJtaLIvgFUw t, tyObject_RGBA8__P4w0wnmH7J1IGztO6QfG5A key) {
	NI result;
	NI hcX60gensym20_;
	NI indexX60gensym20_;
	result = (NI)0;
	hcX60gensym20_ = (NI)0;
	indexX60gensym20_ = rawGet__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871_5416(t, key, (&hcX60gensym20_));
	{
		if (!(((NI) 0) <= indexX60gensym20_)) goto LA3_;
		result = t.data->data[indexX60gensym20_].Field2;
	}
	goto LA1_;
	LA3_: ;
	{
		raiseKeyError__OOZOOZOnimbleZpkgsZnim8078714548O51O49Znim807871_7689(key);
	}
	LA1_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, len__OOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZsdl50_3460)(tyObject_Table__qyR3xLIFK9bnjRhAsVBPjVA t) {
	NI result;
	result = (NI)0;
	result = t.counter;
	return result;
}
N_LIB_PRIVATE N_NOINLINE(void, raiseKeyError__OOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZsdl50_3845)(tyEnum_Keycode__4FafBrLvG2wfvPTkNrrFRQ key) {
	tyObject_KeyError__t7nhKLvXTQS9cS8ByJU9bIag* T1_;
	NimStringDesc* T2_;
	T1_ = NIM_NIL;
	T1_ = (tyObject_KeyError__t7nhKLvXTQS9cS8ByJU9bIag*) newObj((&NTIrefkeyerror__8SzoIAgLw9ci2v0yafHj9b6Q_), sizeof(tyObject_KeyError__t7nhKLvXTQS9cS8ByJU9bIag));
	(*T1_).Sup.Sup.Sup.Sup.m_type = (&NTIkeyerror__t7nhKLvXTQS9cS8ByJU9bIag_);
	(*T1_).Sup.Sup.Sup.name = "KeyError";
	T2_ = NIM_NIL;
	T2_ = rawNewString((reprEnum((NI)key, (&NTIkeycode__4FafBrLvG2wfvPTkNrrFRQ_)) ? reprEnum((NI)key, (&NTIkeycode__4FafBrLvG2wfvPTkNrrFRQ_))->Sup.len : 0) + 15);
appendString(T2_, ((NimStringDesc*) &TM__4SoG2KRQy3oMm9aUzSLtGrA_2));
appendString(T2_, reprEnum((NI)key, (&NTIkeycode__4FafBrLvG2wfvPTkNrrFRQ_)));
	asgnRef((void**) (&(*T1_).Sup.Sup.Sup.message), T2_);
	asgnRef((void**) (&(*T1_).Sup.Sup.Sup.parent), ((Exception*) NIM_NIL));
	raiseExceptionEx((Exception*)T1_, "KeyError", "raiseKeyError", "tables.nim", 233);
}
N_LIB_PRIVATE N_NIMCALL(NU32*, X5BX5D___OOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZsdl50_3773)(tyObject_Table__qyR3xLIFK9bnjRhAsVBPjVA* t, tyEnum_Keycode__4FafBrLvG2wfvPTkNrrFRQ key) {
	NU32* result;
	NI hcX60gensym22_;
	NI indexX60gensym22_;
	result = (NU32*)0;
	hcX60gensym22_ = (NI)0;
	indexX60gensym22_ = rawGet__OOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZsdl50_1668((*t), key, (&hcX60gensym22_));
	{
		if (!(((NI) 0) <= indexX60gensym22_)) goto LA3_;
		result = (&(*t).data->data[indexX60gensym22_].Field2);
	}
	goto LA1_;
	LA3_: ;
	{
		raiseKeyError__OOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZsdl50_3845(key);
	}
	LA1_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, initOrderedTable__pureZjson_91)(NI initialSize, tyObject_OrderedTable__ZZvSdVkA2s2sIyifu4cpkg* Result) {
	NI correctSizeX60gensym0_;
	unsureAsgnRef((void**)&(*Result).data, NIM_NIL);
	(*Result).counter = 0;
	(*Result).first = 0;
	(*Result).last = 0;
	correctSizeX60gensym0_ = slotsNeeded__pureZcollectionsZtables_42(((NI) (initialSize)));
	(*Result).counter = ((NI) 0);
	unsureAsgnRef((void**) (&(*Result).data), (tySequence__MlAD6nAPq9bHKla9cWiIZP0g*) newSeq((&NTIorderedkeyvaluepairseq__MlAD6nAPq9bHKla9cWiIZP0g_), ((NI) (correctSizeX60gensym0_))));
	(*Result).first = ((NI) -1);
	(*Result).last = ((NI) -1);
}
N_LIB_PRIVATE N_NIMCALL(NI, rawGet__pureZjson_362)(tyObject_OrderedTable__ZZvSdVkA2s2sIyifu4cpkg t, NimStringDesc* key, NI* hc) {
	NI result;
	NI h;
	NI T10_;
{	result = (NI)0;
	(*hc) = hash__pureZhashes_279(key);
	{
		if (!((*hc) == ((NI) 0))) goto LA3_;
		(*hc) = ((NI) 314159265);
	}
	LA3_: ;
	{
		NI T7_;
		T7_ = (t.data ? t.data->Sup.len : 0);
		if (!(T7_ == ((NI) 0))) goto LA8_;
		result = ((NI) -1);
		goto BeforeRet_;
	}
	LA8_: ;
	T10_ = ((t.data ? t.data->Sup.len : 0)-1);
	h = (NI)((*hc) & T10_);
	{
		while (1) {
			NIM_BOOL T13_;
			NI T20_;
			T13_ = (NIM_BOOL)0;
			T13_ = isFilled__pureZcollectionsZtables_31(t.data->data[h].Field0);
			if (!T13_) goto LA12;
			{
				NIM_BOOL T16_;
				T16_ = (NIM_BOOL)0;
				T16_ = (t.data->data[h].Field0 == (*hc));
				if (!(T16_)) goto LA17_;
				T16_ = eqStrings(t.data->data[h].Field2, key);
				LA17_: ;
				if (!T16_) goto LA18_;
				result = h;
				goto BeforeRet_;
			}
			LA18_: ;
			T20_ = ((t.data ? t.data->Sup.len : 0)-1);
			h = nextTry__pureZcollectionsZtables_34(h, T20_);
		} LA12: ;
	}
	result = (NI)(((NI) -1) - h);
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NIM_BOOL, mustRehash__pureZjson_698)(tyObject_OrderedTable__ZZvSdVkA2s2sIyifu4cpkg t) {
	NIM_BOOL result;
	NIM_BOOL T1_;
	NI T2_;
	NI T4_;
	result = (NIM_BOOL)0;
	T1_ = (NIM_BOOL)0;
	T2_ = (t.data ? t.data->Sup.len : 0);
	T1_ = ((NI)(T2_ * ((NI) 2)) < (NI)(t.counter * ((NI) 3)));
	if (T1_) goto LA3_;
	T4_ = (t.data ? t.data->Sup.len : 0);
	T1_ = ((NI)(T4_ - t.counter) < ((NI) 4));
	LA3_: ;
	result = T1_;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, rawInsert__pureZjson_1274)(tyObject_OrderedTable__ZZvSdVkA2s2sIyifu4cpkg* t, tySequence__MlAD6nAPq9bHKla9cWiIZP0g** data, NimStringDesc* key, tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* val, NI hc, NI h) {
	NimStringDesc* T1_;
	T1_ = NIM_NIL;
	T1_ = (*data)->data[h].Field2; (*data)->data[h].Field2 = copyStringRC1(key);
	if (T1_) nimGCunrefNoCycle(T1_);
	asgnRef((void**) (&(*data)->data[h].Field3), val);
	(*data)->data[h].Field0 = hc;
	(*data)->data[h].Field1 = ((NI) -1);
	{
		if (!((*t).first < ((NI) 0))) goto LA4_;
		(*t).first = h;
	}
	LA4_: ;
	{
		if (!(((NI) 0) <= (*t).last)) goto LA8_;
		(*data)->data[(*t).last].Field1 = h;
	}
	LA8_: ;
	(*t).last = h;
}
N_LIB_PRIVATE N_NIMCALL(void, enlarge__pureZjson_859)(tyObject_OrderedTable__ZZvSdVkA2s2sIyifu4cpkg* t) {
	tySequence__MlAD6nAPq9bHKla9cWiIZP0g* n;
	NI T1_;
	NI h;
	tySequence__MlAD6nAPq9bHKla9cWiIZP0g* T2_;
	n = NIM_NIL;
	T1_ = ((*t).data ? (*t).data->Sup.len : 0);
	n = (tySequence__MlAD6nAPq9bHKla9cWiIZP0g*) newSeq((&NTIorderedkeyvaluepairseq__MlAD6nAPq9bHKla9cWiIZP0g_), ((NI) ((NI)(T1_ * ((NI) 2)))));
	h = (*t).first;
	(*t).first = ((NI) -1);
	(*t).last = ((NI) -1);
	T2_ = NIM_NIL;
	T2_ = (*t).data;
	unsureAsgnRef((void**) (&(*t).data), n);
	n = T2_;
	{
		while (1) {
			NI nxt;
			NI eh;
			if (!(((NI) 0) <= h)) goto LA4;
			nxt = n->data[h].Field1;
			eh = n->data[h].Field0;
			{
				NIM_BOOL T7_;
				NI j;
				NI T10_;
				NimStringDesc* T15_;
				tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* T16_;
				T7_ = (NIM_BOOL)0;
				T7_ = isFilled__pureZcollectionsZtables_31(eh);
				if (!T7_) goto LA8_;
				T10_ = (((*t).data ? (*t).data->Sup.len : 0)-1);
				j = (NI)(eh & T10_);
				{
					while (1) {
						NIM_BOOL T13_;
						NI T14_;
						T13_ = (NIM_BOOL)0;
						T13_ = isFilled__pureZcollectionsZtables_31((*t).data->data[j].Field0);
						if (!T13_) goto LA12;
						T14_ = (((*t).data ? (*t).data->Sup.len : 0)-1);
						j = nextTry__pureZcollectionsZtables_34(j, T14_);
					} LA12: ;
				}
				T15_ = NIM_NIL;
				T15_ = n->data[h].Field2;
				asgnRef((void**) (&n->data[h].Field2), NIM_NIL);
				T16_ = NIM_NIL;
				T16_ = n->data[h].Field3;
				asgnRef((void**) (&n->data[h].Field3), NIM_NIL);
				rawInsert__pureZjson_1274(t, (&(*t).data), T15_, T16_, n->data[h].Field0, j);
			}
			LA8_: ;
			h = nxt;
		} LA4: ;
	}
}
N_LIB_PRIVATE N_NIMCALL(NI, rawGetKnownHC__pureZjson_1556)(tyObject_OrderedTable__ZZvSdVkA2s2sIyifu4cpkg t, NimStringDesc* key, NI hc) {
	NI result;
	NI h;
	NI T6_;
{	result = (NI)0;
	{
		NI T3_;
		T3_ = (t.data ? t.data->Sup.len : 0);
		if (!(T3_ == ((NI) 0))) goto LA4_;
		result = ((NI) -1);
		goto BeforeRet_;
	}
	LA4_: ;
	T6_ = ((t.data ? t.data->Sup.len : 0)-1);
	h = (NI)(hc & T6_);
	{
		while (1) {
			NIM_BOOL T9_;
			NI T16_;
			T9_ = (NIM_BOOL)0;
			T9_ = isFilled__pureZcollectionsZtables_31(t.data->data[h].Field0);
			if (!T9_) goto LA8;
			{
				NIM_BOOL T12_;
				T12_ = (NIM_BOOL)0;
				T12_ = (t.data->data[h].Field0 == hc);
				if (!(T12_)) goto LA13_;
				T12_ = eqStrings(t.data->data[h].Field2, key);
				LA13_: ;
				if (!T12_) goto LA14_;
				result = h;
				goto BeforeRet_;
			}
			LA14_: ;
			T16_ = ((t.data ? t.data->Sup.len : 0)-1);
			h = nextTry__pureZcollectionsZtables_34(h, T16_);
		} LA8: ;
	}
	result = (NI)(((NI) -1) - h);
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, X5BX5Deq___pureZjson_293)(tyObject_OrderedTable__ZZvSdVkA2s2sIyifu4cpkg* t, NimStringDesc* key, tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q* val) {
	NI hc;
	NI index;
	{
		NI T3_;
		NI correctSizeX60gensym13_;
		T3_ = ((*t).data ? (*t).data->Sup.len : 0);
		if (!(T3_ == ((NI) 0))) goto LA4_;
		correctSizeX60gensym13_ = slotsNeeded__pureZcollectionsZtables_42(((NI) 32));
		(*t).counter = ((NI) 0);
		unsureAsgnRef((void**) (&(*t).data), (tySequence__MlAD6nAPq9bHKla9cWiIZP0g*) newSeq((&NTIorderedkeyvaluepairseq__MlAD6nAPq9bHKla9cWiIZP0g_), ((NI) (correctSizeX60gensym13_))));
		(*t).first = ((NI) -1);
		(*t).last = ((NI) -1);
	}
	LA4_: ;
	hc = (NI)0;
	index = rawGet__pureZjson_362((*t), key, (&hc));
	{
		if (!(((NI) 0) <= index)) goto LA8_;
		asgnRef((void**) (&(*t).data->data[index].Field3), val);
	}
	goto LA6_;
	LA8_: ;
	{
		{
			NI T13_;
			NI correctSizeX60gensym18_;
			T13_ = ((*t).data ? (*t).data->Sup.len : 0);
			if (!(T13_ == ((NI) 0))) goto LA14_;
			correctSizeX60gensym18_ = slotsNeeded__pureZcollectionsZtables_42(((NI) 32));
			(*t).counter = ((NI) 0);
			unsureAsgnRef((void**) (&(*t).data), (tySequence__MlAD6nAPq9bHKla9cWiIZP0g*) newSeq((&NTIorderedkeyvaluepairseq__MlAD6nAPq9bHKla9cWiIZP0g_), ((NI) (correctSizeX60gensym18_))));
			(*t).first = ((NI) -1);
			(*t).last = ((NI) -1);
		}
		LA14_: ;
		{
			NIM_BOOL T18_;
			T18_ = (NIM_BOOL)0;
			T18_ = mustRehash__pureZjson_698((*t));
			if (!T18_) goto LA19_;
			enlarge__pureZjson_859(t);
			index = rawGetKnownHC__pureZjson_1556((*t), key, hc);
		}
		LA19_: ;
		index = (NI)(((NI) -1) - index);
		rawInsert__pureZjson_1274(t, (&(*t).data), key, val, hc, index);
		(*t).counter += ((NI) 1);
	}
	LA6_: ;
}
static N_INLINE(NI, rawGet__pureZjson_2664)(tyObject_OrderedTable__ZZvSdVkA2s2sIyifu4cpkg t, NimStringDesc* key, NI* hc) {
	NI result;
	NI h;
	NI T10_;
{	result = (NI)0;
	(*hc) = hash__pureZhashes_279(key);
	{
		if (!((*hc) == ((NI) 0))) goto LA3_;
		(*hc) = ((NI) 314159265);
	}
	LA3_: ;
	{
		NI T7_;
		T7_ = (t.data ? t.data->Sup.len : 0);
		if (!(T7_ == ((NI) 0))) goto LA8_;
		result = ((NI) -1);
		goto BeforeRet_;
	}
	LA8_: ;
	T10_ = ((t.data ? t.data->Sup.len : 0)-1);
	h = (NI)((*hc) & T10_);
	{
		while (1) {
			NIM_BOOL T13_;
			NI T20_;
			T13_ = (NIM_BOOL)0;
			T13_ = isFilled__pureZcollectionsZtables_31(t.data->data[h].Field0);
			if (!T13_) goto LA12;
			{
				NIM_BOOL T16_;
				T16_ = (NIM_BOOL)0;
				T16_ = (t.data->data[h].Field0 == (*hc));
				if (!(T16_)) goto LA17_;
				T16_ = eqStrings(t.data->data[h].Field2, key);
				LA17_: ;
				if (!T16_) goto LA18_;
				result = h;
				goto BeforeRet_;
			}
			LA18_: ;
			T20_ = ((t.data ? t.data->Sup.len : 0)-1);
			h = nextTry__pureZcollectionsZtables_34(h, T20_);
		} LA12: ;
	}
	result = (NI)(((NI) -1) - h);
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q**, X5BX5D___pureZjson_2657)(tyObject_OrderedTable__ZZvSdVkA2s2sIyifu4cpkg* t, NimStringDesc* key) {
	tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q** result;
	NI hcX60gensym89_;
	NI indexX60gensym89_;
	result = (tyObject_JsonNodeObj__df9bshXB7C9cTiWPIOtX3j1Q**)0;
	hcX60gensym89_ = (NI)0;
	indexX60gensym89_ = rawGet__pureZjson_2664((*t), key, (&hcX60gensym89_));
	{
		if (!(((NI) 0) <= indexX60gensym89_)) goto LA3_;
		result = &(*t).data->data[indexX60gensym89_].Field3;
	}
	goto LA1_;
	LA3_: ;
	{
		raiseKeyError__pureZjson_2938(key);
	}
	LA1_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, hasKey__OOZOOZOnimbleZpkgsZnico4548O52O57Znico_1044)(tyObject_Table__qyR3xLIFK9bnjRhAsVBPjVA t, tyEnum_Keycode__4FafBrLvG2wfvPTkNrrFRQ key) {
	NIM_BOOL result;
	NI hc;
	NI T1_;
	result = (NIM_BOOL)0;
	hc = (NI)0;
	T1_ = (NI)0;
	T1_ = rawGet__OOZOOZOnimbleZpkgsZnico4548O52O57ZnicoZbackendsZsdl50_1668(t, key, (&hc));
	result = (((NI) 0) <= T1_);
	return result;
}
static N_INLINE(NI, rawGet__main_177)(tyObject_Table__Jqg9bbNxGV6Sf9cnDeeNaaIg t, NimStringDesc* key, NI* hc) {
	NI result;
	NI h;
	NI T10_;
{	result = (NI)0;
	(*hc) = hash__pureZhashes_279(key);
	{
		if (!((*hc) == ((NI) 0))) goto LA3_;
		(*hc) = ((NI) 314159265);
	}
	LA3_: ;
	{
		NI T7_;
		T7_ = (t.data ? t.data->Sup.len : 0);
		if (!(T7_ == ((NI) 0))) goto LA8_;
		result = ((NI) -1);
		goto BeforeRet_;
	}
	LA8_: ;
	T10_ = ((t.data ? t.data->Sup.len : 0)-1);
	h = (NI)((*hc) & T10_);
	{
		while (1) {
			NIM_BOOL T13_;
			NI T20_;
			T13_ = (NIM_BOOL)0;
			T13_ = isFilled__pureZcollectionsZtables_31(t.data->data[h].Field0);
			if (!T13_) goto LA12;
			{
				NIM_BOOL T16_;
				T16_ = (NIM_BOOL)0;
				T16_ = (t.data->data[h].Field0 == (*hc));
				if (!(T16_)) goto LA17_;
				T16_ = eqStrings(t.data->data[h].Field1, key);
				LA17_: ;
				if (!T16_) goto LA18_;
				result = h;
				goto BeforeRet_;
			}
			LA18_: ;
			T20_ = ((t.data ? t.data->Sup.len : 0)-1);
			h = nextTry__pureZcollectionsZtables_34(h, T20_);
		} LA12: ;
	}
	result = (NI)(((NI) -1) - h);
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tySequence__qwqHTkRvwhrRyENtudHQ7g*, X5BX5D___main_1793)(tyObject_Table__Jqg9bbNxGV6Sf9cnDeeNaaIg t, NimStringDesc* key) {
	tySequence__qwqHTkRvwhrRyENtudHQ7g* result;
	NI hcX60gensym20_;
	NI indexX60gensym20_;
	result = NIM_NIL;
	hcX60gensym20_ = (NI)0;
	indexX60gensym20_ = rawGet__main_177(t, key, (&hcX60gensym20_));
	{
		if (!(((NI) 0) <= indexX60gensym20_)) goto LA3_;
		genericSeqAssign((&result), t.data->data[indexX60gensym20_].Field2, (&NTIseqLintT__qwqHTkRvwhrRyENtudHQ7g_));
	}
	goto LA1_;
	LA3_: ;
	{
		raiseKeyError__pureZjson_2938(key);
	}
	LA1_: ;
	return result;
}
N_LIB_PRIVATE N_NOINLINE(void, raiseKeyError__OOZOOZOnimbleZpkgsZnico4548O52O57Znico_5148)(NI32 key) {
	tyObject_KeyError__t7nhKLvXTQS9cS8ByJU9bIag* T1_;
	NimStringDesc* T2_;
	NimStringDesc* T3_;
	T1_ = NIM_NIL;
	T1_ = (tyObject_KeyError__t7nhKLvXTQS9cS8ByJU9bIag*) newObj((&NTIrefkeyerror__8SzoIAgLw9ci2v0yafHj9b6Q_), sizeof(tyObject_KeyError__t7nhKLvXTQS9cS8ByJU9bIag));
	(*T1_).Sup.Sup.Sup.Sup.m_type = (&NTIkeyerror__t7nhKLvXTQS9cS8ByJU9bIag_);
	(*T1_).Sup.Sup.Sup.name = "KeyError";
	T2_ = NIM_NIL;
	T3_ = NIM_NIL;
	T3_ = dollar___pureZunicode_591(key);
	T2_ = rawNewString((T3_ ? T3_->Sup.len : 0) + 15);
appendString(T2_, ((NimStringDesc*) &TM__4SoG2KRQy3oMm9aUzSLtGrA_2));
appendString(T2_, T3_);
	asgnRef((void**) (&(*T1_).Sup.Sup.Sup.message), T2_);
	asgnRef((void**) (&(*T1_).Sup.Sup.Sup.parent), ((Exception*) NIM_NIL));
	raiseExceptionEx((Exception*)T1_, "KeyError", "raiseKeyError", "tables.nim", 233);
}
N_LIB_PRIVATE N_NIMCALL(tyTuple__FtZxsWeKlOo83uVL9c4OOmg*, X5BX5D___OOZOOZOnimbleZpkgsZnico4548O52O57Znico_5076)(tyObject_Table__pjVQUpmpjessb3kC1dSh5w* t, NI32 key) {
	tyTuple__FtZxsWeKlOo83uVL9c4OOmg* result;
	NI hcX60gensym22_;
	NI indexX60gensym22_;
	result = (tyTuple__FtZxsWeKlOo83uVL9c4OOmg*)0;
	hcX60gensym22_ = (NI)0;
	indexX60gensym22_ = rawGet__OOZOOZOnimbleZpkgsZnico4548O52O57Znico_3072((*t), key, (&hcX60gensym22_));
	{
		if (!(((NI) 0) <= indexX60gensym22_)) goto LA3_;
		result = (&(*t).data->data[indexX60gensym22_].Field2);
	}
	goto LA1_;
	LA3_: ;
	{
		raiseKeyError__OOZOOZOnimbleZpkgsZnico4548O52O57Znico_5148(key);
	}
	LA1_: ;
	return result;
}
